pages/1.11/networking/index.md
pages/1.12/networking/index.md
pages/1.13/networking/index.md

https://jira.mesosphere.com/browse/DCOS_OSS-5163

Fix typo thw that should be the.

---

pages/1.13/metrics/reference/index.md

https://jira.mesosphere.com/browse/DCOS-50130

1.13 Metrics Reference page - Added new resource information.

---

pages/1.12/installing/production/patching/index.md

https://jira.mesosphere.com/browse/DCOS-53551

Added 1.12 Patching path matrix.

---

pages/1.13/metrics/index.md

https://jira.mesosphere.com/browse/DCOS-54011
Fixed text issues on 1.13 Metrics page.

Fixed text issues in 1.13 Metrics page.

---

pages/1.12/security/ent/ldap/ldap-sync/index.md
pages/1.13/security/ent/ldap/ldap-sync/index.md

https://jira.mesosphere.com/browse/COPS-4889
N/A
Fix typo, missing space

LG/COPS-4889: Fix a couple of minor typos

---

pages/1.13/installing/production/patching/index.md
pages/1.13/installing/production/upgrading/index.md

https://jira.mesosphere.com/browse/DCOS_OSS-5150

1.13 docs: clarify importance of IAM db backup

---

pages/install-include/all-dcos-versions.tmpl
pages/install-include/all-upgrade-cluster.tmpl
pages/install-include/aws-cluster-setup.tmpl
pages/install-include/aws-extended-example.tmpl
pages/install-include/aws-remote-region-all.tmpl
pages/install-include/aws-replaceable-masters-all.tmpl
pages/install-include/aws-tf-faq-all.tmpl
pages/install-include/azure-cluster-setup.tmpl
pages/install-include/azure-extended-example.tmpl
pages/install-include/gcp-cluster-setup.tmpl
pages/install-include/gcp-extended-example.tmpl

https://jira.mesosphere.com/browse/DCOS_OSS-5155
Updates examples to show 1.13.0

CK DCOS_OSS-5155 Update to 1.13 examples in install docs

---

pages/1.12/installing/production/dcos-ansible/ansible-quickstart/index.md
pages/1.13/installing/production/dcos-ansible/ansible-quickstart/index.md

https://jira.mesosphere.com/browse/DCOS-54074
https://jira.mesosphere.com/browse/COPS-4895
- added additional documentation about ip-detect in ansible including some examples.
- changed download links to 1.13.0 as this doc is about 1.13

added more documentation about ip-detect

---

pages/1.13/installing/production/system-requirements/partitions/index.md

https://jira.mesosphere.com/browse/DCOS-54430
n/a
Fixed title text.

Correct the title used for the new Partitions section.

---

pages/1.10/installing/production/advanced-configuration/configuration-reference/index.md
pages/1.10/installing/production/deploying-dcos/installation/index.md
pages/1.11/installing/production/advanced-configuration/configuration-reference/index.md
pages/1.11/installing/production/deploying-dcos/configuration/examples/index.md
pages/1.11/installing/production/deploying-dcos/installation/index.md
pages/1.12/installing/production/advanced-configuration/configuration-reference/index.md
pages/1.12/installing/production/deploying-dcos/configuration/examples/index.md
pages/1.12/installing/production/deploying-dcos/installation/index.md
pages/1.13/installing/production/advanced-configuration/configuration-reference/index.md
pages/1.13/installing/production/deploying-dcos/configuration/examples/index.md
pages/1.13/installing/production/deploying-dcos/installation/index.md

https://jira.mesosphere.com/browse/DCOS-54490
Checked with eng, got clarification on licensing change starting with 1.11 and corrected docs accordingly. 

CK DCOS-54490 Correct licensing information

---

pages/1.10/installing/production/advanced-configuration/configuration-reference/index.md
pages/1.10/installing/production/deploying-dcos/installation/index.md
pages/1.11/installing/production/advanced-configuration/configuration-reference/index.md
pages/1.12/installing/production/advanced-configuration/configuration-reference/index.md
pages/1.12/installing/production/deploying-dcos/installation/index.md
pages/1.13/installing/production/advanced-configuration/configuration-reference/index.md
pages/1.13/installing/production/deploying-dcos/installation/index.md

https://jira.mesosphere.com/browse/DCOS-54553
Add labels to all fault_domain_enabled sections, clean up version mentions.

CK DCOS-54553 Add EE tags to fault_domain_enabled

---

pages/1.13/release-notes/1.13.0/index.md
pages/1.13/release-notes/1.13.1/index.md

https://jira.mesosphere.com/browse/DCOS-53311
Initial draft for 1.13.1 release notes on the **accelerated release schedule**.
- [ N/A ] Make sure you change all affected versions (e.g. 1.10, 1.11, 1.12, 1.13).
- [ N/A ] Test all commands and procedures where applicable.
- [ N/A ] Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects) if you are moving a page.

Lg/rn 1.13.1

---

pages/1.13/monitoring/logging/index.md
pages/1.13/release-notes/1.13.0/index.md

https://jira.mesosphere.com/browse/DCOS-54604
https://jira.mesosphere.com/browse/DCOS-54604
Remove reference to Fluent Bit for now (until 1.13.2 patch).
- [x ] Make sure you change all affected versions (e.g. 1.10, 1.11, 1.12, 1.13).
- [ x] Test all commands and procedures where applicable.
- [ x] Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects) if you are moving a page.

Remove references to Fluent Bit for now (until patch comes).

---

docker/nginx/redirects-307.map

Update latest for services

---

pages/services/confluent-kafka/2.3.0-4.0.0e/index.md
pages/services/confluent-kafka/2.4.0-4.1.1/index.md
pages/services/confluent-kafka/2.5.0-4.1.2/index.md
pages/services/confluent-kafka/2.6.0-5.1.2/index.md

Re-order confluent-kafka

---

pages/1.11/installing/production/dcos-ansible/ansible-quickstart/index.md
pages/1.12/installing/production/dcos-ansible/ansible-quickstart/index.md
pages/1.13/installing/production/dcos-ansible/ansible-quickstart/index.md

https://jira.mesosphere.com/browse/DCOS_OSS-5181
Update to lock in Mazer CLI at 0.4.0 until further notice

CK Update to set Mazer at 0.4.0

---

pages/services/include/service-account.tmpl

https://jira.mesosphere.com/browse/DCOS_OSS-5231
Update template to fix UX throughout security procedures for services docs.
- [ x] Make sure you change all affected versions (e.g. 1.10, 1.11, 1.12, 1.13).

adjusted include file for better UX

---

pages/services/confluent-kafka/2.6.0-5.1.2/security/index.md

https://jira.mesosphere.com/browse/COPS-4940
Fixing security flow - pt 1.
- [x ] Make sure you change all affected versions (e.g. 1.10, 1.11, 1.12, 1.13).

fix security procedure flow

---

pages/1.10/installing/production/advanced-configuration/configuration-reference/index.md
pages/1.11/installing/production/advanced-configuration/configuration-reference/index.md
pages/1.12/installing/production/advanced-configuration/configuration-reference/index.md
pages/1.13/installing/production/advanced-configuration/configuration-reference/index.md

https://jira.mesosphere.com/browse/DCOS-54486
Adding two missing configs
https://github.com/mesosphere/dcos-docs-site/pull/1342/commits/9d8cac00ac75198920b1df26b68e54811555fdf0
https://github.com/mesosphere/dcos-docs-site/pull/1327

CK DCOS-54486 Replace missing config params

---

pages/1.11/release-notes/1.11.0-rc1/index.md
pages/1.11/release-notes/1.11.0-rc4/index.md
pages/1.11/release-notes/1.11.0/index.md
pages/1.11/release-notes/1.11.1/index.md
pages/1.11/release-notes/1.11.10/index.md
pages/1.11/release-notes/1.11.11/index.md
pages/1.11/release-notes/1.11.2/index.md
pages/1.11/release-notes/1.11.3/index.md
pages/1.11/release-notes/1.11.4/index.md
pages/1.11/release-notes/1.11.5/index.md
pages/1.11/release-notes/1.11.6/index.md
pages/1.11/release-notes/1.11.7/index.md
pages/1.11/release-notes/1.11.8/index.md
pages/1.11/release-notes/1.11.9/index.md

https://jira.mesosphere.com/browse/DCOS-53307

1.11.11 Release Notes.

---

pages/services/elastic/2.5.0-6.3.2/index.md
pages/services/spark/2.7.0-2.4.0/index.md

https://jira.mesosphere.com/browse/DCOS-51550
Correct menuweight on Elastic 2.5.0 docs

Dcos 51550 Correct menuweight for Elastic 2.5.0 docs

---

pages/1.10/installing/production/advanced-configuration/configuration-reference/index.md
pages/1.11/installing/production/advanced-configuration/configuration-reference/index.md
pages/1.12/installing/production/advanced-configuration/configuration-reference/index.md
pages/1.13/installing/production/advanced-configuration/configuration-reference/index.md

https://jira.mesosphere.com/browse/DCOS-54906
Original ticket was to fix broken anchor. I was tired of all the issues, so I gave everything a linked bottom section and corrected anchor links.
1.10
1.11
1.12
1.13

CK DCOS-54906 Broken config table links

---

pages/services/dcos-monitoring/index.md

Add missing index.md to dcos-monitoring landing page.

Add dcos-monitoring landing page

---

pages/1.12/installing/production/upgrading/index.md
pages/1.13/installing/production/upgrading/index.md
pages/1.7/index.md
pages/1.8/index.md
scss/base/_table.scss

https://jira.mesosphere.com/browse/DCOS-54912
Updating upgrade tables after Joe Thompson pointed out they hadn't been since 1.12.0 came out
- Updated 1.12 and 1.13 pages
- split into two tables each, one table for each major dc/os version for better readability\
- added captions as titles and styled

CK DCOS-54912 Update supported upgrades tables

---

pages/1.11/security/ent/tls-ssl/ca-custom/index.md
pages/1.12/security/ent/tls-ssl/ca-custom/index.md
pages/1.13/security/ent/tls-ssl/ca-custom/index.md

Docs ticket: https://jira.mesosphere.com/browse/DCOS-54592
This is a clarification of some text that was found to be confusing when dealing with a COPS issue.
Be more specific about what contents are in the certificate chain file, especially for  Use Case 2.

Clarify certificate chain contents

---

pages/services/dcos-monitoring/index.md

https://jira.mesosphere.com/browse/DCOS-55165

CK DCOS-55165 Update menuweight for dcos monitoring

---

pages/1.10/overview/design/overlay/index.md
pages/1.11/overview/design/overlay/index.md
pages/1.12/overview/design/overlay/index.md
pages/1.13/overview/design/overlay/index.md

Fix section header formatting

---

pages/1.11/security/ent/tls-ssl/exhibitor/index.md
pages/1.12/security/ent/tls-ssl/exhibitor/index.md
pages/1.13/security/ent/tls-ssl/exhibitor/index.md

https://jira.mesosphere.com/browse/DCOS-54773
Supporting documentation for the exhibitor-tls-artifacts tool

DCOS-19575 Exhibitor TLS: write install docs

---

pages/services/kafka/2.6.0-2.2.1/advanced/index.md
pages/services/kafka/2.6.0-2.2.1/configuration/index.md
pages/services/kafka/2.6.0-2.2.1/index.md
pages/services/kafka/2.6.0-2.2.1/limitations/index.md
pages/services/kafka/2.6.0-2.2.1/notes/index.md
pages/services/kafka/2.6.0-2.2.1/operations/index.md
pages/services/kafka/2.6.0-2.2.1/policy/index.md
pages/services/kafka/2.6.0-2.2.1/reference/index.md
pages/services/kafka/2.6.0-2.2.1/release-notes/index.md
pages/services/kafka/2.6.0-2.2.1/security/index.md
pages/services/kafka/2.6.0-2.2.1/started/index.md
pages/services/kafka/2.6.0-2.2.1/troubleshooting/index.md
pages/services/kafka/2.6.0-2.2.1/uninstall/index.md
pages/services/kafka/2.6.0-2.2.1/updates/index.md

https://jira.mesosphere.com/browse/DCOS-55253
ℹ️  Added DO NOT MERGE label until the following PRs are merged:
* https://github.com/mesosphere/universe/pull/2302

Release notes and JMX docs for Kafka 2.6.0-2.2.1 Release

---

pages/services/nifi/0.5.0-1.9.2/troubleshooting/debugging/index.md

https://jira.mesosphere.com/browse/DCOS-54560
Additional edits to DCOS-54560.

ss/DCOS-54560 Correcting URL again, edits to procedures.

---

pages/1.11/installing/production/patching/index.md
pages/1.12/installing/production/patching/index.md
pages/1.13/installing/production/patching/index.md

https://jira.mesosphere.com/browse/DCOS-50428
minor backtick and tab fix

CK DCOS-50428 formatting fix

---

pages/1.12/cli/command-reference/dcos-task/dcos-task-exec/index.md
pages/1.13/cli/command-reference/dcos-task/dcos-task-exec/index.md

https://jira.mesosphere.com/browse/DCOS_OSS-5308
A full task ID, a partial task ID, or a Unix shell wildcard pattern (eg. 'my-task*').
- [ X ] Make sure you change all affected versions (1.12, 1.13).

LG/DCOS_OSS-5308: modify the positional argument for matching task IDs

---

pages/1.12/cli/command-reference/dcos-task/dcos-task-attach/index.md
pages/1.13/cli/command-reference/dcos-task/dcos-task-attach/index.md

https://jira.mesosphere.com/browse/DCOS_OSS-5308
minor change of eg to for example for consistency.

Minor change to the dcos task attach positional arguments.

---

pages/1.14/cli/command-reference/dcos-task/dcos-task-attach/index.md
pages/1.14/cli/command-reference/dcos-task/dcos-task-exec/index.md

https://jira.mesosphere.com/browse/DCOS_OSS-5308
Add the change made to 1.12, 1.13 to 1.14 doc.
... UNIX shell wildcard pattern (for example, `my-task*`).

Forward port change for dcos task attach, dcos task exec.

---

pages/1.12/security/ent/secrets/custom-key/index.md
pages/cn/1.12/security/ent/secrets/custom-key/index.md

Fix link forward slash

---

docker/nginx/redirects-301.map
docker/nginx/redirects-307.map
js/services-landing.js
layouts/service-docs-landing.pug
pages/services/kubernetes/latest/index.md

Reverts mesosphere/dcos-docs-site#2356

Revert "CK Update to dynamic links"

---

pages/1.12/cli/command-reference/dcos-license/dcos-license-renew/index.md
pages/1.13/cli/command-reference/dcos-license/dcos-license-renew/index.md
pages/1.14/cli/command-reference/dcos-license/dcos-license-renew/index.md

https://jira.mesosphere.com/browse/COPS-4955

Add info about renewal to 1.12, 1.13, and 1.14.

---

pages/1.11/cli/command-reference/dcos-license/dcos-license-renew/index.md

https://jira.mesosphere.com/browse/COPS-4955
Armand requested this info about license renewal be added to 1.11.

LG/dcos-license-renew:backport info about renewing a license to 1.11

---

pages/1.13/administering-clusters/multiple-clusters/cluster-links/index.md
pages/1.13/hybrid-cloud/cluster-links/index.md
pages/1.13/installing/evaluation/community-supported-methods/azure/index.md
pages/1.13/installing/production/deploying-dcos/installation/index.md
pages/1.13/installing/production/patching/index.md
pages/1.13/networking/SDN/dcos-overlay/index.md
pages/services/marathon-lb/1.13/mlb-advanced-tutorial/index.md
pages/services/marathon-lb/1.13/mlb-basic-tutorial/index.md
pages/services/marathon-lb/1.13/mlb-install/index.md
pages/services/marathon-lb/1.13/mlb-overview/index.md
pages/services/marathon-lb/1.13/mlb-scaling-tutorial/index.md

https://jira.mesosphere.com/browse/DCOS-48197
Update internal references to 1.12 to 1.13, as appropriate.

Update 1.12 references to 1.13 

---

pages/1.11/installing/installation-faq/index.md
pages/1.12/installing/installation-faq/index.md
pages/1.13/installing/installation-faq/index.md

https://jira.mesosphere.com/browse/DCOS-54887
https://jira.mesosphere.com/browse/COPS-4966

LG/DCOS-54887: add info about restoring the iam database

---

pages/1.14/gui/catalog/index.md

https://jira.mesosphere.com/browse/DCOS-55744
Added variable for Catalog
Added new GUI images
Added new procedure for loading packages

DCOS-55744 Adding variable and new images to GUI catalog docs.

---

pages/1.12/monitoring/logging/configure-task-logs/index.md
pages/1.13/monitoring/logging/configure-task-logs/index.md
pages/1.14/monitoring/logging/configure-task-logs/index.md

https://jira.mesosphere.com/browse/DCOS-55727 
note that two options now disabled for security reasons, section deleted completely from 1.14

CK DCOS-55727

---

pages/1.13/metrics/reference/index.md
pages/1.14/metrics/reference/index.md

https://jira.mesosphere.com/browse/DCOS-55728
REPLACES https://github.com/mesosphere/dcos-docs-site/pull/2093
Add table of available metrics to ref list

CK Add procstat metrics table to 1.13 and 1.14 DCOS-55728

---

pages/1.14/data.yml
pages/services/couchbase/1.0.0-6.0.0/configuration/index.md
pages/services/couchbase/1.0.0-6.0.0/getting-started/index.md
pages/services/couchbase/1.0.0-6.0.0/index.md
pages/services/couchbase/1.0.0-6.0.0/limitations/index.md
pages/services/couchbase/1.0.0-6.0.0/operations/index.md
pages/services/couchbase/1.0.0-6.0.0/release-notes/index.md
pages/services/couchbase/1.0.0-6.0.0/security/index.md
pages/services/couchbase/1.0.0-6.0.0/supported-versions/index.md
pages/services/couchbase/1.0.0-6.0.0/troubleshooting/index.md
pages/services/couchbase/1.0.0-6.0.0/uninstall/index.md
pages/services/couchbase/data.yml
pages/services/couchbase/index.md
pages/services/couchbase/quick-start-guide/index.md
pages/services/include/community-warning.tmpl

https://jira.mesosphere.com/browse/DCOS-54563
Added metadata variables, light edits for clarity.

ss/DCOS-54563 Formatting corrections, minor edits.

---

pages/1.12/release-notes/1.12.4/index.md

https://jira.mesosphere.com/browse/DCOS-53404
This is a DOC team ticket.
WIP for producing the release notes content for DC/OS 1.12.4

Lg/rn 1.12.4-Content development for release notes

---

pages/1.13/administering-clusters/deploying-a-local-dcos-universe/index.md
pages/1.13/administering-clusters/package-registry/index.md
pages/1.14/administering-clusters/deploying-a-local-dcos-universe/index.md
pages/1.14/administering-clusters/package-registry/index.md

https://jira.mesosphere.com/browse/DCOS-50426
This PR replaces [PR2317](https://github.com/mesosphere/dcos-docs-site/pull/2317)
Updates to Administering Clusters sections.

Cleanup package registry docs

---

pages/services/edge-lb/1.3/usage/index.md

PR cleanup, Razi provided some edits to bring the page up to a generally accepted level of English 

Update edge-lb usage page with Razi's edits

---

pages/1.12/installing/production/advanced-configuration/configuration-reference/index.md
pages/1.13/installing/production/advanced-configuration/configuration-reference/index.md
pages/1.14/installing/production/advanced-configuration/configuration-reference/index.md

https://jira.mesosphere.com/browse/DCOS-55729

CK DCOS-55729 Document x-frame option

---

pages/1.13/release-notes/1.13.0/index.md
pages/1.13/release-notes/1.13.1/index.md
pages/1.13/release-notes/1.13.2/index.md

https://jira.mesosphere.com/browse/DCOS-55234
This PR has been created by moving content from https://github.com/mesosphere/dcos-docs-site/pull/2361. 

1.13.2 RN 

---

pages/1.12/release-notes/1.12.4/index.md

Final EE download link

---

pages/services/cassandra/2.4.0-3.0.16/index.md
pages/services/cassandra/2.5.0-3.11.3/index.md
pages/services/cassandra/2.6.0-3.11.4/advanced/index.md
pages/services/cassandra/2.6.0-3.11.4/api-reference/index.md
pages/services/cassandra/2.6.0-3.11.4/configuration/index.md
pages/services/cassandra/2.6.0-3.11.4/getting-started/index.md
pages/services/cassandra/2.6.0-3.11.4/index.md
pages/services/cassandra/2.6.0-3.11.4/limitations/index.md
pages/services/cassandra/2.6.0-3.11.4/operations/index.md
pages/services/cassandra/2.6.0-3.11.4/release-notes/index.md
pages/services/cassandra/2.6.0-3.11.4/security/index.md
pages/services/cassandra/2.6.0-3.11.4/support-policy/index.md
pages/services/cassandra/2.6.0-3.11.4/troubleshooting/index.md
pages/services/cassandra/2.6.0-3.11.4/uninstall/index.md
pages/services/cassandra/2.6.0-3.11.4/updates/index.md

Resolves [DCOS-54126](https://jira.mesosphere.com/browse/DCOS-54126)

[DCOS-54126] Add docs for Cassandra 2.6.0-3.11.4 release

---

pages/1.13/tutorials/dcos-101/first-app/index.md
pages/1.13/tutorials/dcos-101/first-package/index.md
pages/1.13/tutorials/dcos-101/index.md
pages/1.13/tutorials/dcos-101/native-app/index.md
pages/1.13/tutorials/dcos-101/resources/index.md
pages/1.13/tutorials/dcos-101/schedule-jobs/index.md
pages/1.13/tutorials/dcos-101/service-discovery/index.md
pages/1.13/tutorials/dcos-101/start-here/index.md

Add render and model to new sections.

---

pages/1.13/tutorials/dcos-101/first-app/index.md
pages/1.13/tutorials/dcos-101/first-package/index.md
pages/1.13/tutorials/dcos-101/index.md
pages/1.13/tutorials/dcos-101/native-app/index.md
pages/1.13/tutorials/dcos-101/resources/index.md
pages/1.13/tutorials/dcos-101/schedule-jobs/index.md
pages/1.13/tutorials/dcos-101/service-discovery/index.md
pages/1.13/tutorials/dcos-101/start-here/index.md

Reverts mesosphere/dcos-docs-site#2397

Revert "Add render and model to new sections."

---

pages/1.12/administering-clusters/repo/package-registry/operating/planning/index.md

- [x ] Make sure you change all affected versions (e.g. 1.10, 1.11, 1.12, 1.13).

Typo in bash snippet

---

pages/1.13/installing/production/advanced-configuration/configuration-reference/index.md
pages/1.13/storage/persistent-volume/index.md
pages/services/dcos-monitoring/1.0.0/operations/alertmanager/storage/index.md
pages/services/dcos-monitoring/1.0.0/operations/grafana/storage/index.md
pages/services/dcos-monitoring/1.0.0/operations/prometheus/storage/index.md
pages/services/dcos-monitoring/1.0.1/operations/alertmanager/storage/index.md
pages/services/dcos-monitoring/1.0.1/operations/grafana/storage/index.md
pages/services/dcos-monitoring/1.0.1/operations/prometheus/storage/index.md

https://jira.mesosphere.com/browse/DCOS-56108
Update links referencing DSS to point to the DSS 1.0 docs. This fix does not touch links in release notes nor docs for older DC/OS versions.

fix: update storage links to point to the DSS 1.0 docs

---

pages/services/storage/1.0.0/release-notes/index.md

https://jira.mesosphere.com/browse/DCOS-53618 (DSS GA release build)
* Fixed hidden DCOS-xxx ticket links for markdown friendliness
* Amended the release notes w/ additional known issues
* n/a
* n/a
* n/a

storage: update storage doc for 1.0.0

---

pages/services/storage/1.0.0/release-notes/index.md
pages/services/storage/1.0.0/troubleshooting/index.md

See https://github.com/mesosphere/dcos-storage/pull/593
https://jira.mesosphere.com/browse/DCOS-53616 (DSS GA epic)
Fix broken metrics lists and troubleshooting headings.
* NA
* NA
* NA

storage/1.0.0: pick edits from dcos-storage#593

---

pages/1.13/overview/concepts/index.md
pages/1.14/overview/concepts/index.md
pages/services/edge-lb/1.3/cli-reference/dcos-edgelb-create/index.md
pages/services/edge-lb/1.3/cli-reference/dcos-edgelb-delete/index.md
pages/services/edge-lb/1.3/cli-reference/dcos-edgelb-endpoints/index.md
pages/services/edge-lb/1.3/cli-reference/dcos-edgelb-lb-config/index.md
pages/services/edge-lb/1.3/cli-reference/dcos-edgelb-list/index.md
pages/services/edge-lb/1.3/cli-reference/dcos-edgelb-ping/index.md
pages/services/edge-lb/1.3/cli-reference/dcos-edgelb-show/index.md
pages/services/edge-lb/1.3/cli-reference/dcos-edgelb-status/index.md
pages/services/edge-lb/1.3/cli-reference/dcos-edgelb-template-create/index.md
pages/services/edge-lb/1.3/cli-reference/dcos-edgelb-template-delete/index.md
pages/services/edge-lb/1.3/cli-reference/dcos-edgelb-template-show/index.md
pages/services/edge-lb/1.3/cli-reference/dcos-edgelb-template-update/index.md
pages/services/edge-lb/1.3/cli-reference/dcos-edgelb-update/index.md
pages/services/edge-lb/1.3/cli-reference/dcos-edgelb-version/index.md
pages/services/edge-lb/1.3/index.md
pages/services/edge-lb/1.3/installing/index.md
pages/services/edge-lb/1.3/permissions/index.md
pages/services/edge-lb/1.3/pool-configuration/index.md
pages/services/edge-lb/1.3/release-notes/index.md
pages/services/edge-lb/1.3/tutorials/multi-lb/index.md
pages/services/edge-lb/1.3/tutorials/single-lb/index.md
pages/services/edge-lb/1.3/usage/index.md
pages/services/spinnaker/0.3.0-1.9.2/overview/edgelb/index.md
pages/services/spinnaker/0.3.1-1.9.2/overview/edgelb/index.md

https://jira.mesosphere.com/browse/DCOS-55995

Change 1.2 to 1.3 in links.

---

pages/services/storage/1.0.0/upgrades/index.md

See https://github.com/mesosphere/dcos-storage/pull/595
https://jira.mesosphere.com/browse/DCOS-53616 (DSS GA epic)
Remove leading `$` from example; removed more backticks from section headers
* NA
* NA
* NA

storage/1.0.0: pick edits from dcos-storage#595

---

pages/1.14/cli/command-reference/dcos-config/dcos-config-keys/index.md

https://jira.mesosphere.com/browse/DCOS-55951

Added documentation for 'dcos config keys'.

---

pages/1.11/deploying-services/fault-domain-awareness/index.md
pages/1.12/deploying-services/fault-domain-awareness/index.md
pages/1.13/deploying-services/fault-domain-awareness/index.md
pages/1.13/deploying-services/scale-service/index.md
pages/1.13/deploying-services/update-user-service/index.md
pages/1.14/deploying-services/fault-domain-awareness/index.md
pages/1.14/deploying-services/scale-service/index.md

https://jira.mesosphere.com/browse/DCOS_OSS-3166

CK DCOS_OSS-3166 Add EE label for fault awareness

---

pages/1.11/overview/telemetry/index.md
pages/1.12/overview/telemetry/index.md
pages/1.13/overview/telemetry/index.md
pages/1.14/overview/telemetry/index.md

* [DCOS-56236](https://jira.mesosphere.com/browse/DCOS-56236)
* [DCOS-55882](https://jira.mesosphere.com/browse/DCOS-55882)

Add licenseID to telemetry documentation

---

pages/1.11/installing/production/system-requirements/index.md
pages/1.12/installing/production/system-requirements/index.md
pages/1.13/installing/production/system-requirements/index.md

**Note: I carefully picked through subsequent edits to these pages between Jan-Jul**

Add cops-4064 edits back in

---

pages/1.11/installing/production/system-requirements/index.md
pages/1.12/installing/production/system-requirements/index.md
pages/1.13/installing/production/system-requirements/index.md
pages/1.14/installing/production/system-requirements/index.md

Addition to https://github.com/mesosphere/dcos-docs-site/pull/2416

Update 1.14 page

---

pages/services/cassandra/2.4.0-3.0.16/operations/index.md
pages/services/cassandra/2.5.0-3.11.3/operations/index.md

Resolves [DCOS-33132](https://jira.mesosphere.com/browse/DCOS-33132)
&  [DCOS-55313](https://jira.mesosphere.com/browse/DCOS-55313)

[DCOS-33132] Cassandra Backup Docs Don't Mention Session Token

---

pages/1.14/cli/command-reference/dcos-task/dcos-task-list/index.md
pages/1.14/cli/command-reference/dcos-task/index.md

https://jira.mesosphere.com/browse/DCOS-56332
* Added `dcos task list` README.md.
* Added documentation about `dcos task --agent-id`.

Added documentation for dcos task list.

---

layouts/dcos-docs-landing.pug
pages/1.13/storage/include/dss-box.md
pages/1.13/storage/index.md
pages/1.14/storage/include/dss-box.md
pages/1.14/storage/index.md
scss/components/_grid.scss

https://jira.mesosphere.com/browse/DCOS-56245

Hack a box fix for DSS DCOS-56245

---

layouts/components/content-grid.pug

Fix display

---

pages/1.10/overview/architecture/task-types/index.md
pages/1.9/overview/architecture/task-types/index.md

Correct to Tasks

---

Makefile
docker-compose.yml

Update docker-compose volumes

---

pages/1.12/cli/command-reference/dcos-task/dcos-task-log/index.md
pages/1.13/cli/command-reference/dcos-task/dcos-task-log/index.md
pages/1.14/cli/command-reference/dcos-task/dcos-task-log/index.md

Add dcos task log --all to ref table for 1.12, 1.13, 1.14

---

pages/services/edge-lb/1.2/api-reference/edgelb/index.md
pages/services/edge-lb/1.2/pool-configuration/index.md
pages/services/edge-lb/1.3/api-reference/edgelb/index.md
pages/services/edge-lb/1.3/pool-configuration/index.md
pages/services/edge-lb/1.3/tutorials/single-lb/index.md
pages/services/edge-lb/1.4/api-reference/edgelb/index.md
pages/services/edge-lb/1.4/pool-configuration/index.md

Link fixes

---

pages/1.13/release-notes/1.13.3/index.md

https://jira.mesosphere.com/browse/DCOS-56224
- [n/a] Make sure you change all affected versions (1.13 only).

Add placeholder for 1.13.3 release notes.

---

pages/services/cassandra/2.6.0-3.11.4/configuration/index.md

Resolves [DCOS-55432](https://jira.mesosphere.com/browse/DCOS-55432)

[DCOS-55432] Add docs for DSS support, including volume profiles, to Cassandra

---

pages/1.14/cli/command-reference/dcos-quota/dcos-quota-create/index.md
pages/1.14/cli/command-reference/dcos-quota/dcos-quota-delete/index.md
pages/1.14/cli/command-reference/dcos-quota/dcos-quota-get/index.md
pages/1.14/cli/command-reference/dcos-quota/dcos-quota-update/index.md
pages/1.14/cli/command-reference/dcos-quota/index.md

https://jira.mesosphere.com/browse/DCOS-56459
Added the new 1.14 `dcos quota` command reference.

Added documentation about dcos quota.

---

pages/1.14/cli/command-reference/dcos-node/dcos-node-list/index.md

https://jira.mesosphere.com/browse/DCOS_OSS-5361
- Added ` --mesos-id` option.
- Added `STATUS` column.

Added --mesos-id and STATUS to dcos node list.

---

pages/1.14/cli/command-reference/dcos-node/dcos-node-deactivate/index.md
pages/1.14/cli/command-reference/dcos-node/dcos-node-drain/index.md
pages/1.14/cli/command-reference/dcos-node/dcos-node-reactivate/index.md

https://jira.mesosphere.com/browse/DCOS_OSS-5362
Added the three new subcommands used for node draining.

Added node draining subcommands.

---

scss/components/_grid-toc.scss
scss/pages/_landing.scss

Initial mobile styling commit

---

pages/services/edge-lb/1.4/permissions/index.md

https://jira.mesosphere.com/browse/DCOS-47769

updates Edge-LB permission for v1.4.0

---

pages/1.14/cli/command-reference/dcos-quota/dcos-quota-create/index.md
pages/1.14/cli/command-reference/dcos-quota/dcos-quota-list/index.md
pages/1.14/cli/command-reference/dcos-quota/dcos-quota-update/index.md

https://jira.mesosphere.com/browse/DCOS_OSS-5377
Update the `dcos quota` command reference following a code update.

Updated command reference for dcos quota.

---

pages/version-policy/index.md

https://jira.mesosphere.com/browse/DCOS_OSS-5378
Update CLI support matrix, my editor also removed unnecessary white spaces.

Updated CLI support matrix.

---

pages/install-include/aws-tf-faq-all.tmpl

https://jira.mesosphere.com/browse/DCOS-54132

short known issue to the time sync related certificate error

---

pages/services/data-science-engine/1.0.0/hdfs/index.md

https://jira.mesosphere.com/browse/DCOS-57166
* Updates the HDFS integration section
* Updates the S3 section of HDFS page

[DCOS-57166] Add/review documentation for HDFS integration

---

pages/services/data-science-engine/1.0.0/examples/index.md

https://jira.mesosphere.com/browse/DCOS-57161
- Adds example of advance section
https://github.com/mesosphere/dcos-docs-site/pull/2452

[DCOS-57161] Add advance section example

---

pages/services/data-science-engine/1.0.0/security/index.md

[DCOS-57168: Add/review documentation for strict mode(https://jira.mesosphere.com/browse/DCOS-57168)
Updated strict mode doc to include the necessary permissions and secrets configuration required to operate in strict mode clusters

DSEngine strict mode

---

pages/services/data-science-engine/1.0.0/hdfs/index.md
pages/services/data-science-engine/1.0.0/kerberos/index.md

https://jira.mesosphere.com/browse/DCOS-57276
* Updates kerberos configurations

[DCOS-57276] Add documentation for Kerberos support

---

pages/services/data-science-engine/1.0.0/security/index.md
pages/services/data-science-engine/data.yml

[DCOS-57163 - [MJS] Add documentation for OpenID configuration](https://jira.mesosphere.com/browse/DCOS-57163)
Adds a section on authentication methods (password and OpenID) to Security page.

[DCOS-57163] Add documentation for OpenID configuration

---

pages/services/data-science-engine/1.0.0/hdfs/index.md
pages/services/data-science-engine/1.0.0/spark/index.md

[DCOS-57164 [MJS] Add documentation for enabling Driver/History UI](https://jira.mesosphere.com/browse/DCOS-57164)
- Updated SHS configuration section
- Added `Spark UI` section with a basic description

Update docs for SHS and Spark UI

---

index.js
layouts/404.pug
layouts/all-products-landing.pug
layouts/partials/header/dcos-cn-header.pug
layouts/partials/header/dcos-en-header.pug
layouts/partials/header/header-dropdown.pug
layouts/partials/header/konvoy-header.pug
scss/base/_header-dropdown.scss
scss/base/_header.scss
scss/components/_chooser.scss

V2 Mobile dropdown

---

pages/ksphere/konvoy/partner-solutions/aqua/index.md
pages/ksphere/konvoy/partner-solutions/confluent/index.md
pages/ksphere/konvoy/partner-solutions/mongodb/index.md

Update partner sols

---

layouts/all-products-landing.pug
layouts/konvoy-docs-landing.pug
scss/base/_header.scss
scss/pages/_landing.scss

Update Konvoy: footers and desc and header

---

pages/mesosphere/dcos/services/edge-lb/1.4/tutorials/customizing-templates/index.md

This replaces https://github.com/mesosphere/dcos-docs-site/pull/2473

Add Edge tutorial PR#2473

---

assets/robots.txt
docker/Dockerfile.production

the robots are coming

---

pages/mesosphere/dcos/services/data-science-engine/1.0.0/security/index.md
pages/mesosphere/dcos/services/include/service-account.tmpl

because sometimes it's easier to start over

Redo of DCOS-56536

---

pages/mesosphere/dcos/install-include/all-create-first-cluster.tmpl
pages/mesosphere/dcos/install-include/all-upgrade-cluster.tmpl

https://jira.mesosphere.com/browse/DCOS-57569
- added `-upgrade` to the terraform init statement. This will make sure users get beside the latest versions of the modules also the latest versions of the used providers

added -upgrade to terraform init and -update for upgrading process

---

pages/ksphere/konvoy/latest/release-notes/index.md

update release date and version konvoy

---

pages/ksphere/konvoy/latest/release-notes/index.md

Add the missing release notes for v1.1.0.

konvoy: add the missing release notes for v1.1.0

---

pages/mesosphere/dcos/version-policy/index.md

Forgot to update the version policy doc after merging PRs #2486, #2501, and #2502. This PR updates the versions to our official policy of supporting N-1 versions of a base-tech

Update version policy page with new package versions

---

pages/mesosphere/dcos/1.14/gui/catalog/index.md

https://jira.mesosphere.com/browse/DCOS-57843
Code is exposed in Community catalog section showing image.
Change made to 1.14 version ONLY; earlier DC/OS versions do not have this text. Local build was successful and correct.

ss/DCOS-57843 Correcting exposed code.

---

pages/mesosphere/dcos/1.14/deploying-services/creating-services/health-checks/index.md

[DCOS-57785](https://jira.mesosphere.com/browse/DCOS-57785)
This PR updates the health check documentation with some concrete recommendations which were the result of recent testing done for [DCOS-54958](https://jira.mesosphere.com/browse/DCOS-54958).

Updated health check documentation with recommendations.

---

pages/ksphere/konvoy/partner-solutions/minio/index.md

https://jira.mesosphere.com/browse/DCOS-58347
some links in the minio document had to be updated

minio doc updated links

---

pages/mesosphere/dcos/1.13/release-notes/1.13.4/index.md

https://jira.mesosphere.com/browse/DCOS-58337
New release notes for DC/OS 1.13.4

Release notes for 1.13.4

---

pages/mesosphere/dcos/services/include/advanced.tmpl
pages/mesosphere/dcos/services/include/api-reference.tmpl
pages/mesosphere/dcos/services/include/configuration-create-json-file.tmpl
pages/mesosphere/dcos/services/include/configuration-install-with-options.tmpl
pages/mesosphere/dcos/services/include/deployment-best-practices.tmpl
pages/mesosphere/dcos/services/include/getting-started.tmpl
pages/mesosphere/dcos/services/include/managing.tmpl
pages/mesosphere/dcos/services/include/operations.tmpl
pages/mesosphere/dcos/services/include/security-create-permissions.tmpl
pages/mesosphere/dcos/services/include/security-service-keytab.tmpl
pages/mesosphere/dcos/services/include/security-transport-encryption-clients.tmpl
pages/mesosphere/dcos/services/include/troubleshooting.tmpl
pages/mesosphere/dcos/services/include/uninstall.tmpl
pages/mesosphere/dcos/services/include/update.tmpl

https://jira.mesosphere.com/browse/DCOS-54586
Review and edit all service/include files to delete prompts which have the $ at the beginning of the line. These prompts are copied with the rest of the command, which is supposed to be pasted into users' CLI, but the $ sign interferes with this.
THESE CHANGES AFFECT ALL DOCUMENTATION WHICH CALLS THESE WITH #include command.

ss/DCOS-54586 Removing $ from prompts, other minor edits.

---

pages/mesosphere/dcos/services/data-science-engine/1.0.0/supported-kernels/index.md

https://jira.mesosphere.com/browse/DCOS-57952
- Adds a section to launch Spark Job using BeakerX Magic

Adds a section to launch Spark job using BeakerX Magic

---

pages/mesosphere/dcos/1.13/installing/production/patching/index.md
pages/mesosphere/dcos/1.13/installing/production/upgrading/index.md
pages/mesosphere/dcos/version-policy/index.md

https://jira.mesosphere.com/browse/DCOS-57957
Just need to update the Upgrading, Patching, and Version Policy pages for 1.13.4

Dcos 57957

---

CODEOWNERS

fix: codeowners file

---

pages/mesosphere/dcos/1.10/installing/evaluation/community-supported-methods/aws/index.md
pages/mesosphere/dcos/1.10/installing/evaluation/community-supported-methods/azure/index.md
pages/mesosphere/dcos/1.10/installing/evaluation/community-supported-methods/digitalocean/index.md
pages/mesosphere/dcos/1.11/installing/evaluation/community-supported-methods/aws/index.md
pages/mesosphere/dcos/1.11/installing/evaluation/community-supported-methods/azure/index.md
pages/mesosphere/dcos/1.11/installing/evaluation/community-supported-methods/digitalocean/index.md
pages/mesosphere/dcos/1.12/installing/evaluation/community-supported-methods/aws/index.md
pages/mesosphere/dcos/1.12/installing/evaluation/community-supported-methods/azure/index.md
pages/mesosphere/dcos/1.12/installing/evaluation/community-supported-methods/digitalocean/index.md
pages/mesosphere/dcos/1.13/installing/evaluation/community-supported-methods/aws/index.md
pages/mesosphere/dcos/1.13/installing/evaluation/community-supported-methods/azure/index.md
pages/mesosphere/dcos/1.13/installing/evaluation/community-supported-methods/digitalocean/index.md
pages/mesosphere/dcos/1.14/installing/evaluation/community-supported-methods/aws/index.md
pages/mesosphere/dcos/1.14/installing/evaluation/community-supported-methods/azure/index.md
pages/mesosphere/dcos/1.14/installing/evaluation/community-supported-methods/digitalocean/index.md

Co/cops 5367 - update disclaimer

---

pages/mesosphere/dcos/1.10/administering-clusters/deploying-a-local-dcos-universe/index.md
pages/mesosphere/dcos/1.11/administering-clusters/deploying-a-local-dcos-universe/index.md
pages/mesosphere/dcos/1.12/administering-clusters/deploying-a-local-dcos-universe/index.md
pages/mesosphere/dcos/1.13/administering-clusters/deploying-a-local-dcos-universe/index.md
pages/mesosphere/dcos/1.14/administering-clusters/deploying-a-local-dcos-universe/index.md
pages/mesosphere/dcos/1.9/administering-clusters/deploying-a-local-dcos-universe/index.md
pages/mesosphere/dcos/cn/1.11/administering-clusters/deploying-a-local-dcos-universe/index.md
pages/mesosphere/dcos/cn/1.12/administering-clusters/deploying-a-local-dcos-universe/index.md

[DCOS-58811](https://jira.mesosphere.com/browse/DCOS-58811)

Replace the cloudfront URL with absolute s3 path for local universe

---

pages/mesosphere/dcos/1.13/administering-clusters/package-registry/index.md
pages/mesosphere/dcos/1.14/administering-clusters/package-registry/index.md

[COPS-5375](https://jira.mesosphere.com/browse/COPS-5375)

Add notes on CLI usage for dcos-registry

---

pages/mesosphere/dcos/1.13/installing/production/patching/index.md
pages/mesosphere/dcos/1.13/installing/production/upgrading/index.md

Updating Upgrading and Patching pages for 1.13.5

---

pages/mesosphere/dcos/1.11/release-notes/1.11.12/index.md

https://jira.mesosphere.com/browse/DCOS-59338
Adding release notes for 1.11.12 patch release.

ss/DCOS-59338 Adding release notes.

---

pages/mesosphere/dcos/1.11/installing/production/patching/index.md
pages/mesosphere/dcos/1.11/installing/production/upgrading/index.md
pages/mesosphere/dcos/1.12/installing/production/upgrading/index.md
pages/mesosphere/dcos/1.13/installing/production/upgrading/index.md

Made changes to reflect 1.11.12 testing

---

pages/mesosphere/dcos/services/kafka/2.4.0-1.1.1/started/index.md
pages/mesosphere/dcos/services/kafka/2.8.0-2.3.0/started/index.md

https://jira.mesosphere.com/browse/COPS-5317
The Kafka broker port configuration section was out-dated and confusing for the users.

[COPS-5317] update the kafka broker configuration explanation

---

scss/base/_header.scss

Requested by design to add in margins to header logo to match marketing site
Still some question as to wordmark letter spacing, design has ticket to provide updated logo when they can
https://jira.mesosphere.com/browse/DCOS-60033

Update header logo margins DCOS-60033

---

pages/mesosphere/dcos/1.10/installing/production/system-requirements/azure-recommendations/index.md
pages/mesosphere/dcos/1.12/installing/production/system-requirements/custom-ami/index.md
pages/mesosphere/dcos/1.13/administering-clusters/sshcluster/index.md
pages/mesosphere/dcos/1.13/deploying-services/marathon-on-marathon/advanced/index.md
pages/mesosphere/dcos/1.13/installing/production/system-requirements/index.md
pages/mesosphere/dcos/1.13/overview/concepts/index.md
pages/mesosphere/dcos/1.13/overview/design/installation/index.md
pages/mesosphere/dcos/1.13/storage/external-storage/index.md
pages/mesosphere/dcos/2.0/administering-clusters/sshcluster/index.md
pages/mesosphere/dcos/2.0/installing/evaluation/community-supported-methods/azure/index.md
pages/mesosphere/dcos/install-include/aws-extended-example.tmpl
pages/mesosphere/dcos/install-include/azure-extended-example.tmpl
pages/mesosphere/dcos/install-include/gcp-extended-example.tmpl
pages/mesosphere/dcos/version-policy/index.md

https://jira.mesosphere.com/browse/DCOS-58988

Made modifications to reflect our noncoverage of CoreOS in 2.0

---

pages/mesosphere/dcos/services/edge-lb/1.5/release-notes/index.md

[DCOS-60078](https://jira.mesosphere.com/browse/DCOS-60078)
Minor edits discovered after edgelb 1.5 release

edgelb: post 1.5 release doc updates

---

pages/ksphere/konvoy/latest/install/install-aws/advanced-provisioning/index.md
pages/ksphere/konvoy/latest/install/install-aws/index.md
pages/ksphere/konvoy/latest/install/install-dev/index.md
pages/ksphere/konvoy/latest/install/install-onprem/index.md
pages/ksphere/konvoy/latest/quick-start/index.md
pages/ksphere/konvoy/latest/reference/cluster-configuration/index.md
pages/ksphere/konvoy/latest/reference/command-line-interface/konvoy-init/index.md
pages/ksphere/konvoy/latest/reference/command-line-interface/konvoy-provision/index.md
pages/ksphere/konvoy/latest/reference/command-line-interface/konvoy-up/index.md
pages/ksphere/konvoy/latest/release-notes/index.md
pages/ksphere/konvoy/latest/tutorials/provision-a-custom-cluster/index.md
pages/ksphere/konvoy/latest/upgrade/upgrade-kubernetes/index.md

https://jira.mesosphere.com/browse/DCOS-60254
Release Notes and some minor additions for Konvoy docs.

konvoy: Update docs for konvoy release

---

pages/mesosphere/dcos/2.0/installing/production/upgrading/index.md

Fixed Upgrade Chart for 2.0

---

pages/mesosphere/dcos/2.0/cli/command-reference/dcos-node/dcos-node-diagnostics-create/index.md
pages/mesosphere/dcos/2.0/cli/command-reference/dcos-node/dcos-node-diagnostics-delete/index.md
pages/mesosphere/dcos/2.0/cli/command-reference/dcos-node/dcos-node-diagnostics-download/index.md
pages/mesosphere/dcos/2.0/cli/command-reference/dcos-node/dcos-node-diagnostics/index.md
pages/mesosphere/dcos/2.0/deploying-services/pods/technical-overview/index.md
pages/mesosphere/dcos/2.0/release-notes/2.0.0/index.md

https://jira.mesosphere.com/browse/DCOS-60191
Add changes from Changelog, JIRA tickets, etc. to Release Notes for 2.0.

Release notes for 2.0.

---

config.json
docker/nginx/redirects-307.map
index.js

https://jira.mesosphere.com/browse/DCOS-59909
Merge PR
Let staging build complete
Promote staging to master

Publish DC/OS 2.0 Docs to Prod

---

pages/mesosphere/dcos/2.0/release-notes/2.0.0/index.md

https://jira.mesosphere.com/browse/DCOS-60191
This update corrects a couple of minor typos in the Release Notes for DC/OS 2.0.0.

DCOS-60191 Fixing minor typos in Release Notes for 2.0.0.

---

pages/mesosphere/dcos/services/edge-lb/1.5/release-notes/index.md

https://jira.mesosphere.com/browse/DCOS-60623
Adding release date, checking spelling and formatting.

ss/DCOS-60623 Added release date, fixed spelling and formatting.

---

pages/ksphere/konvoy/partner-solutions/styra/index.md

https://jira.mesosphere.com/browse/DCOS-60580
Documentation for the Styra partner solution. This is a new partner.

initial styra partner solution documentation

---

pages/ksphere/kommander/latest/administrating/cloud-providers/index.md

Add stand-alone page for cloud-providers with information
for adding & deleting

feat: cloud providers page

---

pages/ksphere/konvoy/partner-solutions/styra/index.md

https://jira.mesosphere.com/browse/DCOS-60580
Fixing menu weight, and link for styra partner docs.

partner solution styra: fixed menu weight, and link which had to be email address

---

pages/mesosphere/dcos/1.13/gui/services/index.md

https://jira.mesosphere.com/browse/DCOS-60581
Source: https://docs.d2iq.com/mesosphere/dcos/2.0/gui/services/
Link to last image on page is broken.

ss/DCOS-60581 Fixing broken image link.

---

pages/mesosphere/dcos/2.0/multi-tenancy/quota-management/index.md

Fix typo : enforeceRole to enforceRole

---

pages/mesosphere/dcos/1.11/networking/SDN/dcos-overlay/index.md
pages/mesosphere/dcos/1.12/networking/SDN/dcos-overlay/index.md
pages/mesosphere/dcos/1.13/networking/SDN/dcos-overlay/index.md
pages/mesosphere/dcos/2.0/networking/SDN/dcos-overlay/index.md

replace `&lt;cluster-name&gt` with `<>`  in three backticks. 
The original `&lt;cluster-name&gt` will present the following result to us, which is not expected.

remove invalid symbols

---

pages/ksphere/kommander/latest/clusters/index.md

Added bullet about cloud provider tags to the create cluster
form section.
[DCOS-60442](https://jira.mesosphere.com/browse/DCOS-60442)

feat(tags): add item for tags

---

pages/mesosphere/dcos/version-policy/index.md

https://jira.mesosphere.com/browse/DCOS-60944
See PR

[DCOS-60944] Remove duplicate Elastic entry

---

pages/mesosphere/dcos/version-policy/index.md

https://jira.mesosphere.com/browse/DCOS-61050

Updated docs with 2.0 OS Qualificaiton

---

pages/mesosphere/dcos/version-policy/index.md

Updating the Support Qualification Matrix with testing that is in progress.

Updating Qualification Matrix with In Progress Testing

---

pages/mesosphere/dcos/2.0/release-notes/2.0.0/index.md

The DC/OS 2.0 release notes contain a reference to `sales@mesosphere.com` which in my opinion should be `sales@d2iq.com`
https://jira.mesosphere.com/browse/COPS-5566

Update index.md with D2iQ email address

---

pages/mesosphere/dcos/1.12/installing/production/deploying-dcos/installation/index.md
pages/mesosphere/dcos/1.13/installing/production/deploying-dcos/installation/index.md
pages/mesosphere/dcos/2.0/installing/production/deploying-dcos/installation/index.md
pages/mesosphere/dcos/2.1/installing/production/deploying-dcos/installation/index.md
pages/mesosphere/dcos/cn/1.12/installing/production/deploying-dcos/installation/index.md

https://jira.mesosphere.com/browse/COPS-4330
An example script has a couple minor mistakes such as setting a variable then not using it.

Fixing incorrect script example - COPS-4330

---

pages/mesosphere/dcos/1.13/deploying-services/gpu/index.md
pages/mesosphere/dcos/1.13/installing/production/advanced-configuration/configuration-reference/index.md
pages/mesosphere/dcos/2.0/deploying-services/gpu/index.md
pages/mesosphere/dcos/2.0/installing/production/advanced-configuration/configuration-reference/index.md
pages/mesosphere/dcos/2.1/deploying-services/gpu/index.md
pages/mesosphere/dcos/2.1/installing/production/advanced-configuration/configuration-reference/index.md

https://jira.mesosphere.com/browse/COPS-5112
Adding missing GPU scheduling params.

Adding missing GPU scheduling params - COPS-5112

---

pages/mesosphere/dcos/services/kubernetes/2.4.0-1.15.1/operations/private-docker-registry/index.md
pages/mesosphere/dcos/services/kubernetes/2.4.1-1.15.2/operations/private-docker-registry/index.md
pages/mesosphere/dcos/services/kubernetes/2.4.2-1.15.3/operations/private-docker-registry/index.md
pages/mesosphere/dcos/services/kubernetes/2.4.3-1.15.3/operations/private-docker-registry/index.md
pages/mesosphere/dcos/services/kubernetes/2.4.4-1.15.4/operations/private-docker-registry/index.md
pages/mesosphere/dcos/services/kubernetes/2.4.5-1.15.5/operations/private-docker-registry/index.md

https://jira.mesosphere.com/browse/COPS-5082
Fixing private Docker repo documentation for MKE.

Fixing private Docker repo documentation for MKE - COPS-5082

---

pages/mesosphere/dcos/2.0/multi-tenancy/quota-management/index.md

https://jira.mesosphere.com/browse/DCOS_OSS-5627
Correct a few errors and help improve consistency of the documentation.

Correct outdated Marathon quota-related information

---

pages/mesosphere/dcos/1.12/deploying-jobs/quickstart/index.md
pages/mesosphere/dcos/1.13/deploying-jobs/quickstart/index.md
pages/mesosphere/dcos/2.0/deploying-jobs/quickstart/index.md

JIRA issues: DCOS-48109
Added documentation for maxLaunchDelay, restart policy and TaskKillGracePeriod

Updated Metronome documentation

---

pages/mesosphere/dcos/2.0/release-notes/2.0.1/index.md

https://jira.mesosphere.com/browse/DCOS-61136

co/dcos-61136 (2.0.1 release notes) 

---

pages/mesosphere/dcos/services/elastic/2.7.0-6.8.1/configuration/index.md
pages/mesosphere/dcos/services/elastic/2.7.0-6.8.1/limitations/index.md
pages/mesosphere/dcos/services/elastic/2.7.0-6.8.1/security/index.md
pages/mesosphere/dcos/services/elastic/3.0.0-7.3.2/configuration/index.md
pages/mesosphere/dcos/services/elastic/3.0.0-7.3.2/security/index.md

https://jira.mesosphere.com/browse/DCOS-59963
https://jira.mesosphere.com/browse/DCOS-58552
[Elastic] Remove mention of unsupported X-Pack authz and authn
[Elastic] Document DC/OS 1.11 Kibana Admin router integration limitation

[DCOS-59963] [Elastic] Remove mention of unsupported X-Pack authz and authn

---

pages/mesosphere/dcos/1.12/installing/production/system-requirements/docker-centos/index.md
pages/mesosphere/dcos/1.13/installing/production/system-requirements/docker-centos/index.md
pages/mesosphere/dcos/2.0/installing/production/system-requirements/docker-centos/index.md
pages/mesosphere/dcos/2.1/installing/production/system-requirements/docker-centos/index.md

https://jira.mesosphere.com/browse/COPS-4589
* Adjusting recommendations to align with both the advisory and out version-policy page.
* Adding note about the second kmem bug.

Correcting Docker recommendations related to kmem bug and adding note about the second kmem bug - COPS-4589

---

pages/ksphere/konvoy/latest/download/index.md
pages/ksphere/konvoy/latest/quick-start/index.md

https://jira.mesosphere.com/browse/DCOS-60737
Adding download topic to Konvoy docs. 

CO/60737 - New Download Topic for Konvoy

---

pages/ksphere/konvoy/latest/download/index.md

fixing links in download topic

---

pages/ksphere/konvoy/latest/download/index.md

fixed missing tag (again)

---

pages/mesosphere/dcos/1.11/release-notes/1.11.0-rc1/index.md
pages/mesosphere/dcos/1.11/release-notes/1.11.0-rc4/index.md
pages/mesosphere/dcos/1.11/release-notes/1.11.0/index.md
pages/mesosphere/dcos/1.11/release-notes/1.11.1/index.md
pages/mesosphere/dcos/1.11/release-notes/1.11.10/index.md
pages/mesosphere/dcos/1.11/release-notes/1.11.11/index.md
pages/mesosphere/dcos/1.11/release-notes/1.11.12/index.md
pages/mesosphere/dcos/1.11/release-notes/1.11.13/index.md
pages/mesosphere/dcos/1.11/release-notes/1.11.2/index.md
pages/mesosphere/dcos/1.11/release-notes/1.11.3/index.md
pages/mesosphere/dcos/1.11/release-notes/1.11.4/index.md
pages/mesosphere/dcos/1.11/release-notes/1.11.5/index.md
pages/mesosphere/dcos/1.11/release-notes/1.11.6/index.md
pages/mesosphere/dcos/1.11/release-notes/1.11.7/index.md
pages/mesosphere/dcos/1.11/release-notes/1.11.8/index.md
pages/mesosphere/dcos/1.11/release-notes/1.11.9/index.md

https://jira.mesosphere.com/browse/DCOS-61492

changing release note menu weights to put in correct TOC order

---

pages/mesosphere/dcos/1.10/installing/production/advanced-configuration/configuration-reference/index.md
pages/mesosphere/dcos/1.11/installing/production/advanced-configuration/configuration-reference/index.md
pages/mesosphere/dcos/1.12/installing/production/advanced-configuration/configuration-reference/index.md
pages/mesosphere/dcos/1.13/installing/production/advanced-configuration/configuration-reference/index.md
pages/mesosphere/dcos/2.0/installing/production/advanced-configuration/configuration-reference/index.md
pages/mesosphere/dcos/2.1/installing/production/advanced-configuration/configuration-reference/index.md

https://jira.mesosphere.com/browse/COPS-4958
* Correcting note about static IPs in AWS. This reverts an earlier change in the documentation of the parameter master_discovery.

Correcting note about static IPs in AWS - COPS-4958

---

pages/mesosphere/dcos/services/nifi/0.1.0-1.5.0/index.md
pages/mesosphere/dcos/services/nifi/0.2.0-1.5.0/index.md
pages/mesosphere/dcos/services/nifi/0.3.0-1.7.1/index.md
pages/mesosphere/dcos/services/nifi/0.4.0-1.8.0/index.md
pages/mesosphere/dcos/services/nifi/0.4.1-1.8.0/index.md
pages/mesosphere/dcos/services/nifi/0.5.0-1.9.2/index.md

https://jira.mesosphere.com/browse/DCOS-61745

Adjust menuweights in top level page of each version in NiFi

---

pages/mesosphere/dcos/1.12/overview/architecture/distributed-process-management/index.md
pages/mesosphere/dcos/1.13/overview/architecture/distributed-process-management/index.md
pages/mesosphere/dcos/2.0/overview/architecture/distributed-process-management/index.md
pages/mesosphere/dcos/2.1/overview/architecture/distributed-process-management/index.md

https://jira.mesosphere.com/browse/DCOS-62121

Add image in distributed process management page

---

pages/mesosphere/dcos/1.10/administering-clusters/deploying-a-local-dcos-universe/index.md
pages/mesosphere/dcos/1.11/administering-clusters/deploying-a-local-dcos-universe/index.md
pages/mesosphere/dcos/1.12/administering-clusters/deploying-a-local-dcos-universe/index.md
pages/mesosphere/dcos/1.13/administering-clusters/deploying-a-local-dcos-universe/index.md
pages/mesosphere/dcos/1.9/administering-clusters/deploying-a-local-dcos-universe/index.md
pages/mesosphere/dcos/2.0/administering-clusters/deploying-a-local-dcos-universe/index.md
pages/mesosphere/dcos/2.1/administering-clusters/deploying-a-local-dcos-universe/index.md
pages/mesosphere/dcos/services/nifi/configure-dcos-access/index.md

https://jira.mesosphere.com/browse/COPS-4669

Add sudo to command in local universe documentation

---

pages/mesosphere/dcos/version-policy/index.md

Updated the Version Policy Page for RHEL 8.0 and CentOS 8.0

---

pages/mesosphere/dcos/2.0/release-notes/legal-notices/index.md

https://jira.mesosphere.com/browse/DCOS-61784?filter=-1 

Added folder and file for Legal Notices

---

pages/mesosphere/dcos/services/dcos-monitoring/1.1.0/cli-references/index.md

https://jira.mesosphere.com/browse/COPS-5572

Fix typo (desribe instead of describe)

---

pages/mesosphere/dcos/1.12/administering-clusters/repo/package-registry/quickstart/index.md

https://jira.mesosphere.com/browse/DCOS-61080

Fix wrong default URL for Package Registry

---

pages/mesosphere/dcos/1.13/administering-clusters/package-registry/index.md
pages/mesosphere/dcos/2.0/administering-clusters/package-registry/index.md
pages/mesosphere/dcos/2.1/administering-clusters/package-registry/index.md

https://jira.mesosphere.com/browse/DCOS-60729

fix inconsistent secret naming

---

pages/mesosphere/dcos/services/jenkins/3.5.2-2.107.2/quickstart/index.md
pages/mesosphere/dcos/services/jenkins/3.5.2-2.107.2/upgrade/index.md
pages/mesosphere/dcos/services/jenkins/3.5.3-2.150.1/quickstart/index.md
pages/mesosphere/dcos/services/jenkins/3.5.3-2.150.1/upgrade/index.md
pages/mesosphere/dcos/services/jenkins/3.5.4-2.150.1/quickstart/index.md
pages/mesosphere/dcos/services/jenkins/3.5.4-2.150.1/upgrade/index.md

https://jira.mesosphere.com/browse/DCOS-50384

Links correction

---

pages/mesosphere/dcos/services/edge-lb/1.5/release-notes/index.md

https://jira.mesosphere.com/browse/DCOS-62290
This commit adds the release notes for the EdgeLB v1.5.1 minor release (https://github.com/mesosphere/dcos-edge-lb/releases/tag/v1.5.1)

Adding release notes for v1.5.1

---

pages/mesosphere/dcos/2.0/release-notes/2.0.0/index.md
pages/mesosphere/dcos/2.0/release-notes/legal-notices/index.md

https://jira.mesosphere.com/browse/DCOS-62209?filter=-2
Changes made in this PR are only for the Release Notes main page and the Legal Notices page.

Dcos 62209

---

pages/mesosphere/dcos/services/beta-jupyter/1.2.0-0.33.7-beta/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.0/integrations/spark/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.0/supported-kernels/index.md

https://jira.mesosphere.com/browse/DCOS-56413

Add model in index.md to display variable value in landing page

---

pages/mesosphere/dcos/1.12/deploying-services/gpu/index.md
pages/mesosphere/dcos/1.13/deploying-services/gpu/index.md
pages/mesosphere/dcos/2.0/deploying-services/gpu/index.md
pages/mesosphere/dcos/2.1/deploying-services/gpu/index.md

https://jira.mesosphere.com/browse/COPS-4559
* Replacing old zen.sh GPU-enabled cluster build with the DC/OS Universal Installer.

Replacing old zen.sh GPU-enabled cluster build with the DC/OS Universal Installer - COPS-4559

---

pages/mesosphere/dcos/2.0/release-notes/2.0.1/index.md

https://jira.mesosphere.com/browse/DCOS-62552
- Gather and send english
- receive translated files
- Work with Translations.com to ensure accurate translation
- Import new files for publishing
- Publish

ss/DCOS-62552 Fixes for DC/OS 2.0.1 Release Notes

---

pages/mesosphere/dcos/1.13/release-notes/1.13.0/index.md
pages/mesosphere/dcos/1.13/release-notes/1.13.1/index.md
pages/mesosphere/dcos/1.13/release-notes/1.13.2/index.md
pages/mesosphere/dcos/1.13/release-notes/1.13.3/index.md
pages/mesosphere/dcos/1.13/release-notes/1.13.4/index.md
pages/mesosphere/dcos/1.13/release-notes/1.13.5/index.md
pages/mesosphere/dcos/1.13/release-notes/1.13.6/index.md
pages/mesosphere/dcos/1.13/release-notes/1.13.7/index.md

https://jira.mesosphere.com/browse/DCOS-62144
New release notes for 1.13.7 

DCOS 1.13.7 Release Notes

---

pages/mesosphere/dcos/1.13/installing/production/upgrading/index.md
pages/mesosphere/dcos/2.0/installing/production/upgrading/index.md
pages/mesosphere/dcos/2.1/installing/production/upgrading/index.md

https://jira.mesosphere.com/browse/COPS-5746
* Removed outdated Enterprise-only tag in 1 step of the DC/OS upgrade documentation.
* Restored the correct path to CockroachDB's certificate directory.

Fixing DC/OS upgrade step regarding to IAM DB replication - COPS-5746

---

pages/mesosphere/dcos/1.13/tutorials/autoscaling/microscaling-queue/index.md
pages/mesosphere/dcos/1.13/tutorials/index.md
pages/mesosphere/dcos/2.0/tutorials/autoscaling/microscaling-queue/index.md

https://jira.mesosphere.com/browse/DCOS-57312
Please update 1.14/tutorials with the updated content that was published in 1.13.

ss/DCOS-57312 Edits to tutorial files.

---

pages/ksphere/kommander/latest/operations/cloud-providers/index.md
pages/ksphere/kommander/latest/projects/index.md
pages/ksphere/kommander/latest/quick-start/index.md

Replaces https://github.com/mesosphere/dcos-docs-site/pull/2689

Rebased RU-DCOS-60843

---

pages/mesosphere/dcos/1.13/installing/production/patching/index.md
pages/mesosphere/dcos/1.13/installing/production/upgrading/index.md
pages/mesosphere/dcos/2.0/installing/production/patching/index.md
pages/mesosphere/dcos/2.0/installing/production/upgrading/index.md

https://jira.mesosphere.com/browse/DCOS-62404

Updated upgrade and patch charts with 1.13.6, and 1.13.7

---

pages/ksphere/konvoy/latest/download/index.md
pages/ksphere/konvoy/latest/release-notes/index.md

Added Konvoy Download button to Download and Release Note page

---

pages/mesosphere/dcos/1.12/release-notes/1.12.5/index.md
pages/mesosphere/dcos/1.13/release-notes/1.13.4/index.md

https://jira.mesosphere.com/browse/DCOS-62894? 
moved dcos-56831 from 1.12.5 to 1.13.4 release notes

moved dcos-56831 from 1.12.5 to 1.13.4 release notes

---

pages/ksphere/dispatch/latest/deployment/index.md
pages/ksphere/dispatch/latest/operations/logging/index.md
pages/ksphere/dispatch/latest/operations/scaling/index.md
pages/ksphere/dispatch/latest/pipeline-configuration/index.md
pages/ksphere/dispatch/latest/starlark-reference/index.md

Be sure to make any changes to the docs in mesosphere/dispatch and not on this PR or else they will be overwritten on releases.

Bump docs from mesosphere/dispatch into mesosphere/dcos-docs-site for release v0.4.2

---

pages/ksphere/kommander/latest/prerequisities/index.md
pages/ksphere/kommander/latest/quick-start/index.md

Reworked Kommander Prerequisites to point to Konvoy Prerequisites

---

pages/mesosphere/dcos/1.11/installing/production/patching/index.md
pages/mesosphere/dcos/1.12/installing/production/patching/index.md
pages/mesosphere/dcos/1.12/installing/production/upgrading/index.md
pages/mesosphere/dcos/1.13/installing/production/upgrading/index.md

Updated upgrade paths for 1.12.5 (and a couple missed 1.11.13 ones...)

---

pages/ksphere/kommander/latest/centralized-monitoring/index.md

Docs ticket: https://jira.mesosphere.com/browse/DCOS-62414
Eng tickets:
https://jira.mesosphere.com/browse/DCOS-62060
https://jira.mesosphere.com/browse/DCOS-62061
Add docs on centralized monitoring (Thanos/Grafana/Karma) in kommander

Add docs on centralized monitoring for Kommander

---

pages/ksphere/kommander/latest/backup-and-restore/index.md

https://jira.mesosphere.com/browse/DCOS-61928
Added some fluffy reassurance about backing up and restoring Kommander.

[DCOS-61928] feat: add more clarity to backup/restore

---

pages/ksphere/kommander/latest/tutorials/using-istio/index.md

Add topic to show non-support for Istio

---

pages/ksphere/dispatch/index.md

https://jira.mesosphere.com/browse/DCOS-63126
Add description to Dispatch landing page.

[DCOS-63126] Add description to Dispatch landing page.

---

pages/ksphere/konvoy/partner-solutions/aqua/index.md
pages/ksphere/konvoy/partner-solutions/cloudflare/index.md
pages/ksphere/konvoy/partner-solutions/confluent/index.md
pages/ksphere/konvoy/partner-solutions/couchbase/index.md
pages/ksphere/konvoy/partner-solutions/hedvig/index.md
pages/ksphere/konvoy/partner-solutions/index.md
pages/ksphere/konvoy/partner-solutions/lightbend/index.md
pages/ksphere/konvoy/partner-solutions/minio/index.md
pages/ksphere/konvoy/partner-solutions/mongodb/index.md
pages/ksphere/konvoy/partner-solutions/openebs/index.md
pages/ksphere/konvoy/partner-solutions/portworx/index.md
pages/ksphere/konvoy/partner-solutions/styra/index.md
pages/ksphere/konvoy/partner-solutions/wallarm/index.md

[DCOS-63216](https://jira.mesosphere.com/browse/DCOS-63216)
In https://docs.d2iq.com/ksphere/konvoy/partner-solutions/, the sub-pages' index.md (the procedures for installation of the partner solutions).  I converted the headings from all lower case to Title Case.  Additionally, I fixed a few typos or incorrect capitalization for a company or it's products.

DCOS-63216 convert headers to titlecase

---

pages/ksphere/konvoy/latest/tutorials/use-ingress-load-balancer/index.md

Add a note for first time customers/users to use the cluster IP/hostname information from their own cluster instead of copy/pasting the curl information from this tutorial
N/A
The change being made is a note to make first time users aware that IP addresses/hostnames in the tutorial don't reflect the real-world ones.
~- [ ] Make sure you change all affected versions (e.g. 1.10, 1.11, 1.12, 1.13).~
~- [ ] Test all commands and procedures where applicable.~
~- [ ] Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects) if you are moving a page.~
See …

Update index.md with a clarification

---

pages/ksphere/konvoy/latest/tutorials/use-istio/index.md

Add warning about unsupported Istio f/Konvoy

---

pages/ksphere/konvoy/partner-solutions/jenkins/index.md

https://jira.mesosphere.com/browse/DCOS-62713
This PR replaces https://github.com/mesosphere/dcos-docs-site/pull/2715
Merged installation and migration docs into one page per Partner Solutions docs
Edit pass: corrected spelling, punctuation
Re-ordered procedures

ss/DCOS-62713 Edits to new Jenkins on Konvoy doc.

---

pages/ksphere/kommander/latest/centralized-monitoring/index.md

Eng ticket https://jira.mesosphere.com/browse/DCOS-62062
Docs ticket https://jira.mesosphere.com/browse/DCOS-63298
Added docs on how to federate alerting rules to managed clusters

[kommander] Docs on federated alert rules

---

pages/ksphere/dispatch/latest/deployment/index.md
pages/ksphere/dispatch/latest/install/index.md
pages/ksphere/dispatch/latest/operations/garbage-collection/index.md
pages/ksphere/dispatch/latest/operations/index.md
pages/ksphere/dispatch/latest/operations/monitoring/index.md
pages/ksphere/dispatch/latest/overview/index.md
pages/ksphere/dispatch/latest/pipeline-configuration/index.md
pages/ksphere/dispatch/latest/repo-setup/index.md
pages/ksphere/dispatch/latest/repository-crd/index.md
pages/ksphere/dispatch/latest/starlark-reference/index.md

https://jira.mesosphere.com/browse/DCOS-63363
Reordered menu per S Mason request.

ss/DCOS-63363 Re-ordering menu

---

pages/ksphere/konvoy/partner-solutions/jenkins/index.md

https://jira.mesosphere.com/browse/DCOS-62713
Added "category: Workload" to Jenkins page to ensure that it will open on Partner Solutions page.

Add category "Workload" to Jenkins page

---

pages/ksphere/konvoy/partner-solutions/portworx/index.md
pages/ksphere/konvoy/partner-solutions/styra/index.md

https://jira.mesosphere.com/browse/DCOS-63366
Correcting numbering error in Styra doc.
Correcting spelling error in Portworx doc.

ss/DCOS-63366 Correcting numbering, spelling errors.

---

pages/mesosphere/dcos/services/data-science-engine/1.0.1/custom-images/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.1/dynamic-allocation/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.1/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.1/integrations/hdfs/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.1/integrations/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.1/integrations/spark/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.1/integrations/tensorflow/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.1/overview/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.1/quick-start/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.1/release-notes/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.1/security/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.1/security/kerberos/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.1/security/tls/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.1/supported-kernels/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.1/uninstall/index.md

https://jira.mesosphere.com/browse/DCOS-63360
* Adds docs for the release of DSEngine 1.0.1
* Adds a new page for Dynamic Allocation
* Adds a new page for Custom Image build
* Adds section of using arbitrary secret on a Security page

Release docs for DSEngine 1.0.1

---

pages/ksphere/konvoy/latest/reference/command-line-interface/index.md

remove colon from yaml

---

pages/mesosphere/dcos/services/data-science-engine/1.0.1/quick-start/index.md

https://jira.d2iq.com/browse/DCOS-63449
Deleted duplicated text on Quick Start page.

Removed duplicate text from Quick Start page.

---

pages/mesosphere/dcos/2.0/release-notes/2.0.2/index.md

https://jira.mesosphere.com/browse/DCOS-62742

draft dcos 2.0.2 release notes

---

pages/mesosphere/dcos/2.0/installing/production/patching/index.md
pages/mesosphere/dcos/2.0/installing/production/upgrading/index.md
pages/mesosphere/dcos/version-policy/index.md

Added results of 2.0.2 Qualifications

---

pages/ksphere/kommander/index.md
pages/ksphere/kommander/latest/backup-and-restore/index.md
pages/ksphere/kommander/latest/centralized-monitoring/index.md
pages/ksphere/kommander/latest/clusters/index.md
pages/ksphere/kommander/latest/index.md
pages/ksphere/kommander/latest/install/index.md
pages/ksphere/kommander/latest/introducing-kommander/index.md
pages/ksphere/kommander/latest/licensing/index.md
pages/ksphere/kommander/latest/operations/access-control/index.md
pages/ksphere/kommander/latest/operations/cloud-providers/index.md
pages/ksphere/kommander/latest/operations/identity-providers/index.md
pages/ksphere/kommander/latest/operations/index.md
pages/ksphere/kommander/latest/prerequisities/index.md
pages/ksphere/kommander/latest/projects/index.md
pages/ksphere/kommander/latest/quick-start/index.md
pages/ksphere/kommander/latest/tutorials/authorize-all-users/index.md
pages/ksphere/kommander/latest/tutorials/duplicating-cluster/index.md
pages/ksphere/kommander/latest/tutorials/index.md
pages/ksphere/kommander/latest/tutorials/using-istio/index.md
pages/ksphere/kommander/latest/uninstall/index.md
pages/ksphere/kommander/search/index.md

Add beta button to landing and first page

---

docker/nginx/redirects-307.map
pages/mesosphere/dcos/services/hive-metastore/1.1.0-3.0.0/advanced/index.md
pages/mesosphere/dcos/services/hive-metastore/1.1.0-3.0.0/cli/index.md
pages/mesosphere/dcos/services/hive-metastore/1.1.0-3.0.0/configuration/index.md
pages/mesosphere/dcos/services/hive-metastore/1.1.0-3.0.0/getting-started/index.md
pages/mesosphere/dcos/services/hive-metastore/1.1.0-3.0.0/index.md
pages/mesosphere/dcos/services/hive-metastore/1.1.0-3.0.0/limitations/index.md
pages/mesosphere/dcos/services/hive-metastore/1.1.0-3.0.0/operations/index.md
pages/mesosphere/dcos/services/hive-metastore/1.1.0-3.0.0/release-notes/index.md
pages/mesosphere/dcos/services/hive-metastore/1.1.0-3.0.0/security/index.md
pages/mesosphere/dcos/services/hive-metastore/1.1.0-3.0.0/support-policy/index.md
pages/mesosphere/dcos/services/hive-metastore/1.1.0-3.0.0/supported-databases/index.md
pages/mesosphere/dcos/services/hive-metastore/1.1.0-3.0.0/troubleshooting/index.md
pages/mesosphere/dcos/services/hive-metastore/1.1.0-3.0.0/uninstall/index.md
pages/mesosphere/dcos/services/hive-metastore/1.1.0-3.0.0/updates/index.md
pages/mesosphere/dcos/services/hive-metastore/index.md

https://jira.d2iq.com/browse/D2IQ-62515
https://jira.d2iq.com/browse/D2IQ-63805
Review and edit documentation for Hive Metastore 1.1.0-3.0.0. Original PR was 
https://github.com/mesosphere/dcos-docs-site/pull/2746
I created a new ticket (D2IQ-63805 to track this work in JIRA for the Doc Team. This PR supersedes PR2746. I will close PR2746 without merging, to avoid merge conflicts.

Edit pass on Hive Metastore 1.1.0-3.0.0 documentation

---

pages/mesosphere/dcos/1.13/release-notes/1.13.6/index.md

https://jira.d2iq.com/browse/COPS-5739 is requesting to let customers know about a bugfix in DCOS-UI
that let's users correctly handle the deletion and re-addition of
secrets.

[COPS-5739] - add a bugfix to the release notes of 1.13.6

---

pages/mesosphere/dcos/1.12/installing/production/dcos-ansible/ansible-quickstart/index.md
pages/mesosphere/dcos/1.13/installing/production/dcos-ansible/ansible-quickstart/index.md
pages/mesosphere/dcos/2.0/installing/production/dcos-ansible/ansible-quickstart/index.md

[COPS-5818](https://jira.d2iq.com/browse/COPS-5818)
[D2IQ-64024](https://jira.d2iq.com/browse/D2IQ-64024)
[D2IQ-63927](https://jira.d2iq.com/browse/D2IQ-63927)

updated ansible docs: use ansible-galaxy instead of mazer

---

pages/index.md

placeholder to get docs page subtitle updated before SKO

Update preview pane text

---

pages/mesosphere/dcos/2.1/release-notes/2.1.0/index.md

https://jira.d2iq.com/browse/D2IQ-64156
need to prep the dcos release notes file for the 2.1 release. 
took out older stuff from 2.0, added 2.1 prep info. 

fixing release notes for 2.1 release

---

pages/mesosphere/dcos/2.1/installing/production/advanced-configuration/configuration-reference/index.md

- [D2IQ-61184](https://jira.d2iq.com/browse/D2IQ-61184)

Add documentation for `mesos_http_executor_domain_sockets`

---

pages/ksphere/kommander/latest/release-notes/legal-notices/index.md

Replace missing legal notice topic and directory.

Replace missing legal notice topic and directory.

---

pages/mesosphere/dcos/services/hive-metastore/1.1.0-3.0.0/release-notes/index.md

https://jira.d2iq.com/browse/DCOS_OSS-5904
Changes done regarding https://jira.d2iq.com/browse/D2IQ-62515
Updated the release-notes section after the release docs changes done in PR # https://github.com/mesosphere/dcos-docs-site/pull/2749.

[D2IQ-62515] HiveMS 1.1.0-3.0.0 specific update on release notes section

---

pages/ksphere/kommander/latest/operations/access-control/index.md
pages/ksphere/kommander/latest/operations/cloud-providers/index.md

Fix figure number and nav bar issues

---

pages/mesosphere/dcos/1.13/administering-clusters/package-registry/index.md
pages/mesosphere/dcos/2.0/administering-clusters/package-registry/index.md
pages/mesosphere/dcos/2.1/administering-clusters/package-registry/index.md

https://jira.d2iq.com/browse/D2IQ-64347
Added a note to address the manual addition of lastUpdated parameter in the schema for most of the universe packages. Also added the instruction on how to fix error during the registry migration of these packages.

[D2IQ-64347]Update package-registry docs

---

pages/ksphere/kommander/latest/operations/cloud-providers/index.md

https://jira.d2iq.com/browse/D2IQ-64369
Added section on Role-based authentication for AWS cloud providers.

D2IQ-64369: Add AWS role based cloud provider

---

pages/mesosphere/dcos/services/kafka/2.8.0-2.3.0/index.md
pages/mesosphere/dcos/services/kafka/2.8.1-2.3.1/index.md
pages/mesosphere/dcos/services/kafka/2.9.0-2.4.0/advanced/index.md
pages/mesosphere/dcos/services/kafka/2.9.0-2.4.0/configuration/index.md
pages/mesosphere/dcos/services/kafka/2.9.0-2.4.0/index.md
pages/mesosphere/dcos/services/kafka/2.9.0-2.4.0/limitations/index.md
pages/mesosphere/dcos/services/kafka/2.9.0-2.4.0/operations/index.md
pages/mesosphere/dcos/services/kafka/2.9.0-2.4.0/policy/index.md
pages/mesosphere/dcos/services/kafka/2.9.0-2.4.0/reference/index.md
pages/mesosphere/dcos/services/kafka/2.9.0-2.4.0/release-notes/index.md
pages/mesosphere/dcos/services/kafka/2.9.0-2.4.0/security/index.md
pages/mesosphere/dcos/services/kafka/2.9.0-2.4.0/started/index.md
pages/mesosphere/dcos/services/kafka/2.9.0-2.4.0/troubleshooting/index.md
pages/mesosphere/dcos/services/kafka/2.9.0-2.4.0/uninstall/index.md
pages/mesosphere/dcos/services/kafka/2.9.0-2.4.0/updates/index.md
pages/mesosphere/dcos/version-policy/index.md

Resolves https://jira.d2iq.com/browse/D2IQ-63949 and https://jira.d2iq.com/browse/D2IQ-64101
This PR adds the release notes for the release of Kafka-2.9.0-2.4.0

[D2IQ-63949] Add release docs for Kafka-2.9.0-2.4.0

---

pages/ksphere/kommander/latest/licensing/index.md

https://jira.d2iq.com/browse/COPS-5865
Add info where one can get a license

add license portal info

---

pages/ksphere/kommander/latest/operations/cloud-providers/configure-on-prem-provider/index.md
pages/ksphere/kommander/latest/tutorials/on-prem-alpha/index.md
pages/ksphere/kommander/latest/tutorials/on-prem/index.md

1. Noticed that on-prem title and the nav item was off `AWS provider`
2. Claimed On-prem to be beta as agreed messaging and implemented in the UI

on prem beta / on prem title

---

layouts/all-products-landing.pug

Remove top level beta tags for Kommander and Dispatch

---

pages/ksphere/konvoy/latest/monitoring/recommendations/index.md

https://jira.d2iq.com/browse/D2IQ-62792
Added to Konvoy docs a topic outlining a table with recommended monitoring setting for Prometheus 

Add Prometheus monitoring settings topic

---

pages/ksphere/kommander/latest/tutorials/use-kcl-from-kubectl/index.md

https://jira.d2iq.com/browse/D2IQ-64929
Adding a tutorial how to operate Kommander Cluster Lifecycle API via kubernetes CLI

Add KCL tutorial

---

pages/ksphere/konvoy/latest/upgrade/upgrade-kubernetes-addons/index.md

[D2IQ-65761] #comment smart commit entry
typo correction
[D2IQ-65761]: https://jira.d2iq.com/browse/D2IQ-65761

corrected "konovy" typo

---

pages/mesosphere/dcos/1.13/release-notes/1.13.7/index.md
pages/mesosphere/dcos/1.13/release-notes/1.13.8/index.md

https://jira.d2iq.com/browse/D2IQ-64568 
Creating draft of 1.13.8 release notes. 

draft of 1.13.8 release notes

---

CODEOWNERS

@cmastr requested to be notified of konvoy docs changes as well

Add @cmastr to konvoy docs codeowners

---

pages/mesosphere/dcos/1.13/storage/external-storage/index.md
pages/mesosphere/dcos/2.0/storage/external-storage/index.md
pages/mesosphere/dcos/2.1/storage/external-storage/index.md

[D2IQ-26077](https://jira.d2iq.com/browse/D2IQ-26077)
This PR adds instructions for using 3rd party Docker volume driver.

Add instructions for using 3rd party Docker volume driver.

---

pages/mesosphere/dcos/services/cassandra/2.4.0-3.0.16/configuration/index.md
pages/mesosphere/dcos/services/cassandra/2.9.0-3.11.6/configuration/index.md
pages/mesosphere/dcos/services/elastic/2.7.0-6.8.1/configuration/index.md
pages/mesosphere/dcos/services/elastic/3.1.1-7.6.0/configuration/index.md
pages/mesosphere/dcos/services/include/configuration-service-settings.tmpl
pages/mesosphere/dcos/services/kafka/2.8.0-2.3.0/configuration/index.md
pages/mesosphere/dcos/services/kafka/2.8.1-2.3.1/configuration/index.md
pages/mesosphere/dcos/services/kafka/2.9.0-2.4.0/configuration/index.md

https://jira.d2iq.com/browse/COPS-5857
Describe how the @zone placement constraint requires a DC/OS feature to be enabled, and describe how that information is passed to the base tech (Kafka, Cassandra, etc).

COPS-5857 - Add zone/rack awareness information to DC/OS packages which support it

---

docker/nginx/redirects-307.map
pages/mesosphere/dcos/services/data-science-engine/1.0.0/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.2/custom-images/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.2/dynamic-allocation/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.2/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.2/integrations/hdfs/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.2/integrations/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.2/integrations/spark/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.2/integrations/tensorflow/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.2/overview/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.2/quick-start/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.2/release-notes/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.2/security/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.2/security/kerberos/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.2/security/tls/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.2/supported-kernels/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.2/uninstall/index.md
pages/mesosphere/dcos/services/data-science-engine/1.0.2/upgrade/index.md

[COPS-5958](https://jira.d2iq.com/browse/COPS-5958)
* Adds updated docs for the release of Data Science Engine 1.0.2.
* Updates redirect entry

[COPS-5958] Add release doc for Data Science Engine 1.0.2

---

scss/base/_layout.scss
scss/components/_grid-toc.scss
scss/components/_sidebar.scss
scss/pages/_landing.scss

It needed a visual pass. Before is on the left, after is on the right.
Top level pages - Increased spacing between jumbotron and content, locked jumbotron font size at xxl
Increased spacing between jumbotron and services page content, set to left aligned and all caps on categories to help distinguish more clearly
Centered version picker on content pages

UI Updates

---

pages/mesosphere/dcos/services/kubernetes/2.4.10-1.15.10/index.md

https://jira.d2iq.com/browse/D2IQ-66508
fix menu weight. 

changing menu weight to put newest on top

---

pages/mesosphere/dcos/1.13/release-notes/1.13.8/index.md

No JIRA b/c quick fix. 
Have to remove release notes. 

tremoving release notes for patch 1.13.8 as download has been removed.

---

pages/ksphere/konvoy/latest/install/node-pools/index.md

https://jira.d2iq.com/browse/COPS-6012

COPS-6012 - Link in Konvoy docs leads to 404

---

pages/ksphere/dispatch/latest/deployment/canary-deployment/index.md
pages/ksphere/dispatch/latest/deployment/rolling-deployment/index.md
pages/ksphere/dispatch/latest/pipeline-configuration/index.md
pages/ksphere/dispatch/latest/references/starlark-reference/index.md
pages/ksphere/dispatch/latest/troubleshooting/index.md
pages/ksphere/kommander/latest/clusters/creating-konvoy-cluster-azure/index.md
pages/ksphere/konvoy/latest/operations/managing-nodes/index.md

https://jira.d2iq.com/browse/COPS-6017

COPS-6017: Fixing links which 404 within ksphere docs

---

pages/mesosphere/dcos/2.0/release-notes/2.0.3/index.md

https://jira.d2iq.com/browse/D2IQ-66070 

draft of 2.0.3 release notes

---

docker/nginx/redirects-307.map

[COPS-6106](https://jira.d2iq.com/browse/COPS-6016)
Fixed the broken link which directed latest to older versions of confluent zookeeper.

[COPS-6106] Fix broken confluent zookeeper link

---

pages/ksphere/dispatch/latest/release-notes/1.0.1/index.md
pages/ksphere/dispatch/latest/release-notes/1.0/index.md
pages/ksphere/dispatch/latest/release-notes/index.md

https://jira.d2iq.com/browse/D2IQ-66833
Release notes for Dispatch 1.0.1

draft Dispatch 1.0.1 release notes

---

pages/mesosphere/dcos/services/jenkins/3.5.2-2.107.2/jenkins-auth/index.md
pages/mesosphere/dcos/services/jenkins/3.5.3-2.150.1/jenkins-auth/index.md
pages/mesosphere/dcos/services/jenkins/3.5.4-2.150.1/jenkins-auth/index.md
pages/mesosphere/dcos/services/jenkins/3.6.0-2.190.1/jenkins-auth/index.md

https://jira.d2iq.com/browse/COPS-6029
Removing shell prompt from command examples

COPS-6029: Removing shell prompt from Jenkins command examples

---

pages/mesosphere/dcos/version-policy/index.md

https://jira.d2iq.com/browse/D2IQ-66651
We decided to remove the Qualification in Progress notices to reflect our future qualification plans.

Removed the Qualification in Progress notices

---

pages/ksphere/kommander/latest/clusters/attach-cluster/index.md

Added base64 options to account for the difference between Nix and Mac OS X.

Added os support in the script.

---

pages/mesosphere/dcos/2.1/deploying-services/creating-services/index.md
pages/mesosphere/dcos/2.1/deploying-services/marathon-parameters/index.md
pages/mesosphere/dcos/2.1/deploying-services/pods/examples/index.md
pages/mesosphere/dcos/2.1/deploying-services/pods/technical-overview/index.md
pages/mesosphere/dcos/2.1/installing/production/advanced-configuration/configuration-reference/index.md
pages/mesosphere/dcos/2.1/release-notes/2.1.0/index.md

https://jira.d2iq.com/browse/D2IQ-66907
This PR adds documentation for the new resource limits feature in Marathon and DC/OS.

Resource limits for Marathon apps and pods

---

pages/ksphere/kommander/latest/clusters/attach-cluster/index.md

https://jira.d2iq.com/browse/D2IQ-67164

Update the attach cluster to Kommander docs

---

pages/ksphere/kommander/latest/operations/cloud-providers/configure-azure-cloud-provider/index.md

[D2IQ-67227]
[D2IQ-67227]: https://jira.d2iq.com/browse/D2IQ-67227
- corrected typo
- added IMPORTANT missing step `az role assignment create --assignee "APP_ID" --role "User Access Administrator"`
- /ksphere/kommander/img/add-cloud-provider.png needs to be updated as well as shown commands in the kommander-ui 

update for kommanders cloud-provider Azure steps

---

pages/mesosphere/dcos/2.1/installing/production/advanced-configuration/configuration-reference/index.md
pages/mesosphere/dcos/2.1/security/ent/tls-ssl/ar-custom/index.md

https://jira.d2iq.com/browse/D2IQ-64357
Custom external certificates, introduced in DC/OS 2.1

Add custom external certificate docs

---

index.js

we use the RENDERING_PATH_PATTERN or RPP env var to speed up
local builds.
we did that by not applying layouts to pages that are outside of the
given RPP. we can do better!
this commit changes the approach to hiding all `.md`-files outside the RPP from
Metalsmith altogether so that all processors only need to deal with the
limited amount of files.
This speeds up the "boot time" to ~10 seconds where it formerly
took ~50 (on my machine).
The same goes for recompilations, which are faster by an equal
proportion.
A nice side effect of this implementation is that the main menu is now
present and functional despite using a RPP.
i tested a couple different RPP (one for each product) - but would encourage you to do something similar (or unexpected).

chore: improve speed when using RPP

---

entry.js
index.js
webpack.config.js

enable livereloading.
open the docs via `npm run dev`, open a page. modify that page and hit save in your editor. wait some time and see how your changes are reflected in the browser without having to move a finger. :)

chore: enable webpack livereload in development

---

pages/mesosphere/dcos/1.13/release-notes/1.13.9/index.md

https://jira.d2iq.com/browse/D2IQ-67249
Draft 1.13.9 Release Notes

draft 1.13.9 release notes

---

pull_request_template

updating PR template with additional checklist items

---

pages/ksphere/kommander/1.0/operations/cloud-providers/configure-aws-cloud-provider-roles/index.md
pages/ksphere/kommander/1.1.0-beta/operations/cloud-providers/configure-aws-cloud-provider-roles/index.md

[D2IQ-67807]
[D2IQ-67807]: https://jira.d2iq.com/browse/D2IQ-67807
- adding the explanation for roles trust relationship

chore: kommander role usage update

---

pages/mesosphere/dcos/1.13/release-notes/1.13.8/index.md
pages/mesosphere/dcos/1.13/release-notes/1.13.9/index.md

https://jira.d2iq.com/browse/COPS-6096
Need to add back in release notes for 1.13.8. 

adding back 1.13.8 release notes

---

pages/mesosphere/dcos/2.0/release-notes/2.0.3/index.md

https://jira.d2iq.com/browse/D2IQ-67999
Adding warning to 2.0.3 page that should not be downloaded. 

2.0.3 warning

---

pages/mesosphere/dcos/2.1/release-notes/2.1.0/index.md

https://jira.d2iq.com/browse/D2IQ-68037
adding a link from the Release Notes to the custom certs section to make it easier to find this information. 

adding link for admin router section

---

pages/mesosphere/dcos/2.0/release-notes/2.0.3/index.md

D2IQ-67999
adding product advisory link, fixing typo 

adding product advisory link, fixing typo

---

pages/mesosphere/dcos/1.13/installing/production/patching/index.md
pages/mesosphere/dcos/1.13/installing/production/upgrading/index.md
pages/mesosphere/dcos/1.13/release-notes/1.13.9/index.md
pages/mesosphere/dcos/2.0/installing/production/patching/index.md
pages/mesosphere/dcos/2.0/installing/production/upgrading/index.md
pages/mesosphere/dcos/2.0/release-notes/2.0.0/index.md
pages/mesosphere/dcos/2.0/release-notes/2.0.1/index.md
pages/mesosphere/dcos/2.0/release-notes/2.0.2/index.md
pages/mesosphere/dcos/2.0/release-notes/2.0.3/index.md

adding warnings to the release notes. Plus adding Kevin's changes to supported version matrix. 

new warnings for 1.13.9

---

pages/mesosphere/dcos/1.13/release-notes/1.13.9/index.md
pages/mesosphere/dcos/2.0/installing/production/upgrading/index.md
pages/mesosphere/dcos/2.0/release-notes/2.0.0/index.md
pages/mesosphere/dcos/2.0/release-notes/2.0.1/index.md
pages/mesosphere/dcos/2.0/release-notes/2.0.2/index.md

Updating warning language

---

config.json

adding dispatch 1.2 to master do not build

---

pages/mesosphere/dcos/2.1/release-notes/2.1.0/index.md

https://jira.d2iq.com/browse/D2IQ-68070
Updates to release notes for 2.1.0 beta 4. 

updating release notes for beta 5

---

pages/mesosphere/dcos/1.13/release-notes/1.13.9/index.md
pages/mesosphere/dcos/2.0/installing/production/upgrading/index.md
pages/mesosphere/dcos/2.0/release-notes/2.0.0/index.md
pages/mesosphere/dcos/2.0/release-notes/2.0.1/index.md
pages/mesosphere/dcos/2.0/release-notes/2.0.2/index.md
pages/mesosphere/dcos/2.0/release-notes/2.0.4/index.md

2.0.4 release notes and warnings

---

pages/mesosphere/dcos/1.12/security/ent/tls-ssl/get-cert/index.md
pages/mesosphere/dcos/1.13/security/ent/tls-ssl/get-cert/index.md
pages/mesosphere/dcos/2.0/security/ent/tls-ssl/get-cert/index.md
pages/mesosphere/dcos/2.1/security/ent/tls-ssl/ar-custom/index.md
pages/mesosphere/dcos/2.1/security/ent/tls-ssl/get-cert/index.md

https://jira.d2iq.com/browse/D2IQ-68023
Some fixes to the new text recently added for custom external certificates, and changes to docs on obtaining the CA bundle info to make it fit with the new page.

Some additional notes on custom external certificates

---

pages/ksphere/kommander/1.1.0-beta/clusters/attach-cluster/index.md

Link: https://github.com/mesosphere/dcos-docs-site/pull/2853
This change has disappeared due to an override.
None.
Reapplying merged PR https://github.com/mesosphere/dcos-docs-site/pull/2853 due to an override while moving files that happened afterwards. Conversation around the issue: https://mesosphere.slack.com/archives/CSLFN7E3X/p1589288449197700

Reapply PR #2853

---

pages/mesosphere/dcos/2.0/deploying-jobs/examples/index.md
pages/mesosphere/dcos/2.0/deploying-jobs/quickstart/index.md
pages/mesosphere/dcos/2.1/deploying-jobs/examples/index.md
pages/mesosphere/dcos/2.1/deploying-jobs/quickstart/index.md

https://jira.d2iq.com/browse/D2IQ-68135
We add documentation for Metronome networking. Metronome networking applies for DC/OS 2.0.4 and 2.1.0.

Metronome networking documentation

---

pages/mesosphere/dcos/services/cassandra/2.4.0-3.0.16/configuration/index.md
pages/mesosphere/dcos/services/cassandra/2.4.0-3.0.16/getting-started/index.md
pages/mesosphere/dcos/services/cassandra/2.9.0-3.11.6/configuration/index.md
pages/mesosphere/dcos/services/cassandra/2.9.0-3.11.6/getting-started/index.md

https://jira.d2iq.com/browse/D2IQ-68490
Make changes to Cassandra docs as requested in https://jira.d2iq.com/browse/COPS-4103
This is a bugfix and can be merged anytime.
- [x ] Change all affected versions, if applicable (e.g. 1.13, 2.0, 2.1).
- [x ] Test all commands and procedures, if applicable.
- [ x] Create your PR against `staging`, not `master`. 
- [X ] Provide an estimated date for deploying the doc change. Note: Improvements or fixes can be merged ASAP. 
- [N/A ] Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects) if you are moving a page.

COPS-4103 fixes

---

pages/ksphere/konvoy/1.4/install/install-airgapped/index.md
pages/ksphere/konvoy/1.4/install/install-aws/index.md
pages/ksphere/konvoy/1.4/install/install-azure/index.md
pages/ksphere/konvoy/1.4/install/install-dev/index.md
pages/ksphere/konvoy/1.4/install/install-onprem/index.md
pages/ksphere/konvoy/1.4/install/node-pools/index.md
pages/ksphere/konvoy/1.4/networking/index.md
pages/ksphere/konvoy/1.4/operations/managing-nodes/index.md
pages/ksphere/konvoy/1.4/quick-start/index.md
pages/ksphere/konvoy/1.4/reference/cluster-configuration/index.md
pages/ksphere/konvoy/1.4/reference/command-line-interface/konvoy-init/index.md
pages/ksphere/konvoy/1.4/reference/command-line-interface/konvoy-provision/index.md
pages/ksphere/konvoy/1.4/reference/command-line-interface/konvoy-up/index.md
pages/ksphere/konvoy/1.4/release-notes/index.md
pages/ksphere/konvoy/1.4/tutorials/provision-a-custom-cluster/index.md
pages/ksphere/konvoy/1.4/upgrade/upgrade-kubernetes-addons/index.md

konvoy: Update docs for konvoy release v1.4.3

---

pages/ksphere/kommander/1.1.0-beta/centralized-monitoring/index.md

https://jira.d2iq.com/browse/D2IQ-68396
Monitoring ID was exposed in the kommander UI - reflecting this in the centralized monitoring docs.

[kommander] Update centralized monitoring docs

---

pages/mesosphere/dcos/1.13/networking/DNS/index.md
pages/mesosphere/dcos/1.13/networking/DNS/mesos-dns/index.md
pages/mesosphere/dcos/2.0/networking/DNS/index.md
pages/mesosphere/dcos/2.0/networking/DNS/mesos-dns/index.md
pages/mesosphere/dcos/2.1/networking/DNS/index.md
pages/mesosphere/dcos/2.1/networking/DNS/mesos-dns/index.md

https://jira.d2iq.com/browse/COPS-5213
Add DNS caching note as requested by support

pages: add caching note to dcos-dns and mesos-dns

---

pages/ksphere/konvoy/1.5.0-beta/autoscaling/index.md
pages/ksphere/konvoy/1.5.0-beta/gpu/index.md
pages/ksphere/konvoy/1.5.0-beta/install/install-airgapped/index.md
pages/ksphere/konvoy/1.5.0-beta/install/install-aws/index.md
pages/ksphere/konvoy/1.5.0-beta/install/install-azure/index.md
pages/ksphere/konvoy/1.5.0-beta/install/install-dev/index.md
pages/ksphere/konvoy/1.5.0-beta/install/install-onprem/index.md
pages/ksphere/konvoy/1.5.0-beta/install/install-secured/index.md
pages/ksphere/konvoy/1.5.0-beta/install/node-pools/index.md
pages/ksphere/konvoy/1.5.0-beta/networking/index.md
pages/ksphere/konvoy/1.5.0-beta/operations/managing-nodes/index.md
pages/ksphere/konvoy/1.5.0-beta/quick-start/index.md
pages/ksphere/konvoy/1.5.0-beta/reference/addons/index.md
pages/ksphere/konvoy/1.5.0-beta/reference/cluster-configuration/index.md
pages/ksphere/konvoy/1.5.0-beta/reference/cluster-configuration/v1beta1/index.md
pages/ksphere/konvoy/1.5.0-beta/reference/cluster-configuration/v1beta2/index.md
pages/ksphere/konvoy/1.5.0-beta/reference/command-line-interface/konvoy-check/index.md
pages/ksphere/konvoy/1.5.0-beta/reference/command-line-interface/konvoy-deploy/index.md
pages/ksphere/konvoy/1.5.0-beta/reference/command-line-interface/konvoy-deploy/konvoy-deploy-kubernetes/index.md
pages/ksphere/konvoy/1.5.0-beta/reference/command-line-interface/konvoy-init/index.md
pages/ksphere/konvoy/1.5.0-beta/reference/command-line-interface/konvoy-provision/index.md
pages/ksphere/konvoy/1.5.0-beta/reference/command-line-interface/konvoy-up/index.md
pages/ksphere/konvoy/1.5.0-beta/release-notes/index.md
pages/ksphere/konvoy/1.5.0-beta/release-notes/kubernetes-base-addon/index.md
pages/ksphere/konvoy/1.5.0-beta/tutorials/addon-repositories/index.md
pages/ksphere/konvoy/1.5.0-beta/tutorials/provision-a-custom-cluster/index.md
pages/ksphere/konvoy/1.5.0-beta/upgrade/upgrade-kubernetes-addons/index.md

* Autoscaling doc
* Release Notes
* Other version changes

konvoy: Update docs for konvoy release v1.5.0-beta.3

---

pages/ksphere/kommander/1.0/clusters/attach-cluster/index.md
pages/ksphere/kommander/1.1.0-beta/clusters/attach-cluster/index.md

N/A
No JIRA, just a minor change because the img path was failing 
---
I checked locally and things are looking good there

Fixing image paths on Attach Clusters Page

---

pages/ksphere/kommander/1.0/release-notes/index.md

Release Notes for Kommander 1.0.1 patch

Release Notes for Kommander 1.0.1 patch.

---

pages/ksphere/konvoy/1.5.0-beta/release-notes/index.md

konvoy: Update docs for konvoy release v1.5.0-beta.4

---

pages/mesosphere/dcos/install-include/aws-remote-region-all.tmpl

https://jira.d2iq.com/browse/DCOS_OSS-5959
Docs recommend t2.medium for masters, this is too small. See ticket for additional details.

Increase instance sizes for DC/OS multi-region install instructions

---

pages/ksphere/konvoy/1.5.0-beta/install/supported-operating-systems/index.md

konvoy: Update docs for konvoy release v1.5.0-beta.5

---

pages/mesosphere/dcos/2.1/networking/SDN/calico/index.md
pages/mesosphere/dcos/2.1/overview/architecture/components/index.md
pages/mesosphere/dcos/2.1/release-notes/2.1.0/index.md

https://jira.d2iq.com/browse/D2IQ-68025
Added in documentation for accessing calico using `dcos calico` as well as how calico works etc.

Add Calico documentation for 2.1

---

pages/mesosphere/dcos/1.13/administering-clusters/replacing-a-master-node/index.md
pages/mesosphere/dcos/2.0/administering-clusters/replacing-a-master-node/index.md
pages/mesosphere/dcos/2.1/administering-clusters/replacing-a-master-node/index.md

https://jira.d2iq.com/browse/COPS-6132
Modifying instructions to point to correct backup topic. 

fixing backup information to point to correct topic

---

pages/mesosphere/dcos/1.13/metrics/index.md
pages/mesosphere/dcos/2.0/metrics/index.md
pages/mesosphere/dcos/2.1/metrics/index.md

https://jira.d2iq.com/browse/DCOS_OSS-5298
adding specific instructions and an example configuration on how to add custom metrics.
You might want to review commit-by-commit, as the first commit should solely be whitespace-changes.

DCOS_OSS-5298 custom metrics

---

pages/ksphere/kommander/1.1.0-beta/clusters/attach-eks-cluster/index.md

Add EKS cluster to Kommander topic

Add EKS cluster topic

---

pages/mesosphere/dcos/services/dcos-monitoring/1.3.0/configuring-edge-lb/index.md

https://jira.d2iq.com/browse/D2IQ-68496
Added step-by-step instructions for how DC/OS Monitoring service can be exposed through EdgeLB (as it's recommended in the documentation).

Adding instructions for exposing Monitoring over EdgeLB

---

pages/mesosphere/dcos/1.13/installing/production/advanced-configuration/configuration-reference/index.md
pages/mesosphere/dcos/2.0/installing/production/advanced-configuration/configuration-reference/index.md
pages/mesosphere/dcos/2.1/installing/production/advanced-configuration/configuration-reference/index.md

https://jira.d2iq.com/browse/COPS-5342

adding statement to exhibitor_explicit_keys

---

pages/mesosphere/dcos/1.13/security/ent/secrets/unseal-store/index.md
pages/mesosphere/dcos/2.0/security/ent/secrets/unseal-store/index.md
pages/mesosphere/dcos/2.1/security/ent/secrets/unseal-store/index.md

https://jira.d2iq.com/browse/COPS-5399
fixing header, shortening statements.  

fixing render with header info change

---

pages/ksphere/konvoy/partner-solutions/portworx/index.md

Add Portworx info back.

---

pages/mesosphere/dcos/2.1/networking/SDN/calico/index.md

https://jira.d2iq.com/browse/COPS-6205

fixing command

---

pages/mesosphere/dcos/2.1/installing/production/advanced-configuration/configuration-reference/index.md
pages/mesosphere/dcos/2.1/networking/SDN/calico/index.md

https://jira.d2iq.com/browse/D2IQ-69024
https://jira.d2iq.com/browse/D2IQ-69026

Calico update

---

pages/ksphere/kommander/1.1.0-beta/release-notes/index.md

JIRA Based Release Notes for existing Kommander Releases. This can go in as soon as its ✅ 

Kommander 1.1.0 Release Notes (Beta 0 - RC 1)

---

config.json
index.js
layouts/kudo-kubeflow-docs-landing.pug
pages/ksphere/kubeflow/1.0.1-0.3.1/download/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/introducing/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/legal-notices/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/secrets-management/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/tutorials/fairing/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/tutorials/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/tutorials/katib/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/tutorials/metadata/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/tutorials/pipelines/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/tutorials/training/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/tutorials/training/mxnet/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/tutorials/training/pytorch/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/tutorials/training/tensorflow/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/user-management/index.md
pages/ksphere/kubeflow/index.md
plugins/metalsmith-algolia.js

chore: enable aloglia search for kubeflow docs

---

pages/mesosphere/dcos/1.12/cli/command-reference/dcos-job/dcos-job-show/index.md
pages/mesosphere/dcos/1.13/cli/command-reference/dcos-job/dcos-job-schedule-show/index.md
pages/mesosphere/dcos/1.13/cli/command-reference/dcos-job/dcos-job-show/index.md
pages/mesosphere/dcos/2.0/cli/command-reference/dcos-job/dcos-job-show/index.md
pages/mesosphere/dcos/2.1/cli/command-reference/dcos-job/dcos-job-show/index.md
pages/mesosphere/dcos/cn/1.12/cli/command-reference/dcos-job/dcos-job-show/index.md
pages/mesosphere/dcos/cn/1.13/cli/command-reference/dcos-job/dcos-job-show/index.md
pages/mesosphere/dcos/cn/2.0/cli/command-reference/dcos-job/dcos-job-show/index.md

https://jira.d2iq.com/browse/D2IQ-68976?filter=-1

Fix wrong usage command for dcos job show command

---

pages/ksphere/kommander/1.1.0-beta/index.md

Updated Introduction to Kommander info

Updated Introduction to Kommander info.

---

layouts/layout.pug
layouts/partials/head.pug
layouts/partials/header/header-dropdown.pug
layouts/partials/header/header.pug
layouts/partials/header/ksphere-dropdown.pug
layouts/partials/header/kubeflow-header.pug
layouts/partials/sidebar/en-sidebar.pug
pages/ksphere/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/download/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/introducing/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/legal-notices/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/secrets-management/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/tutorials/fairing/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/tutorials/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/tutorials/katib/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/tutorials/metadata/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/tutorials/pipelines/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/tutorials/training/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/tutorials/training/mxnet/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/tutorials/training/pytorch/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/tutorials/training/tensorflow/index.md
pages/ksphere/kubeflow/1.0.1-0.3.1/user-management/index.md
pages/ksphere/kubeflow/index.md

fixing kubeflow layout

---

pages/ksphere/kommander/1.0/index.md

adding welcome copy to 1.0

---

pages/ksphere/kommander/1.1.0-beta/release-notes/index.md

Data taken from JIRA: https://jira.d2iq.com/projects/D2IQ/versions/41216

Kommander v1.1.0-rc.2 release notes

---

pages/mesosphere/dcos/services/kubernetes/2.4.10-1.15.10/operations/encrypt-data/index.md

hexdump would show if secrets are encrypted

---

config.json
docker/nginx/redirects-307.map
index.js
pages/ksphere/dispatch/1.0/index.md
pages/ksphere/dispatch/1.1/index.md
pages/ksphere/dispatch/1.2/index.md
pages/ksphere/dispatch/1.2/release-notes/index.md
pages/ksphere/dispatch/index.md

publishing Dispatch 1.2 beta docs

---

pages/mesosphere/dcos/2.1/installing/production/upgrading/index.md

https://jira.d2iq.com/browse/D2IQ-68872
The modified upgrade procedure for 2.1 needs some more discussion before we introduce it. This PR reverts back to the same procedure we use for earlier versions.

Revert master upgrade procedure for DC/OS 2.1

---

pages/mesosphere/dcos/2.0/installing/production/patching/index.md
pages/mesosphere/dcos/2.0/installing/production/upgrading/index.md
pages/mesosphere/dcos/2.1/installing/production/patching/index.md
pages/mesosphere/dcos/2.1/installing/production/upgrading/index.md

https://jira.d2iq.com/browse/D2IQ-68866
Use more relevant version numbers for upgrading and patching docs.
The difference between Enterprise and OSS instructions for the bootstrap node is minor, so moved it into one section, highlighting the difference at the relevant step.

Update versions for upgrading and patching DC/OS

---

pages/ksphere/kommander/1.1.0-beta/licensing/index.md

https://docs.google.com/spreadsheets/d/1BmFL1rOJUPfdwgk8vuaplH_2LCXRqe-LoxVgq8YwRXg/edit#gid=1940499820
Make sure licensing documentation specifies that licensing is found at the global level.

docs: update licensing instructions

---

pages/ksphere/kommander/1.1.0-beta/centralized-cost-monitoring/index.md
pages/ksphere/kommander/1.1.0-beta/introducing-kommander/index.md

https://jira.d2iq.com/browse/D2IQ-65915
Initial add of kubecost docs. @russurquhart1 please feel free to make edits/add more context directly, I wasn't sure how much kubecost context to give since it is a separate product with its own docs. There may need to be docs added on kommander UI kubecost integration, if so we can loop in the UI team to help write them.
TODO: we will also need to add licensing information once the kubecost/kommander licensing strategy is finalized.

Kubecost docs

---

pages/mesosphere/dcos/install-include/aws-remote-region-all.tmpl

https://jira.d2iq.com/browse/D2IQ-62845

fixing version number in template

---

docker/nginx/redirects-307.map
index.js
pages/mesosphere/dcos/2.1/deploying-jobs/examples/index.md
pages/mesosphere/dcos/2.1/deploying-jobs/index.md
pages/mesosphere/dcos/2.1/deploying-services/creating-services/index.md
pages/mesosphere/dcos/2.1/deploying-services/pods/technical-overview/index.md
pages/mesosphere/dcos/2.1/index.md
pages/mesosphere/dcos/2.1/installing/production/advanced-configuration/configuring-zones-regions/multi-zone/index.md
pages/mesosphere/dcos/2.1/installing/production/system-requirements/custom-ami/index.md
pages/mesosphere/dcos/2.1/metrics/datadog/index.md
pages/mesosphere/dcos/2.1/monitoring/debugging/cli-debugging/index.md
pages/mesosphere/dcos/2.1/monitoring/debugging/debug-perms/index.md
pages/mesosphere/dcos/2.1/monitoring/debugging/gui-debugging/index.md
pages/mesosphere/dcos/2.1/monitoring/debugging/index.md
pages/mesosphere/dcos/2.1/monitoring/debugging/task-exec/index.md
pages/mesosphere/dcos/2.1/release-notes/2.1.0/index.md
pages/mesosphere/dcos/2.1/release-notes/index.md
pages/mesosphere/dcos/2.1/security/ent/tls-ssl/ar-custom/index.md
pages/mesosphere/dcos/2.1/security/ent/tls-ssl/ca-trust-browser/index.md
pages/mesosphere/dcos/2.1/storage/external-storage/index.md

https://jira.d2iq.com/browse/D2IQ-68606
This is the GA release of DC/OS 2.1 docs. See JIRA for list of items done. 
Took out beta tags
modified release notes to be similar to blog
adding cops tickets

GA docs for DC/OS 2.1

---

layouts/partials/sidebar/en-sidebar.pug

NONE 
Fixing sidebar 
https://mesosphere.slack.com/archives/CSLFN7E3X/p1591875118260300 

changing sidebar for Kommander

---

pages/ksphere/kommander/1.0/index.md
pages/ksphere/kommander/1.1.0-beta/index.md

chore(kommander): remove welcome from title

---

pages/ksphere/kommander/1.1.0-beta/operations/index.md

N/A
Just added a comma to make it a bit more readable

Tiny Grammar change on ops index page

---

pages/ksphere/kommander/1.1.0-beta/release-notes/index.md

docs: add kommander 1.1.0 rc3 release notes

---

pages/mesosphere/dcos/1.13/release-notes/1.13.0/index.md

https://jira.d2iq.com/browse/COPS-5188

fixing wording on specific line - COPS-5188

---

pages/ksphere/konvoy/1.5.0-beta/autoscaling/index.md
pages/ksphere/konvoy/1.5.0-beta/gpu/index.md
pages/ksphere/konvoy/1.5.0-beta/install/http-proxy/index.md
pages/ksphere/konvoy/1.5.0-beta/install/install-airgapped/index.md
pages/ksphere/konvoy/1.5.0-beta/install/install-aws/advanced-provisioning/index.md
pages/ksphere/konvoy/1.5.0-beta/install/install-onprem/index.md
pages/ksphere/konvoy/1.5.0-beta/networking/index.md
pages/ksphere/konvoy/1.5.0-beta/reference/cluster-configuration/index.md
pages/ksphere/konvoy/1.5.0-beta/reference/cluster-configuration/v1beta1/index.md
pages/ksphere/konvoy/1.5.0-beta/reference/cluster-configuration/v1beta2/index.md
pages/ksphere/konvoy/1.5.0-beta/reference/command-line-interface/konvoy-deploy/index.md
pages/ksphere/konvoy/1.5.0-beta/reference/command-line-interface/konvoy-deploy/konvoy-deploy-addons/index.md
pages/ksphere/konvoy/1.5.0-beta/reference/command-line-interface/konvoy-diagnose/index.md
pages/ksphere/konvoy/1.5.0-beta/reference/command-line-interface/konvoy-up/index.md
pages/ksphere/konvoy/1.5.0-beta/release-notes/index.md
pages/ksphere/konvoy/1.5.0-beta/upgrade/upgrade-kubernetes-addons/index.md

Release notes and other minor changes for Konvoy `v1.5.0-beta.8`

konvoy: Update docs for konvoy release v1.5.0-beta.8

---

pull_request_template

Add Release Date Checklist to Pull Request Template.

---

pages/ksphere/dispatch/1.2/release-notes/index.md

Updated date in the Dispatch 1.2.0 release notes from a RC to GA date.

updated dispatch release date in rn

---

pages/ksphere/kommander/1.1.0-beta/centralized-cost-monitoring/index.md

https://jira.d2iq.com/browse/D2IQ-69759
We are updating the kubecost url, need to reflect the change in docs

Update kubecost url

---

pages/ksphere/kommander/1.1.0-beta/licensing/index.md

https://jira.d2iq.com/browse/D2IQ-66039

docs: add kommander license deletion

---

pages/mesosphere/dcos/version-policy/index.md

Update Version Policy

---

pages/mesosphere/dcos/cn/2.0/storage/index.md

fixes a broken URL in DSS documentation, Chinese translation.
- [2.0] Change all affected versions, if applicable (e.g. 1.13, 2.0, 2.1).

fix include path

---

pages/ksphere/kommander/1.1.0-beta/operations/access-control/index.md

https://jira.d2iq.com/browse/D2IQ-69656
We have a missing feature in access control that needs to be carefully documented but will be fixed in a followup patch release

feat: special Kommander 1.1 limitation for workspace -> project authz inheritance

---

pages/ksphere/kommander/1.1.0-beta/release-notes/index.md

Fix Thanos Version

---

pages/ksphere/konvoy/1.4/install/install-airgapped/index.md
pages/ksphere/konvoy/1.4/install/install-aws/advanced-provisioning/index.md
pages/ksphere/konvoy/1.4/install/install-aws/index.md
pages/ksphere/konvoy/1.4/install/install-azure/advanced-provisioning/index.md
pages/ksphere/konvoy/1.4/install/install-azure/index.md
pages/ksphere/konvoy/1.4/install/install-dev/index.md
pages/ksphere/konvoy/1.4/install/install-onprem/index.md
pages/ksphere/konvoy/1.4/install/install-secured/index.md
pages/ksphere/konvoy/1.4/networking/index.md
pages/ksphere/konvoy/1.4/quick-start/index.md
pages/ksphere/konvoy/1.4/reference/cluster-configuration/index.md
pages/ksphere/konvoy/1.4/release-notes/index.md
pages/ksphere/konvoy/1.4/tutorials/provision-a-custom-cluster/index.md
pages/ksphere/konvoy/1.4/upgrade/upgrade-kubernetes-addons/index.md

Release notes and small changes bumping the versions.

konvoy: Update docs for konvoy release v1.4.5

---

pages/mesosphere/dcos/2.0/release-notes/2.0.0/index.md
pages/mesosphere/dcos/2.0/release-notes/2.0.1/index.md
pages/mesosphere/dcos/2.0/release-notes/2.0.2/index.md
pages/mesosphere/dcos/2.0/release-notes/2.0.3/index.md
pages/mesosphere/dcos/2.0/release-notes/2.0.4/index.md
pages/mesosphere/dcos/2.0/release-notes/2.0.5/index.md

https://jira.d2iq.com/browse/D2IQ-69667

draft release notes for dcos 2.0.5

---

pages/ksphere/konvoy/1.4/release-notes/index.md
pages/ksphere/konvoy/1.4/upgrade/upgrade-kubernetes-addons/index.md
pages/ksphere/konvoy/1.5/release-notes/index.md

N/A
Fixing typo that I saw when doing other stuff

refernce -> reference

---

pages/mesosphere/dcos/services/beta-jupyter/1.2.0-0.33.7-beta/example/index.md
pages/mesosphere/dcos/services/beta-jupyter/1.2.0-0.33.7-beta/index.md
pages/mesosphere/dcos/services/beta-jupyter/1.2.0-0.33.7-beta/installing/index.md
pages/mesosphere/dcos/services/beta-jupyter/1.2.0-0.33.7-beta/limitations/index.md
pages/mesosphere/dcos/services/beta-jupyter/1.2.0-0.33.7-beta/overview/index.md
pages/mesosphere/dcos/services/beta-jupyter/1.2.0-0.33.7-beta/quick-start/index.md
pages/mesosphere/dcos/services/beta-jupyter/1.2.0-0.33.7-beta/uninstall/index.md
pages/mesosphere/dcos/services/beta-jupyter/index.md

https://jira.d2iq.com/browse/D2IQ-56119

fixing links in jupyter beta docs

---

pages/mesosphere/dcos/services/beta-kafka/2.10.0-2.4.0-beta/advanced/index.md
pages/mesosphere/dcos/services/beta-kafka/2.10.0-2.4.0-beta/configuration/index.md
pages/mesosphere/dcos/services/beta-kafka/2.10.0-2.4.0-beta/index.md
pages/mesosphere/dcos/services/beta-kafka/2.10.0-2.4.0-beta/limitations/index.md
pages/mesosphere/dcos/services/beta-kafka/2.10.0-2.4.0-beta/operations/index.md
pages/mesosphere/dcos/services/beta-kafka/2.10.0-2.4.0-beta/policy/index.md
pages/mesosphere/dcos/services/beta-kafka/2.10.0-2.4.0-beta/reference/index.md
pages/mesosphere/dcos/services/beta-kafka/2.10.0-2.4.0-beta/release-notes/index.md
pages/mesosphere/dcos/services/beta-kafka/2.10.0-2.4.0-beta/security/index.md
pages/mesosphere/dcos/services/beta-kafka/2.10.0-2.4.0-beta/started/index.md
pages/mesosphere/dcos/services/beta-kafka/2.10.0-2.4.0-beta/troubleshooting/index.md
pages/mesosphere/dcos/services/beta-kafka/2.10.0-2.4.0-beta/uninstall/index.md
pages/mesosphere/dcos/services/beta-kafka/2.10.0-2.4.0-beta/updates/index.md
pages/mesosphere/dcos/services/beta-kafka/kafka-auth/index.md

NO JIRA 
Adding the correct beta tags to the beta services 

fixing beta tags

---

pages/ksphere/kommander/1.1.0-beta/security/distributed-authnz/index.md

N/A, just checking for 1.1 release, making sure this is done.
Making sure everything looked good for this section, tip top, I say. Mostly grammar

checking for 1.1. Fixing some links, some grammar, looks good otherwise.

---

pages/ksphere/kommander/1.1.0-beta/operations/access-control/index.md
pages/ksphere/kommander/1.1.0-beta/tutorials/authorize-all-users/index.md

Explain explicitly how to create bindings to roles that grant users access to Kommander and Opsportal.

docs: clarify RBAC requirements

---

pages/ksphere/konvoy/1.4/tutorials/addon-repositories/index.md
pages/ksphere/konvoy/1.5/tutorials/addon-repositories/index.md

https://jira.d2iq.com/browse/D2IQ-69711
Updating older private repos, with public internal ones

replacing private repos with public internal repos

---

pages/ksphere/konvoy/1.5/uninstall/index.md

N/A - review of docs for release time
Grammar and adding a header where it looked to need one

some grammar and adding a heading

---

pages/ksphere/kommander/1.1.0-beta/operations/access-control/index.md

https://jira.d2iq.com/browse/D2IQ-69294
Updated the access control document: made clear that we have kommander and cluster roles and other improvements for clarity.

chore: update access-control document to reflect current state

---

pages/ksphere/kommander/1.1.0-beta/centralized-cost-monitoring/index.md
pages/ksphere/kommander/1.1.0-beta/centralized-monitoring/index.md

https://jira.d2iq.com/browse/D2IQ-69982
Minor changes/updates to centralized monitoring docs

Fix centralized monitoring dashboard name and typos

---

pages/ksphere/konvoy/1.5/security/external-idps/howto-dex-github-connector/index.md

N/A - Just 1.5 release doc review
updating link for github, adding link about granting access to k8s from our docs, minor grammar updates

updating link, adding link about granting access to k8s, minor grammar

---

pages/ksphere/kommander/1.0/operations/cloud-providers/configure-on-prem-provider/index.md
pages/ksphere/kommander/1.1.0-beta/operations/infrastructure-providers/configure-on-prem-provider/index.md

DOCS - Add Configuring On-Prem Infrastructure Provider

Kommander On-Prem Infrastructure Provider

---

pages/ksphere/kommander/1.0/operations/cloud-providers/configure-aws-cloud-provider-roles/index.md
pages/ksphere/kommander/1.1.0-beta/operations/infrastructure-providers/configure-aws-infrastructure-provider-roles/index.md

DOC- Update Configuring AWS Provider with User Role topic

Updated Configuring AWS Provider with User Role

---

pages/ksphere/kommander/1.1.0-beta/operations/infrastructure-providers/index.md

Added Docathon input to Infrastructure Provider doc

Kommander Infrastrucutre Provider: Added Docathon input

---

pages/ksphere/dispatch/1.2/release-notes/1.2.2/index.md

Changed menuweight of dispatch 1.2.2 release notes index.md from 20-30

changed menuweight

---

pages/ksphere/kommander/1.1/clusters/attach-cluster/attach-eks-cluster/index.md
pages/ksphere/kommander/1.1/clusters/attach-cluster/federated-addons/index.md
pages/ksphere/kommander/1.1/clusters/attach-cluster/index.md

https://jira.d2iq.com/browse/D2IQ-70202
https://jira.d2iq.com/browse/D2IQ-70203
Adds a page about addon federation in Kommander

Add federated-addons page

---

pages/mesosphere/dcos/1.11/tutorials/dcos-debug/scenarios/scen-1/index.md
pages/mesosphere/dcos/1.12/tutorials/dcos-debug/scenarios/scen-1/index.md
pages/mesosphere/dcos/1.13/tutorials/dcos-debug/scenarios/scen-1/index.md
pages/mesosphere/dcos/2.0/tutorials/dcos-debug/scenarios/scen-1/index.md
pages/mesosphere/dcos/2.1/tutorials/dcos-debug/scenarios/scen-1/index.md

https://jira.d2iq.com/browse/COPS-5954 

removing links to broken images COPS-5954

---

pages/mesosphere/dcos/1.12/metrics/quickstart/index.md
pages/mesosphere/dcos/1.13/metrics/quickstart/index.md
pages/mesosphere/dcos/2.0/metrics/quickstart/index.md
pages/mesosphere/dcos/2.1/metrics/quickstart/index.md

[COPS-3799](https://jira.d2iq.com/browse/COPS-3799)

Improve dcoumentation about dcos task metrics

---

pages/ksphere/kommander/1.1/tutorials/on-prem/index.md

https://jira.d2iq.com/browse/D2IQ-69966
Updates on-premise installation tutorial:
- updates button titles
- fixes embedded HTML styling
- adds a crucial preparation step
- fixes linked image title

chore: updates kommander on-premise installation tutorial.

---

pages/mesosphere/dcos/2.1/administering-clusters/backup-and-restore/backup-restore-cli/index.md

https://jira.d2iq.com/browse/COPS-6375
Adding information about the backup and restore of etcd in DC/OS 2.1 and newer.
Changes can be merged any time.
- [n/a] Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects) if you are moving a page.

COPS-6375: Backup and restore of etcd should be added to DC/OS docs

---

docker/nginx/redirects-307.map
pages/mesosphere/dcos/services/data-science-engine/2.0.1/customizations/custom-environment/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/customizations/custom-images/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/customizations/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/customizations/lab-extensions/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/dynamic-allocation/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/integrations/edge-lb/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/integrations/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/integrations/mxnet/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/integrations/pytorch/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/integrations/spark/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/integrations/tensorflow/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/overview/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/quick-start/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/release-notes/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/security/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/security/kerberos/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/security/tls/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/storage/hdfs/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/storage/host-volume/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/storage/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/storage/s3/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/supported-kernels/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/uninstall/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/upgrade/index.md

[D2IQ-70570](https://jira.d2iq.com/browse/D2IQ-70570)
* Adds updated docs for the release of Data Science Engine 2.0.1

Add release docs for Data Science Engine 2.0.1

---

pages/ksphere/kommander/1.1/release-notes/open-source-attributions/index.md

Updated OSS Attributions for Kommander 1.1

Updated OSS Attributions for Kommander 1.1

---

layouts/dcos-docs-landing.pug

go to https://docs.d2iq.com/mesosphere/dcos/, scroll all the way to the
bottom and click on "Install DC/OS". You get a 404.
This commit fixes that.

fix a landingpage link

---

pages/mesosphere/dcos/2.0/release-notes/2.0.5/index.md
pages/mesosphere/dcos/2.0/release-notes/2.0.6/index.md

https://jira.d2iq.com/browse/D2IQ-70509

DCOS 2.0.6 Release Notes

---

index.js
layouts/partials/sidebar/en-sidebar.pug
layouts/partials/sidebar/sidebar.pug
plugins/metalsmith-hierarchy-rss.js
plugins/metalsmith-hierarchy.js

the sidebar is the single largest time consumer in our build process.
in order to remedy that at some point in time, this commit tries to make
the plugin and the sidebar a bit more approachable by refactoring to a
more intention revealing style as well as documenting interesting bits
of the current implementation.
this slightly speeds up the build but is mainly an enabler for
subsequent optimizations.
the most surface for errors here would be with the sidebar on the left. also the links in the header bar that are next to the d2iq-icon could be affected. tested random sites for each product and did not notice a difference though.

refactor hierarchy-plugin and sidebar

---

pages/ksphere/kommander/1.0/release-notes/index.md
pages/ksphere/kommander/1.1/release-notes/index.md
pages/ksphere/kommander/1.1/upgrade/index.md
pages/ksphere/konvoy/1.4/release-notes/index.md

D2IQ-70989
Adding some info about challenges for upgrading kommander/konvoy

adding Kommander-specific challenges for upgrading

---

pages/mesosphere/dcos/2.0/installing/production/patching/index.md
pages/mesosphere/dcos/2.0/installing/production/upgrading/index.md
pages/mesosphere/dcos/2.1/installing/production/upgrading/index.md

Added upgrade paths for 2.05 and 2.06

---

pages/ksphere/kommander/1.1/release-notes/index.md
pages/ksphere/konvoy/1.5/include/kba-addon-intro.tmpl
pages/ksphere/konvoy/1.5/storage/intro-csi/index.md

qa updatinge links on komm release notes, kba intro, storage csi

---

pull_request_template

updating PR template so it points to the right things 

---

.github/styles/Microsoft/Acronyms.yml
.github/styles/Microsoft/ComplexWords.yml
.github/styles/Microsoft/HeadingAcronyms.yml
.github/styles/Vocab/Docs/accept.txt
.github/styles/Vocab/Docs/reject.txt

tweaking vale linter to be more accurate

---

pages/ksphere/konvoy/1.4/gpu/index.md
pages/ksphere/konvoy/1.4/install/install-airgapped/index.md
pages/ksphere/konvoy/1.4/install/install-onprem/index.md
pages/ksphere/konvoy/1.4/reference/addons/index.md
pages/ksphere/konvoy/1.4/reference/cluster-configuration/index.md
pages/ksphere/konvoy/1.4/reference/command-line-interface/konvoy-init/index.md
pages/ksphere/konvoy/1.4/reference/command-line-interface/konvoy-provision/index.md
pages/ksphere/konvoy/1.4/reference/command-line-interface/konvoy-up/index.md
pages/ksphere/konvoy/1.4/release-notes/index.md
pages/ksphere/konvoy/1.4/tutorials/addon-repositories/index.md
pages/ksphere/konvoy/1.4/upgrade/upgrade-kubernetes-addons/index.md
pages/ksphere/konvoy/1.5/autoscaling/index.md
pages/ksphere/konvoy/1.5/concepts/index.md
pages/ksphere/konvoy/1.5/gpu/index.md
pages/ksphere/konvoy/1.5/include/kba-addon-intro.tmpl
pages/ksphere/konvoy/1.5/install/install-airgapped/index.md
pages/ksphere/konvoy/1.5/install/install-onprem/index.md
pages/ksphere/konvoy/1.5/reference/addons/index.md
pages/ksphere/konvoy/1.5/reference/cluster-configuration/index.md
pages/ksphere/konvoy/1.5/reference/command-line-interface/konvoy-init/index.md
pages/ksphere/konvoy/1.5/reference/command-line-interface/konvoy-provision/index.md
pages/ksphere/konvoy/1.5/reference/command-line-interface/konvoy-up/index.md
pages/ksphere/konvoy/1.5/release-notes/index.md
pages/ksphere/konvoy/1.5/release-notes/kubernetes-base-addon/index.md
pages/ksphere/konvoy/1.5/tutorials/addon-repositories/index.md
pages/ksphere/konvoy/1.5/upgrade/upgrade-cli/index.md

* Konvoy v1.4.6 release-notes and minor changes.
* Konvoy v1.5.2 release-notes and minor changes.

konvoy: Update 1.4 and 1.5 docs

---

pages/mesosphere/dcos/2.0/multi-tenancy/quota-management/index.md
pages/mesosphere/dcos/2.0/security/ent/perms-reference/index.md
pages/mesosphere/dcos/2.1/multi-tenancy/quota-management/index.md
pages/mesosphere/dcos/2.1/security/ent/perms-reference/index.md
pages/mesosphere/dcos/2.2/multi-tenancy/quota-management/index.md

https://jira.d2iq.com/browse/D2IQ-62486
Add documentation for how to use slave_public in DC/OS 2.0

Document the changes to launching slave_public apps with multi-role

---

pages/ksphere/konvoy/partner-solutions/jenkins/index.md

Fix indentation in  jenkins docs

---

pages/mesosphere/dcos/services/kafka/2.10.0-2.4.0/reference/index.md

Fix REST API typos

---

pages/mesosphere/dcos/2.1/installing/production/patching/index.md
pages/mesosphere/dcos/2.1/installing/production/upgrading/index.md

Added UPgrade paths for the 2.1.1 release.

Added upgrade paths for 2.1.1

---

ci/site/1-setup-env.sh

* Pin Pyrsistent due to a broken moving dependency.

Pin Pyrsistent due to a broken moving dependency.

---

.github/styles/Vocab/Docs/accept.txt
pages/ksphere/kommander/1.1/tutorials/configure-rbac/index.md
pages/ksphere/kommander/1.2/tutorials/configure-rbac/index.md

https://jira.d2iq.com/browse/D2IQ-71347
Includes https://jira.d2iq.com/browse/D2IQ-D2IQ-71345
This adds yaml files that can directly be applied in the Kommander clusters for users who don't want to use the UI.

Add RBAC templates to Kommander

---

pages/mesosphere/dcos/1.13/release-notes/1.13.10/index.md
pages/mesosphere/dcos/1.13/release-notes/1.13.9/index.md

https://jira.d2iq.com/browse/D2IQ-71276

1.13.10 release notes

---

pages/ksphere/kubeflow/1.0.1-0.5.0/install/air-gapped/index.md
pages/ksphere/kubeflow/1.0.1-0.5.0/install/index.md
pages/ksphere/kubeflow/1.0.1-0.5.0/install/konvoy/index.md
pages/ksphere/kubeflow/1.0.1-0.5.0/install/on-premise/index.md
pages/ksphere/kubeflow/1.0.1-0.5.0/legal-notices/index.md
pages/ksphere/kubeflow/1.0.1-0.5.0/tutorials/katib/index.md
pages/ksphere/kubeflow/1.0.1-0.5.0/tutorials/training/mxnet/index.md
pages/ksphere/kubeflow/1.0.1-0.5.0/tutorials/training/pytorch/index.md
pages/ksphere/kubeflow/1.0.1-0.5.0/tutorials/training/spark/index.md
pages/ksphere/kubeflow/1.0.1-0.5.0/tutorials/training/tensorflow/index.md
pages/ksphere/kubeflow/1.0.1-0.5.0/user-management/index.md

https://jira.d2iq.com/browse/D2IQ-71592
Add install docs and typo fixes from
https://github.com/mesosphere/kudo-kubeflow/pull/252 to the branch for
kudo-kubeflow 0.5.0 docs update.

Refresh docs from kubeflow repo master.

---

pages/mesosphere/dcos/services/kubernetes/2.7.0-1.18.6/operations/disaster-recovery/index.md

https://jira.d2iq.com/browse/D2IQ-71545
This PR applies the feedback given by SEs regarding MKE backups.

Add instructions to delete MKE backup

---

pages/mesosphere/dcos/services/data-science-engine/2.0.0/storage/host-volume/index.md
pages/mesosphere/dcos/services/data-science-engine/2.0.1/storage/host-volume/index.md

[D2IQ-71676](https://jira.d2iq.com/browse/D2IQ-71676)
* Adds a warning message for use of UID/GID in the service.

[D2IQ-71676][DSEngine] Adds warning for uid/gid

---

pages/mesosphere/dcos/1.13/installing/production/patching/index.md
pages/mesosphere/dcos/2.0/installing/production/upgrading/index.md
pages/mesosphere/dcos/2.1/installing/production/upgrading/index.md

Added all of the upgrade paths for 1.13.10

Added upgrade pathes for 1.13.10

---

pages/mesosphere/dcos/2.2/release-notes/2.2/index.md

https://jira.d2iq.com/browse/D2IQ-71751

DCOS 2.2 Release Notes

---

config.json

removing do not build for 2.2

---

pages/ksphere/kommander/1.2/install-airgapped/index.md

https://jira.d2iq.com/browse/D2IQ-71735
improve air-gapped Kommander installation documentation

docs: improve air-gapped Kommander installation documentation

---

pages/ksphere/konvoy/1.4/install/install-airgapped/index.md
pages/ksphere/konvoy/1.4/release-notes/index.md

konvoy: Update 1.4 docs

---

pages/mesosphere/dcos/1.12/administering-clusters/repo/package-registry/operating/managing/index.md
pages/mesosphere/dcos/1.13/administering-clusters/package-registry/index.md
pages/mesosphere/dcos/2.0/administering-clusters/package-registry/index.md
pages/mesosphere/dcos/2.1/administering-clusters/package-registry/index.md
pages/mesosphere/dcos/2.2/administering-clusters/package-registry/index.md

Docs JIRA Ticket: [D2IQ-71324](https://jira.d2iq.com/browse/D2IQ-71324)
Update documentation for upgrading packages via Package Registry to reflect fixes from [COPS-6456](https://jira.d2iq.com/browse/COPS-6456)
Update documentation page for Package Registry upgrade process from DC/OS 1.12 to later versions of DC/OS.

Update DC/OS documentation to reflect Package Registry based upgrades.

---

pages/ksphere/kommander/1.1/centralized-cost-monitoring/index.md
pages/ksphere/kommander/1.2/centralized-cost-monitoring/index.md

https://jira.d2iq.com/browse/D2IQ-71409
Improve the Kubecost/centralized cost monitoring docs to include more Kubecost information and useful links out to Kubecost docs.

Improve Kubecost docs

---

docker/nginx/redirects-307.map
pages/mesosphere/dcos/services/marathon-lb/1.15/index.md
pages/mesosphere/dcos/services/marathon-lb/1.15/mlb-advanced-tutorial/index.md
pages/mesosphere/dcos/services/marathon-lb/1.15/mlb-basic-tutorial/index.md
pages/mesosphere/dcos/services/marathon-lb/1.15/mlb-configuration/index.md
pages/mesosphere/dcos/services/marathon-lb/1.15/mlb-install/index.md
pages/mesosphere/dcos/services/marathon-lb/1.15/mlb-overview/index.md
pages/mesosphere/dcos/services/marathon-lb/1.15/mlb-reference/index.md
pages/mesosphere/dcos/services/marathon-lb/1.15/mlb-scaling-tutorial/index.md
pages/mesosphere/dcos/services/marathon-lb/1.15/mlb-troubleshooting/index.md
pages/mesosphere/dcos/services/marathon-lb/1.15/release-notes/index.md

https://jira.d2iq.com/browse/COPS-5755

marathon-lb: add 1.15 docs

---

.github/styles/Vocab/Docs/accept.txt

Updating Accept List

---

pages/mesosphere/dcos/services/dcos-monitoring/1.0.0/operations/placement-constraint/index.md
pages/mesosphere/dcos/services/dcos-monitoring/1.0.1/operations/placement-constraint/index.md
pages/mesosphere/dcos/services/dcos-monitoring/1.0.2/operations/placement-constraint/index.md
pages/mesosphere/dcos/services/dcos-monitoring/1.1.0/operations/placement-constraint/index.md
pages/mesosphere/dcos/services/dcos-monitoring/1.2.0/operations/placement-constraint/index.md
pages/mesosphere/dcos/services/dcos-monitoring/1.3.0/operations/placement-constraint/index.md
pages/mesosphere/dcos/services/dcos-monitoring/1.3.1/operations/placement-constraint/index.md
pages/mesosphere/dcos/services/dcos-monitoring/1.4.0/operations/placement-constraint/index.md

Fixes: https://jira.d2iq.com/browse/COPS-6547
- [] Test all commands and procedures, if applicable.

Fix constraints example for dcos-monitoring

---

pages/mesosphere/dcos/version-policy/index.md

https://jira.d2iq.com/browse/COPS-6358?focusedCommentId=346000&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-346000
Main motivation is to see this supported OS section:
https://docs.docker.com/engine/install/centos/#os-requirements
- [ x] Create your PR against `staging`, not `master`. 

Update OS policy

---

pages/ksphere/kommander/1.2/release-notes/index.md

https://jira.d2iq.com/browse/D2IQ-72119
Added release not about infra provider view

D2IQ-72119: Document infra provider view

---

pages/ksphere/kommander/1.2/tutorials/duplicating-cluster/index.md

Docathon
Updates infrastructure provider verbiage in kommander tutorial

chore: update verbiage cloud provider -> infrastructure provider

---

pages/ksphere/kommander/1.2/projects/project-configmaps/index.md

added plain configmap explanation and reference to K8s concept and clarified configmap object explanation

Updated ConfigMap

---

pages/ksphere/kommander/1.2/operations/access-control/index.md

n/a - docathon	
syntax fix, link fix in markdown

quick PR to fix beta docs and non md links

---

pages/ksphere/kommander/1.2/projects/platform-services/index.md

Small Update

---

pages/ksphere/kommander/1.2/tutorials/project-administrator/index.md

Docathon
- Fix broken link
- Update project admin persona instructions to add step to give group workspace view permissions

Kommander project admin tutorial

---

pages/ksphere/kommander/1.2/uninstall/index.md

Same as https://github.com/mesosphere/dcos-docs-site/pull/3274 but for uninstall

Point to corresponding Konvoy uninstall docs instead of latest

---

pages/ksphere/kommander/1.2/projects/index.md

trying to more explicitly explain what the term federation means in this scenario

Added Federation Definition

---

pages/ksphere/kommander/1.2/troubleshooting/index.md

Docathon
Updates link to point to konvoy latest instead of 1.5

Update troubleshooting link to point to latest

---

pages/mesosphere/dcos/2.1/installing/production/system-requirements/ports/index.md
pages/mesosphere/dcos/2.2/installing/production/system-requirements/ports/index.md

https://jira.d2iq.com/browse/COPS-6602

Add etcd and calico ports

---

pages/ksphere/kommander/1.2/projects/index.md

Clarify exactly what a Project creates and does in terms of Kubernetes concepts/artifacts

Update Project Namespace Definition

---

pages/ksphere/kommander/1.2/projects/index.md

Adding an example Kubernetes YAML Project Object since the page references the object but does not document or give any example. A full object specification should be added later or in a completely separate documentation section describing how to declaratively create all of these Kommander objects but something is better than nothing, especially if we're going to mention it in the documentation.

Example Project Object

---

index.js
pages/ksphere/dispatch/1.2/index.md
pages/ksphere/dispatch/index.md

making dispatch 1.3 primary

---

.github/workflows/vale.yml

this tells vale to only annotate lines that have been changed in a PR.

lint only changed lines

---

pages/ksphere/dispatch/1.3/release-notes/open-source-attribution/index.md

Removed references to possible GPL usages

---

pages/mesosphere/dcos/2.2/deploying-jobs/quickstart/index.md
pages/mesosphere/dcos/2.2/gui/jobs/index.md
pages/mesosphere/dcos/2.2/release-notes/2.2/index.md
pages/mesosphere/dcos/2.2/storage/external-storage/csi/index.md

https://jira.d2iq.com/browse/D2IQ-71751

DCOS 2.2 GA Docs

---

index.js
pages/mesosphere/dcos/1.11/index.md
pages/mesosphere/dcos/1.13/index.md
pages/mesosphere/dcos/2.0/index.md
pages/mesosphere/dcos/2.1/index.md

fixing order of TOC drop down

---

pages/ksphere/kommander/1.1/troubleshooting/index.md
pages/ksphere/kommander/1.2/troubleshooting/index.md

no ticket
Add guide on how to remove clusters stuck in pending state. See https://mesosphere.slack.com/archives/CJQURP1FT/p1603889592292200 for context.

Add guide on how to remove clusters stuck in pending state.

---

pages/ksphere/kommander/1.2/tutorials/use-kcl-from-kubectl/index.md

Use variables for the workspace namespace and project namespace to make it easier to follow the tutorial with copy & paste.

Improve Kommander Tutorial - Use Variables for Namespaces

---

pages/mesosphere/dcos/2.2/archives/index.md

accessing archived docs

---

pages/ksphere/kommander/1.2/install-airgapped/index.md

fix: document konvoy-addons-chart-repo tag adjustment need

---

pages/mesosphere/dcos/install-include-0.3/aws-intro-and-prereqs.tmpl

[D2IQ-72879](https://jira.d2iq.com/browse/D2IQ-72879)
- [ x ] Change all affected versions, if applicable (e.g. 1.13, 2.0, 2.1).
- [ x ] Test all commands and procedures, if applicable.
- [ x ] Create your PR against `staging`, not `master`. 
- [ x ] Update all links if you are moving a page.

Fix wrong upgrade guide link

---

pages/ksphere/kommander/1.2/install-airgapped/index.md

https://jira.d2iq.com/browse/D2IQ-72882
Give details about how to set up a custom CA certificate
when setting up a custom registry.

docs: utilityApiserver dockerRegistryCaBundle

---

pages/mesosphere/dcos/2.1/release-notes/2.1.0/index.md
pages/mesosphere/dcos/2.1/release-notes/2.1.1/index.md
pages/mesosphere/dcos/2.2/release-notes/2.2.1/index.md
pages/mesosphere/dcos/2.2/release-notes/2.2/index.md

fixing merge conflicts for 2.2.1 release notes

---

pages/mesosphere/dcos/2.2/installing/production/upgrading/index.md
pages/mesosphere/dcos/version-policy/index.md

https://jira.d2iq.com/browse/D2IQ-72976
- [ x ] Create your PR against `staging`, not `master`. 

Added upgrade path for 2.2

---

layouts/all-products-landing.pug

fixing image for Kaptain

---

pages/ksphere/kommander/1.2/release-notes/index.md

fixing link in release notes

---

pages/ksphere/konvoy/1.6/multi-cluster/index.md

Fixing a broken link

---

pages/mesosphere/dcos/2.1/release-notes/2.1.2/index.md

Add DC/OS 2.1.2 release notes

---

pages/dkp/konvoy/1.6/legal/open-source-attribution/index.md

Added Konvoy 1.6 OSS attributions

---

pages/dkp/kommander/1.2/release-notes/open-source-attributions/index.md

updated the OSS licesnes for Kommander 1.2

---

pages/dkp/dispatch/1.3/release-notes/1.3.1/index.md

adding 1.3.1 release notes

---

js/search.js

closes https://jira.d2iq.com/browse/D2IQ-73450

show all products in the product selector

---

pages/dkp/dispatch/1.2/install/configure-argocd/index.md
pages/dkp/dispatch/1.3/install/configure-argocd/index.md

https://jira.d2iq.com/browse/COPS-6685
Fix the YAML formatting

Fix broken YAML formatting in argo-cd customization poge

---

pages/mesosphere/dcos/services/dcos-monitoring/1.4.0/operations/grafana/config/index.md

https://jira.d2iq.com/browse/COPS-6713

Fix missing/truncated link in Grafana docs

---

pages/mesosphere/dcos/services/include/configuration-service-settings.tmpl

https://jira.d2iq.com/browse/COPS-6722
Add "user" section into services configuration documentation

Update common SDK doc

---

pages/dkp/kommander/1.1/operations/manage-docker-hub-rate-limits/index.md
pages/dkp/kommander/1.2/operations/manage-docker-hub-rate-limits/index.md
pages/dkp/kommander/1.2/release-notes/index.md
pages/dkp/kommander/1.3/operations/manage-docker-hub-rate-limits/index.md
pages/dkp/kommander/1.3/release-notes/index.md

Add Docker Hub Rate Limit info for Kommander.

[DOC][Kommander] Add Docker Hub Rate Limit info for Kommander.

---

pages/dkp/kaptain/1.0.1-0.6.0/install/index.md

https://jira.d2iq.com/browse/COPS-6741

Add upgrade note to Kaptain install docs

---

pages/mesosphere/dcos/2.1/release-notes/2.1.3/index.md

https://jira.d2iq.com/browse/D2IQ-73456
Add release noted of 2.1.3

dcos: add 2.1.3 release notes

---

pages/dkp/kommander/1.3/release-notes/index.md

Updated Kommander 1.3 Release Notes for New Features.

[Doc][Kommander]Updated Kommander 1.3 Release Notes for New Features.

---

pages/dkp/kommander/1.3/release-notes/index.md
pages/dkp/konvoy/1.4/introduction/index.md
pages/dkp/konvoy/1.5/release-notes/index.md
pages/dkp/konvoy/1.6/install/install-airgapped/index.md
pages/dkp/konvoy/1.6/install/install-aws/index.md
pages/dkp/konvoy/1.6/install/install-azure/index.md
pages/dkp/konvoy/1.6/install/install-dev/index.md
pages/dkp/konvoy/1.6/install/install-onprem/index.md
pages/dkp/konvoy/1.6/install/install-secured/index.md
pages/dkp/konvoy/1.6/install/provision-a-custom-cluster/index.md
pages/dkp/konvoy/1.6/legal/open-source-attribution/index.md
pages/dkp/konvoy/1.6/networking/index.md
pages/dkp/konvoy/1.6/quick-start/index.md
pages/dkp/konvoy/1.6/reference/cluster-configuration/index.md
pages/dkp/konvoy/1.6/reference/cluster-configuration/v1beta1/index.md
pages/dkp/konvoy/1.6/reference/cluster-configuration/v1beta2/index.md
pages/dkp/konvoy/1.6/upgrade/upgrade-cli/index.md
pages/dkp/konvoy/1.6/upgrade/upgrade-kubernetes-addons/index.md
pages/dkp/konvoy/1.6/version-policy/index.md

updating feature branch

---

pages/dkp/konvoy/1.5/install/install-azure/index.md
pages/dkp/konvoy/1.6/install/install-azure/index.md
pages/dkp/konvoy/1.7/install/install-azure/index.md

https://jira.d2iq.com/browse/COPS-6769
Make Azure subscription example clearere

Fix subscription name in az command example

---

pages/dkp/kommander/1.3/release-notes/index.md

fixing release notes for Kommander 

---

pages/dkp/konvoy/1.6/operations/manage-docker-hub-rate-limits/index.md

missing "config: " parameter under the autoProvisioning section when configuring container registry

Update index.md to add missing parameter

---

pages/dkp/kommander/1.3/release-notes/index.md

Doc - Fixed broken link in Release Notes.

[Doc][Kom]Fixed broken link in Release Notes.

---

pages/dkp/kommander/1.3/licensing/index.md

[Doc Review for release](https://jira.d2iq.com/browse/D2IQ-74042)
Just some minor changes that were found when running the commands in kubectl for deleting the license. They're super minor and sort of superfluous, but thought I could just update while in here.

license updates pages/dkp/kommander/1.3/licensing/index.md

---

pages/dkp/kommander/1.3/install/index.md
pages/dkp/kommander/1.3/upgrade/index.md

N/A
Just updating link in the install page for kommander - where the install link goes to the install section, not prereqs.

updating link in pages/dkp/kommander/1.3/install/index.md

---

pages/dkp/kommander/1.3/workspaces/platform-service-requirements/index.md

kommander: Update fedaddon ES req

---

index.js
layouts/404.pug
pages/404/index.md
scss/base/_content.scss
scss/base/_layout.scss
scss/base/_search.scss
scss/base/_typography.scss

... along we remove some complexity on the page layout. i checked most
page-layouts and am pretty sure we don't break anything with this.

make 404 page not look broken

---

index.js
pages/dkp/dispatch/1.3/index.md
pages/dkp/dispatch/1.4/release-notes/1.4/index.md
pages/dkp/dispatch/1.4/tutorials/ci_tutorials/image-repo-setup/index.md
pages/dkp/kommander/1.3/install-airgapped/index.md
pages/dkp/konvoy/1.4/operations/manage-docker-hub-rate-limits/index.md
pages/dkp/konvoy/1.5/operations/manage-docker-hub-rate-limits/index.md
pages/dkp/konvoy/1.5/version-support/index.md
pages/dkp/konvoy/1.7/index.md

fixing some things we missed

---

pages/dkp/konvoy/1.7/release-notes/index.md

adding to release notes - Konvoy

---

pages/dkp/kaptain/1.2.0-1.0.0/custom-configuration/external-spark/index.md
pages/dkp/kaptain/1.2.0-1.0.0/custom-configuration/notebook-servers-configuration/index.md
pages/dkp/kaptain/1.2.0-1.0.0/install/index.md
pages/dkp/kaptain/1.2.0-1.0.0/troubleshooting/kaptain-1.0.0/index.md
pages/dkp/kaptain/1.2.0-1.0.0/tutorials/index.md
pages/dkp/kaptain/1.2.0-1.0.0/tutorials/sdk/index.md
pages/dkp/kaptain/1.2.0-1.0.0/user-management/index.md
pages/dkp/kaptain/1.2.0-1.0.0/version-policy/index.md

Changes applied after publishing the docs have been worked into the Kaptain repo, from where they are pushed to the public docs repo. This PR contains these changes:
- https://github.com/mesosphere/dcos-docs-site/pull/3437
- https://github.com/mesosphere/dcos-docs-site/pull/3430
- https://jira.d2iq.com/browse/COPS-6825

[Kaptain] Resolve COPS-6825

---

pages/dkp/konvoy/1.7/version-policy/index.md

reverting 1.8 konvoy version ref

reverting so this stays current with the 1.7 Konvoy version

---

pages/dkp/dispatch/1.4/release-notes/1.4/index.md

https://jira.d2iq.com/browse/COPS-6830
Fix typo in Dispatch release date.

Fix typo in Dispatch 1.4.0 release date

---

pages/dkp/kaptain/1.2.0-1.0.0/version-policy/index.md

https://jira.d2iq.com/browse/COPS-6831

Add clarification about Istio support status

---

pull_request_template

updating PR template

---

pages/dkp/dispatch/1.3/install/configure-argocd/index.md

Fix dead link

---

ci/docs-to-upstream.sh
ci/upstream-prs.sh

Implement tooling to make backport prs

---

pages/dkp/dispatch/1.4/release-notes/1.4.1/index.md

This PR also fixes a small error in the 1.4.0 RN.

Add Dispatch 1.4.1 RN.

---

Jenkinsfile.cron

https://jira.d2iq.com/browse/D2IQ-74072
This PR adds the documentation pages for Kommander 2.0 to the sync process.

sync Kommander 2.0 pages

---

pages/dkp/kommander/1.2/release-notes/1.2.1/index.md
pages/dkp/kommander/1.2/release-notes/1.2/index.md
pages/dkp/kommander/1.2/release-notes/index.md
pages/dkp/kommander/1.2/version-policy/index.md

Release Notes for Kommander 1.2.1 Patch

[Doc][Kommander] Kommander 1.2.1 Release Notes for Patch.

---

pages/dkp/kommander/1.4/release-notes/index.md
pages/dkp/kommander/1.4/version-policy/index.md

https://jira.d2iq.com/browse/D2IQ-74609
Added updated Release Notes info for 1.4 beta 1.

[Doc][Kommander] Added updated Release Notes info for 1.4 beta 1.

---

pages/dkp/kommander/1.1/release-notes/index.md

release notes for 1.1.4

---

pages/dkp/kommander/1.2/release-notes/1.2.2/index.md

Added info for Kommander 1.2.1 Patch to Release Notes.

[Doc][Kommander] Added info for Kommander 1.2.2 Patch to Release Notes.

---

pages/dkp/konvoy/1.7/release-notes/1.7.1/index.md

https://jira.d2iq.com/browse/COPS-6883
Release notes for bug that was fixed.

adding note to cover COPS-6883 being resolved

---

pages/dkp/kommander/1.4/clusters/tunnel-cli/api-reference/index.md
pages/dkp/kommander/1.4/clusters/tunnel-cli/index.md

https://jira.d2iq.com/browse/D2IQ-74360
Instructions for configuring a tunnel using the CLI.

CLI instructions to add a managed cluster using a tunnel

---

pages/dkp/kommander/1.4/clusters/index.md

n/a
Just removing this tag - this will fix the first level heading - so this will be in the navigation for this section.

beta tag in top of pages/dkp/kommander/1.4/clusters/index.md

---

pages/dkp/kommander/1.4/clusters/attach-cluster/access-managed-cluster/index.md
pages/dkp/kommander/1.4/clusters/attach-cluster/cluster-no-network-restrictions/index.md
pages/dkp/kommander/1.4/clusters/attach-cluster/cluster-with-networking-restrictions/index.md
pages/dkp/kommander/1.4/clusters/attach-cluster/finish-attaching-cluster/index.md
pages/dkp/kommander/1.4/clusters/attach-cluster/generate-kubeconfig/index.md

https://jira.d2iq.com/browse/D2IQ-74942
CNeth found several things to fix in PR#3518 that weren't done before it was merged. One of them was critical to fix as it affected display of an entire section of doc. One was very important to fix as the page title and its contents were opposites. All other changes are enumerated in the named Jira ticket.

[DOC][Komm] "Managing Clusters" section - Implemented review comments from cneth

---

pages/dkp/kommander/1.4/clusters/tunnel-cli/index.md

https://jira.d2iq.com/browse/D2IQ-74360
Add examples of accessing services on the managed cluster through a tunnel.

CLI tunnel examples

---

pages/dkp/kommander/1.4/clusters/tunnel-cli/api-reference/index.md

Cleanup API reference docs for tunnel.
Changes to this PR should be matched with a change in https://github.com/mesosphere/kubetunnel/pull/57

Cleanup tunnel API reference page

---

pages/dkp/kommander/1.3/release-notes/1.3.2/index.md

https://jira.d2iq.com/browse/D2IQ-74912
Updated Release Note info for Kommander 1.3.2.

[Doc][Kommander]Updated Release Note info for Kommander 1.3.2.

---

pages/mesosphere/dcos/services/kubernetes/2.8.0-1.19.2/operations/docker-custom-config/index.md

This help resolves the ratelimit issue with MKE

add registry mirror example

---

pages/dkp/kommander/1.4/projects/index.md

https://jira.d2iq.com/browse/D2IQ-74752
add documentation about resource placement

docs: add documentation about resource placement

---

pages/dkp/kommander/1.1/centralized-cost-monitoring/index.md
pages/dkp/kommander/1.1/operations/manage-docker-hub-rate-limits/index.md
pages/dkp/kommander/1.2/centralized-cost-monitoring/index.md
pages/dkp/kommander/1.2/clusters/attach-cluster/attach-eks-cluster/index.md
pages/dkp/kommander/1.2/operations/manage-docker-hub-rate-limits/index.md
pages/dkp/kommander/1.2/projects/project-configmaps/index.md
pages/dkp/kommander/1.3/centralized-cost-monitoring/index.md
pages/dkp/kommander/1.3/clusters/attach-cluster/attach-eks-cluster/index.md
pages/dkp/kommander/1.3/operations/manage-docker-hub-rate-limits/index.md
pages/dkp/kommander/1.3/projects/project-configmaps/index.md
pages/dkp/kommander/1.3/projects/project-deployments/index.md
pages/dkp/kommander/1.3/workspaces/platform-service-dependencies/index.md
pages/dkp/kommander/1.3/workspaces/workspace-platform-services/index.md
pages/dkp/kommander/1.4/clusters/attach-cluster/attach-eks-cluster/index.md
pages/dkp/kommander/1.4/operations/manage-docker-hub-rate-limits/index.md
pages/dkp/kommander/1.4/projects/project-configmaps/index.md
pages/dkp/kommander/1.4/workspaces/platform-service-dependencies/index.md
pages/dkp/kommander/1.4/workspaces/workspace-platform-services/index.md
pages/dkp/kommander/2.0/projects/project-configmaps/index.md
pages/dkp/kommander/2.0/projects/project-deployments/index.md
pages/dkp/kommander/2.0/workspaces/platform-service-dependencies/index.md
pages/dkp/kommander/2.0/workspaces/workspace-platform-services/index.md

N/A
Getting rid of please in the directions of the docs, as we're not asking folks to please do something, but just more letting them know what's what.

getting rid of 'please' in Kommander docs

---

pages/dkp/kommander/1.4/clusters/attach-cluster/generate-kubeconfig/index.md
pages/dkp/kommander/1.4/clusters/attach-cluster/requirements-for-attaching/index.md

PR review comment updates 2

---

pages/dkp/kommander/1.3/include/kudo-zookeeper-instance.tmpl
pages/dkp/kommander/1.3/include/kudo-zookeeper-plans.tmpl
pages/dkp/kommander/1.3/projects/platform-services/platform-services-catalog/kudo-zookeeper/index.md

[D2IQ-75006](https://jira.d2iq.com/browse/D2IQ-75006)

KUDO Zookeeper Platform Service Docs

---

pages/dkp/kommander/1.4/clusters/attach-cluster/requirements-for-attaching/index.md
pages/dkp/kommander/1.4/clusters/creating-konvoy-cluster-azure/index.md

n/a
cleaning up some links and updating a kubernetes and kommander version to be up to date with the release

editing link and updating k8s version for attach cluster

---

pages/dkp/kommander/1.0/install/index.md
pages/dkp/kommander/1.1/install/index.md
pages/dkp/kommander/1.2/install/index.md
pages/dkp/kommander/1.3/install/index.md
pages/dkp/kommander/1.4/install/index.md

Updating links in the installation/index.md page to be up to date.
see above.

updating konvoy/kommander installation/index.md links

---

pages/dkp/kommander/1.4/uninstall/index.md

n/a
Uninstall links updated. Other tiny grammar stuff.

updating links pages/dkp/kommander/1.4/uninstall/index.md

---

pages/dkp/kommander/1.4/release-notes/index.md

https://jira.d2iq.com/browse/D2IQ-75019
Updating 1.4 Kommander Release Notes.

[Doc]{Kommander] Updated Release Notes for 1.4 Kommander.

---

pages/dkp/kommander/1.4/operations/access-control/index.md

Add documentation of the `sync-to-project` annotation

Document the sync-to-project annotation

---

index.js

updating latest for GAs

---

pages/dkp/kommander/1.4/release-notes/index.md

Add RN and update component versions to match https://github.com/mesosphere/kubeaddons-kommander/releases/tag/v1.4.0. It's weird, I thought we've been updating these for every beta/RC, but it's pretty outdated here 🤔 

Update kommander 1.4.0 RN

---

index.js
pages/dkp/kaptain/1.2.0-1.0.0/index.md
pages/dkp/kaptain/1.2.0-1.0.0/introducing/index.md
pages/dkp/kaptain/1.2.0-1.1.0/index.md
pages/dkp/kaptain/1.2.0-1.1.0/introducing/index.md

https://jira.d2iq.com/browse/D2IQ-70907
- Merge unreachable doc with introduction.
- Mentioned update and upgrade operations in benefits section.

Fix for unreachable Kaptain docs page

---

pages/dkp/kaptain/1.2.0-1.1.0/legal-notices/index.md

DKP docs should not have `model`.

kaptain: remove  model option

---

pages/dkp/konvoy/1.8/upgrade/upgrade-cli/index.md

n/a
Making changes to docs with Russ's feedback to make it more clear/readable with bulleted items.

konvoy: Update 1.8 docs with Russ Feedback

---

pages/dkp/kaptain/1.2.0-1.0.0/support/index.md
pages/dkp/kaptain/1.2.0-1.1.0/support/index.md

Ported fix from https://github.com/mesosphere/kudo-kubeflow/pull/435 for https://jira.d2iq.com/browse/COPS-6936

COPS-6936: Fix frontmatter for Kaptain support page

---

pages/dkp/kommander/1.4/release-notes/open-source-attributions/index.md

N/A
Added OSS attributions for Kommander, Yakcl, and Kubetunnel

chore: Updated kommander, yakcl, and kubetunnel oss attributions

---

pages/dkp/kommander/1.4/clusters/attach-cluster/access-managed-cluster/index.md

Changed kubeconfig to monospace

---

pages/dkp/kommander/1.4/release-notes/1.4.0/index.md
pages/dkp/kommander/1.4/release-notes/1.4.1/index.md
pages/dkp/kommander/1.4/release-notes/index.md
pages/dkp/kommander/1.4/release-notes/legal-notices/index.md

https://jira.d2iq.com/browse/D2IQ-75884
Added Release Note Info for 1.4.1 Patch.

[DOC]{Kommander]Added Release Note Info for 1.4.1 Patch.

---

pages/dkp/kommander/2.0/clusters/attach-cluster/access-managed-cluster/index.md
pages/dkp/kommander/2.0/clusters/attach-cluster/attach-eks-cluster/index.md
pages/dkp/kommander/2.0/clusters/attach-cluster/index.md
pages/dkp/kommander/2.0/clusters/attach-cluster/requirements-for-attaching/index.md
pages/dkp/kommander/2.0/clusters/index.md
pages/dkp/kommander/2.0/clusters/management-cluster/index.md
pages/dkp/kommander/2.0/custom-git/index.md
pages/dkp/kommander/2.0/index.md
pages/dkp/kommander/2.0/install/index.md
pages/dkp/kommander/2.0/projects/index.md
pages/dkp/kommander/2.0/projects/project-configmaps/index.md
pages/dkp/kommander/2.0/projects/project-network-policies/index.md
pages/dkp/kommander/2.0/projects/project-policies/index.md
pages/dkp/kommander/2.0/projects/project-quotas-limit-range/index.md
pages/dkp/kommander/2.0/projects/project-roles/index.md
pages/dkp/kommander/2.0/projects/project-secrets/index.md
pages/dkp/kommander/2.0/workspaces/index.md
pages/dkp/kommander/2.0/workspaces/workspace-platform-services/index.md
pages/dkp/kommander/2.0/workspaces/workspace-platform-services/platform-service-dependencies/index.md
pages/dkp/kommander/2.0/workspaces/workspace-platform-services/platform-service-requirements/index.md

Manually copied latest beta docs.

---

pages/dkp/konvoy/2.0/install/advanced/prerequisites/index.md
pages/dkp/konvoy/2.0/quick-start-aws/index.md
pages/dkp/konvoy/2.0/quick-start-azure/index.md

doc: Manually copy konvoy2 latest docs

---

pages/dkp/kommander/2.0/clusters/attach-cluster/index.md
pages/dkp/kommander/2.0/clusters/attach-cluster/requirements-for-attaching/index.md
pages/dkp/kommander/2.0/clusters/index.md
pages/dkp/kommander/2.0/clusters/management-cluster/index.md
pages/dkp/kommander/2.0/custom-git/index.md
pages/dkp/kommander/2.0/index.md
pages/dkp/kommander/2.0/install/index.md
pages/dkp/kommander/2.0/projects/project-configmaps/index.md
pages/dkp/kommander/2.0/projects/project-policies/index.md
pages/dkp/kommander/2.0/projects/project-quotas-limit-range/index.md
pages/dkp/kommander/2.0/projects/project-roles/index.md
pages/dkp/kommander/2.0/projects/project-secrets/index.md
pages/dkp/kommander/2.0/workspaces/index.md
pages/dkp/kommander/2.0/workspaces/workspace-platform-services/index.md
pages/dkp/kommander/2.0/workspaces/workspace-platform-services/platform-service-dependencies/index.md
pages/dkp/kommander/2.0/workspaces/workspace-platform-services/platform-service-requirements/index.md

kommander2: Manually sync latest kommander 2.0 docs

---

pages/dkp/kommander/1.3/version-policy/index.md
pages/dkp/kommander/1.4/version-policy/index.md

https://jira.d2iq.com/browse/COPS-6758

adding new support terms

---

pages/dkp/kommander/1.4/version-policy/index.md

https://jira.d2iq.com/browse/COPS-6962

chore: added addon support levels

---

pages/dkp/konvoy/1.7/release-notes/1.7.4/index.md
pages/dkp/konvoy/1.8/release-notes/1.8.2/index.md

konvoy: release-note fixes

---

pages/dkp/kommander/1.2/archives/index.md
pages/dkp/kommander/1.3/archives/index.md
pages/dkp/kommander/1.4/archives/index.md

adding archive instructions to Kommander

---

README.md

No ticket
I added instructions how to archive the docs

docs: add archiving instructions to readme

---

Jenkinsfile.cron
ci/pull-upstreams.sh

https://jira.d2iq.com/browse/D2IQ-77810
This combines kommander2/konvoy2 PRs into one sync PR.
I left the single ones alive as a fallback for now, until we have tested this a bit.
https://mesosphere.slack.com/archives/C02AVBS638R/p1628286710018400

feat: combine konvoy and kommander into one pr

---

Jenkinsfile
README.md

This is a model how our ci implementation could look like. There are some TODOS open but I wanted to push it already so that @vacas5 could have a look and make suggestions.
I already created three branches (fresh out of main: `production`, `beta).

DO NOT MERGE ci: Add branching workflow scripts

---

Jenkinsfile

added CI stage to restart K8s deployment when build is finished

Jenkins k8s rollout

---

pages/dkp/kommander/1.3/release-notes/1.3.4/index.md
pages/dkp/kommander/1.4/release-notes/1.4.2/index.md

https://jira.d2iq.com/browse/D2IQ-78658
https://jira.d2iq.com/browse/D2IQ-78660
Updated Release notes for Patch versions 1.4.2 and 1.3.4.

[Docs][Kommander] Update Kommander 1.4.2 and 1.3.4 RNs

---

pages/dkp/kommander/1.3/release-notes/1.3.4/index.md
pages/dkp/kommander/1.4/release-notes/1.4.2/index.md

No JIRA
Fix menuweights on Kommander RN

fix: menu weight for kommander docs

---

pages/dkp/kaptain/1.2.0/upgrade/index.md

This PR update Kaptain upgrade documentation with additional steps required before installation.

Update Kaptain upgrade steps

---

index.js

changing latest to 2.1 for GA

---

Jenkinsfile.cron

Until we get 2.1 docs into a somewhat stable place, we will simply use
the release branches.

use kommander 2.1 temporarily

---

Jenkinsfile.cron
index.js
pages/dkp/kommander/2.1/gpu/kommander-config/index.md
pages/dkp/kommander/2.1/index.md
pages/dkp/kommander/2.1/install/networked/index.md
pages/dkp/kommander/2.1/major-upgrade/index.md
pages/dkp/kommander/2.1/major-upgrade/upgrade-clusters/index.md
pages/dkp/kommander/2.1/major-upgrade/upgrade-clusters/migrate-platform-apps/cleanup/index.md
pages/dkp/kommander/2.1/major-upgrade/upgrade-clusters/migrate-platform-apps/index.md
pages/dkp/kommander/2.1/major-upgrade/upgrade-clusters/migrate-platform-apps/prepare-apps/index.md
pages/dkp/kommander/2.1/major-upgrade/upgrade-clusters/migrate-platform-apps/supported-apps/index.md
pages/dkp/kommander/2.1/projects/applications/index.md
pages/dkp/kommander/2.1/projects/applications/platform-applications/application-deployment/index.md
pages/dkp/kommander/2.1/projects/project-deployments/continuous-delivery/index.md
pages/dkp/kommander/2.1/projects/project-deployments/gitops/index.md
pages/dkp/kommander/2.1/projects/project-deployments/index.md
pages/dkp/kommander/2.1/projects/project-deployments/prerequisites/index.md
pages/dkp/kommander/2.1/projects/project-deployments/troubleshooting/index.md
pages/dkp/kommander/2.1/projects/project-deployments/view-helm-releases/index.md
pages/dkp/kommander/2.1/release-notes/index.md
pages/dkp/kommander/2.1/tutorials/continuous-delivery/index.md
pages/dkp/kommander/2.1/tutorials/continuous-delivery/storing-secrets-with-gitops/index.md
pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/aws/index.md
pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/preprovisioned/index.md
s3config.json

updates from main to prod

---

pages/dkp/kommander/2.1/install/networked/index.md
pages/dkp/kommander/2.1/logging/disable-audit-logs/index.md
pages/dkp/kommander/2.1/major-upgrade/upgrade-clusters/migrate-platform-apps/cleanup/index.md
pages/dkp/kommander/2.1/major-upgrade/upgrade-clusters/migrate-platform-apps/index.md
pages/dkp/kommander/2.1/major-upgrade/upgrade-clusters/migrate-platform-apps/prepare-apps/index.md

Co-authored-by: Docs Bot <docs-bot@d2iq.com>

merge main into production

---

Jenkinsfile.cron

This will help us make sure that docs changes get back ported to the
release docs. Created branches and sync jobs for 2.1 and use main for
2.2.

sync jobs for 2.2

---

CODEOWNERS

This should auto request their review of any docs site PR.
Closes D2IQ-81838

Make docs team owners of dkp

---

pages/dkp/kommander/2.1/install/http-proxy/index.md
pages/dkp/kommander/2.1/licensing/index.md
pages/dkp/kommander/2.1/reference/apps/v1alpha2/index.md
pages/dkp/kommander/2.1/release-notes/index.md
plugins/metalsmith-hierarchy.test.js

docs: sync with mesosphere/kommander:release-2.1

---

pages/dkp/konvoy/2.1/choose-infrastructure/aks/aks-advanced/aa-bootstrap/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/aks/aks-advanced/aa-delete/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/aks/aks-advanced/aa-explore/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/aks/aks-advanced/aa-new/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/aks/aks-advanced/aa-prerequisites/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/aks/aks-advanced/aa-replace-node/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/aks/aks-advanced/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/aks/aks-quickstart/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/aks/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/eks/advanced/self-managed/index.md
pages/dkp/konvoy/2.1/supported-operating-systems/index.md

Autosync/mesosphere/konvoy2/release 2.1

---

pages/dkp/kommander/2.1/gpu/kommander-config/index.md

https://jira.d2iq.com/browse/D2IQ-81538
Fixes an outdated description of the setup procedure for enabling Nvidia platform services on Kommander 2.1.  Should not wait for a new release, if possible.

fix: updates nvidia platform services installation

---

README.md

point out vale asdf plugin

---

pages/dkp/kommander/2.2/gpu/kommander-config/index.md

https://jira.d2iq.com/browse/D2IQ-81538
Fixes an outdated description of the setup procedure for enabling Nvidia platform services on Kommander. We just landed a hot fix, this is the long term fix for 2.2.

fix: updates nvidia platform services installation - kommander 2.2

---

.github/styles/Vocab/Docs/accept.txt

This should eliminate the errors encountered when we do the workspace docs restructure

add more terms for workspace docs restructure

---

.github/pull_request_template.md
.github/styles/Vocab/Docs/accept.txt

https://jira.d2iq.com/browse/D2IQ-81840
Added preview url template, but as a comment in case we'd rather keep the preview url more hidden (to get it, you can "edit" the pr description to see it. If we don't care that much about it, I can un-comment it out. I also wasn't sure if this should go into develop or main, if this goes into develop now will it go into main eventually? Or should I create a PR for both branches?

chore: Add preview link to pr template as comment

---

pages/dkp/kommander/1.4/release-notes/1.4.3/index.md

Starts draft for kommander 1.4.3 release notes.
https://jira.d2iq.com/browse/D2IQ-81787 

[RN] Add kommander 1.4.3 release notes

---

pages/dkp/konvoy/1.8/addons/addon-repositories/index.md
pages/dkp/konvoy/1.8/autoscaling/index.md
pages/dkp/konvoy/1.8/cli/command-line-interface/konvoy-init/index.md
pages/dkp/konvoy/1.8/cli/command-line-interface/konvoy-provision/index.md
pages/dkp/konvoy/1.8/gpu/index.md
pages/dkp/konvoy/1.8/install/install-airgapped/index.md
pages/dkp/konvoy/1.8/install/install-onprem/index.md
pages/dkp/konvoy/1.8/install/install-small-env/index.md
pages/dkp/konvoy/1.8/install/provision-a-custom-cluster/index.md
pages/dkp/konvoy/1.8/legal/open-source-attribution/index.md
pages/dkp/konvoy/1.8/quick-start/index.md
pages/dkp/konvoy/1.8/reference/addons/index.md
pages/dkp/konvoy/1.8/reference/cluster-configuration/index.md
pages/dkp/konvoy/1.8/reference/cluster-configuration/v1beta1/index.md
pages/dkp/konvoy/1.8/reference/cluster-configuration/v1beta2/index.md
pages/dkp/konvoy/1.8/upgrade/upgrade-cli/index.md
pages/dkp/konvoy/1.8/version-policy/index.md

https://jira.d2iq.com/browse/D2IQ-82339
Various versioning updates related to patch bump 1.8.4 based enclosed list:
https://github.com/mesosphere/konvoy/pull/3407/files?authenticity_token=ZyB3wUJzfmRzdeKpLxWeazbSeh7o5c0rLA9C0YG9CQrhtWi3iarjYDIphCf%2FOhFK12ZbooI2zgMXueOtxh2emA%3D%3D&file-filters%5B%5D=.md

Patch Bump Updates Konvoy 1.8.4

---

pages/dkp/konvoy/1.8/upgrade/upgrade-cli/index.md

docs: updating upgrade cli for calico

---

pages/dkp/kommander/2.1/security/oidc/index.md

Not having an example config mentioned here led to
https://jira.d2iq.com/browse/D2IQ-81508

docs: add example to OIDC page

---

pages/dkp/kommander/2.1/workspaces/applications/platform-applications/index.md
pages/dkp/kommander/2.2/projects/applications/catalog-applications/custom-resources-workspace-catalog/index.md
pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/application-deployment/index.md
pages/dkp/kommander/2.2/workspaces/applications/platform-applications/index.md
pages/dkp/kommander/2.2/workspaces/applications/platform-applications/platform-service-requirements/index.md

Following up from this link
https://github.com/mesosphere/dcos-docs-site/pull/3956/files
I did not have time to look at it before
it merged and just had some minor change
suggestions.
Normally I wouldn't follow up with a PR, but I already started to make comments on the other PR before I realized it was already closed.
n/a
Minor style changes and phrasing changes.

docs: minor edits following up workspace updates

---

.github/styles/Vocab/Docs/accept.txt
pages/dkp/kommander/2.1/projects/applications/catalog-applications/custom-resources-workspace-catalog/index.md
pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/application-deployment/index.md
pages/dkp/kommander/2.1/workspaces/applications/platform-applications/index.md
pages/dkp/kommander/2.1/workspaces/applications/platform-applications/platform-service-requirements/index.md

Keeping pace with what is on develop
Needed to add some words that are acceptable
things like nvidia and other apps need
to be lower case for our tables and whatnot
Sort of dup-ing this one:
https://github.com/mesosphere/dcos-docs-site/pull/3974
n/a
Keeping pace with what is on develop
Needed to add some words that are acceptable
things like nvidia and other apps need
to be lower case for our tables and whatnot

docs: minor adjustments to workspace pages

---

s3config.json

redirect for dispatch broken link

---

pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/application-deployment/index.md

modified from the project custom catalog app ui steps

feat: workspace catalog app ui steps 2.1.1

---

pages/dkp/kommander/2.1/projects/applications/catalog-applications/custom-resources-workspace-catalog/spark-operator-custom-resources/index.md
pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/spark-operator/index.md

https://jira.d2iq.com/browse/D2IQ-82303
Docs about Spark Operator and its CR

Spark operator doc 2.1.1

---

.github/styles/write-good/Weasel.yml
pages/dkp/kommander/2.1/clusters/creating-konvoy-cluster-advanced/index.md
pages/dkp/kommander/2.1/clusters/creating-konvoy-cluster-aws/index.md

This is just copied from the content of: 
https://github.com/mesosphere/dcos-docs-site/pull/3946
@cmastr here's a first draft but it should probably be taken over by someone
Closes D2IQ-81810
Document the workflow for users to use the new YAML editor in the UI.

Create advanced cluster with YAML

---

pages/dkp/kommander/2.1/projects/applications/catalog-applications/custom-resources-workspace-catalog/spark/index.md
pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/spark-operator/index.md

https://jira.d2iq.com/browse/D2IQ-82303
rename folder & added link to spark CR doc

Spark link to cr 2.1.1

---

.github/styles/Vocab/Docs/accept.txt
pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/index.md

Adding docs about how to install the workspace catalog since this will be a manual task until https://jira.d2iq.com/browse/D2IQ-79950 is resolved. I just don't want this to get lost!

Add install instructions for the workspace catalog repo

---

pages/dkp/kommander/2.1/projects/applications/catalog-applications/custom-applications/index.md
pages/dkp/kommander/2.1/projects/applications/catalog-applications/custom-resources-workspace-catalog/index.md
pages/dkp/kommander/2.1/projects/applications/catalog-applications/dkp-applications/custom-resources-workspace-catalog/index.md
pages/dkp/kommander/2.1/projects/applications/catalog-applications/dkp-applications/custom-resources-workspace-catalog/kafka/index.md
pages/dkp/kommander/2.1/projects/applications/catalog-applications/dkp-applications/custom-resources-workspace-catalog/spark/index.md
pages/dkp/kommander/2.1/projects/applications/catalog-applications/dkp-applications/custom-resources-workspace-catalog/zookeeper/index.md
pages/dkp/kommander/2.1/projects/applications/catalog-applications/dkp-applications/index.md
pages/dkp/kommander/2.1/projects/applications/catalog-applications/index.md
pages/dkp/kommander/2.1/projects/applications/index.md
pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/dkp-applications/index.md
pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/dkp-applications/kafka-operator/index.md
pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/dkp-applications/spark-operator/index.md
pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/dkp-applications/zookeeper-operator/index.md
pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/index.md

https://jira.d2iq.com/browse/D2IQ-82743
LIVE PREVIEW - http://docs-d2iq-com-pr-3989.s3-website-us-west-2.amazonaws.com/dkp/kommander/2.1/release-notes/ 
Restructure docs with new hierarchy of apps - instead of using "catalog apps" to describe dkp-supported apps (apps in dkp-catalog-applications), we should instead refer to these as "dkp apps". Reflect this updated hierarchy in both workspace and project app docs. Updated structure:
```
$ tree pages/dkp/kommander/2.1/workspaces/applications/
pages/dkp/kommander/2.1/workspaces/applications/
├── catalog-applications
│   ├── application-deployment
│   │   └── index.md
│   ├── dkp-applications
│   │   ├── index.md
│   │   ├── kafka-operator
│   │   │   └── index.md
│   │   ├── spark-operator
│   │   │   └── index.md
│   │   └── …
```

docs: Add dkp-applications subdir under catalog-apps

---

pages/dkp/konvoy/2.1/choose-infrastructure/azure/advanced/bootstrap/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/azure/advanced/certificate_renewal/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/azure/advanced/delete/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/azure/advanced/explore/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/azure/advanced/new/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/azure/quick-start-azure/index.md
pages/dkp/konvoy/2.1/image-builder/override-files/create-custom-or-files/proxy-or-files/index.md

https://jira.d2iq.com/browse/D2IQ-82072 
The original D2IQ-82072 ticket asked for three updates to the Azure cluster creation process. This PR handles the 1st (making use of existing network infrastructure) and 3rd: updating the proxy override file creation/format.
This PR is the remake of PR#3979 which has already been reviewed. I closed that PR because of unresolvable merge conflicts with Vale's `accept.txt` file.

[Konvoy 2.1][DOCS] D2IQ-82072 Azure install updates

---

pages/dkp/konvoy/2.1/image-builder/override-files/create-custom-or-files/container-image-or-files/index.md

Updating list of images to use.

konvoy: update list of images

---

pages/dkp/kommander/2.1/release-notes/index.md

docs: fixed typo in kommander 2.1 RN

---

layouts/all-products-landing.pug

This was requested by PM a while ago and just getting to it. 
http://docs-d2iq-com-pr-3997.s3-website-us-west-2.amazonaws.com/

changing order of products on home page

---

pages/dkp/kommander/2.1/release-notes/2.1.1/index.md

fix: change release version to 2.1.1 instead of 2.1.0

---

.github/styles/Vocab/Docs/accept.txt
pages/dkp/kommander/2.1/release-notes/2.1.1/index.md

update date and version

---

.github/styles/Vocab/Docs/accept.txt
pages/dkp/konvoy/2.1/release-notes/2.1.1/index.md

[](https://jira.d2iq.com/browse/D2IQ-83122)
Corrected date, verified presence of air-gapped bundles mention, and corrected formatting in some sections to resemble Kommander RN more closely.

D2IQ-83122 fixes to 211 release notes

---

.github/styles/Vocab/Docs/accept.txt
pages/dkp/kommander/2.1/release-notes/2.1.1/index.md
pages/dkp/konvoy/2.1/release-notes/2.1.1/index.md

backporting changes from Main to Develop 

---

.github/styles/Vocab/Docs/accept.txt
pages/dkp/kommander/2.1/major-upgrade/upgrade-clusters/migrate-platform-apps/index.md
pages/dkp/kommander/2.1/major-upgrade/upgrade-clusters/migrate-platform-apps/prepare-apps/index.md
pages/dkp/konvoy/2.1/major-version-upgrade/plan/aws-environment-special-considerations/index.md
pages/dkp/konvoy/2.1/major-version-upgrade/plan/index.md
pages/dkp/konvoy/2.1/major-version-upgrade/plan/on-prem-environment-special-considerations/index.md
pages/dkp/konvoy/2.1/major-version-upgrade/understand-standard-config/index.md
pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/aws/index.md
pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/prepare-local-environment/index.md
pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/preprovisioned/index.md

n/a
Updating some bits so it's more sytlistically like ours, fixing linting errors, some other minor version bumps for the major upgrade path topic

docs: updating major upgrade path

---

pages/dkp/kommander/2.1/projects/applications/catalog-applications/dkp-applications/custom-resources-workspace-catalog/kafka/index.md
pages/dkp/kommander/2.1/projects/applications/catalog-applications/dkp-applications/custom-resources-workspace-catalog/spark/index.md
pages/dkp/kommander/2.1/projects/applications/catalog-applications/dkp-applications/custom-resources-workspace-catalog/zookeeper/index.md
pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/dkp-applications/kafka-operator/index.md
pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/dkp-applications/spark-operator/index.md
pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/dkp-applications/zookeeper-operator/index.md

fix: Add note about operators installation

---

.github/styles/Vocab/Docs/accept.txt

n/a
Adding words that are in the API docs. It also beats not having spellcheck on the api docs, which could be bad.

docs: adding words that are found in api ref docs

---

.github/styles/Vocab/Docs/accept.txt

N/A
updating this so the tests will pass on main

docs: adding words from api ref docs

---

pages/dkp/kommander/2.1/major-upgrade/upgrade-clusters/migrate-platform-apps/index.md
pages/dkp/kommander/2.2/major-upgrade/upgrade-clusters/migrate-platform-apps/index.md

n/a
Fixing typo for kuberentes -> kubernetes

docs: fixing typo for kuberentes

---

pages/dkp/kommander/2.1/install/air-gapped/index.md

fix kommander airgapped instructions

---

pages/dkp/konvoy/2.1/supported-operating-systems/index.md

http://docs-d2iq-com-pr-4023.s3-website-us-west-2.amazonaws.com/
https://jira.d2iq.com/browse/D2IQ-83125 

updating rhel to include FIPS and Air gapped

---

pages/dkp/konvoy/2.2/supported-operating-systems/index.md

http://docs-d2iq-com-pr-4028.s3-website-us-west-2.amazonaws.com/
none

adding rhel to 2.2

---

pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/upgrade/control-plane/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/upgrade/node-pool/index.md

n/a - just copying changes that were relevant in the 2.1 folder to the develop branch +2.2 folder:
https://github.com/mesosphere/dcos-docs-site/pull/4031
styling for somethings that I saw when I was reviewing some docs 

docs: styling

---

pages/dkp/kommander/2.2/install/air-gapped/index.md

docs: backport #4030 to develop from main

---

pages/dkp/kommander/2.1/install/air-gapped/index.md

[D2IQ-83639](https://jira.d2iq.com/browse/D2IQ-83639)
Just cleaning up this YAML to add context of where this is in the install yaml file, and also alphabetizing things on the same level of the YAML file.

docs: cleaning up yaml for apps area of install

---

.github/styles/Vocab/Docs/accept.txt
pages/dkp/konvoy/2.1/choose-infrastructure/awsgovcloud/clusterconfig/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/awsgovcloud/clustercontrol/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/awsgovcloud/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/awsgovcloud/prerequisites/index.md

Hey all,
This new subset of docs are for the Air-gapped AWS GovCloud environment as outlined here: https://hackmd.io/kxTqHRn-S5WOXYl1klRc_w#Prerequisties by John Miller.
Preview: http://docs-d2iq-com-pr-4025.s3-website-us-west-2.amazonaws.com/
https://jira.d2iq.com/browse/D2IQ-82031
Information concerning OS/image bundles have been added, as well as environment setup for AWS GovCloud.

[Konvoy 2.1.1] AirGap Bundle - Gov Environment Requirements(2)

---

pages/dkp/kommander/2.1/install/custom-domain/index.md

n/a
I just was reviewing this topic - and noticed just some small nits. So, thought I could just push them up quick.

docs: nit changes on custom domain topic

---

pages/dkp/konvoy/2.1/release-notes/2.1.1/index.md

http://docs-d2iq-com-pr-4053.s3-website-us-west-2.amazonaws.com/

adding a link to govcloud info

---

pages/dkp/kommander/2.2/install/air-gapped/index.md

https://jira.d2iq.com/browse/D2IQ-83457
Document new helm repository related k-cli commands. These changes are for upcoming 2.2 release. There is no 2.2 directory for kommander yet so I edited the 2.1 docs. Please feel free to adjust/change this PR however you like. 

docs: document new helm repository related k-cli commands

---

pages/dkp/konvoy/2.1/choose-infrastructure/eks/advanced/bootstrap/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/eks/advanced/delete/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/eks/advanced/explore/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/eks/advanced/new/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/eks/advanced/replace-node/index.md

http://docs-d2iq-com-pr-4029.s3-website-us-west-2.amazonaws.com/

Docs updating eks command outputs

---

pages/dkp/konvoy/2.1/choose-infrastructure/awsgovcloud/prerequisites/index.md

Updated DL links 2.1

---

pages/dkp/kommander/2.1/networking/domains/index.md
pages/dkp/kommander/2.1/networking/ingress/index.md
pages/dkp/kommander/2.1/networking/load-balancing/index.md
pages/dkp/kommander/2.1/networking/use-ingress-load-balancer/index.md

http://docs-d2iq-com-pr-4060.s3-website-us-west-2.amazonaws.com/

Moving to correct branch COPS-7143

---

pages/dkp/konvoy/2.2/choose-infrastructure/aks/aks-advanced/aa-bootstrap/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aks/aks-advanced/aa-delete/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aks/aks-advanced/aa-explore/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aks/aks-advanced/aa-new/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aks/aks-advanced/aa-prerequisites/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aks/aks-advanced/aa-replace-node/index.md

[Docs] updating aks commands and outputs

---

pages/dkp/konvoy/2.1/choose-infrastructure/aks/aks-advanced/aa-bootstrap/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/aks/aks-advanced/aa-delete/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/aks/aks-advanced/aa-explore/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/aks/aks-advanced/aa-new/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/aks/aks-advanced/aa-prerequisites/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/aks/aks-advanced/aa-replace-node/index.md

n/a
Porting over the changes from 2.2 to this in 2.1:
https://github.com/mesosphere/dcos-docs-site/pull/4058

docs: updating AKS sections of docs

---

pages/dkp/kaptain/1.3.0/secrets-management/index.md

Port of https://github.com/mesosphere/kudo-kubeflow/pull/645.
This fix should be included in Kaptain 1.3 release docs, so I specified the target branch based on the https://github.com/mesosphere/dcos-docs-site/pull/4057.
Updates documentation to use a Secret instead of a ConfigMap for storing a Docker configuration file, which could include sensitive data, such as the user's credentials.

Update tutorial for managing Docker credentials

---

.github/styles/Vocab/Docs/accept.txt
pages/dkp/kommander/2.2/networking/domains/index.md
pages/dkp/kommander/2.2/networking/ingress/index.md
pages/dkp/kommander/2.2/networking/load-balancing/index.md
pages/dkp/kommander/2.2/networking/use-ingress-load-balancer/index.md

http://docs-d2iq-com-pr-4066.s3-website-us-west-2.amazonaws.com/

backporting cops 7143 to 2.2

---

pages/dkp/konvoy/1.8/release-notes/1.8.4/index.md

https://jira.d2iq.com/browse/COPS-7146
Add a Warning in the Konvoy release docs about the removal of Argo CD.

konvoy: add a Warning about removal of Argo

---

pages/dkp/kommander/2.1/operations/access-control/index.md

n/a
I saw this and I cannot unsee it and I made this, so I need to change it.

docs: blah typo

---

pages/dkp/kommander/2.2/install/air-gapped/index.md

This is mainly a forward-port of
https://github.com/mesosphere/dcos-docs-site/pull/4087 plus some
formatting fixes applied to code blocks.
http://docs-d2iq-com-pr-4105.s3-website-us-west-2.amazonaws.com/

fix: MetalLB documentation for air-gapped install

---

pages/dkp/kommander/2.2/projects/applications/catalog-applications/custom-applications/git-repo-structure/index.md

https://jira.d2iq.com/browse/D2IQ-81514
Added note.

Add link to dkp-catalog-applications gitrepo for example

---

pages/dkp/kommander/2.2/clusters/attach-cluster/requirements-for-attaching/index.md

Jira: https://jira.d2iq.com/browse/D2IQ-82431?filter=57924
Updated to 1.22 in the scope of support.

updated 1.21 to 1.22

---

pages/dkp/kommander/2.1/backup-and-restore/index.md

http://docs-d2iq-com-pr-4110.s3-website-us-west-2.amazonaws.com/
https://jira.d2iq.com/browse/D2IQ-78903 

adding backup and restore file on it's own

---

pages/dkp/kommander/2.1/install/configuration/index.md
pages/dkp/kommander/2.2/install/configuration/index.md

Fixes the example configuration for grafana to be technically correct

docs: fix grafana example config

---

pages/dkp/kaptain/1.3.0/upgrade/index.md

The topic now includes information on how to update Kaptain on Konvoy 1.x and not only on Konvoy 2.x.
Some restructuring of the article was done as well, any feedback is appreciated.
Jira: https://jira.d2iq.com/browse/COPS-7176?filter=57924

Upgrade Kaptain for Konvoy 1.x

---

pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/custom-applications/add-create-git-repo/index.md
pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/custom-applications/application-metadata/index.md
pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/custom-applications/deploy-custom-app/index.md
pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/custom-applications/git-repo-structure/index.md
pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/custom-applications/index.md
pages/dkp/kommander/2.2/projects/applications/catalog-applications/custom-applications/application-metadata/index.md
pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/custom-applications/add-create-git-repo/index.md
pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/custom-applications/application-metadata/index.md
pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/custom-applications/deploy-custom-app/index.md
pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/custom-applications/git-repo-structure/index.md
pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/custom-applications/index.md

2 Subtasks included here:
Copied Custom Applications: https://jira.d2iq.com/browse/D2IQ-84556
Added scope field: https://jira.d2iq.com/browse/D2IQ-84557

Add Applications, 2 sub-tasks here

---

pages/dkp/kommander/2.1/release-notes/2.1.0/index.md

Removes a sentence that slipped through while it shouldn't have; see https://github.com/mesosphere/dcos-docs-site/pull/4138/files/1aa54d03b0c96f42fab40222d6ea5919059914c2#r811337514
http://docs-d2iq-com-pr-4143.s3-website-us-west-2.amazonaws.com/dkp/kommander/2.1/release-notes/2.1.0/

chore: removing unhelpful passage

---

pages/dkp/konvoy/2.1/supported-operating-systems/index.md

n/a - per product request
Validated DKP install for SLES + SLES GPU
Also just made the table prettier in a code editor
http://docs-d2iq-com-pr-4141.s3-website-us-west-2.amazonaws.com/

docs: adding sles and sles gpu for os qual

---

pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/aws/index.md

Preview
http://docs-d2iq-com-pr-4140.s3-website-us-west-2.amazonaws.com/dkp/konvoy/2.1/major-version-upgrade/upgrade/aws/

[Docs] some update on major-version-upgrade/upgrade/aws/index.md page

---

pages/dkp/konvoy/1.7/networking/control-plane-high-availability/index.md
pages/dkp/konvoy/1.8/networking/control-plane-high-availability/index.md

Jira: https://jira.d2iq.com/browse/COPS-7156
Added note to 1.7 and 1.8. Please verify if we need to add this to 2.x anywhere

[Konvoy 1.7, 1.8] COPS-7156 HA Control Plane

---

pages/dkp/kommander/2.2/projects/applications/catalog-applications/index.md
pages/dkp/kommander/2.2/release-notes/index.md

Jira: https://jira.d2iq.com/browse/D2IQ-77905
We have the UI steps added here, but NOT yet the CLI steps. We can merge this and continue the CLI work next sprint, if necessary, or we can knock it out today and tomorrow if we have that procedure worked out.
ALSO, I started the new 2.2 release notes with a blurb about this.

Upgrade Catalog Applications with UI and CLI

---

pages/dkp/konvoy/1.6/install/install-azure/index.md
pages/dkp/konvoy/1.7/install/install-azure/index.md
pages/dkp/konvoy/1.8/install/install-azure/index.md

http://docs-d2iq-com-pr-4159.s3-website-us-west-2.amazonaws.com/

changing wording of prerequs to help customers - COPS-7180

---

pages/dkp/kommander/2.2/release-notes/index.md

Very small change, therefore no Jira.
http://docs-d2iq-com-pr-4168.s3-website-us-west-2.amazonaws.com/

Updated menuweight so RNs are displayed first 

---

pages/dkp/konvoy/2.1/choose-infrastructure/pre-provisioned/bootstrap/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/pre-provisioned/create-secrets-and-overrides/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/pre-provisioned/define-infrastructure/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/pre-provisioned/prerequisites/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/bootstrap/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/create-secrets-and-overrides/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/define-infrastructure/index.md

http://docs-d2iq-com-pr-4167.s3-website-us-west-2.amazonaws.com/

[docs]-update-pre-provisioned-commands

---

pages/dkp/kommander/2.2/projects/applications/catalog-applications/index.md

n/a
There was an open `<strong>` bracket - just ending that
http://docs-d2iq-com-pr-4170.s3-website-us-west-2.amazonaws.com/

docs: unclosed html bracket

---

pages/dkp/konvoy/2.1/choose-infrastructure/aws/advanced/prerequisites/index.md

n/a
This got merged in and it's making tests fail :-/
http://docs-d2iq-com-pr-4175.s3-website-us-west-2.amazonaws.com/

docs: fixing broken test

---

README.md

No Jira ticket, but getting ready for a new colleague joining us. I made some proposals based on my own experience, so please add/change anything as necessary.

Improvements on the docs set-up file for new contributors

---

pages/dkp/kommander/2.1/install/networked/index.md

https://jira.d2iq.com/browse/COPS-7173
Please verify/validate note & location, line 18.

[Kommander] COPS-7173 added note

---

pages/dkp/kommander/2.1/security/howto-dex-saml-connector/index.md
pages/dkp/kommander/2.2/security/howto-dex-saml-connector/index.md

Closes  https://jira.d2iq.com/browse/D2IQ-78937 
http://docs-d2iq-com-pr-4164.s3-website-us-west-2.amazonaws.com/

docs: Install -- SAML

---

pages/dkp/kommander/2.1/backup-and-restore/index.md
pages/dkp/kommander/2.2/backup-and-restore/index.md

JIRA: https://jira.d2iq.com/browse/D2IQ-85886
We've found that it is not possible to run Velero backup and restore on the management cluster where the Kommander is installed without seeing some restore errors. This PR describes additional manual steps necessary to provide workaround for these errors.
The engineering PR that exercise these manual steps is https://github.com/mesosphere/kommander/pull/1543

chore: add note about restoring management cluster backup

---

pages/dkp/konvoy/2.1/release-notes/2.1.1/index.md

https://jira.d2iq.com/browse/COPS-7195
Added new Known Issues section and the note to 2.1.1 release notes.

COPS-7195 note

---

pages/dkp/kommander/2.2/install/air-gapped/index.md

Blocked by mesosphere/dkp-cli#98
http://docs-d2iq-com-pr-4169.s3-website-us-west-2.amazonaws.com/

docs: Use new push image-bundle command

---

pages/dkp/konvoy/1.8/storage/static-local-volume/index.md

http://docs-d2iq-com-pr-4173.s3-website-us-west-2.amazonaws.com/

 QA: static-local-volume-update

---

pages/dkp/konvoy/2.1/choose-infrastructure/pre-provisioned/define-control-plane-endpoint/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/define-control-plane-endpoint/index.md

https://jira.d2iq.com/browse/COPS-7172
Added a page-to-page URL link in both 2.1 and 2.2.

COPS-7172 added URL

---

pages/dkp/kommander/2.2/install/configuration/enterprise-catalog/index.md

http://docs-d2iq-com-pr-4184.s3-website-us-west-2.amazonaws.com/
Based on top of https://github.com/mesosphere/dcos-docs-site/pull/4193/files

docs: add docs on enterprise catalog

---

layouts/404.pug
layouts/all-products-landing.pug
layouts/cn-dcos-docs-landing.pug
layouts/dcos-docs-landing.pug
layouts/dispatch-docs-landing.pug
layouts/kaptain-docs-landing.pug
layouts/kommander-docs-landing.pug
layouts/konvoy-docs-landing.pug
layouts/partials/header/header.pug
layouts/search.pug

No JIRA
http://docs-d2iq-com-pr-4208.s3-website-us-west-2.amazonaws.com/

taking out drop downs

---

pages/dkp/kommander/2.2/clusters/creating-konvoy-cluster-aws/index.md

Closes D2IQ-85658
https://jira.d2iq.com/browse/D2IQ-85658
http://docs-d2iq-com-pr-4211.s3-website-us-west-2.amazonaws.com/

docs: Update Create Cluster docs with advanced AWS options

---

pages/dkp/konvoy/2.1/choose-infrastructure/aws/multi-account/index.md

http://docs-d2iq-com-pr-4218.s3-website-us-west-2.amazonaws.com/

adding syntax for formatting

---

pages/dkp/kommander/2.2/dkp-upgrade/index.md

https://jira.d2iq.com/browse/D2IQ-85868
This is the central place for all upgrade-related documentation. For now, we are putting everything under Kommander, but once we have all topics ready, we will have them copied over to Konvoy's doc section as well. 
Some parts were difficult to phrase (specially when referring to single and multi-cluster experiences), so let me know if you can think of better ways to structure/phrase that :). All feedback is appreciated, thank you! 
http://docs-d2iq-com-pr-4204.s3-website-us-west-2.amazonaws.com/

DKP Upgrade overview

---

pages/dkp/kommander/2.2/projects/applications/platform-applications/index.md

https://jira.d2iq.com/browse/D2IQ-86401
Just adding a warning to make sure operators upgrade platform apps before proceeding with Konvoy upgrade.

Warning platform apps

---

pages/dkp/konvoy/2.1/choose-infrastructure/pre-provisioned/create-cluster/index.md

https://jira.d2iq.com/browse/COPS-7230

Add clarification about Virtual-ip uses kube-vip

---

pages/dkp/kommander/2.2/projects/applications/catalog-applications/index.md

This PR introduces a small formatting change to allow commands to be copy/pasted. It also updates the example command to run at the workspace level (since thats where the kakfa operator will be deployed).

docs: Update formatting to allow copy/pasting

---

pages/dkp/konvoy/2.1/choose-infrastructure/aws/multi-account/index.md

No JiRA, abut we have this:
https://docs.google.com/document/d/1WZl_5irXwwaZLmQo5xAj_xSB_9YAV4DVZKZRESdpJ1g/edit#
http://docs-d2iq-com-pr-4217.s3-website-us-west-2.amazonaws.com/

adding Shafiques request

---

pages/dkp/kommander/2.2/dkp-upgrade/upgrade-kommander/index.md
pages/dkp/kommander/2.2/dkp-upgrade/upgrade-konvoy/index.md

https://jira.d2iq.com/browse/D2IQ-85868
Second iteration of the Kommander Upgrade document. This time I added steps on air-gapped environments, fixed some links and added a whole segment on loading images that needs to be done for air-gapped. 
Also added another file, just to have an index.md file for when we are ready to write that part of the documentation. (The whole DKP-upgrade folder will live both in Kommander and Konvoy sections, but doing all the work here for now until we have everything)
http://docs-d2iq-com-pr-4201.s3-website-us-west-2.amazonaws.com/

Kommander Upgrade including air-gapped scenarios

---

pages/dkp/kommander/2.2/release-notes/2.2.0/index.md

https://jira.d2iq.com/browse/D2IQ-87155
This PR will merge into existing RN pr https://github.com/mesosphere/dcos-docs-site/pull/4206
Add workaround steps to override configuration for kube-oidc-proxy  and traefik-forward-auth.
http://docs-d2iq-com-pr-4239.s3-website-us-west-2.amazonaws.com/

[2.2.0 RN] Add workaround to configure KOP/TFA

---

pages/dkp/kommander/2.2/reference/kommander/v1beta1/index.md

https://jira.d2iq.com/browse/D2IQ-85326
This updates API docs for Kommander 2.2. See https://github.com/mesosphere/kommander/tree/main/api-docs#api-docs.

Update API docs for Kommander 2.2

---

pages/dkp/kommander/2.2/dkp-upgrade/index.md

Just fixing a link
http://docs-d2iq-com-pr-4256.s3-website-us-west-2.amazonaws.com/

Just fixing a link

---

pages/dkp/konvoy/2.2/choose-infrastructure/aws/advanced/prerequisites/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aws/quick-start-aws/index.md

fix: updated default name for machine

---

pages/dkp/konvoy/2.2/choose-infrastructure/aws/advanced/prerequisites/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aws/quick-start-aws/index.md

n/a
I meant to get this in before @clintonmedbery merged -but I saw it AND I CAN'T LET IT GO:
https://github.com/mesosphere/dcos-docs-site/pull/4257

docs: an ubuntu vs a ubunut

---

pages/dkp/konvoy/2.2/choose-infrastructure/aks/aks-advanced/index.md

https://jira.d2iq.com/browse/COPS-7231
Added Self-managed page to Advanced section of AKS since was missing.
http://docs-d2iq-com-pr-4254.s3-website-us-west-2.amazonaws.com/

COPS7231 Added Self-Managed

---

pages/dkp/konvoy/2.2/choose-infrastructure/eks/advanced/new/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/eks/quick-start/index.md

[QA] fixed Create the cluster command

---

pages/dkp/kommander/2.2/projects/project-quotas-limit-range/index.md
pages/dkp/kommander/2.2/projects/project-secrets/index.md

- Project Quotas & Limit Ranges
- Project Secrets
http://docs-d2iq-com-pr-4240.s3-website-us-west-2.amazonaws.com/dkp/kommander/2.2/projects/project-secrets/
http://docs-d2iq-com-pr-4240.s3-website-us-west-2.amazonaws.com/dkp/kommander/2.2/projects/project-quotas-limit-range/

docs: screenshot and copy updates - projects

---

pages/dkp/kommander/2.2/licensing/essential/index.md

No JIRA, chaff needing to be cut per @cneth 

[DKP 2.2] Licensing deletions

---

pages/dkp/konvoy/2.2/choose-infrastructure/destroy-with-one-command/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/eks/quick-start/index.md

n/a
Fixing a spelling mistake found by the vp of eng
http://docs-d2iq-com-pr-4268.s3-website-us-west-2.amazonaws.com/

docs: fixing some spelling mistakes

---

pages/dkp/konvoy/2.1/storage/static-local-volume/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/upgrade/control-plane/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/upgrade/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/upgrade/node-pool/index.md
pages/dkp/konvoy/2.2/storage/static-local-volume/index.md

http://docs-d2iq-com-pr-4265.s3-website-us-west-2.amazonaws.com/

QA updated pre-provisioned/upgrade section

---

pages/dkp/kommander/2.2/insights/index.md
pages/dkp/kommander/2.2/insights/insights-setup/index.md
pages/dkp/kommander/2.2/insights/insights-view/index.md

Insight Docs Tweaks

---

.github/styles/Microsoft/Avoid.yml
.github/styles/Microsoft/Quotes.yml
.github/styles/Vocab/Docs/accept.txt
.github/styles/ttd-light/Quotes.yml
pages/dkp/kommander/2.2/projects/applications/catalog-applications/custom-applications/deploy-custom-app/index.md
pages/dkp/kommander/2.2/projects/applications/catalog-applications/index.md
pages/dkp/kommander/2.2/projects/applications/platform-applications/index.md
pages/dkp/kommander/2.2/projects/project-configmaps/index.md
pages/dkp/kommander/2.2/projects/project-deployments/continuous-delivery/index.md
pages/dkp/kommander/2.2/projects/project-deployments/view-helm-releases/index.md
pages/dkp/kommander/2.2/projects/project-network-policies/index.md

https://jira.d2iq.com/browse/D2IQ-86815
These are just some things I noticed when reading through the Project docs, which I wanted to suggest changes for. However, I'm happy to revert anything that isn't quite working, or include any additional changes.
http://docs-d2iq-com-pr-4261.s3-website-us-west-2.amazonaws.com/

docs: suggestions for updates - projects

---

pages/dkp/kommander/2.2/install/configuration/enterprise-catalog/index.md

[kommander]  init command

---

pages/dkp/konvoy/2.1/choose-infrastructure/azure/advanced/bootstrap/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/azure/advanced/bootstrap/index.md

https://jira.d2iq.com/browse/COPS-7235

Add identity secret cretimg for bootstrap clusters running inside Azure

---

pages/dkp/kommander/2.2/workspaces/applications/platform-applications/platform-application-requirements/index.md

https://jira.d2iq.com/browse/D2IQ-85916
We need to review & update the Platform Apps table.
The original PR had a problem, so starting a new clean PR with the updates from @cbuto.

[Kommander] Update platform app requirements table

---

pages/dkp/kommander/2.2/logging/disable-audit-logs/index.md
pages/dkp/kommander/2.2/logging/enable-logging/restrict-logging/index.md
pages/dkp/kommander/2.2/logging/multi-tenant-logging/create-appdeployment/index.md
pages/dkp/kommander/2.2/monitoring/index.md
pages/dkp/kommander/2.2/projects/applications/platform-applications/application-deployment/index.md
pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/application-deployment/index.md
pages/dkp/kommander/2.2/workspaces/applications/platform-applications/application-deployment/index.md

Update some appdeployment example versions

docs: Update appdeployment examples with new versions

---

pages/dkp/kommander/2.2/release-notes/2.2.0/index.md
pages/dkp/kommander/2.2/release-notes/index.md
pages/dkp/konvoy/2.2/release-notes/index.md

Jira: https://jira.d2iq.com/browse/D2IQ-85318
First draft. Please see New Features and Capabilities items and ensure we're highlighting everything that we want to mention here for 2.2.
NOTE!!!
While we are going to publish the RN for both Konvoy and Kommander, we are going to copy this RN exactly and publish to both product documentation sets.

Combined DKP 2.2 release notes draft 2

---

pages/dkp/kommander/2.2/install/mgmt-cluster-apps/index.md

Jira: https://jira.d2iq.com/browse/D2IQ-85917
Copied table from https://docs.d2iq.com/dkp/kommander/2.1/workspaces/applications/platform-applications/platform-application-requirements/#workspace-platform-application-requirements and changed the intro.
The idea here is to list ONLY Management Cluster apps, NOT all apps. Please review the list & add/update as necessary.

[Kommander] Management cluster app requirements

---

pages/dkp/kommander/2.2/insights/insights-setup/index.md

This is to provide more clarity on the steps to enable the Insights engine from the UI. 

updates for enable dkp insights engine steps

---

pages/dkp/kommander/2.2/dkp-upgrade/index.md
pages/dkp/konvoy/2.2/dkp-upgrade/index.md

Jira: https://jira.d2iq.com/browse/D2IQ-87271
Please validate the 2.1 to 2.2 upgrade paths! Once we have the table set, then we will duplicate this to the same pages in Kommander.
http://docs-d2iq-com-pr-4284.s3-website-us-west-2.amazonaws.com/

[DKP] Added Upgrade paths table

---

pages/dkp/konvoy/2.2/supported-operating-systems/index.md

chore: Updated Docs with 2.2 OS Qual Testing

---

pages/dkp/kommander/2.2/dkp-upgrade/upgrade-kommander/index.md

It was deleted in #4279 supposedly by accident.

re-add deleted line

---

pages/dkp/kommander/2.2/download/index.md
pages/dkp/konvoy/2.2/download/index.md

http://docs-d2iq-com-pr-4297.s3-website-us-west-2.amazonaws.com/

changing download instructions

---

pages/dkp/kommander/2.2/release-notes/2.2.0/index.md
pages/dkp/konvoy/2.2/release-notes/index.md

Updating release date to 4/8, plus any other changes we need today.

[DKP 2.2] Updated Release Notes for date & misc

---

pages/dkp/kaptain/2.0.0/download/index.md

Kaptain 2.0.0 Docs download folder

---

pages/dkp/kaptain/2.0.0/introducing/index.md

Kaptain 2.0.0 Docs introducing folder

---

pages/dkp/kaptain/2.0.0/version-policy/index.md

version-policy folder for #4309

Kaptain 2.0.0 Docs version-policy folder

---

pages/dkp/kaptain/2.0.0/support/index.md

Kaptain 2.0.0 Docs support folder

---

pages/dkp/kaptain/2.0.0/operations/index.md
pages/dkp/kaptain/2.0.0/operations/minio/index.md
pages/dkp/kaptain/2.0.0/operations/mysql-cluster/index.md

Kaptain 2.0.0 Docs operations folder

---

pages/dkp/kaptain/2.0.0/upgrade/index.md

Kaptain 2.0.0 Docs upgrade folder

---

pages/dkp/kaptain/2.0.0/install/konvoy-dkp/index.md

https://jira.d2iq.com/browse/D2IQ-75579
Reworking Install topics. Started by updating the prerequisites section and added a warning 

Updating install topic non air-gapped part 1: prereq section and warning

---

pages/dkp/kommander/2.2/dkp-upgrade/upgrade-kommander/index.md

chore: removed duplicated output line

---

.github/styles/Vocab/Docs/accept.txt

With Kaptain Docs there are plenty of new terms we have to add to accept.txt

Kaptain 2.0.0 Docs - Add Kaptain specific accepted terms

---

pages/dkp/kommander/2.2/release-notes/2.2.0/index.md
pages/dkp/konvoy/2.2/release-notes/index.md

https://jira.d2iq.com/browse/D2IQ-86410
Updated the app / component version chart in RN. Do we need to link every app to the origin? We can do that in follow up

doce: Update RN component chart with app versions

---

pages/dkp/kaptain/2.0.0/user-management/index.md

Kaptain 2.0.0 Docs user-management folder

---

pages/dkp/kaptain/2.0.0/secrets-management/index.md

Kaptain 2.0.0 Docs secrets-management folder

---

pages/dkp/kaptain/2.0.0/release-notes/1.3.0/index.md
pages/dkp/kaptain/2.0.0/release-notes/index.md

Kaptain 2.0.0 Docs release-notes folder

---

pages/dkp/kaptain/2.0.0/legal-notices/index.md
pages/dkp/kaptain/2.0.0/legal-notices/open-source-attribution/index.md

Kaptain 2.0.0 Docs legal-notices folder

---

pages/dkp/kaptain/2.0.0/troubleshooting/index.md

Kaptain 2.0.0 Docs troubleshooting folder

---

pages/dkp/kaptain/2.0.0/install/air-gapped-dkp/index.md
pages/dkp/kaptain/2.0.0/install/air-gapped-konvoy/index.md
pages/dkp/kaptain/2.0.0/install/index.md
pages/dkp/kaptain/2.0.0/install/konvoy-dkp/index.md
pages/dkp/kaptain/2.0.0/install/on-premise/index.md

Kaptain 2.0.0 Docs install folder

---

pages/dkp/kommander/2.1/install/networked/index.md
pages/dkp/kommander/2.2/dkp-upgrade/upgrade-kommander/index.md
pages/dkp/kommander/2.2/install/networked/index.md

https://jira.d2iq.com/browse/D2IQ-85660
Add command on how to force HR reconciliation in case it is "stuck" in a failed state 

docs: Add section on how to force reconcile HRs

---

pages/dkp/konvoy/2.2/choose-infrastructure/aks/aks-advanced/aa-bootstrap/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aks/aks-advanced/aa-delete/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aks/aks-advanced/aa-explore/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aks/aks-advanced/aa-new/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aks/aks-advanced/aa-replace-node/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aks/aks-quickstart/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aws/advanced/bootstrap/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aws/advanced/delete/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aws/advanced/explore/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aws/advanced/new/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aws/advanced/replace-node/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aws/advanced/self-managed/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aws/quick-start-aws/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/azure/advanced/bootstrap/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/azure/advanced/delete/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/azure/advanced/explore/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/azure/advanced/new/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/azure/advanced/replace-node/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/azure/advanced/self-managed/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/azure/quick-start-azure/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/eks/advanced/bootstrap/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/eks/advanced/delete/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/eks/advanced/explore/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/eks/advanced/new/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/eks/advanced/replace-node/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/eks/quick-start/index.md

http://docs-d2iq-com-pr-4341.s3-website-us-west-2.amazonaws.com/

[QA] fixing outputs

---

pages/dkp/kaptain/2.0.0/sdk/1.0.x/api/index.md

update kaptain generated docs

---

pages/dkp/kommander/2.2/insights/index.md
pages/dkp/kommander/2.2/legal/version-policy/index.md

https://jira.d2iq.com/browse/D2IQ-87587
Added Technical Preview information.
http://docs-d2iq-com-pr-4332.s3-website-us-west-2.amazonaws.com/

[Insights] Added the Tech preview information

---

pages/dkp/konvoy/2.2/choose-infrastructure/destroy-with-one-command/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/create-cluster/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/create-secrets-and-overrides/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/define-infrastructure/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/delete-cluster/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/self-managed/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/verify-installation/index.md

http://docs-d2iq-com-pr-4344.s3-website-us-west-2.amazonaws.com/

QA updated pre-provisioned pages

---

pages/dkp/kaptain/2.0.0/install/index.md

https://jira.d2iq.com/browse/D2IQ-86797
- Making sure support of Managed and Attached clusters is transparent to customers.
- Changed structure a bit to match existing docs
http://docs-d2iq-com-pr-4340.s3-website-us-west-2.amazonaws.com/

[Kaptain]: Managed and Attached clusters support

---

pages/dkp/kommander/2.2/insights/index.md

Quick URL fix

---

pages/dkp/kommander/2.1/major-upgrade/upgrade-clusters/migrate-platform-apps/index.md
pages/dkp/kommander/2.1/workspaces/applications/platform-applications/platform-application-requirements/index.md
pages/dkp/kommander/2.2/install/mgmt-cluster-apps/index.md
pages/dkp/kommander/2.2/workspaces/applications/platform-applications/platform-application-requirements/index.md

https://jira.d2iq.com/browse/D2IQ-85915
- Add table of mgmt cluster apps to 2.1 migration docs under prereqs
- Update platform apps tables
- Fix a table alignment issue
http://docs-d2iq-com-pr-4342.s3-website-us-west-2.amazonaws.com/

[kommander] Add and update mgmt/platform app tables

---

pages/dkp/kommander/2.2/insights/insights-licensing/index.md

Update Insight to Insights 

---

pages/dkp/konvoy/2.2/choose-infrastructure/aws/nodepools/create/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aws/nodepools/delete/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aws/nodepools/list/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aws/nodepools/scale/index.md

http://docs-d2iq-com-pr-4356.s3-website-us-west-2.amazonaws.com/

QA fixed nodepools pages

---

pages/dkp/kaptain/2.0.0/configuration/external-dex/index.md

[Kaptain JIRA](https://jira.d2iq.com/browse/D2IQ-86129)
[Docs Jira](https://jira.d2iq.com/browse/D2IQ-86797)
- Update Commands for Dex Client Creation 
http://docs-d2iq-com-pr-4345.s3-website-us-west-2.amazonaws.com/

[Kaptain] Update Commands for Dex Client Creation

---

pages/dkp/kaptain/2.0.0/install/index.md

Just fixing links to topics that now exist.
http://docs-d2iq-com-pr-4363.s3-website-us-west-2.amazonaws.com/

[Kaptain] Fixing install links

---

pages/dkp/konvoy/2.2/supported-operating-systems/index.md

Updating flatcar to be more generic with all patchy patches
http://docs-d2iq-com-pr-4364.s3-website-us-west-2.amazonaws.com/

docs: updating flatcar

---

pages/dkp/kaptain/2.0.0/install/deploy-kaptain/index.md
pages/dkp/kaptain/2.0.0/install/dkp/index.md
pages/dkp/kaptain/2.0.0/install/index.md

Fixing last details 
http://docs-d2iq-com-pr-4368.s3-website-us-west-2.amazonaws.com/

[Kaptain] Fixed links & fine-tuning

---

layouts/kaptain-docs-landing.pug
pages/dkp/kaptain/1.2.0/index.md
pages/dkp/kaptain/1.3.0/index.md
pages/dkp/kaptain/2.0.0/index.md
pages/dkp/kaptain/index.md

http://docs-d2iq-com-pr-4373.s3-website-us-west-2.amazonaws.com/

[Kaptain] fixed dropdown menu order

---

pages/dkp/kaptain/2.0.0/operations/minio/index.md
pages/dkp/kaptain/2.0.0/operations/mysql-cluster/index.md

https://jira.d2iq.com/browse/D2IQ-87581
http://docs-d2iq-com-pr-4369.s3-website-us-west-2.amazonaws.com/

Update operations docs

---

pages/dkp/kaptain/2.0.0/sdk/compatibility/index.md

Sorry, was too quick and merged without seeing Alex's comment. Addressed them in this PR. 

REDO: addressing Alex's comment

---

pages/dkp/konvoy/2.1/choose-infrastructure/aws/air-gapped/new/index.md
pages/dkp/konvoy/2.1/image-builder/override-files/create-custom-or-files/container-image-or-files/index.md

https://jira.d2iq.com/browse/COPS-7201
Removed invalid hyperlink.

Removes invalid hyperlink.

---

pages/dkp/kommander/2.2/projects/applications/platform-applications/index.md

http://docs-d2iq-com-pr-4387.s3-website-us-west-2.amazonaws.com/

updating URL link that's broken

---

pages/dkp/kaptain/2.0.0/sdk/1.0.x/credentials/index.md
pages/dkp/kaptain/2.0.0/sdk/1.0.x/troubleshooting/index.md
pages/dkp/kaptain/2.0.0/tutorials/sdk/pytorch/index.md
pages/dkp/kaptain/2.0.0/tutorials/sdk/quick-start/index.md
pages/dkp/kaptain/2.0.0/tutorials/sdk/tensorflow/index.md
pages/dkp/kaptain/2.0.0/tutorials/training/tensorflow/index.md

http://docs-d2iq-com-pr-4394.s3-website-us-west-2.amazonaws.com/

[Kaptain] - fixed notes

---

pages/dkp/kaptain/1.2.0/operations/mysql-cluster/index.md
pages/dkp/kaptain/1.3.0/operations/mysql-cluster/index.md
pages/dkp/kaptain/2.0.0/operations/mysql-cluster/index.md

Just small suggestions to help others avoid making similar mistakes that I made

Make instructions for mysql backup a bit more foolproof

---

pages/dkp/kaptain/2.0.0/index.md

http://docs-d2iq-com-pr-4405.s3-website-us-west-2.amazonaws.com/

[docs] remove outdated kaptain diagram

---

pages/dkp/kommander/2.1/networking/use-ingress-load-balancer/index.md
pages/dkp/kommander/2.2/networking/use-ingress-load-balancer/index.md

https://jira.d2iq.com/browse/COPS-7223
Fix ingress example as suggested by Casey in 
https://mesosphere.slack.com/archives/C01LNF6KML5/p1649278588425029
http://docs-d2iq-com-pr-4397.s3-website-us-west-2.amazonaws.com/

docs: Fix ingress example

---

pages/dkp/kommander/2.2/clusters/attach-cluster/requirements-for-attaching/index.md
pages/dkp/kommander/2.2/install/air-gapped/index.md
pages/dkp/kommander/2.2/install/configuration/index.md
pages/dkp/kommander/2.2/install/networked/index.md

Add some notes to the kommander install docs to review the mgmt cluster and workspace app requirements to ensure cluster has sufficient resources prior to installing kommander.
http://docs-d2iq-com-pr-4400.s3-website-us-west-2.amazonaws.com/

[kommander] docs: Add line to review app requirements on install/config pages

---

.github/styles/Vocab/Docs/accept.txt
pages/dkp/kommander/2.0/workspaces/workspace-platform-services/index.md
pages/dkp/kommander/2.1/workspaces/applications/platform-applications/index.md
pages/dkp/kommander/2.2/install/mgmt-cluster-apps/index.md
pages/dkp/kommander/2.2/release-notes/2.2.0/index.md
pages/dkp/kommander/2.2/workspaces/applications/platform-applications/index.md
pages/dkp/konvoy/2.2/release-notes/index.md

https://jira.d2iq.com/browse/COPS-7149
http://docs-d2iq-com-pr-4390.s3-website-us-west-2.amazonaws.com/

adding common name to tables

---

pages/dkp/kaptain/2.0.0/release-notes/index.md

[kaptain] update release notes version in title

---

pages/dkp/kaptain/2.0.0/download/index.md
pages/dkp/kaptain/2.0.0/fresh-install/index.md
pages/dkp/kaptain/2.0.0/install/air-gapped-2.1/index.md
pages/dkp/kaptain/2.0.0/install/air-gapped-2.2/index.md
pages/dkp/kaptain/2.0.0/install/deploy-kaptain/index.md
pages/dkp/kaptain/2.0.0/install/dkp/index.md
pages/dkp/kaptain/2.0.0/install/index.md

No Jira, just cleaning up
Adding references, fixing links and getting rid of a few typos.
http://docs-d2iq-com-pr-4411.s3-website-us-west-2.amazonaws.com/

[Kaptain] Fixing references, links and typos

---

pages/dkp/konvoy/2.1/choose-infrastructure/pre-provisioned/prerequisites-airgapped/index.md

No ticket, hotfix
Fix so that pre-prov steps are in sync with AWS steps for registry seeding.

[Konvoy] Hotfix add->replace scripting/steps for registry seeding

---

pages/dkp/kaptain/1.2.0-1.0.0/index.md
pages/dkp/kaptain/1.2.0-1.1.0/index.md
pages/dkp/kaptain/1.2.0/index.md
pages/dkp/kaptain/1.3.0/index.md
pages/dkp/kaptain/2.0.0/index.md
pages/dkp/kommander/1.2/index.md
pages/dkp/kommander/1.3/index.md
pages/dkp/kommander/1.4/index.md
pages/dkp/kommander/2.0/index.md
pages/dkp/kommander/2.1/index.md
pages/dkp/kommander/2.2/index.md
pages/dkp/konvoy/1.6/index.md
pages/dkp/konvoy/1.7/index.md
pages/dkp/konvoy/1.8/index.md
pages/dkp/konvoy/2.0/index.md
pages/dkp/konvoy/2.1/index.md
pages/dkp/konvoy/2.2/index.md

No Jira, fixing this:
http://docs-d2iq-com-pr-4412.s3-website-us-west-2.amazonaws.com/

[Kaptain] Fixing all menu weights to show latest to oldest

---

pages/dkp/konvoy/2.0/choose_infrastructure/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/index.md

https://jira.d2iq.com/browse/D2IQ-78963
Added a note in 2.x Choose Infrastructure documentation mentioning that uninstall steps are listed per environment.

[Konvoy 2.x] Uninstall Note

---

pages/dkp/kommander/2.2/dkp-upgrade/upgrade-konvoy/enterprise/index.md
pages/dkp/kommander/2.2/dkp-upgrade/upgrade-konvoy/essential/index.md
pages/dkp/konvoy/2.2/dkp-upgrade/upgrade-konvoy/enterprise/index.md
pages/dkp/konvoy/2.2/dkp-upgrade/upgrade-konvoy/essential/index.md

https://jira.d2iq.com/browse/D2IQ-87530
Adding examples of other Infrastructure Providers besides AWS on our upgrade pages.  Equal touting : )
http://docs-d2iq-com-pr-4429.s3-website-us-west-2.amazonaws.com/

JIRS87530 Other InfraStr Examples

---

pages/dkp/kaptain/2.0.0/sdk/1.0.x/release-notes/index.md

Update sdk release notes to reflect 1.0.1 changes

---

pages/dkp/konvoy/2.2/Install/index.md

No ticket
broken Homebrew link fixed
http://docs-d2iq-com-pr-4439.s3-website-us-west-2.amazonaws.com/

add broken Homebrew link

---

.github/styles/Vocab/Docs/accept.txt
pages/dkp/kommander/2.1/install/configuration/index.md
pages/dkp/kommander/2.1/install/small-environment/index.md
pages/dkp/kommander/2.2/install/configuration/index.md
pages/dkp/kommander/2.2/install/small-environment/index.md
pages/dkp/kommander/2.3/install/configuration/index.md
pages/dkp/kommander/2.3/install/small-environment/index.md

https://jira.d2iq.com/browse/D2IQ-86138?filter=-1
https://jira.d2iq.com/browse/COPS-7174
We require a new topic on how to install Kommander on a small environment for testing/demo purposes for 2.1 and 2.2.
http://docs-d2iq-com-pr-4432.s3-website-us-west-2.amazonaws.com/

[Komm] Adding a topic on minimal installation for bug and cops

---

pages/dkp/konvoy/2.2/supported-operating-systems/index.md
pages/dkp/konvoy/2.3/supported-operating-systems/index.md

In Supported Operating Systems, Changed SLES 15 to SP3 link
http://docs-d2iq-com-pr-4441.s3-website-us-west-2.amazonaws.com/

Changed SLES 15 to SP3 link

---

pages/dkp/kaptain/2.0.0/release-notes/2.0.0/index.md

EKS -> AKS typo

---

pages/dkp/konvoy/2.3/supported-operating-systems/index.md

"front" port of this - #4449 
http://docs-d2iq-com-pr-4451.s3-website-us-west-2.amazonaws.com/

adding the changes from 2.2 into 2.3 as well.

---

pages/dkp/kommander/2.3/projects/applications/catalog-applications/custom-applications/application-metadata/index.md
pages/dkp/kommander/2.3/workspaces/applications/catalog-applications/custom-applications/application-metadata/index.md

https://jira.d2iq.com/browse/D2IQ-88102
I've added the `allowMultipleInstaces` key to the catalog app definition tables.
http://docs-d2iq-com-pr-4454.s3-website-us-west-2.amazonaws.com/

D2IQ-88102: add `allowMultipleInstaces` key to catalog applications

---

pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/dkp-applications/index.md
pages/dkp/kommander/2.3/workspaces/applications/catalog-applications/dkp-applications/index.md

https://jira.d2iq.com/browse/D2IQ-89372
Added a column on the supported Kubernetes versions. Also added other supported DKP catalog app versions.
http://docs-d2iq-com-pr-4460.s3-website-us-west-2.amazonaws.com/

[DKP] Added supported Kubernetes versions to DKP apps table

---

.github/styles/Vocab/Docs/accept.txt
pages/dkp/kommander/2.2/download/index.md
pages/dkp/kommander/2.2/install/air-gapped/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aws/air-gapped/create-an-ami/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aws/air-gapped/seed-a-registry/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/prerequisites-airgapped/index.md
pages/dkp/konvoy/2.2/download/index.md

Urgent ask from legal and Tobi
http://docs-d2iq-com-pr-4453.s3-website-us-west-2.amazonaws.com/

Add minio attributions to newest versions of Konvoy, Kommander, and Kaptain

---

pages/dkp/kommander/1.4/install-airgapped/index.md
pages/dkp/konvoy/1.8/addons/requirements/index.md
pages/dkp/konvoy/1.8/install/install-onprem/index.md
pages/dkp/konvoy/1.8/install/tips-tricks/check-components/index.md
pages/dkp/konvoy/1.8/install/tips-tricks/ssh-connection-issues/index.md
pages/dkp/konvoy/1.8/networking/required-domains/index.md
pages/dkp/konvoy/1.8/networking/tips-tricks/ssh-connection-issues/index.md
pages/dkp/konvoy/1.8/operations/replace-a-failed-node/index.md
pages/dkp/konvoy/1.8/operations/replace-failed-control-plane-node/index.md
pages/dkp/konvoy/1.8/operations/update-worker-machines/index.md
pages/dkp/konvoy/1.8/troubleshooting/replace-a-failed-node/index.md
pages/dkp/konvoy/1.8/troubleshooting/replace-failed-control-plane-node/index.md
pages/dkp/konvoy/1.8/upgrade/tips-tricks/check-components/index.md
pages/dkp/konvoy/1.8/upgrade/update-worker-machines/index.md

fix: update include references to 1.8

---

pages/dkp/konvoy/2.2/choose-infrastructure/aks/aks-advanced/aa-bootstrap/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aws/advanced/bootstrap/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/azure/advanced/bootstrap/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/eks/advanced/bootstrap/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/air-gapped/bootstrap/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/bootstrap/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/delete/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/aks/aks-advanced/aa-bootstrap/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/aws/advanced/bootstrap/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/azure/advanced/bootstrap/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/eks/advanced/bootstrap/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/vsphere/air-gapped/bootstrap/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/vsphere/bootstrap/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/vsphere/delete/index.md

https://jira.d2iq.com/browse/COPS-7261
Removing sample output and text about `ClusterResourceSets`. `ClusterResourceSets` is an implementation detail of how these addons are installed.

konvoy: remove outdated info about CRS

---

pages/dkp/kommander/2.2/insights/index.md
pages/dkp/kommander/2.2/insights/insights-setup/index.md
pages/dkp/kommander/2.3/insights/index.md
pages/dkp/kommander/2.3/insights/insights-setup/index.md

http://docs-d2iq-com-pr-4463.s3-website-us-west-2.amazonaws.com/

fix: Add instructions on how to disable Insights Management Component.

---

pages/dkp/kaptain/1.2.0/download/index.md
pages/dkp/kaptain/1.3.0/download/index.md
pages/dkp/kaptain/2.0.0/download/index.md
pages/dkp/kommander/2.1/download/index.md
pages/dkp/kommander/2.1/install/air-gapped/catalog/index.md
pages/dkp/kommander/2.1/install/air-gapped/index.md
pages/dkp/kommander/2.2/dkp-upgrade/upgrade-kommander/index.md
pages/dkp/kommander/2.2/download/index.md
pages/dkp/kommander/2.2/install/air-gapped/catalog/index.md
pages/dkp/kommander/2.2/install/air-gapped/index.md
pages/dkp/kommander/2.2/install/configuration/enterprise-catalog/index.md
pages/dkp/konvoy/1.8/download/index.md
pages/dkp/konvoy/1.8/install/install-gcp/advanced-provisioning/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/aws/air-gapped/create-an-ami/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/aws/air-gapped/seed-a-registry/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/pre-provisioned/prerequisites-airgapped/index.md
pages/dkp/konvoy/2.1/download/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aws/air-gapped/create-an-ami/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aws/air-gapped/seed-a-registry/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/prerequisites-airgapped/index.md
pages/dkp/konvoy/2.2/download/index.md

http://docs-d2iq-com-pr-4470.s3-website-us-west-2.amazonaws.com/

Added MinIO attributions for all download links

---

pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/new/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/vsphere/new/index.md

Updated the ssh flag to reflect the correct flag reference

Updated ssh flag

---

pages/dkp/konvoy/2.3/Install/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/aks/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/eks/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/gcp/advanced/bootstrap/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/gcp/advanced/delete/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/gcp/advanced/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/gcp/advanced/new/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/gcp/advanced/prerequisites/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/gcp/advanced/self-managed/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/gcp/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/gcp/quick-start-gcp/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/index.md
pages/dkp/konvoy/2.3/dkp-upgrade/upgrade-konvoy/enterprise/index.md
pages/dkp/konvoy/2.3/dkp-upgrade/upgrade-konvoy/essential/index.md
pages/dkp/konvoy/2.3/release-notes/2.3.0/index.md

https://jira.d2iq.com/browse/D2IQ-87530
PHASE 1 STRUCTURE and BASIC CONTENT ready to create/merge. Additions to come as code is written.
Total work in progress that will take some time.... overhaul changing Choose Infrastructure section to Infrastructure Provider. Also adding GCP section to Providers. Also changing Install page to "Getting started." Changing wording around "infrastructure" in paragraphs to include "provider" sometimes using both words depending on which infrastructure provider or setup it being documented
http://docs-d2iq-com-pr-4477.s3-website-us-west-2.amazonaws.com/
See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more …

Added GCP Structure

---

pages/dkp/kaptain/1.2.0/archive/index.md
pages/dkp/kaptain/1.3.0/archive/index.md
pages/dkp/kaptain/2.0.0/archive/index.md
pages/dkp/kaptain/2.1.0/archive/index.md

http://docs-d2iq-com-pr-4480.s3-website-us-west-2.amazonaws.com/

Archiving Kaptain Docs 

---

pages/dkp/kaptain/1.3.0/install/air-gapped-dkp/index.md
pages/dkp/kaptain/2.0.0/install/air-gapped-2.1/index.md
pages/dkp/kaptain/2.0.0/install/air-gapped-2.2/index.md

No ticket, discussed this with @lukeogg via slack. 
The `tar` command was not working properly, so we had to change it is able to untar properly. 
http://docs-d2iq-com-pr-4494.s3-website-us-west-2.amazonaws.com/

[Kaptain/MinIO]: updating commands

---

pages/dkp/kommander/2.2/install/small-environment/index.md
pages/dkp/kommander/2.3/install/small-environment/index.md

No Jira, this came up in the Kap sync. 
Fixing the yaml

[Kommander] fixing yaml

---

pages/dkp/konvoy/2.3/choose-infrastructure/gcp/advanced/explore/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/gcp/advanced/new/index.md

https://jira.d2iq.com/browse/D2IQ-88884
Doc ticket https://jira.d2iq.com/browse/D2IQ-90120
Add functionality to update bootstrap credentials (similar to aws and azure)
`dkp update bootstrap credentials gcp`
http://docs-d2iq-com-pr-4497.s3-website-us-west-2.amazonaws.com/

Adding Update Bootstrap Command for GCP

---

pages/dkp/kaptain/2.0.0/user-management/index.md
pages/dkp/kaptain/2.1.0/user-management/index.md

Update the yaml snippet with complete parameter configuration
http://docs-d2iq-com-pr-4500.s3-website-us-west-2.amazonaws.com/

Fix "registrationFlow" parameter

---

pages/dkp/konvoy/2.2/dkp-upgrade/upgrade-konvoy/enterprise/index.md
pages/dkp/konvoy/2.2/dkp-upgrade/upgrade-konvoy/essential/index.md

No Jira, @jimmidyson discovered this and raised it in slack: https://mesosphere.slack.com/archives/C01MPKVBB5E/p1653480727899819
Adding Konvoy Essential and Enterprise files back, as it seems we missed/accidentally deleted them. 
Say "objection" very loudly if deleting this files was on purpose 🤣.
http://docs-d2iq-com-pr-4499.s3-website-us-west-2.amazonaws.com/

[Konvoy] adding missing files to upgrade docs]

---

pages/dkp/konvoy/2.1/choose-infrastructure/aws/advanced/certificate_renewal/index.md
pages/dkp/konvoy/2.1/choose-infrastructure/azure/advanced/certificate_renewal/index.md

https://jira.d2iq.com/browse/COPS-7297

certificate_renewal doc correction

---

pages/dkp/kommander/2.2/release-notes/2.2.1/index.md
pages/dkp/konvoy/2.2/release-notes/2.2.0/index.md
pages/dkp/konvoy/2.2/release-notes/2.2.1/index.md

https://jira.d2iq.com/browse/D2IQ-88896
For this issue: https://jira.d2iq.com/browse/COPS-7275
We ARE NOT adding this as a COPS fix, only adding Containerd to the Component Updates table.
**REMINDER!!** For 2.2 versions, we're doing a combined Release Notes with the same file posted to both Kommander and Konvoy. To alleviate confusion of working in duplicate pages, we'll work on this one page and then duplicate it before merging. 
http://docs-d2iq-com-pr-4475.s3-website-us-west-2.amazonaws.com/

2.2.1 Release Notes Draft

---

pages/dkp/konvoy/2.1/release-notes/2.1.2/index.md

https://jira.d2iq.com/browse/D2IQ-87724
Konvoy 2.1.2 Release Notes

[Konvoy 2.1.2] Release Notes

---

pages/dkp/konvoy/2.1/release-notes/2.1.2/index.md

No ticket.
Minor bump to title.

Rel note title update

---

pages/dkp/konvoy/2.3/dkp-upgrade/upgrade-konvoy/enterprise/index.md
pages/dkp/konvoy/2.3/dkp-upgrade/upgrade-konvoy/essential/index.md

(https://jira.d2iq.com/browse/D2IQ-89920?filter=-1
https://jira.d2iq.com/browse/D2IQ-88470?filter=-1)
Did Commit on two formatting suggestions in previous PR and for some reason they didn't work.  So redoing the formatting on those two sections from PR https://github.com/mesosphere/dcos-docs-site/pull/4508
http://docs-d2iq-com-pr-4518.s3-website-us-west-2.amazonaws.com/

Fix code snippet formatting from previous PR

---

pages/dkp/konvoy/2.2/troubleshooting/generate-a-support-bundle/index.md

https://jira.d2iq.com/browse/COPS-7257
http://docs-d2iq-com-pr-4520.s3-website-us-west-2.amazonaws.com/

updating cli command dkp diagnose 

---

pages/dkp/konvoy/2.1/choose-infrastructure/pre-provisioned/create-secrets-and-overrides/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/create-secrets-and-overrides/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/pre-provisioned/create-secrets-and-overrides/index.md

https://jira.d2iq.com/browse/COPS-7244
http://docs-d2iq-com-pr-4524.s3-website-us-west-2.amazonaws.com/

updating yaml name in file

---

pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/prerequisites/permissions/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/vsphere/prerequisites/permissions/index.md

https://jira.d2iq.com/browse/D2IQ-88866
Customer needs minimum required roles for provisioning vSphere nodes and installing Konvoy. Added per JIRA request.

Adding minimal permissions role for vSphere

---

pages/dkp/konvoy/2.1/choose-infrastructure/azure/quick-start-azure/index.md

https://jira.d2iq.com/browse/COPS-7216 

updating quotes 2

---

pages/dkp/kommander/2.2/release-notes/2.2.1/index.md

https://jira.d2iq.com/browse/D2IQ-90212
Release Notes for DKP Insights released with DKP 2.2.1
http://docs-d2iq-com-pr-4535.s3-website-us-west-2.amazonaws.com/

Insights DKP 2.2.1 Release Notes.

---

pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/prerequisites/permissions/index.md
pages/dkp/konvoy/2.3/choose-infrastructure/vsphere/prerequisites/permissions/index.md

[
](https://jira.d2iq.com/browse/D2IQ-88866)## Description of changes being made
http://docs-d2iq-com-pr-4537.s3-website-us-west-2.amazonaws.com/

Fixing broken links

---

pages/dkp/konvoy/2.1/choose-infrastructure/aks/aks-quickstart/index.md

https://jira.d2iq.com/browse/COPS-7216

updating quotes

---

pages/dkp/kommander/2.2/operations/identity-providers/ldap/index.md

https://jira.d2iq.com/browse/D2IQ-90545
This PR updates the configuration of LDAP connector for DKP 2.3. The configuration available is still functioning despite being deprecated for 2.2. I suggest keeping documentation for this version as is, to guarantee compatibility with other releases of 2.2.X.
http://docs-d2iq-com-pr-4555.s3-website-us-west-2.amazonaws.com/

chore: update ldap configuration to dex v2.31.0

---

pages/dkp/kommander/2.1/legal/version-policy/index.md
pages/dkp/kommander/2.2/legal/version-policy/index.md
pages/dkp/konvoy/2.1/legal/version-policy/index.md
pages/dkp/konvoy/2.2/legal/version-policy/index.md

Signed-off-by: Casie 2 <casie2@MacBook-Pro.local>
https://jira.d2iq.com/browse/D2IQ-90961
http://docs-d2iq-com-pr-4566.s3-website-us-west-2.amazonaws.com/

adding secondary support section

---

pages/dkp/kommander/2.2/release-notes/2.2.2/index.md

adding rn to kommander

---

pages/dkp/konvoy/2.1/major-version-upgrade/understand-standard-config/index.md

[D2IQ-91372](https://jira.d2iq.com/browse/D2IQ-91372) 
http://docs-d2iq-com-pr-4568.s3-website-us-west-2.amazonaws.com/

making note more visible 

---

pages/dkp/kaptain/2.1.0/tutorials/ngc/index.md

https://jira.d2iq.com/browse/D2IQ-91017
This new page introduces on of Kaptains new features for 2.1: NGC support
http://docs-d2iq-com-pr-4573.s3-website-us-west-2.amazonaws.com/

[Kaptain]: NGC support

---

pages/dkp/kommander/2.2/gpu/index.md
pages/dkp/konvoy/2.2/choose-infrastructure/aws/gpu/index.md

https://jira.d2iq.com/browse/D2IQ-90847
After digging into GPUs recenly it was discovered that we do not currently support GPUs On Prem in an Airgap Environment.  ALso the supported versions of Nvidia needed to be called out and links to Official Nvidia driver installation docs.
2.3 added in Confluence 
https://d2iq.atlassian.net/wiki/spaces/DENT/pages/29917892/GPUs+in+an+AWS+environment
https://d2iq.atlassian.net/wiki/spaces/DENT/pages/29921205/GPUs
http://docs-d2iq-com-pr-4589.s3-website-us-west-2.amazonaws.com/

GPU additional info

---

pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/create-base-os-image/index.md

fix: Adding further details on how to build OS base image D2IQ-91249

---

pages/dkp/kaptain/2.0.0/configuration/external-dex/index.md

https://jira.d2iq.com/browse/D2IQ-91796
Fixes the docs for configuring the external dex client for Kaptain 2.0. 
This has to be copied to the upcoming 2.1 docs as well.

Update Dex configuration docs for Kaptain

---

pages/dkp/kaptain/2.1.0/configuration/index.md
pages/dkp/kaptain/2.1.0/sdk/1.1.x/api/index.md
pages/dkp/kaptain/2.1.0/sdk/1.1.x/index.md
pages/dkp/kaptain/2.1.0/sdk/1.2.x/api/index.md
pages/dkp/kaptain/2.1.0/sdk/1.2.x/index.md
pages/dkp/kaptain/2.1.0/tutorials/katib/index.md
pages/dkp/kaptain/2.1.0/tutorials/pipelines/index.md
pages/dkp/kaptain/2.1.0/tutorials/sdk/image-builder/index.md
pages/dkp/kaptain/2.1.0/tutorials/sdk/pytorch/index.md
pages/dkp/kaptain/2.1.0/tutorials/sdk/quick-start/index.md
pages/dkp/kaptain/2.1.0/tutorials/sdk/tensorflow/index.md
pages/dkp/kaptain/2.1.0/tutorials/training/mxnet/index.md
pages/dkp/kaptain/2.1.0/tutorials/training/pytorch/index.md
pages/dkp/kaptain/2.1.0/tutorials/training/spark/index.md
pages/dkp/kaptain/2.1.0/tutorials/training/tensorflow/index.md

Kaptain 2.1.0-rc.0 autogenerated docs

---

pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/aws/index.md

Documentation for https://github.com/mesosphere/konvoy2/pull/1492

konvoy: document details about upgrade with multiple AZs

---

pages/dkp/konvoy/2.2/choose-infrastructure/aks/aks-advanced/index.md

The section name is very misleading because AKS doesn't support self-managed
http://docs-d2iq-com-pr-4602.s3-website-us-west-2.amazonaws.com/

fix: AKS self managed fixes 

---

pages/dkp/konvoy/2.2/dkp-upgrade/index.md

https://jira.d2iq.com/browse/D2IQ-91375 
http://docs-d2iq-com-pr-4614.s3-website-us-west-2.amazonaws.com/

Updating upgrade path with link to new 2.3 version

---

pages/dkp/konvoy/2.1/major-version-upgrade/index.md

https://jira.d2iq.com/browse/D2IQ-91375 
http://docs-d2iq-com-pr-4614.s3-website-us-west-2.amazonaws.com/

update upgrade paths. 

---

pages/dkp/konvoy/2.1/supported-operating-systems/index.md

Signed-off-by: Casie 2 <casie2@MacBook-Pro.local>
https://jira.d2iq.com/browse/D2IQ-92601 

adding 2.1 oses

---

pages/dkp/kaptain/2.0.0/install/deploy-kaptain/index.md

extra parenthesis

---

pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/prepare-local-environment/index.md

https://d2iq.atlassian.net/browse/D2IQ-93478
Added new fetch.yaml file to upgrade docs.
http://docs-d2iq-com-pr-4644.s3-website-us-west-2.amazonaws.com/

[Konvoy] Update fetch.yaml file in Upgrade Documentation

---

pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/prepare-local-environment/index.md

While going through this [page](https://archive-docs.d2iq.com/dkp/konvoy/2.1/major-version-upgrade/upgrade/prepare-local-environment/) I found this code snippet doesn't properly display on the archive docs site. This change is simply just a formatting fix.
Is this the correct branch to use for this change?
http://docs-d2iq-com-pr-4646.s3-website-us-west-2.amazonaws.com/

docs: fix playbook formatting

---

pages/dkp/kommander/2.2/workspaces/applications/platform-applications/platform-application-requirements/index.md

docs: update PV requirement for grafana-loki

---

pages/dkp/kommander/2.2/gpu/kommander-config/index.md
pages/dkp/kommander/2.2/insights/insights-setup/index.md
pages/dkp/kommander/2.2/install/small-environment/index.md
pages/dkp/kommander/2.2/workspaces/applications/platform-applications/platform-application-requirements/index.md

https://d2iq.atlassian.net/browse/D2IQ-92307 
Backporting some improvements to the Kommander on small environment topic.
http://docs-d2iq-com-pr-4651.s3-website-us-west-2.amazonaws.com/

[Komm] small installation improvements

---

pages/dkp/kaptain/2.2.0/configuration/index.md
pages/dkp/kaptain/2.2.0/sdk/1.3.x/api/index.md
pages/dkp/kaptain/2.2.0/sdk/1.3.x/index.md
pages/dkp/kaptain/2.2.0/tutorials/feast/index.md
pages/dkp/kaptain/2.2.0/tutorials/katib/index.md
pages/dkp/kaptain/2.2.0/tutorials/pipelines/index.md
pages/dkp/kaptain/2.2.0/tutorials/sdk/image-builder/index.md
pages/dkp/kaptain/2.2.0/tutorials/sdk/pytorch/index.md
pages/dkp/kaptain/2.2.0/tutorials/sdk/quick-start/index.md
pages/dkp/kaptain/2.2.0/tutorials/sdk/tensorflow/index.md
pages/dkp/kaptain/2.2.0/tutorials/training/mxnet/index.md
pages/dkp/kaptain/2.2.0/tutorials/training/pytorch/index.md
pages/dkp/kaptain/2.2.0/tutorials/training/tensorflow/index.md

http://docs-d2iq-com-pr-4660.s3-website-us-west-2.amazonaws.com/

Generate Kaptain 2.2 docs

---

.github/workflows/dkp-cli.yml
ci/update-dkp-cli-docs.sh

https://d2iq.atlassian.net/browse/D2IQ-94468
Restores the known, previously deactivated automation around the DKP CLI docs. The automation is not scheduled, but needs to be triggered manually when there is a need to sync docs.

build: on-demand DKP-CLI docs for v2.1, v2.2

---

.github/workflows/dkp-cli.yml

https://d2iq.atlassian.net/browse/D2IQ-94468
Fixup for #4664

fix: errors in dkp cli automation yaml

---

.github/workflows/vale.yml

fix: vale gh action

---

pages/dkp/kommander/2.2/release-notes/2.2.0/index.md
pages/dkp/kommander/2.2/release-notes/2.2.1/index.md
pages/dkp/kommander/2.2/release-notes/2.2.2/index.md
pages/dkp/kommander/2.2/release-notes/2.2.3/index.md

Reverts mesosphere/dcos-docs-site#4672

Revert "Bug: 94862 Calico workaround"

---

.github/workflows/vale.yml
pages/dkp/kommander/2.2/release-notes/2.2.0/index.md
pages/dkp/kommander/2.2/release-notes/2.2.1/index.md
pages/dkp/kommander/2.2/release-notes/2.2.2/index.md
pages/dkp/kommander/2.2/release-notes/2.2.3/index.md

Merging main into the feature branch

fix: vale gh actions

---

pages/dkp/kommander/2.2/release-notes/2.2.0/index.md
pages/dkp/kommander/2.2/release-notes/2.2.1/index.md
pages/dkp/kommander/2.2/release-notes/2.2.2/index.md
pages/dkp/kommander/2.2/release-notes/2.2.3/index.md

C
https://d2iq.atlassian.net/browse/D2IQ-94862
http://docs-d2iq-com-pr-4676.s3-website-us-west-2.amazonaws.com/ 

docs: redoing for what was pr 4672

---

pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/preprovisioned/index.md

https://d2iq.atlassian.net/browse/D2IQ-95189
See Jira ticket - we need to add a snippet of code to address the GPG issue.
http://docs-d2iq-com-pr-4680.s3-website-us-west-2.amazonaws.com/

[Incident] GPG, KIB Process during upgrade bypasses proxy 

---

pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/preprovisioned/index.md

No JIRA ticket, per se - but these got left as a suggestion, so just committing these now to the doc: 
https://github.com/mesosphere/dcos-docs-site/pull/4680/files
The above didn't get actually pushed as a commit, but stuck in a suggestion, so just adding this here.
http://docs-d2iq-com-pr-4682.s3-website-us-west-2.amazonaws.com/

docs: commiting the changes into the doc

---

pages/dkp/konvoy/2.1/major-version-upgrade/migration-for-metallb/index.md

[](https://d2iq.atlassian.net/browse/D2IQ-96652)
Created new page for MetalLB considerations during migration from 1.8.x to 2.1.x. (Baker pushed this for Charles Du who owns the Jira ticket)

[DOC] d2iq-96652 metallb considerations pushed for charles du

---

pages/dkp/kommander/2.2/dkp-upgrade/upgrade-konvoy/enterprise/index.md
pages/dkp/kommander/2.3/dkp-upgrade/upgrade-konvoy/enterprise/index.md
pages/dkp/konvoy/2.2/dkp-upgrade/upgrade-konvoy/enterprise/index.md
pages/dkp/konvoy/2.3/dkp-upgrade/upgrade-konvoy/enterprise/index.md

https://d2iq.atlassian.net/browse/D2IQ-96951
http://docs-d2iq-com-pr-4695.s3-website-us-west-2.amazonaws.com/

konvoy: document steps to upgrade EBS CSI after 1.8 upgrade
