- package-lock.json
- package.json
- plugins/metalsmith-algolia.js
> added version weight to search records

- pages/1.9/security/ent/index.md
- pages/services/beta-hdfs/v1.3.2-2.6.0-cdh5.9.1-beta/install/index.md
- pages/services/beta-hdfs/v1.3.3-2.6.0-cdh5.11.0-beta/install/index.md
- pages/services/beta-hdfs/v2.0.0-2.6.0-cdh5.11.0/install/index.md
- pages/services/beta-kafka/1.1.27-0.11.0-beta/install-and-customize/index.md
- pages/services/beta-kafka/v1.1.25-0.10.1.0-beta/install-and-customize/index.md
- pages/services/beta-kafka/v1.1.26-0.10.1.0-beta/install-and-customize/index.md
- pages/services/confluent-kafka/2.0.1-3.3.0e/install/index.md
- pages/services/confluent-kafka/2.0.1.1-3.3.0e/install/index.md
- pages/services/confluent-kafka/2.0.2-3.3.0e/install/index.md
- pages/services/hdfs/2.0.1-2.6.0-cdh5.11.0/install/index.md
- pages/services/hdfs/2.0.2-2.6.0-cdh5.11.0/install/index.md
- pages/services/hdfs/2.0.3-2.6.0-cdh5.11.0/install/index.md
- pages/services/hdfs/v1.3.0-2.6.0-cdh5.9.1/install/index.md
- pages/services/hdfs/v2.0.0-2.6.0-cdh5.11.0/install/index.md
- pages/services/kafka/2.0.1-0.11.0/install/index.md
- pages/services/kafka/2.0.2-0.11.0/install/index.md
- pages/services/kafka/2.0.3-0.11.0/install/index.md
- pages/services/kafka/v2.0.0-0.11.0/install/index.md
- pages/services/spark/v1.0.9-2.1.0-1/install/index.md
- pages/services/spark/v1.1.0-2.1.1/install/index.md
> hdfs link fixes and incidentals

- scripts/migration.sh
> Modify migration script to work on mac too

- pages/1.9/release-notes/1.9.0-rc1/index.md
- pages/1.9/release-notes/1.9.0-rc2/index.md
- pages/1.9/release-notes/1.9.0-rc3/index.md
- pages/1.9/release-notes/1.9.0-rc4/index.md
- pages/1.9/release-notes/1.9.0/index.md
- pages/1.9/release-notes/1.9.1/index.md
- pages/1.9/release-notes/1.9.2/index.md
- pages/1.9/release-notes/1.9.3/index.md
- pages/1.9/release-notes/1.9.4/index.md
- pages/1.9/release-notes/1.9.5/index.md
- pages/1.9/release-notes/1.9.6/index.md
> 1.9.6 release notes

- docker/nginx/redirects-301.map
> redirects for OSS, version policy, service docs

- pages/1.10/release-notes/1.10.3/index.md
> Fix OSS titling

- README.md
> Mention contribution in link to Wiki

- README.md
Add link to Jira project for filing issues.
- [ X] High
> Add link to Jira project for filing issues.

- pages/services/beta-kubernetes/0.2.0-1.7.6-beta/index.md
- pages/services/beta-kubernetes/0.2.1-1.7.7-beta/index.md
- pages/services/beta-kubernetes/0.2.2-1.7.7-beta/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/advanced-install/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/connecting-clients/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/disaster-recovery/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/install/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/limitations/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/quick-start/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/release-notes/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/supported-versions/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/uninstall/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/upgrade/index.md
- pages/services/beta-kubernetes/v0.1.0-1.7.5-beta/index.md
> new K8s version

- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/advanced-install/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/connecting-clients/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/disaster-recovery/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/install/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/limitations/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/quick-start/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/release-notes/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/supported-versions/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/uninstall/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/upgrade/index.md
> fix stupid mistakes

- 1.11/deploying-services/marathon-parameters/index.md
- 1.11/deploying-services/pods/examples/index.md
- 1.11/deploying-services/pods/index.md
- 1.11/gui/cluster/index.md
- 1.11/gui/index.md
- 1.11/storage/mount-disk-resources/index.md
- 1.11/storage/persistent-volume/index.md
- pages/1.10/deploying-services/pods/examples/index.md
- pages/1.9/deploying-services/pods/examples/index.md
https://jira.mesosphere.com/browse/DOCS-2377
For the purposes of this PR you can ignore the commit 55ff5dc.
- [ x] Blocker 
> persistent volumes for pods

- 1.11/api/cluster-link.yaml
https://jira.mesosphere.com/browse/DOCS-2340
- [ x] High
> Update cluster link API.

- pages/1.9/release-notes/1.9.0-rc4/index.md
Updated badge shortcode.
- [ x] Medium
> Updated preview badge shortcode

- docker/nginx/redirects-301.map
> fix advanced install redirects

- docker/nginx/redirects-301.map
> redirect experiment

- layouts/dcos-docs-landing.pug
Resolving: https://github.com/mesosphere/dcos-docs-site/issues/364
> Fix #364 - Home Page Search

- 1.11/deploying-services/containerizers/index.md
https://jira.mesosphere.com/browse/DOCS-2241
- [x ] Blocker 
> Add image GC.

- pages/1.10/tutorials/dcos-101/loadbalancing/index.md
- pages/1.9/tutorials/dcos-101/loadbalancing/index.md
> Fixed a typo: https://jira.mesosphere.com/browse/DOCS-2306

- pages/1.10/overview/concepts/index.md
- pages/1.8/overview/concepts/index.md
- pages/1.9/overview/concepts/index.md
> typo fixes!

- pages/1.10/cli/command-reference/index.md
> fixed erroneous first link to dcos

- docker/nginx/redirects-301.map
> fix regex for networking 1.10

- docker/nginx/redirects-301.map
> fix installing redirect, or try to

- docker/nginx/redirects-301.map
> installation redirect fix again

- pages/services/beta-cassandra/index.md
- pages/services/beta-confluent-kafka/index.md
- pages/services/beta-dse/index.md
- pages/services/beta-elastic/index.md
- pages/services/beta-hdfs/index.md
- pages/services/beta-kafka/index.md
- pages/services/beta-kubernetes/index.md
- pages/services/beta-zookeeper/index.md
- pages/services/dse/index.md
- pages/services/edge-lb/index.md
- pages/services/elastic/index.md
- pages/services/hdfs/index.md
- pages/services/jenkins/index.md
- pages/services/kafka/index.md
- pages/services/marathon-lb/index.md
- pages/services/spark/index.md
> update service doc sort order

- pages/1.10/release-notes/1.10.4/index.md
> First draft of release notes for 1.10.4.

- pages/services/kafka/2.0.4-1.0.0/api-reference/index.md
- pages/services/kafka/2.0.4-1.0.0/connecting-clients/index.md
- pages/services/kafka/2.0.4-1.0.0/index.md
- pages/services/kafka/2.0.4-1.0.0/install/index.md
- pages/services/kafka/2.0.4-1.0.0/kerberos/index.md
- pages/services/kafka/2.0.4-1.0.0/limitations/index.md
- pages/services/kafka/2.0.4-1.0.0/managing/index.md
- pages/services/kafka/2.0.4-1.0.0/quick-start/index.md
- pages/services/kafka/2.0.4-1.0.0/release-notes/index.md
- pages/services/kafka/2.0.4-1.0.0/ssl-auth/index.md
- pages/services/kafka/2.0.4-1.0.0/troubleshooting/index.md
- pages/services/kafka/2.0.4-1.0.0/uninstall/index.md
- pages/services/kafka/2.0.4-1.0.0/upgrade/index.md
> add fixed kafka 2.0.4-1.0.0

- pages/services/beta-zookeeper/2.1.0-3.4.11-beta/install/index.md
- pages/services/beta-zookeeper/2.1.1-3.4.11-beta/install/index.md
> Corrected link to custom-service-auth

- docker/nginx/redirects-301.map
> fix edge-lb redirects

- docker/nginx/redirects-301.map
> remove anchor link

- pages/services/ops-guide/common-operations/index.md
- pages/services/ops-guide/diagnostic-tools/index.md
- pages/services/ops-guide/index.md
- pages/services/ops-guide/overview/index.md
- pages/services/ops-guide/troubleshooting/index.md
> Add SDK ops guide

- pages/services/beta-confluent-kafka/v1.2.3-3.2.2e-beta/managing/index.md
> corrected typo pods->pod

- pages/services/elastic/2.1.1-5.6.5/index.md
- pages/services/hdfs/2.0.4-2.6.0-cdh5.11.0/index.md
> Ps/hdfs 2.0.4 2.6.0 cdh5.11.0 publish

- 1.11/installing/ent/custom/node-cluster-health-check/index.md
- 1.11/installing/oss/custom/node-cluster-health-check/index.md
https://jira.mesosphere.com/browse/DOCS-2133
> Document custom check executables

- pages/1.10/installing/ent/upgrading/index.md
> Corrected Mesos version from 1.2.0 to 1.4.0

- pages/services/spark/2.1.0-2.2.0-1/index.md
- pages/services/spark/2.1.0-2.2.1-1/custom-docker/index.md
- pages/services/spark/2.1.0-2.2.1-1/fault-tolerance/index.md
- pages/services/spark/2.1.0-2.2.1-1/hdfs/index.md
- pages/services/spark/2.1.0-2.2.1-1/history-server/index.md
- pages/services/spark/2.1.0-2.2.1-1/index.md
- pages/services/spark/2.1.0-2.2.1-1/install/index.md
- pages/services/spark/2.1.0-2.2.1-1/job-scheduling/index.md
- pages/services/spark/2.1.0-2.2.1-1/limitations/index.md
- pages/services/spark/2.1.0-2.2.1-1/quickstart/index.md
- pages/services/spark/2.1.0-2.2.1-1/release-notes/index.md
- pages/services/spark/2.1.0-2.2.1-1/run-job/index.md
- pages/services/spark/2.1.0-2.2.1-1/runtime-config-change/index.md
- pages/services/spark/2.1.0-2.2.1-1/security/index.md
- pages/services/spark/2.1.0-2.2.1-1/spark-shell/index.md
- pages/services/spark/2.1.0-2.2.1-1/troubleshooting/index.md
- pages/services/spark/2.1.0-2.2.1-1/uninstall/index.md
- pages/services/spark/2.1.0-2.2.1-1/upgrade/index.md
- pages/services/spark/2.1.0-2.2.1-1/usage-examples/index.md
- pages/services/spark/2.1.0-2.2.1-1/version-policy/index.md
- pages/services/spark/2.2.0-2.2.0-2-beta/index.md
- pages/services/spark/spark-auth/index.md
- pages/services/spark/v1.0.9-2.1.0-1/index.md
- pages/services/spark/v1.1.1-2.2.0/index.md
- pages/services/spark/v2.0.0-2.2.0-1/index.md
- pages/services/spark/v2.0.1-2.2.0-1/index.md
- scripts/service-update-scripts/merge-lists/spark-build-merge-list.txt
- scripts/service-update-scripts/spark-merge.sh
Also:
- Removed kerberos.md from file list
- Fixed file path in merge script
https://jira.mesosphere.com/browse/RELEASE-309
- [ x] Blocker
> Docs for Spark 2.1.0-2.2.1-1

- pages/services/spark/2.1.0-2.2.1-1/custom-docker/index.md
- pages/services/spark/2.1.0-2.2.1-1/fault-tolerance/index.md
- pages/services/spark/2.1.0-2.2.1-1/hdfs/index.md
- pages/services/spark/2.1.0-2.2.1-1/history-server/index.md
- pages/services/spark/2.1.0-2.2.1-1/index.md
- pages/services/spark/2.1.0-2.2.1-1/install/index.md
- pages/services/spark/2.1.0-2.2.1-1/job-scheduling/index.md
- pages/services/spark/2.1.0-2.2.1-1/limitations/index.md
- pages/services/spark/2.1.0-2.2.1-1/quickstart/index.md
- pages/services/spark/2.1.0-2.2.1-1/release-notes/index.md
- pages/services/spark/2.1.0-2.2.1-1/run-job/index.md
- pages/services/spark/2.1.0-2.2.1-1/runtime-config-change/index.md
- pages/services/spark/2.1.0-2.2.1-1/security/index.md
- pages/services/spark/2.1.0-2.2.1-1/spark-shell/index.md
- pages/services/spark/2.1.0-2.2.1-1/troubleshooting/index.md
- pages/services/spark/2.1.0-2.2.1-1/uninstall/index.md
- pages/services/spark/2.1.0-2.2.1-1/upgrade/index.md
- pages/services/spark/2.1.0-2.2.1-1/usage-examples/index.md
- pages/services/spark/2.1.0-2.2.1-1/version-policy/index.md
Also: 
- updated service docs links
- small doc update in history.md
> [Spark docs] Updated the metadata in index.md files

- 1.11/installing/ent/cloud/aws/index.md
- 1.11/installing/oss/cloud/aws/index.md
- pages/1.10/installing/ent/cloud/aws/index.md
- pages/1.10/installing/oss/cloud/aws/index.md
- pages/1.8/administration/installing/ent/cloud/aws/index.md
- pages/1.8/administration/installing/oss/cloud/aws/index.md
- pages/1.9/installing/ent/cloud/aws/index.md
- pages/1.9/installing/oss/cloud/aws/index.md
https://jira.mesosphere.com/browse/DOCS-2362
> Added the disclaimer to not use AWS CF templates in Production

- 1.11/installing/oss/cloud/aws/index.md
- pages/1.10/installing/oss/cloud/aws/index.md
- pages/1.8/administration/installing/oss/cloud/aws/index.md
- pages/1.9/installing/oss/cloud/aws/index.md
https://jira.mesosphere.com/browse/DOCS-2362
> Fixed links for OSS that accidently went to ENT

- pages/services/spark/2.1.0-2.2.1-1/release-notes/index.md
> Updated metadata in RN for Spark 2.1.0-2.2.1-1.

- pages/1.11/index.md
> Release notes for 1.11-rc1

- pages/1.11/administering-clusters/licenses/index.md
- pages/1.11/cli/command-reference/dcos-backup/index.md
- pages/1.11/cli/command-reference/dcos-cluster/index.md
- pages/1.11/cli/command-reference/dcos-config/index.md
- pages/1.11/cli/command-reference/dcos-edgelb/index.md
- pages/1.11/cli/command-reference/dcos-experimental/index.md
- pages/1.11/cli/command-reference/dcos-help/index.md
- pages/1.11/cli/command-reference/dcos-job/index.md
- pages/1.11/cli/command-reference/dcos-license/index.md
- pages/1.11/cli/command-reference/dcos-marathon/index.md
- pages/1.11/cli/command-reference/dcos-node/index.md
- pages/1.11/cli/command-reference/dcos-package/index.md
- pages/1.11/cli/command-reference/dcos-security/index.md
- pages/1.11/cli/command-reference/dcos-service/index.md
- pages/1.11/cli/command-reference/dcos-storage/index.md
- pages/1.11/cli/command-reference/dcos-task/index.md
- pages/1.11/cli/command-reference/index.md
- pages/1.11/cli/enterprise-cli/index.md
- pages/1.11/installing/ent/custom/advanced/index.md
- pages/1.11/installing/ent/custom/cli/index.md
- pages/1.11/installing/ent/custom/gui/index.md
> dcos backup changes stephanie

- pages/1.10/installing/oss/cloud/gce/index.md
- pages/1.10/installing/oss/index.md
- pages/1.11/installing/oss/index.md
> Updated GCE install instructions to use terraform.

- pages/1.11/administering-clusters/licenses/index.md
- pages/1.11/administering-clusters/licenses/license-api/index.md
- pages/1.11/cli/command-reference/dcos-license/dcos-license-audit-get/index.md
- pages/1.11/cli/command-reference/dcos-license/dcos-license-get/index.md
- pages/1.11/cli/command-reference/dcos-license/dcos-license-status/index.md
> added some of the changes specified by Isabel Jimenez

- pages/1.10/monitoring/logging/aggregating/elk/index.md
- pages/1.11/monitoring/logging/aggregating/elk/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-2112
> Fixes DCOS_OSS-2112

- pages/1.11/administering-clusters/licenses/license-api/index.md
- pages/1.11/installing/ent/custom/advanced/index.md
- pages/1.11/installing/ent/custom/gui/index.md
> Last batch of edits Stephanie made in December.

- 1.11/overview/feature-maturity/index.md
> replaced old three feature maturity stages with two new stages

- pages/services/marathon-lb/marathon-lb-advanced-tutorial/index.md
> Change references from "1.7.7" to "latest"

- pages/1.11/administering-clusters/licenses/index.md
> Added section on cluster upgrades

- pages/1.11/administering-clusters/licenses/index.md
> Add material confirmed by Somik

- pages/1.10/api/package-manager.yaml
- pages/1.11/api/package-manager.yaml
- pages/1.9/api/package-manager.yaml
Fix pdf build error by putting swagger header at top of yaml files
> Put swagger type at the top of file

- pages/1.11/release-notes/index.md
> Added download button.

- pages/1.11/deploying-services/index.md
- pages/1.11/monitoring/logging/access-component-logs/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/api-reference/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/connecting-clients/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/disaster-recovery/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/install/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/kerberos/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/limitations/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/managing/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/quick-start/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/release-notes/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/ssl-auth/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/supported-versions/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/troubleshooting/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/uninstall/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/upgrade/index.md
- pages/services/beta-confluent-kafka-zookeeper/index.md
Adding Beta Confluent Kafka Zookeeper 2.1.1-4.0.0e-beta
> Adding Yishan's Beta Confluent Kafka Zookeeper doc changes & minor docs fixes.

- pages/1.11/deploying-services/index.md
- pages/1.11/monitoring/logging/access-component-logs/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/api-reference/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/connecting-clients/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/disaster-recovery/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/install/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/kerberos/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/limitations/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/managing/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/quick-start/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/release-notes/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/ssl-auth/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/supported-versions/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/troubleshooting/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/uninstall/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/upgrade/index.md
- pages/services/beta-confluent-kafka-zookeeper/index.md
https://jira.mesosphere.com/browse/DCOS-20642
> Added "beta-confluent-kafka-zookeeper" directory to services, update broken img link/typos

- pages/1.11/release-notes/index.md
> Updated download link for DC/OS Open Source.

- pages/services/edge-lb/0.1.9/api-reference/index.md
- pages/services/edge-lb/0.1.9/cli-reference/index.md
- pages/services/edge-lb/0.1.9/input-formats/index.md
- pages/services/edge-lb/0.1.9/installing/index.md
- pages/services/edge-lb/0.1.9/permissions/index.md
- pages/services/edge-lb/0.1.9/pool-configuration/index.md
- pages/services/edge-lb/0.1.9/release-notes/index.md
- pages/services/edge-lb/0.1.9/uninstalling/index.md
- pages/services/edge-lb/0.1.9/upgrading/index.md
- pages/services/edge-lb/1.0.0/api-reference/index.md
- pages/services/edge-lb/1.0.0/api-reference/v1/index.md
- pages/services/edge-lb/1.0.0/api-reference/v2/index.md
- pages/services/edge-lb/1.0.0/cli-reference/index.md
- pages/services/edge-lb/1.0.0/input-formats/index.md
- pages/services/edge-lb/1.0.0/installing/index.md
- pages/services/edge-lb/1.0.0/permissions/index.md
- pages/services/edge-lb/1.0.0/pool-configuration/index.md
- pages/services/edge-lb/1.0.0/pool-configuration/v1-examples/index.md
- pages/services/edge-lb/1.0.0/pool-configuration/v1-reference/index.md
- pages/services/edge-lb/1.0.0/pool-configuration/v2-examples/index.md
- pages/services/edge-lb/1.0.0/pool-configuration/v2-reference/index.md
- pages/services/edge-lb/1.0.0/release-notes/index.md
- pages/services/edge-lb/1.0.0/uninstalling/index.md
- pages/services/edge-lb/1.0.0/upgrading/index.md
https://jira.mesosphere.com/browse/EDGELB-35
> Add excerpts to the top of each Edge-LB section

- pages/1.11/release-notes/1.11.0-rc1/index.md
https://jira.mesosphere.com/browse/RELEASE-455
> Added link to Mesosphere Support, for downloading DC/OS Enterprise.

- pages/services/beta-cassandra/2.1.2-3.0.15-beta/release-notes/index.md
- pages/services/beta-elastic/2.1.2-5.6.5-beta/release-notes/index.md
- pages/services/beta-hdfs/2.1.2-2.6.0-cdh5.11.0-beta/release-notes/index.md
- pages/services/beta-kafka/2.1.2-1.0.0-beta/release-notes/index.md
> Adding release notes for Beta-Cassandra, Beta-Elastic, Beta-Kafka, & Beta-HDFS

- pages/1.11/release-notes/1.11.0-rc1/index.md
https://jira.mesosphere.com/browse/RELEASE-455
> Fixed a few broken links.

- pages/services/edge-lb/0.1.9/release-notes/index.md
- pages/services/edge-lb/1.0.0/release-notes/index.md
Fixes some broken links in edge-lb release notes
> Fix release notes links

- pages/1.9/release-notes/1.9.6/index.md
- pages/1.9/release-notes/1.9.7/index.md
https://jira.mesosphere.com/browse/RELEASE-434
> First draft of release notes for DC/OS 1.9.7.

- pages/1.9/release-notes/1.9.7/index.md
https://jira.mesosphere.com/browse/RELEASE-434
> Changed download link back to being version-specific.

- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/advanced-install/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/connecting-clients/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/disaster-recovery/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/ingress/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/install/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/limitations/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/quick-start/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/release-notes/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/supported-versions/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/uninstall/index.md
- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/upgrade/index.md
> Updating Kubernetes 0.4.0-1.9.0-beta docs.

- pages/services/beta-kubernetes/0.4.0-1.9.0-beta/index.md
> Fixed metedata issue for Kubernetes 0.4.0-1.9.0-beta docs

- docker/Dockerfile.htmltopdf
- docker/docker-compose.production.yml
- scripts/pdf.sh
> improved htmltopdf build time by parallel

- pages/services/beta-cassandra/2.1.2-3.0.15-beta/index.md
- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/index.md
- pages/services/beta-confluent-kafka/2.1.2-4.0.0e-beta/index.md
- pages/services/beta-elastic/2.1.2-5.6.5-beta/index.md
- pages/services/beta-kafka-zookeeper/2.1.2-3.4.11-beta/index.md
- pages/services/beta-kafka/2.1.2-1.0.0-beta/index.md
- pages/services/beta-spark/2.2.0-2.2.0-2-beta/index.md
- pages/services/beta-spark/2.2.1-2.2.0-2-beta/index.md
> Adjusting navigation titles for data services.

- docker/Dockerfile.htmltopdf
- scripts/genpdf.js
- scripts/pdf.sh
added phantomjs to build pdfs. Local build takes about 25min now
> added phantomjs pdf build

- pages/1.11/installing/ent/custom/configuration/configuration-parameters/index.md
- pages/1.11/installing/oss/custom/configuration/configuration-parameters/index.md
- pages/1.11/networking/DNS/index.md
- pages/1.11/networking/SDN/dcos-overlay/index.md
- pages/1.11/networking/SDN/index.md
- pages/1.11/networking/SDN/usage/index.md
- pages/1.11/networking/index.md
[DCOS_OSS-1404](https://jira.mesosphere.com/browse/DCOS_OSS-1404)
> Edits and some more texts

- pages/1.11/installing/oss/cloud/digitalocean/index.md
> Fixed a typo.

- pages/1.10/installing/oss/custom/configuration/configuration-parameters/index.md
- pages/1.10/security/ent/tls-ssl/ca-custom/index.md
https://jira.mesosphere.com/browse/DCOS-19638
- [ X ] High
This is detailed documentation on installing DC/OS with a custom CA certificate. (improvement on the existing doc)
> Improved documentation on DC/OS installation with a custom CA certificate

- pages/1.11/tutorials/stateful-services/index.md
https://jira.mesosphere.com/browse/DOCS-2433
> Added a layout page

- pages/1.11/administering-clusters/multiple-clusters/cluster-links/index.md
> JIRA-COPS-2416

- pages/1.11/tutorials/stateful-services/index.md
https://jira.mesosphere.com/browse/DOCS-2433
> Fixed the names of some page variables

- pages/1.11/administering-clusters/licenses/index.md
- pages/1.11/administering-clusters/licenses/license-cli/index.md
- pages/1.11/administering-clusters/multiple-clusters/cluster-link-api/index.md
- pages/1.11/administering-clusters/multiple-clusters/cluster-links/index.md
Administering Clusters improvements : https://jira.mesosphere.com/browse/DOCS-2366
There has already been some work on it so this is mainly a second pass to update them according to the changes made in the meanwhile.
> Reorganize Administering Clusters section

- pages/1.11/installing/ent/custom/advanced/index.md
> fixed typo in 1.1/installing/ent/custom/advanced

- pages/1.11/administering-clusters/multiple-clusters/cluster-links/index.md
- pages/1.11/cli/command-reference/dcos-storage/index.md
- pages/1.11/cli/enterprise-cli/index.md
- pages/1.11/installing/ent/custom/advanced/index.md
> multiple changes from Bug Bash

- pages/services/beta-spark/2.3.1-2.2.1-2-beta/custom-docker/index.md
- pages/services/beta-spark/2.3.1-2.2.1-2-beta/fault-tolerance/index.md
- pages/services/beta-spark/2.3.1-2.2.1-2-beta/hdfs/index.md
- pages/services/beta-spark/2.3.1-2.2.1-2-beta/history-server/index.md
- pages/services/beta-spark/2.3.1-2.2.1-2-beta/index.md
- pages/services/beta-spark/2.3.1-2.2.1-2-beta/install/index.md
- pages/services/beta-spark/2.3.1-2.2.1-2-beta/job-scheduling/index.md
- pages/services/beta-spark/2.3.1-2.2.1-2-beta/limitations/index.md
- pages/services/beta-spark/2.3.1-2.2.1-2-beta/quickstart/index.md
- pages/services/beta-spark/2.3.1-2.2.1-2-beta/release-notes/index.md
- pages/services/beta-spark/2.3.1-2.2.1-2-beta/run-job/index.md
- pages/services/beta-spark/2.3.1-2.2.1-2-beta/runtime-config-change/index.md
- pages/services/beta-spark/2.3.1-2.2.1-2-beta/security/index.md
- pages/services/beta-spark/2.3.1-2.2.1-2-beta/spark-shell/index.md
- pages/services/beta-spark/2.3.1-2.2.1-2-beta/troubleshooting/index.md
- pages/services/beta-spark/2.3.1-2.2.1-2-beta/uninstall/index.md
- pages/services/beta-spark/2.3.1-2.2.1-2-beta/upgrade/index.md
- pages/services/beta-spark/2.3.1-2.2.1-2-beta/usage-examples/index.md
- pages/services/beta-spark/2.3.1-2.2.1-2-beta/version-policy/index.md
> Spark 2.3.1-2.2.1-2-beta

- docs/package/advanced-install/index.md
- docs/package/connecting-clients/index.md
- docs/package/disaster-recovery/index.md
- docs/package/ingress/index.md
- docs/package/install/index.md
- docs/package/limitations/index.md
- docs/package/quick-start/index.md
- docs/package/release-notes/index.md
- docs/package/supported-versions/index.md
- docs/package/uninstall/index.md
- docs/package/upgrade/index.md
- pages/services/beta-kubernetes/0.5.0-1.9.1-beta/advanced-install/index.md
- pages/services/beta-kubernetes/0.5.0-1.9.1-beta/connecting-clients/index.md
- pages/services/beta-kubernetes/0.5.0-1.9.1-beta/disaster-recovery/index.md
- pages/services/beta-kubernetes/0.5.0-1.9.1-beta/index.md
- pages/services/beta-kubernetes/0.5.0-1.9.1-beta/ingress/index.md
- pages/services/beta-kubernetes/0.5.0-1.9.1-beta/install/index.md
- pages/services/beta-kubernetes/0.5.0-1.9.1-beta/limitations/index.md
- pages/services/beta-kubernetes/0.5.0-1.9.1-beta/quick-start/index.md
- pages/services/beta-kubernetes/0.5.0-1.9.1-beta/release-notes/index.md
- pages/services/beta-kubernetes/0.5.0-1.9.1-beta/supported-versions/index.md
- pages/services/beta-kubernetes/0.5.0-1.9.1-beta/uninstall/index.md
- pages/services/beta-kubernetes/0.5.0-1.9.1-beta/upgrade/index.md
- scripts/service-update-scripts/beta-kubernetes-merge-branch.sh
> Kubernetes0.5.0-1.9.1-beta

- pages/1.11/administering-clusters/multiple-clusters/cluster-links/index.md
> COPS-2516 Bug Fix

- pages/1.10/release-notes/1.10.4/index.md
- pages/1.10/release-notes/1.10.5/index.md
https://jira.mesosphere.com/browse/RELEASE-498
> Release notes for 1.10.5

- pages/1.11/installing/oss/ports/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-2093
> Updated first table so port numbers are in increasing order.

- pages/1.11/installing/ent/custom/configuration/configuration-parameters/index.md
JIRA: https://jira.mesosphere.com/browse/DCOS-20137
> Add documentation for Admin Router Master TLS configuration

- pages/1.10/release-notes/1.10.4/index.md
> Minor editing changes.

- pages/1.10/api/package-manager.yaml
- pages/1.11/api/package-manager.yaml
- pages/1.9/api/package-manager.yaml
> Fix installResponse in package manager api

- pages/services/beta-hdfs/2.1.2-2.6.0-cdh5.11.0-beta/index.md
> COPS-2366 bug fixes.

- pages/1.11/security/ent/sso/setup-openid/index.md
> COPS-2410 Bug Fix

- pages/1.10/installing/ent/custom/configuration/configuration-parameters/index.md
- pages/1.10/installing/oss/custom/configuration/configuration-parameters/index.md
- pages/1.11/installing/ent/custom/configuration/configuration-parameters/index.md
- pages/1.11/installing/oss/custom/configuration/configuration-parameters/index.md
This PR is fixing the links to DC/OS Configuration Reference that are present in the DC/OS EE Configuration Reference.
https://jira.mesosphere.com/browse/DCOS-21144
- [ X ] Medium
> Fix links in EE Coniguration Reference

- pages/services/beta-kubernetes/0.6.0-1.9.1-beta/advanced-install/index.md
- pages/services/beta-kubernetes/0.6.0-1.9.1-beta/cni/index.md
- pages/services/beta-kubernetes/0.6.0-1.9.1-beta/connecting-clients/index.md
- pages/services/beta-kubernetes/0.6.0-1.9.1-beta/disaster-recovery/index.md
- pages/services/beta-kubernetes/0.6.0-1.9.1-beta/index.md
- pages/services/beta-kubernetes/0.6.0-1.9.1-beta/ingress/index.md
- pages/services/beta-kubernetes/0.6.0-1.9.1-beta/install/index.md
- pages/services/beta-kubernetes/0.6.0-1.9.1-beta/limitations/index.md
- pages/services/beta-kubernetes/0.6.0-1.9.1-beta/quick-start/index.md
- pages/services/beta-kubernetes/0.6.0-1.9.1-beta/release-notes/index.md
- pages/services/beta-kubernetes/0.6.0-1.9.1-beta/supported-versions/index.md
- pages/services/beta-kubernetes/0.6.0-1.9.1-beta/uninstall/index.md
- pages/services/beta-kubernetes/0.6.0-1.9.1-beta/upgrade/index.md
- scripts/service-update-scripts/beta-kubernetes-merge-branch.sh
- scripts/service-update-scripts/beta-kubernetes-merge.sh
This will need a push to live ASAP...
> kubernetes: fix merge scripts relative links and fix up docs ordering

- pages/1.10/release-notes/1.10.5/index.md
- pages/1.11/security/ent/sso/setup-openid/index.md
https://jira.mesosphere.com/browse/RELEASE-498
> 1.10.5 Release Notes

- pages/services/kafka/2.0.4-1.0.0/api-reference/index.md
- pages/services/kafka/2.0.4-1.0.0/connecting-clients/index.md
- pages/services/kafka/2.0.4-1.0.0/install/index.md
- pages/services/kafka/2.0.4-1.0.0/managing/index.md
- pages/services/kafka/2.0.4-1.0.0/quick-start/index.md
- pages/services/kafka/2.0.4-1.0.0/troubleshooting/index.md
- pages/services/kafka/2.0.4-1.0.0/uninstall/index.md
> Kafka. Remove the word beta from production docs

- pages/1.11/release-notes/1.11.0-rc4/index.md
> 1.11.0-rc4 Release Notes

- pages/1.11/release-notes/1.11.0-rc4/index.md
> Fixing 1.11.0-rc4 installer URL

- pages/1.11/installing/ent/custom/gui/index.md
- pages/1.11/installing/ent/custom/system-requirements/index.md
- pages/1.11/installing/oss/custom/gui/index.md
> retired GUI installer and fixed broken links on various pages

- pages/services/beta-hdfs/2.1.2-2.6.0-cdh5.11.0-beta/install/index.md
> corrected typos in HDFS docs

- pages/services/beta-elastic/2.1.2-5.6.5-beta/connecting-clients/index.md
- pages/services/beta-elastic/2.1.2-5.6.5-beta/install/index.md
- pages/services/beta-elastic/2.1.2-5.6.5-beta/release-notes/index.md
- pages/services/beta-kafka-zookeeper/2.1.2-3.4.11-beta/quick-start/index.md
- pages/services/beta-kafka/2.1.2-1.0.0-beta/connecting-clients/index.md
- pages/services/beta-kafka/2.1.2-1.0.0-beta/install/index.md
- pages/services/beta-kafka/2.1.2-1.0.0-beta/quick-start/index.md
- pages/services/cassandra/2.0.3-3.0.14/install/index.md
- pages/services/confluent-kafka/2.0.3-3.3.1e/managing/index.md
- pages/services/elastic/2.1.1-5.6.5/connecting-clients/index.md
- pages/services/elastic/2.1.1-5.6.5/release-notes/index.md
- pages/services/kafka/2.0.4-1.0.0/connecting-clients/index.md
- pages/services/kafka/2.0.4-1.0.0/troubleshooting/index.md
> INFINITY 3138 - correct broken and invalid URLs

- pages/1.11/release-notes/1.11.0-rc1/index.md
https://jira.mesosphere.com/browse/DOCS-2162
> DOCS-2162 bug fix

- pages/1.11/release-notes/1.11.0-rc1/index.md
- pages/1.11/release-notes/1.11.0-rc4/index.md
https://jira.mesosphere.com/browse/DOCS-2444
> Fixed two broken links.

- pages/1.11/release-notes/1.11.0-rc1/index.md
- pages/1.11/release-notes/1.11.0-rc4/index.md
https://jira.mesosphere.com/browse/DOCS-2444
> Replaced Markdown with HTML in two links in table.

- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/quick-start/index.md
- pages/services/kafka/2.0.4-1.0.0/connecting-clients/index.md
- pages/services/kafka/2.0.4-1.0.0/install/index.md
- pages/services/kafka/2.0.4-1.0.0/kafka-auth/index.md
- pages/services/kafka/2.0.4-1.0.0/managing/index.md
> Last of the broken URL fixes

- pages/services/beta-confluent-kafka/2.1.2-4.0.0e-beta/quick-start/index.md
- pages/services/kafka/2.0.4-1.0.0/quick-start/index.md
> kafka and confluent-kafka typos corrected

- pages/1.11/installing/ent/custom/advanced/index.md
- pages/services/beta-confluent-kafka/2.1.2-4.0.0e-beta/quick-start/index.md
> more kafka typos

- pages/1.11/installing/ent/custom/advanced/index.md
- pages/services/beta-cassandra/2.1.0-3.0.15-beta/quick-start/index.md
- pages/services/beta-cassandra/2.1.1-3.0.15-beta/quick-start/index.md
- pages/services/beta-cassandra/2.1.2-3.0.15-beta/quick-start/index.md
- pages/services/cassandra/2.0.1-3.0.14/quick-start/index.md
- pages/services/cassandra/2.0.2-3.0.14/quick-start/index.md
- pages/services/cassandra/2.0.3-3.0.14/quick-start/index.md
- pages/services/cassandra/v2.0.0-3.0.14/quick-start/index.md
> Cassandra bug fixes

- pages/services/beta-storage/0.1.0-beta/architecture/index.md
- pages/services/beta-storage/0.1.0-beta/volume-plugins/index.md
Fix typos in https://github.com/mesosphere/dcos-docs-site/pull/626
> pages/services/beta-storage/0.1.0-beta: fix typos

- pages/1.11/installing/ent/custom/system-requirements/install-docker-RHEL/index.md
> added instructions for RHEL installation

- pages/services/beta-storage/0.1.0-beta/architecture/index.md
- pages/services/beta-storage/0.1.0-beta/terminology-and-concepts/index.md
- pages/services/beta-storage/0.1.0-beta/tutorials/index.md
- pages/services/beta-storage/0.1.0-beta/volume-plugins/index.md
Addressed the comments from @jdef.
> Fixed some small issues in the storage service doc

- scripts/service-update-scripts/dcos-commons-merge.sh
N/A
- Test all commands and procedures. N/A
- Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects). N/A
- Change all affected versions (e.g. 1.7, 1.8, 1.9, 1.10, 1.11). N/A
- See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/wiki/Contributing). N/A
> On OSX sed requires a '' when using -i #shrug

- pages/services/beta-storage/0.1.0-beta/release-notes/index.md
Add release notes for storage service 0.1.0-beta release.
> Added release notes for storage service

- pages/1.10/monitoring/debugging/slow-docker/index.md
- pages/1.11/monitoring/debugging/slow-docker/index.md
> Fix documentation for CFS changes

- pages/1.11/monitoring/logging/logging-api/index.md
- pages/1.11/monitoring/logging/logging-api/logging-v1/index.md
- pages/1.11/monitoring/logging/logging-api/logging-v2/index.md
- pages/services/beta-hdfs/2.1.2-2.6.0-cdh5.11.0-beta/install/index.md
- pages/services/hdfs/2.0.4-2.6.0-cdh5.11.0/install/index.md
> HDFS and logging API changes

- docker/nginx/redirects-301.map
https://jira.mesosphere.com/browse/COPS-2596?filter=-1
> Redirected the broken link

- pages/services/confluent-kafka/2.0.2-3.3.0e/index.md
- pages/services/confluent-kafka/2.0.3-3.3.1e/index.md
- pages/services/confluent-kafka/2.1.0-4.0.0e/api-reference/index.md
- pages/services/confluent-kafka/2.1.0-4.0.0e/common-operations/index.md
- pages/services/confluent-kafka/2.1.0-4.0.0e/connecting-clients/index.md
- pages/services/confluent-kafka/2.1.0-4.0.0e/diagnostic-tools/index.md
- pages/services/confluent-kafka/2.1.0-4.0.0e/index.md
- pages/services/confluent-kafka/2.1.0-4.0.0e/install/index.md
- pages/services/confluent-kafka/2.1.0-4.0.0e/limitations/index.md
- pages/services/confluent-kafka/2.1.0-4.0.0e/managing/index.md
- pages/services/confluent-kafka/2.1.0-4.0.0e/overview/index.md
- pages/services/confluent-kafka/2.1.0-4.0.0e/quick-start/index.md
- pages/services/confluent-kafka/2.1.0-4.0.0e/release-notes/index.md
- pages/services/confluent-kafka/2.1.0-4.0.0e/security/index.md
- pages/services/confluent-kafka/2.1.0-4.0.0e/supported-versions/index.md
- pages/services/confluent-kafka/2.1.0-4.0.0e/troubleshooting/index.md
- pages/services/confluent-kafka/2.1.0-4.0.0e/uninstall/index.md
- pages/services/confluent-kafka/2.1.0-4.0.0e/upgrade/index.md
- pages/services/confluent-kafka/data.yml
- pages/services/confluent-kafka/v2.0.0.1-3.3.0e/index.md
> Confluent Kafka 2.1.0-4.0.0e docs

- pages/services/cassandra/2.1.0-3.0.16/release-notes/index.md
- pages/services/confluent-kafka/2.1.0-4.0.0e/release-notes/index.md
- pages/services/confluent-zookeeper/2.1.0-4.0.0e/release-notes/index.md
- pages/services/elastic/2.2.0-5.6.5/release-notes/index.md
- pages/services/hdfs/2.1.0-2.6.0-cdh5.11.0/release-notes/index.md
- pages/services/kafka-zookeeper/2.1.0-3.4.11/release-notes/index.md
- pages/services/kafka/2.0.4-1.0.0/release-notes/index.md
- pages/services/kafka/2.1.0-1.0.0/release-notes/index.md
> Release notes for GA packages

- docker/nginx/redirects-301.map
> Changing redirects for version-policy pages for 1.9, 1.10, & 1.11

- pages/1.10/overview/architecture/node-types/index.md
https://jira.mesosphere.com/browse/DOCS-2229?filter=-1
> Updated content to reflect recommendation

- pages/services/beta-storage/index.md
https://jira.mesosphere.com/browse/DOCS-2463
> Changed navigation pane title to DC/OS Storage Service.

- pages/services/confluent-kafka/2.1.0-4.0.0e/supported-versions/index.md
- pages/services/confluent-zookeeper/2.1.0-4.0.0e/supported-versions/index.md
- pages/services/dse/2.1.2-5.1.2/supported-versions/index.md
- pages/services/include/supported-versions.tmpl
> Fix supported versions template and its consumers where applicable

- pages/1.11/installing/ent/custom/configuration/configuration-parameters/index.md
for an enterprise install.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mesosphere/dcos-docs-site/664)
> Added `feature_dcos_storage_enabled` flag to configuration parameters

- pages/1.11/installing/ent/custom/configuration/configuration-parameters/index.md
- pages/1.11/installing/oss/custom/configuration/configuration-parameters/index.md
- [*] Blocker 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mesosphere/dcos-docs-site/676)
> Added the `enable_ipv6` flag to DC/OS configuration parameters.

- pages/1.11/installing/ent/custom/configuration/configuration-parameters/index.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mesosphere/dcos-docs-site/677)
> Added the `ENTERPRISE` label to `feature_dcos_storage_enabled` flag.

- pages/version-policy/index.md
> Fixed the heading issue for DC/OS Platform Version Compatibility Matrix

- pages/1.11/installing/ent/custom/system-requirements/index.md
The changes will be reflected in 
http://docs-staging.mesosphere.com/1.11/installing/ent/custom/system-requirements/
> Fixed URL in installation page (ent) for 1.11 

- pages/services/beta-elastic/1.0.13-5.4.1-beta/limitations/index.md
- pages/services/beta-elastic/1.0.14-5.5.0-beta/limitations/index.md
- pages/services/beta-elastic/1.0.15-5.5.1-beta/limitations/index.md
- pages/services/beta-elastic/2.0.0-5.5.1/limitations/index.md
- pages/services/elastic/2.0.1-5.5.1/limitations/index.md
- pages/services/elastic/2.0.2-5.6.2/limitations/index.md
- pages/services/elastic/2.1.0-5.6.2/limitations/index.md
- pages/services/elastic/2.1.1-5.6.5/limitations/index.md
- pages/services/elastic/v1.0.8-5.2.2/limitations/index.md
- pages/services/elastic/v2.0.0-5.5.1/limitations/index.md
https://jira.mesosphere.com/browse/INFINITY-3261
> Serial deploy does not wait for green health status.

- pages/version-policy/index.md
> Changed the menu-weight to 5 for version policy page

- pages/1.9/installing/ent/custom/system-requirements/index.md
- pages/1.9/installing/oss/custom/system-requirements/index.md
https://jira.mesosphere.com/browse/DOCS-2409
> Added version policy link and removed RHEL and CoreOS from tables

- pages/services/confluent-zookeeper/2.1.0-4.0.0e/install/index.md
- pages/services/confluent-zookeeper/2.1.0-4.0.0e/security/index.md
> confluent-zookeeper fixes

- pages/1.11/installing/ent/custom/advanced/index.md
- pages/1.11/installing/ent/upgrading/index.md
- pages/1.11/installing/oss/upgrading/index.md
- pages/services/dse/2.1.2-5.1.2/connecting-clients/index.md
- pages/services/dse/2.1.2-5.1.2/install/index.md
- pages/services/dse/2.1.2-5.1.2/managing/index.md
- pages/services/dse/2.1.2-5.1.2/uninstall/index.md
> upgrade instructions modified

- pages/1.11/installing/oss/upgrading/index.md
> OSS changes

- pages/1.11/installing/ent/upgrading/index.md
- pages/1.11/installing/oss/upgrading/index.md
> OSS and ENT install instructions modified and updated

- pages/1.11/installing/ent/custom/system-requirements/index.md
- pages/1.11/installing/oss/custom/system-requirements/index.md
https://jira.mesosphere.com/browse/DOCS-2471
> In Recommendations section - Removed the first bullet

- pages/1.10/installing/ent/custom/advanced/index.md
- pages/1.11/installing/ent/custom/advanced/index.md
- pages/1.11/installing/oss/upgrading/index.md
> fix install bugs

- pages/services/beta-hdfs/v1.3.3-2.6.0-cdh5.11.0-beta/managing/index.md
- pages/services/confluent-kafka/2.0.1-3.3.0e/managing/index.md
- pages/services/confluent-kafka/2.0.1.1-3.3.0e/managing/index.md
- pages/services/confluent-kafka/2.0.2-3.3.0e/managing/index.md
- pages/services/confluent-kafka/2.0.3-3.3.1e/managing/index.md
- pages/services/confluent-kafka/v2.0.0.1-3.3.0e/managing/index.md
https://jira.mesosphere.com/browse/DOCS-2186
Original reported issue fixed. However, upon further investigation discovered problem near ubiquitous throughout not only other versions of Confluent-Kafka docs, but other relevant service docs that have 'Managing' sections and some that link back to their 'Managing' section from the 'Limitations' section.
The plan is to submit for approval after fixing the discovered related bugs.
> Docs 2186 - (PT 1)

- pages/1.9/installing/ent/custom/system-requirements/index.md
https://jira.mesosphere.com/browse/DOCS-2471
> For 1.9(ent) fixed broken URL

- pages/1.10/overview/architecture/node-types/index.md
- pages/1.11/overview/architecture/node-types/index.md
- pages/1.9/overview/architecture/node-types/index.md
https://jira.mesosphere.com/browse/DOCS-2229
> Added an important note as a call out

- pages/1.10/security/ent/index.md
- pages/1.11/security/ent/index.md
- pages/services/beta-confluent-kafka/confluent-auth/index.md
- pages/services/cassandra/cass-auth/index.md
- pages/services/confluent-kafka/kafka-auth/index.md
- pages/services/confluent-zookeeper/confluent-zookeeper-auth/index.md
- pages/services/elastic/elastic-auth/index.md
- pages/services/hdfs/hdfs-auth/index.md
- pages/services/jenkins/jenkins-auth/index.md
- pages/services/kafka-zookeeper/kafka-zookeeper-auth/index.md
- pages/services/kafka/2.0.4-1.0.0/kafka-auth/index.md
- pages/services/kafka/kafka-auth/index.md
- pages/services/marathon-lb/mlb-auth/index.md
- pages/services/spark/spark-auth/index.md
https://jira.mesosphere.com/browse/DCOS-20947
This corrects incorrect documentation about `dcos_anonymous`.
> [DCOS-20947] Correct documentation about `dcos_anonymous`

- pages/1.10/deploying-services/containerizers/index.md
- pages/1.10/security/ent/secrets/use-secrets/index.md
- pages/1.11/deploying-services/containerizers/index.md
- pages/1.11/security/ent/secrets/use-secrets/index.md
https://jira.mesosphere.com/browse/DOCS-2429
> Added the limitation note for file based secrets

- docker/nginx/redirects-301.map
https://jira.mesosphere.com/browse/DOCS-2480
> added ; in the end of the URL

- pages/1.11/installing/ent/custom/gui/index.md
https://jira.mesosphere.com/browse/DCOS-18371
> Changed the navigation title and title

- pages/1.11/installing/ent/custom/system-requirements/index.md
- pages/1.11/installing/oss/custom/system-requirements/index.md
- pages/services/confluent-kafka/2.1.0-4.0.0e/quick-start/index.md
- pages/services/dse/2.1.2-5.1.2/api-reference/index.md
- pages/services/dse/2.1.2-5.1.2/limitations/index.md
> installation updates

- pages/services/confluent-zookeeper/2.1.0-4.0.0e/managing/index.md
- pages/services/edge-lb/1.0/index.md
> corrections for Edge LB and Confluent zookeeper

- pages/services/jenkins/advanced-configuration/index.md
- pages/services/jenkins/custom-docker/index.md
- pages/services/jenkins/custom-install/index.md
- pages/services/jenkins/jenkins-auth/index.md
- pages/services/jenkins/quickstart/index.md
- pages/services/jenkins/script-template-job-dsl/index.md
- pages/services/jenkins/uninstall/index.md
- pages/services/jenkins/upgrade/index.md
> corrected Jenkins information related to strict mode

- pages/1.11/installing/ent/index.md
- pages/1.11/installing/oss/index.md
- pages/1.11/release-notes/open-source-attribution/index.md
- pages/1.11/release-notes/version-policy/index.md
https://jira.mesosphere.com/browse/DOCS-2482
> Changed section titles for 1.11 on doc site landing page

- ci/site/1-setup-env.sh
> Possible fix for libcurl failure.

- ci/pdf/1-setup-env.sh
> Fix for libcurl error for pdf build.

- pages/1.10/installing/ent/ports/index.md
- pages/1.10/installing/oss/ports/index.md
- pages/1.11/installing/ent/ports/index.md
- pages/1.11/installing/oss/cloud/index.md
- pages/1.11/installing/oss/custom/index.md
- pages/1.11/installing/oss/faq/index.md
- pages/1.11/installing/oss/high-availability/index.md
- pages/1.11/installing/oss/index.md
- pages/1.11/installing/oss/local/index.md
- pages/1.11/installing/oss/opt-out/index.md
- pages/1.11/installing/oss/ports/index.md
- pages/1.11/installing/oss/troubleshooting/index.md
- pages/1.9/installing/ent/ports/index.md
- pages/1.9/installing/oss/ports/index.md
- pages/services/edge-lb/1.0/release-notes/index.md
https://jira.mesosphere.com/browse/COPS-1989
> Added a note for port 123

- pages/1.11/installing/oss/cloud/index.md
- pages/1.11/installing/oss/custom/index.md
- pages/1.11/installing/oss/faq/index.md
- pages/1.11/installing/oss/high-availability/index.md
- pages/1.11/installing/oss/index.md
- pages/1.11/installing/oss/local/index.md
- pages/1.11/installing/oss/opt-out/index.md
- pages/1.11/installing/oss/ports/index.md
- pages/1.11/installing/oss/troubleshooting/index.md
- pages/services/edge-lb/1.0/release-notes/index.md
https://jira.mesosphere.com/browse/COPS-2888
> Marathon-LB and Edge-LB cannot be installed at the same time

- pages/1.11/deploying-services/gpu/index.md
> updated GPU information

- pages/1.10/tutorials/iot_pipeline/index.md
https://jira.mesosphere.com/browse/DOCS-2481
- [ X] High
> Moving draft into tutorial .md file.

- pages/1.10/tutorials/iot_pipeline/index.md
https://jira.mesosphere.com/browse/DOCS-2481
- [x ] High
> Smooth-out edits.

- pages/1.11/installing/oss/cloud/azure/index.md
> Azure bug fix

- ci/pdf/1-setup-env.sh
> Fix for build-pdf, Curl issue

- pages/1.10/installing/oss/custom/advanced/index.md
- pages/1.10/installing/oss/custom/cli/index.md
- pages/1.11/installing/oss/custom/advanced/index.md
- pages/1.11/installing/oss/custom/cli/index.md
- pages/1.9/installing/oss/custom/advanced/index.md
- pages/1.9/installing/oss/custom/cli/index.md
https://jira.mesosphere.com/browse/DOCS-2318
> Added oss tags and organized the heading hierarchy

- pages/services/beta-cassandra/1.0.32-3.0.14-beta/managing/index.md
- pages/services/beta-cassandra/2.1.0-3.0.15-beta/managing/index.md
- pages/services/beta-cassandra/2.1.1-3.0.15-beta/managing/index.md
- pages/services/beta-cassandra/2.1.2-3.0.15-beta/managing/index.md
- pages/services/beta-confluent-kafka/2.1.0-4.0.0e-beta/managing/index.md
- pages/services/beta-confluent-kafka/2.1.1-4.0.0e-beta/managing/index.md
- pages/services/beta-confluent-kafka/2.1.2-4.0.0e-beta/managing/index.md
- pages/services/beta-dse/2.1.0-5.1.2-beta/managing/index.md
- pages/services/beta-dse/2.1.2-5.1.2-beta/managing/index.md
- pages/services/beta-hdfs/2.1.1-2.6.0-cdh5.11.0-beta/install/index.md
https://jira.mesosphere.com/browse/COPS-2442
- [x ] High
> Fix for bcass and dse

- pages/1.9/release-notes/1.9.2/index.md
- pages/1.9/release-notes/1.9.3/index.md
- pages/1.9/release-notes/1.9.4/index.md
- pages/1.9/release-notes/1.9.5/index.md
- pages/1.9/release-notes/1.9.6/index.md
- pages/1.9/release-notes/1.9.8/index.md
Release notes for 1.9.8 - re-committing due to errors on #779 & addressed all comments on that PR.
> 1.9.8 Release Notes

- Makefile
- scripts/pandocpdf.sh
I am adding the Mesosphere style Latex. A fix for the images, as well as trying a utf-8 fix. 
Removing unused UTF8 script. 
> Style update

- pages/services/edge-lb/0.1/tutorials/blue-green-deploy/index.md
- pages/services/edge-lb/1.0/tutorials/blue-green-deploy/index.md
> Moved docker images to Mesosphere org.

- pages/1.11/installing/oss/custom/system-requirements/index.md
- pages/1.7/administration/installing/oss/custom/system-requirements/index.md
- pages/1.8/administration/installing/oss/custom/system-requirements/index.md
- pages/1.9/installing/oss/custom/system-requirements/index.md
https://jira.mesosphere.com/browse/DCOS_SITE-304
> Removed ent tag.

- pages/services/edge-lb/1.0/release-notes/index.md
https://jira.mesosphere.com/browse/COPS-2888
> Updated a new entry under "known issues" section

- pages/1.11/hybrid-cloud/features/capacity-extension-with-regions/index.md
- pages/1.11/hybrid-cloud/features/cluster-links/index.md
- pages/1.11/hybrid-cloud/features/decommission-nodes/index.md
- pages/1.11/hybrid-cloud/features/fault-domain-awareness-with-zones/index.md
- pages/1.11/hybrid-cloud/features/index.md
- pages/1.11/hybrid-cloud/index.md
Added a new page for Hybrid cloud features.
> Added a new page for Hybrid cloud features.

- assets/opensearch.xml
> Add whitespace to XML search definition.

- assets/opensearch.xml
> fix search query template

- pages/1.7/administration/installing/oss/custom/cli/index.md
- pages/1.8/administration/installing/oss/custom/cli/index.md
https://jira.mesosphere.com/browse/DOCS-2318
> Added oss tags for CLI install guide - 1.7 and 1.8

- assets/opensearch.xml
> Reconfigure XML.

- pages/1.11/installing/ent/custom/system-requirements/index.md
- pages/1.11/installing/oss/custom/system-requirements/index.md
https://jira.mesosphere.com/browse/DOCS-2487
> Document installing DC/OS to separate volume

- pages/1.10/installing/ent/custom/uninstall/index.md
- pages/1.10/installing/oss/custom/uninstall/index.md
- pages/1.11/installing/ent/custom/uninstall/index.md
- pages/1.11/installing/oss/custom/uninstall/index.md
- pages/1.7/administration/installing/ent/custom/uninstall/index.md
- pages/1.7/administration/installing/oss/custom/uninstall/index.md
- pages/1.8/administration/installing/ent/custom/uninstall/index.md
- pages/1.8/administration/installing/oss/custom/uninstall/index.md
- pages/1.9/installing/ent/custom/uninstall/index.md
- pages/1.9/installing/oss/custom/uninstall/index.md
This updates some ticket links that point to the old Jira instance.
> Update ticket links

- pages/services/spark/2.3.0-2.2.1-2/usage-examples/index.md
https://jira.mesosphere.com/browse/DCOS_SITE-303
> Fix broken link by changing path.

- pages/services/confluent-kafka/2.2.0-4.0.0e/api-reference/index.md
- pages/services/confluent-kafka/2.2.0-4.0.0e/common-operations/index.md
- pages/services/confluent-kafka/2.2.0-4.0.0e/connecting-clients/index.md
- pages/services/confluent-kafka/2.2.0-4.0.0e/diagnostic-tools/index.md
- pages/services/confluent-kafka/2.2.0-4.0.0e/index.md
- pages/services/confluent-kafka/2.2.0-4.0.0e/install/index.md
- pages/services/confluent-kafka/2.2.0-4.0.0e/limitations/index.md
- pages/services/confluent-kafka/2.2.0-4.0.0e/managing/index.md
- pages/services/confluent-kafka/2.2.0-4.0.0e/overview/index.md
- pages/services/confluent-kafka/2.2.0-4.0.0e/quick-start/index.md
- pages/services/confluent-kafka/2.2.0-4.0.0e/release-notes/index.md
- pages/services/confluent-kafka/2.2.0-4.0.0e/security/index.md
- pages/services/confluent-kafka/2.2.0-4.0.0e/supported-versions/index.md
- pages/services/confluent-kafka/2.2.0-4.0.0e/troubleshooting/index.md
- pages/services/confluent-kafka/2.2.0-4.0.0e/uninstall/index.md
- pages/services/confluent-kafka/2.2.0-4.0.0e/upgrade/index.md
Document new security features
> Add release notes for confluent-kafka 2.2.0-4.0.0e

- pages/services/kafka/2.2.0-1.0.0/api-reference/index.md
- pages/services/kafka/2.2.0-1.0.0/common-operations/index.md
- pages/services/kafka/2.2.0-1.0.0/connecting-clients/index.md
- pages/services/kafka/2.2.0-1.0.0/diagnostic-tools/index.md
- pages/services/kafka/2.2.0-1.0.0/index.md
- pages/services/kafka/2.2.0-1.0.0/install/index.md
- pages/services/kafka/2.2.0-1.0.0/limitations/index.md
- pages/services/kafka/2.2.0-1.0.0/managing/index.md
- pages/services/kafka/2.2.0-1.0.0/overview/index.md
- pages/services/kafka/2.2.0-1.0.0/quick-start/index.md
- pages/services/kafka/2.2.0-1.0.0/release-notes/index.md
- pages/services/kafka/2.2.0-1.0.0/security/index.md
- pages/services/kafka/2.2.0-1.0.0/supported-versions/index.md
- pages/services/kafka/2.2.0-1.0.0/troubleshooting/index.md
- pages/services/kafka/2.2.0-1.0.0/uninstall/index.md
- pages/services/kafka/2.2.0-1.0.0/upgrade/index.md
> Add documentation of new Kafka feature: custom domain for security

- pages/services/percona-mongo/0.2.0-3.4.13/api-reference/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/connecting-clients/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/deploy-best-practice/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/disaster-recovery/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/install/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/known-issues/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/limitations/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/managing/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/mongodb-administration/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/quick-start/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/release-notes/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/support/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/terms-of-use/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/troubleshooting/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/uninstall/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/upgrade/index.md
> Layout changes

- pages/1.11/cli/command-reference/dcos-edgelb/index.md
Issue raised by Daniel Mennell on documentation channel on Slack.
> Fixed 404 error for 1.11/cli/command-reference/dcos-edgelb.

- pages/services/cassandra/2.0.3-3.0.14/install/index.md
https://jira.mesosphere.com/browse/DCOS_SITE-287
- [ x] Blocker 
> Modify relevant code sample. Testing formatting.

- pages/services/percona-mongo/0.2.0-3.4.13/api-reference/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/connecting-clients/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/deploy-best-practice/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/disaster-recovery/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/install/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/limitations/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/managing/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/mongodb-administration/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/quick-start/index.md
- pages/services/percona-mongo/0.2.0-3.4.13/support/index.md
- pages/services/percona-mongo/index.md
> Dcos site 319

- pages/services/percona-mongo/0.2.0-3.4.13/disaster-recovery/index.md
> Correcting the backup plan name, it is 'backup-s3' not 'backup'. (#38)

- ci/pdf/6-jenkins-build-changes.sh
> Deleting line to find later scripts

- ci/pdf/0-commit-hook.sh
- ci/pdf/6-jenkins-build-changes.sh
- docker/docker-compose.production.yml
- pages/1.8/administration/id-and-access-mgt/index.md
- templates/mesosphere.latex
> Inserting env. variable in yaml config file

- pages/services/spark/2.3.1-2.2.1-1/release-notes/index.md
> Version mention

- ci/pdf/0-commit-hook.sh
- ci/pdf/6-jenkins-build-changes.sh
> Pdf improvement

- ci/pdf/6-jenkins-build-changes.sh
> Changing the env bash since it is somewhere different

- ci/pdf/0-commit-hook.sh
- scripts/build-pdf.sh
> Changing the variable from stage in the process of the docker compose

- docker/docker-compose.production.yml
- scripts/build-pdf.sh
> Passing LOG directly inline in the docker-compose instruction

- pages/services/spark/2.3.0-2.2.1-2/index.md
- pages/services/spark/2.3.1-2.2.1-1/release-notes/index.md
https://jira.mesosphere.com/browse/RELEASE-815
- [X ] High
> Release 815

- pages/services/spark/2.3.1-2.2.1-2/release-notes/index.md
> version change in release notes.

- pages/services/spark/2.3.1-2.2.1-2/release-notes/index.md
> Fix link to limits page by updating version ref in path.

- pages/services/spark/2.3.1-2.2.1-2/limits/index.md
https://jira.mesosphere.com/browse/DOCS-2505
- [x ] Medium
> Adjust MD for docs-site build.

- pages/services/marathon-lb/advanced/index.md
- pages/services/marathon-lb/release-notes/index.md
- pages/services/marathon-lb/usage-oss/index.md
This should not be merged until Marathon-LB 1.12 is released.
> Update template guide and add release notes

- pages/1.11/installing/ent/upgrading/index.md
> Corrected Mesos version COPS-1828

- docker/Dockerfile.htmltopdf
> removing concat at the end, not needed

- pages/1.10/metrics/prometheus/index.md
- pages/1.11/metrics/prometheus/index.md
- pages/1.9/metrics/prometheus/index.md
[DCOS-22016](https://jira.mesosphere.com/browse/DCOS-22016) - Update prometheus documentation
> Improve Prometheus documentation

- pages/1.10/metrics/datadog/index.md
- pages/1.10/metrics/metrics-api/index.md
- pages/1.10/metrics/prometheus/index.md
- pages/1.10/metrics/quickstart/index.md
- pages/1.11/metrics/datadog/index.md
- pages/1.11/metrics/index.md
- pages/1.11/metrics/metrics-api/index.md
- pages/1.11/metrics/quickstart/index.md
- pages/1.11/metrics/reference/index.md
- pages/1.9/metrics/datadog/index.md
- pages/1.9/metrics/metrics-api/index.md
- pages/1.9/metrics/prometheus/index.md
- pages/1.9/metrics/quickstart/index.md
- [DCOS-21965](https://jira.mesosphere.com/browse/DCOS-21965) - Clarify dcos-metrics role and routes in documentation
> Clarify dcos-metrics role and routes

- docker/Dockerfile.htmltopdf
- scripts/build-pdf.sh
- scripts/mdtopdf.sh
> Reducing Texlive install and packages from 45 mins to 10.

- pages/1.11/release-notes/1.11.0-rc1/index.md
- pages/1.11/release-notes/1.11.0-rc4/index.md
- pages/1.11/release-notes/1.11.0/index.md
- pages/1.11/release-notes/1.11.1/index.md
> 1.11.1 Release Notes

- docker/Dockerfile.test
- docker/docker-compose.test.yml
- scripts/mdtopdf.sh
> Fixing broken function

- docker/Dockerfile.htmltopdf
> Adding curl to download packages

- scripts/mdtopdf.sh
> Fixing download of AWS file

- scripts/mdtopdf.sh
> Changes to tgz file download

- scripts/mdtopdf.sh
> Commiting changes for the folder

- scripts/mdtopdf.sh
> CHanges to make directory

- pages/1.11/release-notes/1.11.1/index.md
> Changed title for "Issues Fixed" section based on docs team feedback.

- pages/1.11/release-notes/1.11.1/index.md
Added DCOS-22128.
Removed DCOS-19586.
> Added "Known Issues" section in 1.11.1 RN

- pages/1.11/release-notes/1.11.1/index.md
> Renamed Known Issues and Limitation section in 1.11.1 RN

- scripts/mdtopdf.sh
> Checking what it's the current output folder

- scripts/mdtopdf.sh
> Saving to another folder

- scripts/mdtopdf.sh
> Moving output folders

- scripts/mdtopdf.sh
> Fixing clean function

- pages/version-policy/index.md
https://jira.mesosphere.com/browse/DOCS-2517
> Added 17.06 to RHEL 7.4 docker to compatibility matrix.

- pages/1.10/installing/oss/custom/system-requirements/index.md
- pages/1.11/installing/oss/custom/system-requirements/index.md
> COPS-2519 Removing broken links to shell script.

- scss/base/_content.scss
[Jira issue](https://jira.mesosphere.com/browse/DCOS_SITE-289)
> Overflow of text is now fixed. Fix #519

- scss/components/_grid-toc.scss
[Jira issue](https://jira.mesosphere.com/browse/DCOS_SITE-290)
> Fix #332. Titles now wrap instead of cut

- pages/1.10/installing/oss/custom/system-requirements/install-docker-centos/index.md
https://jira.mesosphere.com/browse/DCOS_SITE-284
> Updated docker version mapping to the version policy page in step 8.

- pages/version-policy/index.md
https://jira.mesosphere.com/browse/DOCS-2520
> Added Docker EE/CE 17.06 in RHEL 7.4 row.

- pages/version-policy/index.md
https://jira.mesosphere.com/browse/DOCS-2524
> Added new entry for CentOS 7.4 in 1.11

- pages/1.10/release-notes/1.10.4/index.md
- pages/1.10/release-notes/1.10.5/index.md
- pages/1.10/release-notes/1.10.6/index.md
Finalized 1.10.6 Release Notes.
> 1.10.6 Release Notes

- pages/1.10/release-notes/1.10.6/index.md
> Changed the Metronome link

- pages/1.10/release-notes/1.10.6/index.md
> Change log added for 1.10.6 RN

- layouts/components/content-actions.pug
> fix JIRA generation for documentation ticket

- docker/nginx/redirects-301.map
> Add redirect for logging v1 and v2 merge to one.

- docker/nginx/redirects-301.map
> Syntax fix in redirect file.

- pages/services/kafka/2.3.0-1.0.0/index.md
- pages/services/kafka/2.3.0-1.0.0/ordr_0-getting-started/index.md
- pages/services/kafka/2.3.0-1.0.0/ordr_1-configuration/index.md
- pages/services/kafka/2.3.0-1.0.0/ordr_10-support-policy/index.md
- pages/services/kafka/2.3.0-1.0.0/ordr_11-release-notes/index.md
- pages/services/kafka/2.3.0-1.0.0/ordr_2-operations/index.md
- pages/services/kafka/2.3.0-1.0.0/ordr_3-updates/index.md
- pages/services/kafka/2.3.0-1.0.0/ordr_4-security/index.md
- pages/services/kafka/2.3.0-1.0.0/ordr_5-uninstall/index.md
- pages/services/kafka/2.3.0-1.0.0/ordr_6-troubleshooting/index.md
- pages/services/kafka/2.3.0-1.0.0/ordr_7-advanced/index.md
- pages/services/kafka/2.3.0-1.0.0/ordr_8-api-reference/index.md
- pages/services/kafka/2.3.0-1.0.0/ordr_9-limitations/index.md
> Initial docs for Kafka 2.3.0-1.1.1.

- pages/1.11/deploying-services/fault-domain-awareness/index.md
> Adjust format for readability.

- pages/services/kafka/kafka-auth/index.md
https://jira.mesosphere.com/browse/COPS-2197
> COPS-2197 Change service_account_name to service_account_secret

- pages/services/confluent-zookeeper/index.md
- pages/services/kafka-zookeeper/index.md
> Fix ZooKeeper landing pages

- pages/services/edge-lb/1.0/pool-configuration/v2-examples/index.md
> Fixed typo for port number.

- pages/1.11/deploying-services/gpu/index.md
> Update GPU AMIs (Going with changelog for other to GPU AMI regions here.)

- scripts/mdtopdf.sh
> trying new commit

- docker/nginx/redirects-301.map
- pages/1.11/installing-upgrading/custom/index.md
> 1.11 install and upgrade pages - fixed redirects

- docker/nginx/redirects-301.map
> Fixed redirect issue for old installing

- pages/1.10/installing/ent/custom/system-requirements/index.md
- pages/1.11/installing-upgrading/custom/system-requirements/index.md
- pages/1.9/installing/ent/custom/system-requirements/index.md
https://jira.mesosphere.com/browse/COPS-3214
Updated content for master nodes for 1.9, 1.10 and 1.11.
> Updated content for master nodes

- docker/nginx/redirects-301.map
> Redirected custom advanced installer link to point to latest (1.11)

- pages/1.10/security/ent/users-groups/reset-superuser/index.md
- pages/1.11/security/ent/users-groups/reset-superuser/index.md
https://jira.mesosphere.com/browse/DCOS-34465
> Make it clear that you can use multiple methods to SSH to a master node.

- docker/nginx/redirects-301.map
> Redirects for /custom/advanced/

- pages/1.11/administering-clusters/multiple-clusters/cluster-link-api/index.md
> Fixed broken link

- pages/version-policy/index.md
https://jira.mesosphere.com/browse/DCOS-34546
> Updated compatibility matrix on Version Policy page

- pages/1.11/overview/architecture/node-types/index.md
- pages/1.11/overview/what-is-dcos/index.md
https://jira.mesosphere.com/browse/DCOS-25822
> Fixing Overview excerpts

- pages/1.11/administering-clusters/securing-your-cluster/index.md
- pages/1.11/overview/architecture/components/index.md
> Fixing title cards DCOS-25822

- pages/1.11/metrics/datadog/index.md
- pages/1.11/metrics/index.md
- pages/1.11/metrics/metrics-api/index.md
- pages/1.11/metrics/prometheus/index.md
- pages/1.11/metrics/quickstart/index.md
- pages/1.11/metrics/reference/index.md
https://jira.mesosphere.com/browse/DCOS-35754
- Change all affected versions (**only 1.11 docs affected**).
> DCOS-35754 Removing Beta tags from Metrics docs

- pages/services/confluent-kafka/2.3.0-4.0.0e/index.md
- pages/services/confluent-kafka/2.3.0-4.0.0e/ordr_0-getting-started/index.md
- pages/services/confluent-kafka/2.3.0-4.0.0e/ordr_1-configuration/index.md
- pages/services/confluent-kafka/2.3.0-4.0.0e/ordr_10-support-policy/index.md
- pages/services/confluent-kafka/2.3.0-4.0.0e/ordr_11-release-notes/index.md
- pages/services/confluent-kafka/2.3.0-4.0.0e/ordr_2-operations/index.md
- pages/services/confluent-kafka/2.3.0-4.0.0e/ordr_3-updates/index.md
- pages/services/confluent-kafka/2.3.0-4.0.0e/ordr_4-security/index.md
- pages/services/confluent-kafka/2.3.0-4.0.0e/ordr_5-uninstall/index.md
- pages/services/confluent-kafka/2.3.0-4.0.0e/ordr_6-troubleshooting/index.md
- pages/services/confluent-kafka/2.3.0-4.0.0e/ordr_7-advanced/index.md
- pages/services/confluent-kafka/2.3.0-4.0.0e/ordr_8-api-reference/index.md
- pages/services/confluent-kafka/2.3.0-4.0.0e/ordr_9-limitations/index.md
https://jira.mesosphere.com/browse/DCOS-29241
> Docs for confluent-kafka 2.3.0-4.0.0e.

- pages/services/beta-storage/0.2.0-beta/architecture/index.md
- pages/services/beta-storage/0.2.0-beta/index.md
- pages/services/beta-storage/0.2.0-beta/install/index.md
- pages/services/beta-storage/0.2.0-beta/release-notes/index.md
- pages/services/beta-storage/0.2.0-beta/terminology-and-concepts/index.md
- pages/services/beta-storage/0.2.0-beta/tutorials/index.md
- pages/services/beta-storage/0.2.0-beta/uninstall/index.md
- pages/services/beta-storage/0.2.0-beta/upgrades/index.md
- pages/services/beta-storage/0.2.0-beta/volume-plugins/index.md
https://jira.mesosphere.com/browse/DCOS-35738
> storage: update storage doc for 0.2.0

- pages/services/beta-storage/0.1.0-beta/index.md
"Overview" in the nav bar isn't a good experience for readers. Tweak the nav text to align w/ the auto-generated nav text that we're using for DSS 0.2.0+
> dss: tweak nav for 0.1.0 docs

- pages/1.11/tutorials/dcos-debug/index.md
> Switch paragraph order at the introduction.

- pages/1.10/administering-clusters/replacing-a-master-node/index.md
- pages/1.11/administering-clusters/replacing-a-master-node/index.md
https://jira.mesosphere.com/browse/DOCS-2470
> administering-clusters/replacing-a-master-node: add initial instructions

- pages/version-policy/index.md
https://jira.mesosphere.com/browse/DCOS-34546
> Removed CoreOS 1688.5.3 entry.

- pages/1.11/tutorials/dcos-debug/index.md
> Small change.

- pages/1.7/usage/registry/index.md
> Minor editing change.

- pages/1.11/release-notes/1.11.2/index.md
> Minor Edits on 1.11.2 RN

- pages/1.11/networking/SDN/index.md
- pages/1.11/networking/load-balancing-vips/index.md
- pages/1.11/networking/load-balancing-vips/virtual-ip-addresses/index.md
- pages/1.11/security/ent/restrict-service-access/index.md
> DCOS-26632 Fixing Networking titles

- pages/1.11/installing/ent/custom/configuration/examples/index.md
- pages/1.11/installing/oss/custom/configuration/examples/index.md
> Fixed formatting issues in 1.11

- pages/1.10/release-notes/1.10.0-beta1/index.md
- pages/1.10/release-notes/1.10.0-beta2/index.md
- pages/1.10/release-notes/1.10.2/index.md
- pages/1.10/release-notes/1.10.3/index.md
- pages/1.10/release-notes/1.10.4/index.md
- pages/1.10/release-notes/1.10.5/index.md
- pages/1.10/release-notes/1.10.7/index.md
> 1.10.7 Release Notes

- pages/services/nifi/0.1.0-1.5.0/diagnostictools/index.md
- pages/services/nifi/0.1.0-1.5.0/index.md
- pages/services/nifi/0.1.0-1.5.0/overview/index.md
- pages/services/nifi/0.1.0-1.5.0/release-notes/index.md
- pages/services/nifi/0.1.0-1.5.0/supported-versions/index.md
- pages/services/nifi/0.2.0-1.5.0/api-reference/index.md
- pages/services/nifi/0.2.0-1.5.0/command-reference/index.md
- pages/services/nifi/0.2.0-1.5.0/diagnostictools/index.md
- pages/services/nifi/0.2.0-1.5.0/index.md
- pages/services/nifi/0.2.0-1.5.0/install/index.md
- pages/services/nifi/0.2.0-1.5.0/limitations/index.md
- pages/services/nifi/0.2.0-1.5.0/managing/index.md
- pages/services/nifi/0.2.0-1.5.0/overview/index.md
- pages/services/nifi/0.2.0-1.5.0/release-notes/index.md
- pages/services/nifi/0.2.0-1.5.0/security/index.md
- pages/services/nifi/0.2.0-1.5.0/supported-versions/index.md
- pages/services/nifi/0.2.0-1.5.0/troubleshooting/index.md
- pages/services/nifi/0.2.0-1.5.0/uninstall/index.md
- pages/services/nifi/index.md
https://jira.mesosphere.com/browse/DCOS-37545
> DCOS-37545 Correcting nav titles, formatting, removed TOC.

- pages/1.10/release-notes/1.10.7/index.md
> Added timestamp on 1.10.7 RN

- pages/1.10/release-notes/1.10.7/index.md
> Added a new entry for COPS-3195 in 1.10.7 RN

- pages/1.10/deploying-services/faq/index.md
- pages/1.11/deploying-services/faq/index.md
- pages/1.9/deploying-services/faq/index.md
https://jira.mesosphere.com/browse/DCOS-25697
> DCOS25697 Deleting FAQ about adding Mesos roles for a node

- pages/1.10/installing/ent/custom/configuration/configuration-parameters/index.md
- pages/1.10/installing/oss/custom/configuration/configuration-parameters/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-2416
> DCOS_OSS-2416 corrections to /ent/ and /oss/ examples dns_forward_zones

- pages/1.11/installing/oss/cloud/azure/index.md
Documentation updates for Azure.
https://jira.mesosphere.com/browse/DCOS_SITE-291
> Add Azure recommendations for OSS

- pages/1.7/index.md
- pages/1.7/open-source-attribution/index.md
> Updating metadata

- scripts/mdtopdf.sh
> changes to last succ. build

- pages/1.11/deploying-services/containerizers/ucr/index.md
Reverts mesosphere/dcos-docs-site#1044
> Revert "Update index.md"

- scripts/mdtopdf.sh
> Formal solution for job date

- scripts/mdtopdf.sh
> Deleting the groovy line, no longer needed

- scripts/mdtopdf.sh
> Cleaning up the scripts from variables it no longer needs

- pages/1.11/storage/external-storage/index.md
Also, group together EBS caveats for greater clarity
> Add pitfall note about 13 volume limitation with EBS / REX-Ray

- ci/pdf/0-commit-hook.sh
> Testing how to catch unbound vars

- ci/pdf/0-commit-hook.sh
> turning off one var

- docker/nginx/redirects-301.map
> Deleted wrong entry

- docker/nginx/redirects-301.map
> Added a missed semicolon.

- docker/nginx/redirects-301.map
> Deleted duplicate entry.

- ci/pdf/3-extract-pdf-bundle.sh
> Turning off a debug

- pages/1.10/installing/ent/custom/cli/index.md
- pages/1.10/installing/ent/custom/system-requirements/index.md
- pages/1.10/installing/oss/custom/cli/index.md
- pages/1.10/installing/oss/custom/system-requirements/index.md
- pages/1.11/installing/ent/custom/cli/index.md
- pages/1.11/installing/ent/custom/system-requirements/index.md
- pages/1.11/installing/oss/custom/cli/index.md
- pages/1.11/installing/oss/custom/system-requirements/index.md
https://jira.mesosphere.com/browse/COPS-1971
> Removed odd lines from System requirements document in 1.10

- pages/1.11/installing/ent/custom/gui/index.md
- pages/1.11/installing/oss/custom/gui/index.md
> Change navigation title in GUI Installer.

- pages/1.10/installing/ent/troubleshooting/index.md
- pages/1.10/installing/oss/troubleshooting/index.md
- pages/1.11/installing/ent/troubleshooting/index.md
- pages/1.11/installing/oss/troubleshooting/index.md
- pages/1.8/administration/installing/ent/custom/troubleshooting/index.md
- pages/1.8/administration/installing/oss/custom/troubleshooting/index.md
- pages/1.9/installing/ent/troubleshooting/index.md
- pages/1.9/installing/oss/troubleshooting/index.md
https://jira.mesosphere.com/browse/COPS-2995
> COPS-2995 Replaced Spartan references with dcos-net

- pages/1.11/api/logs2.yaml
> changed to sync with logs repo api yaml

- pages/1.10/installing/ent/custom/advanced/index.md
- pages/1.10/installing/oss/custom/advanced/index.md
https://jira.mesosphere.com/browse/COPS-1967
> Changed the AWS DNS server IP in resolver section of config.yaml file

- pages/1.10/installing/high-availability/index.md
- pages/1.10/installing/oss/cloud/azure/index.md
- pages/1.10/installing/oss/high-availability/index.md
- pages/1.10/overview/high-availability/index.md
- pages/1.11/installing/oss/cloud/azure/index.md
- pages/1.11/installing/oss/high-availability/index.md
- pages/1.8/administration/installing/ent/cloud/aws/upgrading/index.md
- pages/1.8/administration/installing/oss/cloud/aws/upgrading/index.md
- pages/1.8/administration/upgrading/index.md
- pages/1.8/development/cli-spec/index.md
- pages/1.8/overview/high-availability/index.md
- pages/1.9/developing-services/cli-spec/index.md
- pages/1.9/installing/oss/cloud/azure/index.md
- pages/1.9/overview/high-availability/index.md
> Renamed the occurrence of "document" with "page" in 1.10, 1.9, 1.8

- docker/nginx/redirects-301.map
> Postfixed a forward slash.

- docker/nginx/redirects-301.map
> Added a space between the paths in line 167 and 169

- docker/nginx/redirects-301.map
> Deleted entry in row # 217.

- docker/nginx/redirects-301.map
> Deleted entry in row # 231.

- docker/nginx/redirects-301.map
> Deleted entry in row # 239.

- ci/pdf/0-commit-hook.sh
> checking for the var in a different way

- scripts/genpdf.js
> trivial for CI

- docker/nginx/redirects-301.map
> Used wildcards for 1.10 virtual-networks entries.

- docker/nginx/redirects-301.map
> Deleted duplicated entry.

- pages/1.10/installing/ent/custom/advanced/index.md
- pages/1.11/installing/ent/custom/advanced/index.md
https://jira.mesosphere.com/browse/COPS-1850
> Updated filename path in ent files for 1.11 and 1.10.

- docker/nginx/redirects-301.map
> Added entries for 1.10 patching pages

- docker/nginx/redirects-301.map
> Added a redirect for 1.10 ent custom installation

- docker/nginx/redirects-301.map
> Added a redirect for ENT upgrading.

- pages/1.11/administering-clusters/multiple-clusters/cluster-connections/index.md
- pages/1.11/administering-clusters/multiple-clusters/cluster-link-api/index.md
- pages/1.11/administering-clusters/multiple-clusters/cluster-links/index.md
- pages/1.11/administering-clusters/multiple-clusters/index.md
https://jira.mesosphere.com/browse/COPS-2016
Fixing typos on cluster-links pages.
> ss/DOCS-2016 Fixing typos on cluster link page

- pages/services/edge-lb/1.0/release-notes/index.md
> Adds v1.0.3 release notes

- pages/1.10/monitoring/logging/logging-api-examples/index.md
- pages/1.11/monitoring/logging/logging-api/index.md
- pages/1.9/monitoring/logging/logging-api-examples/index.md
https://jira.mesosphere.com/browse/COPS-2174
> COPS-2174 Replacing code snippet for journald substitute

- pages/services/marathon-lb/mlb-auth/index.md
> Use proper terminology for Marathon-LB service account configuration.

- pages/services/nifi/0.2.0-1.5.0/connecting-clients/index.md
- pages/services/nifi/0.2.0-1.5.0/install/index.md
- pages/services/nifi/0.2.0-1.5.0/release-notes/index.md
Git issue :
https://github.com/mesosphere/LCM/issues/5
> changing web to node endpoint

- pages/services/beta-confluent-kafka-zookeeper/index.md
- pages/services/beta-kafka-zookeeper/index.md
- pages/services/beta-storage/index.md
- pages/services/nifi/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-3612
Re-ordered/alphabetized Service docs landing page. Menu weights adjusted; beta documents sorted alphabetically at bottom.
> DCOS_OSS-3612 Re-ordering Service docs landing page

- pages/1.10/installing/ent/patching/index.md
- pages/1.10/installing/oss/patching/index.md
- pages/1.11/installing/ent/patching/index.md
- pages/1.11/installing/oss/patching/index.md
- pages/1.9/installing/ent/patching/index.md
- pages/1.9/installing/oss/patching/index.md
> Added upgrading link in patching page for 1.9 1.10 and 1.11.

- pages/services/kubernetes/1.1.1-1.10.4/connecting-clients/index.md
- pages/services/kubernetes/1.1.1-1.10.4/exposing-the-kubernetes-api/index.md
- pages/services/kubernetes/1.1.1-1.10.4/release-notes/index.md
Signed-off-by: Bruno Custodio <bcustodio@mesosphere.io>
> docs: update kubernetes 1.1.1-1.10.4 docs

- js/sidebar.js
[Jira issue](https://jira.mesosphere.com/browse/DCOS_SITE-288)
> Navigation searches for version match

- scss/base/_content.scss
[JIRA issue](https://jira.mesosphere.com/browse/DCOS_SITE-285)
Should fix #368 issues with sizes. 
> Docs image size

- scss/components/_prism.scss
- scss/vendor/_ngindox.scss
[Jira issue](https://jira.mesosphere.com/browse/DCOS_SITE-282)
> In line code wrapping

- pages/services/edge-lb/1.0/usage/index.md
https://jira.mesosphere.com/browse/COPS-3337
Added a section to Usage on how to relocate a pool when a node goes down.
> ss/COPS-3337 Adding info to Usage on how to replace a failed pod.

- pages/services/cassandra/data.yml
- pages/services/confluent-kafka/data.yml
- pages/services/dse/data.yml
- pages/services/hdfs/data.yml
- pages/services/include/security-configure-transport-encryption.tmpl
- pages/services/kafka/data.yml
- pages/services/nifi/data.yml
> Fix transport encryption formatting

- pages/services/cassandra/2.2.0-3.0.16/ordr_1-configuration/index.md
> Added content relating to sidecar CPU usage

- pages/1.11/deploying-services/marathon-constraints/index.md
> Fix the name of attribute.

- pages/1.11/security/ent/ldap/ldap-auth/index.md
Fixing display error in one page of the 1.11/security/ent/ldap directory. No other pages or versions affected. Corrected excerpt in metadata and added nav title so that it will display.
> DCOS-26632 Fixing display error in 1.11/security/ent/ldap doc

- pages/1.10/release-notes/1.10.0/index.md
- pages/1.10/release-notes/1.10.1/index.md
- pages/1.10/release-notes/1.10.2/index.md
- pages/1.10/release-notes/1.10.3/index.md
- pages/1.10/release-notes/1.10.4/index.md
- pages/1.10/release-notes/1.10.5/index.md
- pages/1.10/release-notes/1.10.6/index.md
- pages/1.10/release-notes/1.10.7/index.md
- pages/1.11/release-notes/1.11.0/index.md
- pages/1.11/release-notes/1.11.1/index.md
- pages/1.11/release-notes/1.11.2/index.md
- pages/1.9/release-notes/1.9.0/index.md
- pages/1.9/release-notes/1.9.1/index.md
- pages/1.9/release-notes/1.9.2/index.md
- pages/1.9/release-notes/1.9.3/index.md
- pages/1.9/release-notes/1.9.4/index.md
- pages/1.9/release-notes/1.9.5/index.md
- pages/1.9/release-notes/1.9.6/index.md
- pages/1.9/release-notes/1.9.7/index.md
- pages/1.9/release-notes/1.9.8/index.md
https://docs.google.com/document/d/1Lx2QXLpXpZa8--jkzkmdmNgH-RoTR_3l2U_VXjZpqzA/edit
The release dates are documented and embedded in the release notes based on information (GA announcement emails and gSheets) provided by release and support teams. 
> Embedded release dates for release notes across different versions.

- pages/1.11/installing/ent/upgrading/index.md
Added note regarding disabling event subscriber(s). We've had some customers asking about this and it was not clear how to check this and if needed how to disable this.
- Test all commands and procedures. Procedure has been tested.
- Change all affected versions (Add notes to 1.9 docs and remove from 1.10, 1.11 docs).
> Add note re. event subscriber disabling

- pages/services/kubernetes/1.0.0-1.9.3/cni/index.md
- pages/services/kubernetes/1.0.1-1.9.4/cni/index.md
- pages/services/kubernetes/1.0.2-1.9.6/cni/index.md
- pages/services/kubernetes/1.0.3-1.9.7/cni/index.md
- pages/services/kubernetes/1.1.0-1.10.3/cni/index.md
- pages/services/kubernetes/1.1.1-1.10.4/cni/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-3663
Correcting grammar mistake in all versions of Kubernetes /cni/ docs.
> DCOS_OSS-3663 Correcting grammar in cni doc

- pages/1.11/installing/oss/custom/system-requirements/index.md
https://jira.mesosphere.com/browse/DCOS-38444
> Updated master node table on 1.11 System Requirements page

- pages/1.8/administration/installing/oss/custom/system-requirements/index.md
- pages/1.9/installing/oss/custom/system-requirements/index.md
https://jira.mesosphere.com/browse/COPS-3297
> Changed DCOS setup file URL for 1.8 and 1.9

- pages/1.11/installing/ent/custom/advanced/index.md
- pages/1.11/installing/oss/custom/advanced/index.md
https://jira.mesosphere.com/browse/COPS-1967
> 1.11 - Changed the AWS DNS server IP in resolver section of config.yaml file.

- pages/version-policy/index.md
> Change Docker versions in compatibility matrix. 

- pages/1.11/tutorials/dcos-debug/gen-strat/index.md
> trivial change for flush

- pages/1.11/tutorials/dcos-debug/gen-strat/index.md
> trivial change to flush pipeline

- pages/1.11/tutorials/dcos-debug/gen-strat/index.md
> flush again

- pages/1.7/overview/design/installation/index.md
> Small check fix

- pages/1.10/installing/oss/custom/configuration/configuration-parameters/index.md
- pages/1.11/installing/oss/custom/configuration/configuration-parameters/index.md
- pages/1.9/installing/oss/custom/configuration/configuration-parameters/index.md
https://jira.mesosphere.com/browse/DCOS-25737
Added statement re TCP mode to configuration docs for 1.9, 1.10 and 1.11
> DCOS-25737 Added note to configuration parameters

- pages/1.10/administering-clusters/deploying-a-local-dcos-universe/index.md
- pages/1.11/administering-clusters/deploying-a-local-dcos-universe/index.md
- pages/1.9/administering-clusters/deploying-a-local-dcos-universe/index.md
https://jira.mesosphere.com/browse/COPS-1837
Added link and text to step 27 of /administering-clusters/deploying-a-local-dcos-universe/#installing-your-own-set-of-universe-packages to inform users how to resolve `master.mesos`. Changed in docs for 1.9, 1.10 and 1.11.
> COPS-1837 Added link to FAQ re resolving master.mesos

- pages/version-policy/index.md
https://jira.mesosphere.com/browse/COPS-3369
> Fixed URLs.

- index.js
- package.json
- plugins/metalsmith-include-content-dcos.js
Starts to fix [DCOS_OSS-3737](https://jira.mesosphere.com/browse/DCOS_OSS-3737).
The watch pipeline was broken. This pull fixes it and adds some comments to the relevant files for later work.
> Fix broken watch pipeline for md and tmpl files.

- pages/1.11/release-notes/1.11.3/index.md
https://jira.mesosphere.com/browse/COPS-3468
> Changed Apache Mesos version in 1.11.3 RN

- pages/1.10/monitoring/logging/aggregating/elk/index.md
- pages/1.11/monitoring/logging/aggregating/elk/index.md
- pages/1.9/monitoring/logging/aggregating/elk/index.md
https://jira.mesosphere.com/browse/DCOS-25686
"Please note that the DC/OS provided as a service by Azure is deployed on Ubuntu servers, where the journalctl is located under /bin/journalctl and not /usr/bin/journalctl"
Versions fixed:
> DCOS-25686 Corrected file name in 1.9, 1.10 and 1.11 versions.

- docker/nginx/redirects-301.map
> redirect map chnge

- docker/nginx/redirects-301.map
> redirect try

- package.json
- plugins/metalsmith-hierarchy-rss.js
- plugins/metalsmith-hierarchy.js
- plugins/metalsmith-in-place-dcos.js
> Linter reformatting

- docker/nginx/redirects-301.map
> another redirect attempt

- docker/nginx/redirects-301.map
> brute force redirect

- docker/nginx/redirects-301.map
> Update redirect map to not redirect / to //

- docker/nginx/redirects-301.map
> redirect 1.9

- pages/services/edge-lb/1.0/installing/index.md
https://jira.mesosphere.com/browse/COPS-3321
Deleted extra quotation mark in command.
> COPS-3321 Correcting extra quotation marks in command.

- pages/services/cassandra/2.3.0-3.0.16/advanced/index.md
- pages/services/cassandra/2.3.0-3.0.16/api-reference/index.md
- pages/services/cassandra/2.3.0-3.0.16/configuration/index.md
- pages/services/cassandra/2.3.0-3.0.16/getting-started/index.md
- pages/services/cassandra/2.3.0-3.0.16/index.md
- pages/services/cassandra/2.3.0-3.0.16/limitations/index.md
- pages/services/cassandra/2.3.0-3.0.16/operations/index.md
- pages/services/cassandra/2.3.0-3.0.16/release-notes/index.md
- pages/services/cassandra/2.3.0-3.0.16/security/index.md
- pages/services/cassandra/2.3.0-3.0.16/support-policy/index.md
- pages/services/cassandra/2.3.0-3.0.16/troubleshooting/index.md
- pages/services/cassandra/2.3.0-3.0.16/uninstall/index.md
- pages/services/cassandra/2.3.0-3.0.16/updates/index.md
https://jira.mesosphere.com/browse/DCOS-37996
> Add Cassandra 2.3.0-3.0.16 documentation.

- pages/1.11/security/ent/perms-reference/index.md
> Update secret store permissions to include leading slash in secret path.

- pages/1.11/tutorials/dcos-debug/gen-strat/index.md
> trivial content change

- pages/services/edge-lb/1.0/api-reference/v1/index.md
- pages/services/edge-lb/1.0/api-reference/v2/index.md
> typo in snippet

- pages/1.9/release-notes/1.9.10/index.md
> Updated 1.9.10 RN with COPS tickets.

- pages/1.10/installing/ent/faq/index.md
- pages/1.11/installing/ent/faq/index.md
https://jira.mesosphere.com/browse/DCOS-37684: document how to recover IAM database from backup
> faq: recover iam database

- pages/1.11/release-notes/1.11.0-rc1/index.md
- pages/1.11/release-notes/1.11.0-rc4/index.md
- pages/1.11/release-notes/1.11.0/index.md
- pages/1.11/release-notes/1.11.1/index.md
- pages/1.11/release-notes/1.11.3/index.md
- pages/1.11/release-notes/1.11.4/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-3854
> 1.11.4 Release Notes

- index.js
- package.json
This package is no longer being used.
https://jira.mesosphere.com/browse/DCOS-39249
>  DCOS-39249 Remove metalsmith copy

- pages/services/percona-mongo/0.2.0-3.4.13/connecting-clients/index.md
Fix for mesosphere/dcos-mongo#219
CC @ryadav88
> Fix for mesosphere/dcos-mongo#219

- pages/1.11/monitoring/debugging/task-exec/index.md
> Correct the acronym for pseudo-terminal

- pages/1.11/administering-clusters/delete-node/index.md
- pages/1.11/hybrid-cloud/features/decommission-nodes/index.md
> Update decomissioning 

- pages/1.11/release-notes/1.11.0-rc1/index.md
- pages/1.11/release-notes/1.11.0-rc4/index.md
- pages/1.11/release-notes/1.11.0/index.md
- pages/1.11/release-notes/1.11.1/index.md
- pages/1.11/release-notes/1.11.2/index.md
- pages/1.11/release-notes/1.11.3/index.md
- pages/1.11/release-notes/1.11.4/index.md
https://jira.mesosphere.com/projects/DCOS/issues/DCOS-39744
> Updated 1.11 RNs with a note on Kubernetes package dependencies.

- docker/nginx/redirects-301.map
https://jira.mesosphere.com/browse/DCOS-38342
> 1.11 improved install docs - fixed redirects for latest entries

- pages/1.11/installing/evaluation/index.md
https://jira.mesosphere.com/browse/DCOS-38342
> Added a note for community support 

- scss/components/_grid-toc.scss
https://jira.mesosphere.com/browse/DCOS-25951
> DCOS-25951 Doc titles cut rather than wrap

- scss/components/_prism.scss
https://jira.mesosphere.com/browse/DCOS-25787
> DCOS-25787 Remove style to break inline code on char

- shortcodes/index.js
> Lint shortcodes file

- assets/js/clipboard.js
https://jira.mesosphere.com/browse/DCOS-39252
> DCOS-39252 The copy button copies a newline

- pages/1.11/installing/evaluation/cloud-installation/aws/index.md
- pages/1.11/installing/evaluation/cloud-installation/azure/index.md
- pages/1.11/installing/evaluation/cloud-installation/digitalocean/index.md
- pages/1.11/installing/evaluation/cloud-installation/gce/index.md
- pages/1.11/installing/evaluation/cloud-installation/index.md
- pages/1.11/installing/evaluation/cloud-installation/packet/index.md
- pages/1.11/installing/evaluation/on-premise-installation/index.md
https://jira.mesosphere.com/browse/DCOS-38342
> Evaluation page - Added disclaimer and note for community support.

- pages/services/percona-mongo/0.3.0-3.6.5/disaster-recovery/index.md
- pages/services/percona-mongo/0.3.0-3.6.5/mongodb-administration/index.md
- pages/services/percona-mongo/0.3.1-3.6.5/api-reference/index.md
- pages/services/percona-mongo/0.3.1-3.6.5/connecting-clients/index.md
- pages/services/percona-mongo/0.3.1-3.6.5/deploy-best-practice/index.md
- pages/services/percona-mongo/0.3.1-3.6.5/disaster-recovery/index.md
- pages/services/percona-mongo/0.3.1-3.6.5/getting-started/index.md
- pages/services/percona-mongo/0.3.1-3.6.5/index.md
- pages/services/percona-mongo/0.3.1-3.6.5/known-issues/index.md
- pages/services/percona-mongo/0.3.1-3.6.5/limitations/index.md
- pages/services/percona-mongo/0.3.1-3.6.5/managing/index.md
- pages/services/percona-mongo/0.3.1-3.6.5/mongodb-administration/index.md
- pages/services/percona-mongo/0.3.1-3.6.5/quick-start/index.md
- pages/services/percona-mongo/0.3.1-3.6.5/release-notes/index.md
- pages/services/percona-mongo/0.3.1-3.6.5/support/index.md
- pages/services/percona-mongo/0.3.1-3.6.5/terms-of-use/index.md
- pages/services/percona-mongo/0.3.1-3.6.5/troubleshooting/index.md
- pages/services/percona-mongo/0.3.1-3.6.5/uninstall/index.md
> Add 0.3.1 docs and fixes to 0.3.0 docs

- plugins/metalsmith-algolia.js
https://jira.mesosphere.com/browse/DCOS-25755
This search is currently live on algolia review index. Feel free to test there:
https://www.algolia.com/apps/Z0ZSQ5T6T2/explorer/browse/dcos-docs-site-review
> DCOS-25755 Search for code

- .gitignore
- scripts/count_words.rb
> Add script to count words for translation estimates

- pages/1.11/cli/command-reference/dcos-license/dcos-license-renew/index.md
https://jira.mesosphere.com/browse/COPS-3544
> Removed --filename from dcos license renew command.

- docker/nginx/redirects-301.map
https://jira.mesosphere.com/browse/DCOS-40217
> Deleted redundant entries.

- pages/1.10/installing/ent/upgrading/index.md
- pages/1.10/installing/oss/upgrading/index.md
- pages/1.10/release-notes/1.10.5/index.md
- pages/1.11/installing/production/upgrading/index.md
https://jira.mesosphere.com/browse/COPS-2961
> Added version specs on 1.10 upgrading pages and  1.10.5 RN.

- scripts/count_words.rb
> Make word count based on script arg

- pages/1.11/release-notes/1.11.1/index.md
- pages/1.11/release-notes/1.11.2/index.md
- pages/1.11/release-notes/1.11.3/index.md
> Changes Mesos change log links 

- pages/1.10/installing/ent/upgrading/index.md
- pages/1.11/installing/production/upgrading/index.md
https://jira.mesosphere.com/browse/DCOS-40310
> Changed the command to monitor cockroach db state.

- pages/services/kubernetes/1.0.0-1.9.3/advanced-install/index.md
- pages/services/kubernetes/1.0.0-1.9.3/disaster-recovery/index.md
- pages/services/kubernetes/1.0.0-1.9.3/ingress/index.md
- pages/services/kubernetes/1.0.1-1.9.4/advanced-install/index.md
- pages/services/kubernetes/1.0.1-1.9.4/disaster-recovery/index.md
- pages/services/kubernetes/1.0.1-1.9.4/ingress/index.md
- pages/services/kubernetes/1.0.2-1.9.6/advanced-install/index.md
- pages/services/kubernetes/1.0.2-1.9.6/disaster-recovery/index.md
- pages/services/kubernetes/1.0.2-1.9.6/ingress/index.md
- pages/services/kubernetes/1.0.3-1.9.7/advanced-install/index.md
- pages/services/kubernetes/1.0.3-1.9.7/disaster-recovery/index.md
- pages/services/kubernetes/1.0.3-1.9.7/ingress/index.md
- pages/services/kubernetes/1.1.0-1.10.3/advanced-install/index.md
- pages/services/kubernetes/1.1.0-1.10.3/disaster-recovery/index.md
- pages/services/kubernetes/1.1.0-1.10.3/ingress/index.md
- pages/services/kubernetes/1.1.0-1.10.3/kubernetes-dashboard/index.md
- pages/services/kubernetes/1.1.1-1.10.4/advanced-install/index.md
- pages/services/kubernetes/1.1.1-1.10.4/disaster-recovery/index.md
- pages/services/kubernetes/1.1.1-1.10.4/ingress/index.md
- pages/services/kubernetes/1.1.1-1.10.4/kubernetes-dashboard/index.md
- pages/services/kubernetes/1.2.0-1.10.5/advanced-install/index.md
- pages/services/kubernetes/1.2.0-1.10.5/disaster-recovery/index.md
- pages/services/kubernetes/1.2.0-1.10.5/ingress/index.md
- pages/services/kubernetes/1.2.0-1.10.5/kubernetes-dashboard/index.md
[DCOS_OSS-3656](https://jira.mesosphere.com/browse/DCOS_OSS-3656)
[DCOS_OSS-3657](https://jira.mesosphere.com/browse/DCOS_OSS-3657)
[DCOS_OSS-3659](https://jira.mesosphere.com/browse/DCOS_OSS-3659)
[DCOS_OSS-3660](https://jira.mesosphere.com/browse/DCOS_OSS-3660)
[DCOS_OSS-3661](https://jira.mesosphere.com/browse/DCOS_OSS-3661)
> Some services/kubernetes doc changes

- pages/services/beta-confluent-kafka/2.3.0-4.1.1-beta/advanced/index.md
- pages/services/beta-confluent-kafka/2.3.0-4.1.1-beta/api-reference/index.md
- pages/services/beta-confluent-kafka/2.3.0-4.1.1-beta/configuration/index.md
- pages/services/beta-confluent-kafka/2.3.0-4.1.1-beta/getting-started/index.md
- pages/services/beta-confluent-kafka/2.3.0-4.1.1-beta/index.md
- pages/services/beta-confluent-kafka/2.3.0-4.1.1-beta/limitations/index.md
- pages/services/beta-confluent-kafka/2.3.0-4.1.1-beta/operations/index.md
- pages/services/beta-confluent-kafka/2.3.0-4.1.1-beta/release-notes/index.md
- pages/services/beta-confluent-kafka/2.3.0-4.1.1-beta/security/index.md
- pages/services/beta-confluent-kafka/2.3.0-4.1.1-beta/support-policy/index.md
- pages/services/beta-confluent-kafka/2.3.0-4.1.1-beta/troubleshooting/index.md
- pages/services/beta-confluent-kafka/2.3.0-4.1.1-beta/uninstall/index.md
- pages/services/beta-confluent-kafka/2.3.0-4.1.1-beta/updates/index.md
- pages/services/beta-confluent-kafka/data.yml
> beta-confkafka 2.3.0-4.1.1 service docs

- pages/1.11/overview/architecture/boot-sequence/index.md
https://jira.mesosphere.com/browse/COPS-3406
> Corrected boot sequence page.

- pages/services/prometheus/0.1.1-2.3.2/configuration/alerting-overview/index.md
- pages/services/prometheus/0.1.1-2.3.2/configuration/prometheus-federation/index.md
- pages/services/prometheus/0.1.1-2.3.2/configuration/service-discovery/index.md
- pages/services/prometheus/0.1.1-2.3.2/configuration/visualization/index.md
- pages/services/prometheus/0.1.1-2.3.2/index.md
- pages/services/prometheus/0.1.1-2.3.2/limitations/index.md
- pages/services/prometheus/0.1.1-2.3.2/quick-start-guide/index.md
- pages/services/prometheus/0.1.1-2.3.2/release-notes/index.md
- pages/services/prometheus/0.1.1-2.3.2/security/index.md
- pages/services/prometheus/0.1.1-2.3.2/uninstall/index.md
https://jira.mesosphere.com/browse/DCOS-40325
Perform a light edit pass on the Prometheus service documents, looking for typos, grammar, etc. No major revision to structure.
This edit will be performed on v. 0.1.0-2.3.2 ONLY.
> ss/DCOS-40325 Edit pass for Prometheus 0.1.1-2.3.2

- pages/1.10/release-notes/1.10.5/index.md
- pages/1.10/release-notes/1.10.6/index.md
- pages/1.10/release-notes/1.10.7/index.md
- pages/1.10/release-notes/1.10.8/index.md
- pages/1.11/release-notes/1.11.1/index.md
- pages/1.11/release-notes/1.11.2/index.md
- pages/1.11/release-notes/1.11.3/index.md
- pages/1.11/release-notes/1.11.4/index.md
> Changed -dev to -sha in Mesos change log links.

- pages/services/cassandra/2.3.0-3.0.16/configuration/index.md
- pages/services/cassandra/2.3.0-3.0.16/getting-started/index.md
- pages/services/cassandra/2.3.0-3.0.16/security/index.md
- pages/services/cassandra/cass-auth/index.md
- pages/services/hdfs/2.2.0-2.6.0-cdh5.11.0/advanced/index.md
- pages/services/hdfs/2.2.0-2.6.0-cdh5.11.0/api-reference/index.md
- pages/services/hdfs/2.2.0-2.6.0-cdh5.11.0/configuration/index.md
- pages/services/hdfs/2.2.0-2.6.0-cdh5.11.0/getting-started/index.md
- pages/services/hdfs/2.2.0-2.6.0-cdh5.11.0/limitations/index.md
- pages/services/hdfs/2.2.0-2.6.0-cdh5.11.0/operations/index.md
- pages/services/hdfs/2.2.0-2.6.0-cdh5.11.0/security/index.md
- pages/services/hdfs/2.2.0-2.6.0-cdh5.11.0/support-policy/index.md
- pages/services/hdfs/2.2.0-2.6.0-cdh5.11.0/troubleshooting/index.md
- pages/services/hdfs/2.2.0-2.6.0-cdh5.11.0/uninstall/index.md
- pages/services/hdfs/2.2.0-2.6.0-cdh5.11.0/updates/index.md
- pages/services/hdfs/hdfs-auth/index.md
- pages/services/include/advanced.tmpl
- pages/services/include/configuration-create-json-file.tmpl
- pages/services/include/getting-started.tmpl
- pages/services/include/security-configure-transport-encryption.tmpl
- pages/services/include/security-create-permissions.tmpl
- pages/services/include/service-account.tmpl
https://jira.mesosphere.com/browse/DCOS-40321
r revision to structure.
This edit will be performed on v. 2.2.0-2.6.0-cdh5.11.0 ONLY.
> Updates to HDFS docs with revised templates

- pages/services/spark/2.3.1-2.2.1-2/index.md
> ss/COPS-3227 Fixing menuweight.

- pages/services/marathon-lb/advanced/index.md
- pages/services/marathon-lb/index.md
- pages/services/marathon-lb/marathon-lb-advanced-tutorial/index.md
- pages/services/marathon-lb/marathon-lb-basic-tutorial/index.md
- pages/services/marathon-lb/mlb-auth/index.md
- pages/services/marathon-lb/release-notes/index.md
- pages/services/marathon-lb/usage-ee/index.md
- pages/services/marathon-lb/usage-oss/index.md
https://jira.mesosphere.com/browse/DCOS-40322
Perform a light edit pass on the Marathon-LB service documents, looking for typos, grammar, etc. No major revision to structure.
This edit will be performed on v. 1.0 ONLY.
> ss/DCOS-40322 Edit pass for Marathon-LB service docs.

- docker/nginx/redirects-301.map
> Add redirect for broken link in DC/OS web UI

- pages/services/include/configuration-install-with-options.tmpl
- pages/services/include/configuration-service-settings.tmpl
- pages/services/include/uninstall.tmpl
- pages/services/kafka/2.3.0-1.1.0/advanced/index.md
- pages/services/kafka/2.3.0-1.1.0/configuration/index.md
- pages/services/kafka/2.3.0-1.1.0/index.md
- pages/services/kafka/2.3.0-1.1.0/limitations/index.md
- pages/services/kafka/2.3.0-1.1.0/notes/index.md
- pages/services/kafka/2.3.0-1.1.0/operations/index.md
- pages/services/kafka/2.3.0-1.1.0/policy/index.md
- pages/services/kafka/2.3.0-1.1.0/reference/index.md
- pages/services/kafka/2.3.0-1.1.0/security/index.md
- pages/services/kafka/2.3.0-1.1.0/started/index.md
- pages/services/kafka/2.3.0-1.1.0/troubleshooting/index.md
- pages/services/kafka/2.3.0-1.1.0/uninstall/index.md
- pages/services/kafka/2.3.0-1.1.0/updates/index.md
- pages/services/kafka/index.md
- pages/services/kafka/kafka-auth/index.md
- pages/services/spark/spark-auth/index.md
https://jira.mesosphere.com/browse/DCOS-40326
Edit pass for Kafka docs (v. 2.3.0-1.1.0 ONLY) for localization. Also edits to templates.
> ss/DCOS-40326 Kafka docs edit.

- pages/services/kafka/2.3.0-1.1.0/configuration/index.md
https://jira.mesosphere.com/browse/DCOS-40326
Correcting configuration/index.md
> ss/DCOS-40326 Correction to config doc.

- pages/services/include/advanced.tmpl
https://jira.mesosphere.com/browse/DCOS-40326
Fixed variable error in advanced.tmpl
> ss/DCOS-40326 advanced.tmpl fix.

- pages/1.10/installing/ent/custom/system-requirements/install-docker-centos/index.md
- pages/1.11/installing/production/system-requirements/docker-centos/index.md
https://jira.mesosphere.com/browse/COPS-2357
> Added a note about the usage of XFS in 1.10 and 1.11 documentation

- pages/1.12/installing/production/advanced-configuration/configuration-reference/index.md
https://jira.mesosphere.com/browse/DCOS-26412?
- [x ] Blocker 
> Update adminrouter_auth_cache_enabled default

- pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/advanced/index.md
- pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/api-reference/index.md
- pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/configuration/index.md
- pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/getting-started/index.md
- pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/index.md
- pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/limitations/index.md
- pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/operations/index.md
- pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/release-notes/index.md
- pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/security/index.md
- pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/support-policy/index.md
- pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/troubleshooting/index.md
- pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/uninstall/index.md
- pages/services/hdfs/2.3.0-2.6.0-cdh5.11.0/updates/index.md
https://jira.mesosphere.com/browse/DCOS-38720
> [DCOS-38720] Add docs for HDFS 2.3.0-2.6.0-cdh5.11.0

- pages/1.9/release-notes/1.9.0-rc1/index.md
- pages/1.9/release-notes/1.9.0-rc2/index.md
- pages/1.9/release-notes/1.9.0-rc3/index.md
- pages/1.9/release-notes/1.9.0-rc4/index.md
- pages/1.9/release-notes/1.9.0/index.md
- pages/1.9/release-notes/1.9.1/index.md
- pages/1.9/release-notes/1.9.2/index.md
- pages/1.9/release-notes/1.9.3/index.md
- pages/1.9/release-notes/1.9.4/index.md
- pages/1.9/release-notes/1.9.5/index.md
- pages/1.9/release-notes/1.9.6/index.md
- pages/1.9/release-notes/1.9.7/index.md
- pages/1.9/release-notes/1.9.8/index.md
- pages/1.9/release-notes/open-source-attribution/index.md
- pages/1.9/release-notes/version-policy/index.md
Reverts mesosphere/dcos-docs-site#1042
> Revert "DCOS_OSS-3220 Re-configure 1.9 release notes"

- js/search.js
- plugins/metalsmith-algolia.js
https://jira.mesosphere.com/browse/DCOS-39607
Search testing is available at the review site and algolia:
- http://docs-review.mesosphere.com/search/
- https://www.algolia.com/apps/Z0ZSQ5T6T2/explorer/browse/dcos-docs-site-review
You can see the second to last entry is `undefined` here:
https://docs.mesosphere.com/search/?q=1.11%20release%20notes
and is not here:
http://docs-review.mesosphere.com/search/?q=1.11%20release%20notes
You can also see an additional warning in the build logs below `Algolia: Cleared index`:
https://jenkins-docs.mesosphere.com/service/jenkins-docs/job/dcos-docs-site-review/38/console
- …
> DCOS-39607 Algolia remove undefined results in search

- pages/1.11/administering-clusters/add-a-node/index.md
- pages/1.11/administering-clusters/component-management/index.md
- pages/1.11/administering-clusters/convert-agent-type/index.md
- pages/1.11/administering-clusters/delete-node/index.md
- pages/1.11/administering-clusters/deploying-a-local-dcos-universe/index.md
- pages/1.11/administering-clusters/index.md
- pages/1.11/administering-clusters/licenses/index.md
- pages/1.11/administering-clusters/licenses/license-api/index.md
- pages/1.11/administering-clusters/licenses/license-cli/index.md
- pages/1.11/administering-clusters/locate-public-agent/index.md
- pages/1.11/administering-clusters/managing-aws/index.md
- pages/1.11/administering-clusters/multiple-clusters/cluster-links/index.md
- pages/1.11/administering-clusters/recovering-agent-disk-space/index.md
- pages/1.11/administering-clusters/replacing-a-master-node/index.md
- pages/1.11/administering-clusters/repo/index.md
- pages/1.11/administering-clusters/securing-your-cluster/index.md
- pages/1.11/administering-clusters/sshcluster/index.md
- pages/1.11/administering-clusters/update-a-node/index.md
- pages/1.11/cli/command-reference/dcos-marathon/dcos-marathon-task-stop/index.md
Edits to /administering-clusters/ pages, version 1.11 ONLY>
> ss/DCOS-26632 Edits to administering-clusters pages.

- pages/services/beta-storage/0.3.1-beta/index.md
Since DC/OS 1.12 is not out yet.
> Hide DSS 0.3.1

- pages/1.11/api/access/index.md
- pages/1.11/api/index.md
- pages/1.11/api/master-routes/index.md
- pages/1.11/api/versioning/index.md
Edits to 1.11/api/ docs. Version 1.11 ONLY.
> ss/DCOS-26632 Edits to API docs.

- pages/1.11/gui/catalog/index.md
- pages/1.11/gui/cluster/index.md
- pages/1.11/gui/components/index.md
- pages/1.11/gui/dashboard/index.md
- pages/1.11/gui/jobs/index.md
- pages/1.11/gui/networking/index.md
- pages/1.11/gui/nodes/index.md
- pages/1.11/gui/organization/index.md
- pages/1.11/gui/secrets/index.md
- pages/1.11/gui/services/index.md
- pages/1.11/gui/settings/index.md
Edits to 1.11/gui/ docs, version 1.11 ONLY.
> ss/DCOS-26632 Changes to 1.11/gui/ docs.

- pages/1.11/hybrid-cloud/features/capacity-extension-with-regions/index.md
- pages/1.11/hybrid-cloud/features/cluster-links/index.md
- pages/1.11/hybrid-cloud/features/decommission-nodes/index.md
- pages/1.11/hybrid-cloud/features/index.md
Edits to 1.11/gui docs, version 1.11 ONLY.
> ss/DCOS-26632 Edits to hybrid-cloud docs for 1.11 only.

- pages/1.11/deploying-jobs/examples/index.md
- pages/1.11/deploying-jobs/index.md
- pages/1.11/deploying-jobs/job-groups/index.md
- pages/1.11/deploying-jobs/quickstart/index.md
Edits to 1.11/deploying-jobs files, version 1.11 ONLY.
> ss/DCOS-26632 Edits to 1.11/deploying-jobs docs.

- pages/1.11/developing-services/cli-spec/index.md
- pages/1.11/developing-services/tunnel/index.md
Edits to developing-services docs, version 1.11 ONLY.
> ss/DCOS-26632 Edits to 1.11/developing-services docs.

- pages/1.10/administering-clusters/add-a-node/index.md
- pages/1.11/administering-clusters/add-a-node/index.md
- pages/1.9/administering-clusters/add-a-node/index.md
https://jira.mesosphere.com/browse/COPS-3347
> 1.11, 1.10, and 1.9 - Called out information about master nodes.

- pages/1.12/installing/production/advanced-configuration/configuration-reference/index.md
https://jira.mesosphere.com/browse/DCOS-38662
> Added documentation for the log_offers config parameter.

- pages/1.11/installing/production/patching/index.md
https://jira.mesosphere.com/browse/COPS-3668
> Fixed generate node command in Patching docs.

- pages/1.12/monitoring/performance-monitoring/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-3935
> Update the documentation on Marathon metrics

- pages/1.11/installing/production/patching/index.md
- pages/1.11/installing/production/upgrading/index.md
https://jira.mesosphere.com/browse/COPS-3532
> Fixed patch and upgrade commands/instructions.

- layouts/components/content-actions.pug
https://jira.mesosphere.com/browse/DCOS_OSS-3990
> DCOS-40712 Add team field to jira link

- pages/1.11/networking/DNS/index.md
- pages/1.11/networking/DNS/mesos-dns/expose-mesos-zone/index.md
- pages/1.11/networking/DNS/mesos-dns/index.md
- pages/1.11/networking/DNS/mesos-dns/mesos-dns-api/index.md
- pages/1.11/networking/DNS/mesos-dns/service-naming/index.md
- pages/1.11/networking/DNS/mesos-dns/troubleshooting/index.md
- pages/1.11/networking/SDN/cni-plugins/index.md
- pages/1.11/networking/SDN/dcos-overlay/index.md
- pages/1.11/networking/SDN/index.md
- pages/1.11/networking/SDN/usage/index.md
- pages/1.11/networking/index.md
- pages/1.11/networking/load-balancing-vips/index.md
- pages/1.11/networking/load-balancing-vips/virtual-ip-addresses/index.md
Edit pass on 1.11 networking docs.
This is part of an editing project to clean up some of the networking docs. There were several issues with this set of docs, including broken links. Some of this material may be very much out of date. Please review.
Versions:
1.11 ONLY
> ss/DCOS-26632 Edits to networking docs.

- pages/1.11/networking/SDN/usage/index.md
Reverts mesosphere/dcos-docs-site#1379
> Revert "ss/COPS-2883 Replaced older JSON file with newer version."

- docker/Dockerfile.docs
- scripts/build-site.sh
> Add google verification file

- pages/1.11/release-notes/1.11.2/index.md
- pages/1.11/release-notes/1.11.3/index.md
- pages/1.11/release-notes/1.11.4/index.md
- pages/1.11/release-notes/open-source-attribution/index.md
- pages/1.11/release-notes/version-policy/index.md
> ss/DCOS-26632 Edits to 1.11 release notes.

- .gitignore
- plugins/metalsmith-algolia.js
https://jira.mesosphere.com/browse/DCOS-26318
> Algolia ordering dcos 26318

- plugins/metalsmith-algolia.js
https://jira.mesosphere.com/browse/DCOS-40424
> DCOS-40424 Replace html entities with actual characters

- pages/1.11/security/ent/service-auth/auth-tokens/index.md
- pages/1.11/tutorials/autoscaling/cpu-memory/index.md
- pages/1.11/tutorials/autoscaling/index.md
- pages/1.11/tutorials/autoscaling/microscaling-queue/index.md
- pages/1.11/tutorials/autoscaling/requests-second/index.md
- pages/1.11/tutorials/create-service/index.md
- pages/1.11/tutorials/dcos-101/app1/index.md
- pages/1.11/tutorials/dcos-101/app2/index.md
- pages/1.11/tutorials/dcos-101/cli/index.md
- pages/1.11/tutorials/dcos-101/index.md
- pages/1.11/tutorials/dcos-101/loadbalancing/index.md
- pages/1.11/tutorials/dcos-101/marathon-lb/index.md
- pages/1.11/tutorials/dcos-101/redis-package/index.md
- pages/1.11/tutorials/dcos-101/resources/index.md
- pages/1.11/tutorials/dcos-101/service-discovery/index.md
- pages/1.11/tutorials/dcos-debug/gen-strat/index.md
- pages/1.11/tutorials/dcos-debug/index.md
- pages/1.11/tutorials/dcos-debug/scenarios/index.md
- pages/1.11/tutorials/dcos-debug/scenarios/scen-1/index.md
- pages/1.11/tutorials/dcos-debug/scenarios/scen-2/index.md
- pages/1.11/tutorials/dcos-debug/scenarios/scen-3/index.md
- pages/1.11/tutorials/dcos-debug/tools/index.md
- pages/1.11/tutorials/deploy-on-marathon/index.md
- pages/1.11/tutorials/index.md
- pages/1.11/tutorials/iot_pipeline/index.md
- pages/1.11/tutorials/stateful-services/index.md
- pages/1.11/tutorials/task-labels/index.md
> ss/DCOS-26632 Edit pass on 1.11 tutorials.

- pages/1.11/developing-services/cli-spec/index.md
- pages/1.11/developing-services/index.md
- pages/1.11/developing-services/tunnel/index.md
Edited 1.11 developing-services pages.
> ss/DCOS-26632 Edited 1.11 developing-services docs.

- pages/services/percona-mongo/0.3.0-3.6.5/quick-start/index.md
- pages/services/percona-mongo/0.3.1-3.6.5/quick-start/index.md
Fix for https://github.com/mesosphere/dcos-mongo/issues/257.
CC @ryadav88 
> Percona-mongo: update JSON user examples to have quoted keys

- pages/1.11/installing/evaluation/cloud-installation/packet/index.md
https://jira.mesosphere.com/browse/DCOS-41321
> Updated maintenance mode reference.

- pages/1.11/installing/production/advanced-configuration/configuration-reference/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-3529
> Added fault_domain_enabled option.

- pages/1.11/cli/command-reference/dcos-marathon/dcos-marathon-debug-list/index.md
- pages/1.11/cli/command-reference/dcos-marathon/dcos-marathon-debug-summary/index.md
- pages/1.11/monitoring/debugging/cli-debugging/index.md
- pages/1.11/monitoring/debugging/debug-perms/index.md
- pages/1.11/monitoring/debugging/gui-debugging/index.md
- pages/1.11/monitoring/debugging/index.md
- pages/1.11/monitoring/debugging/slow-docker/index.md
- pages/1.11/monitoring/debugging/stuck-deployment/index.md
- pages/1.11/monitoring/debugging/task-exec/index.md
- pages/1.11/monitoring/index.md
- pages/1.11/monitoring/logging/access-component-logs/index.md
- pages/1.11/monitoring/logging/access-task-logs/index.md
- pages/1.11/monitoring/logging/aggregating/elk/index.md
- pages/1.11/monitoring/logging/aggregating/filter-elk/index.md
- pages/1.11/monitoring/logging/aggregating/filter-splunk/index.md
- pages/1.11/monitoring/logging/aggregating/index.md
- pages/1.11/monitoring/logging/aggregating/splunk/index.md
- pages/1.11/monitoring/logging/index.md
- pages/1.11/monitoring/logging/logging-api-examples/index.md
- pages/1.11/monitoring/logging/logging-api/index.md
- pages/1.11/monitoring/logging/quickstart/index.md
- pages/1.11/monitoring/performance-monitoring/index.md
- pages/1.11/monitoring/performance-monitoring/nagios/index.md
<https://jira.mesosphere.com/browse/DCOS-26632
Editing the 1.11/monitoring docs.
> ss/DCOS-26632 Editing 1.11 monitoring docs.

- pages/1.11/storage/external-storage/index.md
- pages/1.11/storage/index.md
- pages/1.11/storage/mount-disk-resources/index.md
- pages/1.11/storage/nfs/index.md
- pages/1.11/storage/persistent-volume/index.md
> ss/DCOS-26632 Edits to 1.11 storage docs

- pages/1.11/installing/production/deploying-dcos/installation/index.md
https://jira.mesosphere.com/browse/COPS-3783
> Added GCP support in fault domain script.

- pages/1.11/security/ent/secrets/use-secrets/index.md
https://jira.mesosphere.com/browse/DCOS-41511
> 1.11/Security - Added Metronome secrets.

- pages/1.11/installing/production/patching/index.md
https://jira.mesosphere.com/browse/DCOS-41443
> 1.11 - Added matrix table for supported patching paths.

- pages/1.9/release-notes/1.9.0-rc1/index.md
- pages/1.9/release-notes/1.9.0-rc2/index.md
- pages/1.9/release-notes/1.9.0-rc3/index.md
- pages/1.9/release-notes/1.9.0-rc4/index.md
https://jira.mesosphere.com/browse/DCOS-25889
> 1.9.0-rc1 RN - Fixed preview and experimental badges.

- pages/1.10/security/ent/service-auth/custom-service-auth/index.md
- pages/1.11/security/ent/service-auth/custom-service-auth/index.md
- pages/1.12/security/ent/service-auth/custom-service-auth/index.md
- pages/1.9/security/ent/service-auth/custom-service-auth/index.md
> Fix typo across 1.9-1.12

- pages/1.11/release-notes/1.11.5/index.md
Pointing to the URI ( https://github.com/dcos/dcos/pull/3289)
> Fix Marathon Release Notes URI

- pages/services/percona-server-mongodb/0.4.0-3.6.6/limitations/index.md
To resolve limitations identified during Percona QA.
Resolves issue https://github.com/mesosphere/dcos-mongo/issues/265.
CC @ryadav88
> Add to Limitations docs for https://github.com/dcos_mongo/issues/265

- pages/version-policy/index.md
> Add Edge-LB 1.1 to versions matrix

- pages/1.11/release-notes/1.11.5/index.md
https://jira.mesosphere.com/browse/DCOS-41857
> 1.11.5 RN - Removed COPS-3658/DCOS-21258 entry.

- pages/1.11/release-notes/1.11.5/index.md
https://jira.mesosphere.com/browse/DCOS-41901
> Remove DC/OS UI plugin links from 1.11.5 RN.

- pages/1.12/installing/production/system-requirements/index.md
Please do not review yet.
https://jira.mesosphere.com/browse/DCOS-40141
> [WIP] DCOS-40141: Add SELinux support

- pages/services/beta-cassandra/1.0.32-3.0.14-beta/connecting-clients/index.md
- pages/services/beta-cassandra/1.0.32-3.0.14-beta/quickstart/index.md
- pages/services/beta-cassandra/1.0.32-3.0.14-beta/supported-versions/index.md
- pages/services/beta-cassandra/2.1.0-3.0.15-beta/connecting-clients/index.md
- pages/services/beta-cassandra/2.1.0-3.0.15-beta/quick-start/index.md
- pages/services/beta-cassandra/2.1.0-3.0.15-beta/supported-versions/index.md
- pages/services/beta-cassandra/2.1.1-3.0.15-beta/connecting-clients/index.md
- pages/services/beta-cassandra/2.1.1-3.0.15-beta/quick-start/index.md
- pages/services/beta-cassandra/2.1.1-3.0.15-beta/supported-versions/index.md
- pages/services/beta-cassandra/2.1.2-3.0.15-beta/connecting-clients/index.md
- pages/services/beta-cassandra/2.1.2-3.0.15-beta/quick-start/index.md
- pages/services/beta-cassandra/2.1.2-3.0.15-beta/supported-versions/index.md
- pages/services/cassandra/2.0.1-3.0.14/connecting-clients/index.md
- pages/services/cassandra/2.0.1-3.0.14/quick-start/index.md
- pages/services/cassandra/2.0.1-3.0.14/supported-versions/index.md
- pages/services/cassandra/2.0.2-3.0.14/connecting-clients/index.md
- pages/services/cassandra/2.0.2-3.0.14/quick-start/index.md
- pages/services/cassandra/2.0.2-3.0.14/supported-versions/index.md
- pages/services/cassandra/2.0.3-3.0.14/connecting-clients/index.md
- pages/services/cassandra/2.0.3-3.0.14/supported-versions/index.md
- pages/services/cassandra/v2.0.0-3.0.14/connecting-clients/index.md
- pages/services/cassandra/v2.0.0-3.0.14/quick-start/index.md
- pages/services/cassandra/v2.0.0-3.0.14/supported-versions/index.md
https://jira.mesosphere.com/browse/DCOS-38569?filter=-1
- [x ] Medium
> DCOS-38569 fix cassandra versioning

- pages/test/style/index.md
- scss/shortcodes/_message.scss
- scss/shortcodes/_notes.scss
- scss/utils/_colors.scss
- scss/variables/_colors.scss
https://jira.mesosphere.com/browse/DCOS-41893
Adding styles for notes, warnings and important notes to stylesheets.
> ss/DCOS-41893 Added Notes and Warnings styles to stylesheets.

- pages/1.10/api/marathon.yaml
- pages/1.11/api/marathon.yaml
- pages/1.12/api/marathon.yaml
- pages/1.9/api/marathon.yaml
- pages/services/confluent-zookeeper/2.1.0-4.0.0e/security/index.md
- pages/services/confluent-zookeeper/2.2.0-4.0.0e/security/index.md
- pages/services/confluent-zookeeper/2.3.0-4.0.0e/security/index.md
- pages/services/kafka-zookeeper/2.1.0-3.4.11/security/index.md
- pages/services/kafka-zookeeper/2.2.0-3.4.11/security/index.md
- pages/services/kafka-zookeeper/2.3.0-3.4.12/security/index.md
- pages/test/api/marathon.yaml
https://jira.mesosphere.com/browse/DCOS-26538?filter=-1
- [x ] Medium
> DCOS-26538 Correct spelling of deployment

- pages/1.11/administering-clusters/licenses/license-api/index.md
- pages/1.12/administering-clusters/licenses/license-api/index.md
https://jira.mesosphere.com/browse/DCOS-40614
Tested results are in the ticket.
Not required.
Changed for DC/OS 1.11 and 1.12
> updating license permissions for DC/OS 1.11 and 1.12

- pages/1.11/installing/installation-faq/index.md
- pages/1.11/installing/production/upgrading/index.md
DCOS-40123
https://jira.mesosphere.com/browse/DCOS-40123?filter=-1
- [ x] Medium
> Add enterprise label to IAM restore and fix link to IAM backup faq

- pages/services/beta-kubernetes/2.0.0-1.12.0-beta/release-notes/index.md
Upstream PR: https://github.com/mesosphere/dcos-kubernetes/pull/722.
> docs: remove misleading note about upgrades

- pages/services/edge-lb/1.2/api-reference/index.md
- pages/services/edge-lb/1.2/cli-reference/dcos-edgelb-list/index.md
- pages/services/edge-lb/1.2/cli-reference/index.md
- pages/services/edge-lb/1.2/installing/index.md
- pages/services/edge-lb/1.2/permissions/index.md
- pages/services/edge-lb/1.2/pool-configuration/index.md
- pages/services/edge-lb/1.2/release-notes/index.md
- pages/services/edge-lb/1.2/uninstalling/index.md
- pages/services/edge-lb/1.2/upgrading/index.md
- pages/services/edge-lb/1.2/usage/index.md
https://jira.mesosphere.com/browse/DCOS-42151
Need to remove these sections from the RN:
https://docs.mesosphere.com/services/edge-lb/1.2/release-notes/
Universe Repo Artifacts
- https://downloads.mesosphere.com/edgelb/v1.2.1/assets/stub-universe-edgelb.json
- https://downloads.mesosphere.com/edgelb-pool/v1.2.1/assets/stub-universe-edgelb-pool.json
Universe Repo Artifacts
- EdgeLB on DC/OS.
- EdgeLB pool on DC/OS.
Add this line under Notable Changes under v1.2.1:
Notable Changes
- Added logging for better troubleshooting of Edge-LB
Removed cited text. Minor formatting edits.
> ss/DCOS-42151 Revising release notes, minor formatting edits.

- pages/services/couchbase/0.2.0-5.5.0/index.md
- pages/services/couchbase/0.2.0-5.5.0/limitations/index.md
> making xdcr a limitation

- pages/services/couchbase/0.2.0-5.5.0/index.md
> removed another mentione re xdcr

- js/image.js
https://jira.mesosphere.com/browse/DCOS-25749
> DCOS-25749 No longer insert a link for images

- layouts/components/content-grid.pug
- scss/components/_grid.scss
https://jira.mesosphere.com/browse/DCOS-39233
A good page to test that has two labels is `1.11/deploying-jobs/`
> DCOS-39233 Allow grid of cards to accept multiple labels

- pages/services/elastic/2.4.0-5.6.9/configuration/index.md
https://jira.mesosphere.com/browse/DCOS-42188
>  Elastic 2.4.0-5.6.9 >> Fixed broken links for X-Pack documentation.

- pages/1.10/security/ent/gui-permissions/services-tab/index.md
- pages/1.11/security/ent/gui-permissions/services-tab/index.md
- pages/1.12/security/ent/gui-permissions/services-tab/index.md
- pages/1.9/security/ent/gui-permissions/services-tab/index.md
https://jira.mesosphere.com/browse/COPS-3631
> COPS-3631 Section formatting, remove indents to fix formatting issue

- pages/services/edge-lb/0.1/api-reference/index.md
- pages/services/edge-lb/1.0/api-reference/v1/index.md
- pages/services/edge-lb/1.0/api-reference/v2/index.md
- pages/services/edge-lb/1.1/api-reference/v1/index.md
- pages/services/edge-lb/1.1/api-reference/v2/index.md
- pages/services/edge-lb/1.2/api-reference/v1/index.md
- pages/services/edge-lb/1.2/api-reference/v2/index.md
https://jira.mesosphere.com/browse/COPS-3564
Remove s from services to make singular service, remove hyphen from edgelb
Lines Changing:
1. Routes -> /service/edgelb/
2. Auth -> 
2a. Route -> /service/edgelb/
2b. Permission -> dcos:adminrouter:service:edgelb
- [ x] Medium
> Remove hyphen from edgelb on code snippets COPS-3564

- pages/services/beta-storage/0.3.0-beta/index.md
So that the latest version 0.3.1 is showned by default.
> Change the menuWeight for DSS 0.3.0.

- pages/1.12/cli/command-reference/dcos-node/dcos-node-log/index.md
> simple typo in 1.12 docs

- pages/services/beta-dse/2.1.0-5.1.2-beta/dse-authentication/index.md
- pages/services/beta-dse/2.1.2-5.1.2-beta/dse-authentication/index.md
- pages/services/beta-dse/v1.1.7-5.0.7-beta/dse-authentication/index.md
- pages/services/beta-dse/v1.1.8-5.1.2-beta/dse-authentication/index.md
- pages/services/dse/2.0.2-5.1.2/dse-authentication/index.md
- pages/services/dse/2.0.3-5.1.2/dse-authentication/index.md
- pages/services/dse/2.0.4-5.1.2/dse-authentication/index.md
- pages/services/dse/2.0.5-5.1.2/dse-authentication/index.md
- pages/services/dse/2.1.2-5.1.2/security/index.md
- pages/services/dse/2.2.0-5.1.2/security/index.md
- pages/services/dse/2.3.0-5.1.2/security/index.md
- pages/services/dse/v2.0.0-5.1.2/dse-authentication/index.md
https://jira.mesosphere.com/browse/COPS-2188
One of the sentences is being treated by the formatter as code snippet, inserted newline 
Fixed across entire set of DSE docs
- [ x] Medium
> ck/COPS-2188 Formatting fix, take informational text out of code snippet

- docker/nginx/redirects-301.map
- index.js
- package.json
- pages/1.10/index.md
- pages/1.12/index.md
- pages/1.7/index.md
- pages/1.8/index.md
- pages/1.9/index.md
- scss/base/_layout.scss
> Prepare to release 1.12-beta

- pages/1.12/release-notes/1.12.0-beta1/index.md
https://jira.mesosphere.com/browse/DCOS-41672
> Added ENT tags.

- pages/1.12/overview/architecture/boot-sequence/index.md
- pages/1.12/overview/architecture/components/index.md
- pages/1.12/overview/architecture/distributed-process-management/index.md
- pages/1.12/overview/architecture/index.md
- pages/1.12/overview/architecture/node-types/index.md
- pages/1.12/overview/architecture/task-types/index.md
- pages/1.12/overview/concepts/index.md
- pages/1.12/overview/design/auth-flow/index.md
- pages/1.12/overview/design/azure-container-service/index.md
- pages/1.12/overview/design/dns-proxy/index.md
- pages/1.12/overview/design/installation/index.md
- pages/1.12/overview/design/overlay/index.md
- pages/1.12/overview/feature-maturity/index.md
- pages/1.12/overview/high-availability/index.md
- pages/1.12/overview/telemetry/index.md
- pages/1.12/overview/what-is-dcos/index.md
Replaced the occurrence of 1.11 to 1.12 in https://docs.mesosphere.com/1.12/overview/
> 1.2>>Overview: Changed occurrence of 1.11 to 1.12.

- pages/1.12/metrics/index.md
- pages/1.12/metrics/metrics-api/index.md
- pages/1.12/metrics/prometheus/index.md
- pages/1.12/metrics/quickstart/index.md
Changed occurrence of 1.11 to 1.12 in https://docs.mesosphere.com/1.12/metrics/
> 1.12>>Metrics: Changed occurrence of 1.11 to 1.12.

- pages/1.12/installing/production/patching/index.md
- pages/1.12/installing/production/upgrading/index.md
Changed occurrence of 1.11 to 1.12 in https://docs.mesosphere.com/1.12/installing/production/patching/
https://docs.mesosphere.com/1.12/installing/production/upgrading/
> Fixed conversion from 1.11 to 1.12.

- pages/1.12/release-notes/1.12.0-beta1/index.md
https://jira.mesosphere.com/browse/DCOS-41672
> Added docs link to multi-kubernetes engine.

- pages/1.12/storage/external-storage/index.md
- pages/1.12/storage/mount-disk-resources/index.md
- pages/1.12/storage/persistent-volume/index.md
https://jira.mesosphere.com/browse/DCOS-42272
Find and update 1.11 references and update as necessary
checked all links to confirm functionality
changed img link and confirmed
- [ x] Medium
> ck/1.12 update Storage section DCOS-42272

- pages/1.12/hybrid-cloud/features/capacity-extension-with-regions/index.md
- pages/1.12/hybrid-cloud/features/cluster-links/index.md
- pages/1.12/hybrid-cloud/features/decommission-nodes/index.md
https://jira.mesosphere.com/browse/DCOS-42276
Check through Hybrid Cloud section and update links and image links where needed
Tested all links
- [ x] Medium
> 1.12 pass on Hybrid Cloud DCOS-42276

- docker/nginx/redirects-301.map
https://jira.mesosphere.com/browse/COPS-3835
> Added regex for version policy.

- pages/1.12/release-notes/1.12.0-beta1/index.md
https://jira.mesosphere.com/browse/DCOS-42314
> Added a deprecated warning in 1.12.0-Beta 1 RN.

- pages/1.12/monitoring/debugging/cli-debugging/index.md
- pages/1.12/monitoring/debugging/debug-perms/index.md
- pages/1.12/monitoring/debugging/gui-debugging/index.md
- pages/1.12/monitoring/debugging/slow-docker/index.md
- pages/1.12/monitoring/debugging/stuck-deployment/index.md
- pages/1.12/monitoring/debugging/task-exec/index.md
- pages/1.12/monitoring/index.md
- pages/1.12/monitoring/logging/access-component-logs/index.md
- pages/1.12/monitoring/logging/access-task-logs/index.md
- pages/1.12/monitoring/logging/aggregating/filter-elk/index.md
- pages/1.12/monitoring/logging/aggregating/filter-splunk/index.md
- pages/1.12/monitoring/logging/index.md
- pages/1.12/monitoring/logging/logging-api-examples/index.md
- pages/1.12/monitoring/logging/logging-api/index.md
- pages/1.12/monitoring/logging/quickstart/index.md
- pages/1.12/monitoring/performance-monitoring/index.md
https://jira.mesosphere.com/browse/DCOS-42279
Merge for Section: Monitoring, Logging, Debugging
- [x ] Medium
> 1.12 edits Monitoring,Logging,Debugging

- scss/shortcodes/_message.scss
Correcting formatting of warnings and notes in scss files.
> Corrected message formats.

- pages/1.12/release-notes/1.12.0-beta1/index.md
https://jira.mesosphere.com/browse/DCOS-41672
> 1.12.0 Beta 1 RN - Updated Datadog entry

- pages/services/edge-lb/1.2/release-notes/index.md
> fixed release notes

- pages/1.10/installing/ent/patching/index.md
- pages/1.10/installing/oss/patching/index.md
https://jira.mesosphere.com/browse/DCOS-42238
> 1.10 - Added supported patching path matrix.

- pages/1.11/release-notes/1.11.0-rc1/index.md
- pages/1.11/release-notes/1.11.0-rc4/index.md
- pages/1.11/release-notes/1.11.0/index.md
- pages/1.11/release-notes/1.11.1/index.md
- pages/1.11/release-notes/1.11.2/index.md
- pages/1.11/release-notes/1.11.3/index.md
- pages/1.11/release-notes/1.11.5/index.md
- pages/1.11/release-notes/1.11.6/index.md
- pages/version-policy/index.md
https://jira.mesosphere.com/browse/DCOS-42089
> 1.11.6 Release Notes

- pages/1.11/release-notes/1.11.6/index.md
> Removed extra bullet.

- pages/services/beta-elastic/1.0.13-5.4.1-beta/api-reference/index.md
- pages/services/beta-elastic/1.0.14-5.5.0-beta/api-reference/index.md
- pages/services/beta-elastic/1.0.15-5.5.1-beta/api-reference/index.md
- pages/services/beta-elastic/2.0.0-5.5.1/api-reference/index.md
- pages/services/cassandra/2.0.1-3.0.14/api-reference/index.md
- pages/services/cassandra/2.0.2-3.0.14/api-reference/index.md
- pages/services/cassandra/2.0.3-3.0.14/api-reference/index.md
- pages/services/cassandra/v2.0.0-3.0.14/api-reference/index.md
- pages/services/elastic/2.0.1-5.5.1/api-reference/index.md
- pages/services/elastic/2.0.2-5.6.2/api-reference/index.md
- pages/services/elastic/2.1.0-5.6.2/api-reference/index.md
- pages/services/elastic/v2.0.0-5.5.1/api-reference/index.md
https://jira.mesosphere.com/browse/DCOS-38573
- [X ] Medium
> Correct link formatting DCOS-38573

- pages/1.11/overview/architecture/components/index.md
- pages/1.12/overview/architecture/components/index.md
https://jira.mesosphere.com/browse/DCOS-42481
change header to ### to match other styling, add backticks where needed for service
- [X ] Medium
> Update header formatting DCOS-42481

- pages/example-snippets/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-3493
> Added code snippet for multi-pod.

- pages/1.10/security/ent/gui-permissions/secrets-tab/index.md
https://jira.mesosphere.com/browse/COPS-3039
> Changed Tip/s to Note.

- pages/1.11/installing/production/system-requirements/docker-centos/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4095
> 1.11 system requirements docs: Changed sudo command.

- pages/example-snippets/index.md
> Fixed layout issue.

- pages/1.11/security/ent/service-auth/custom-service-auth/index.md
- pages/1.12/security/ent/service-auth/custom-service-auth/index.md
https://jira.mesosphere.com/browse/DCOS-42298
> DCOS-42298: add priviledges note about dcos_marathon and dcos_metronome service accounts

- pages/1.11/deploying-services/marathon-on-marathon/advanced/index.md
- pages/1.11/deploying-services/private-docker-registry/index.md
- pages/1.12/deploying-services/marathon-on-marathon/advanced/index.md
> Backport Marathon-on-Marathon EE install instructions to 1.11

- pages/version-policy/index.md
> Add the CLI to the DC/OS compatibility matrix

- js/search.js
- plugins/metalsmith-algolia.js
https://jira.mesosphere.com/browse/DCOS-42301
See a [live build](https://docs-review.mesosphere.com/search)
> DCOS-42301 Search excerpt dcos 42301

- pages/1.12/release-notes/1.12.0-beta1/index.md
https://jira.mesosphere.com/browse/DCOS-42932
> Fixed 404 link in package registry section.

- pages/1.11/installing/production/advanced-configuration/configuration-reference/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-3478
> Updated parameter descriptions section.

- pages/1.11/installing/production/advanced-configuration/configuration-reference/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-3478
> Added ENT tag for license key.

- pages/1.11/release-notes/1.11.5/index.md
https://jira.mesosphere.com/browse/COPS-3810
> 1.11.5 RN - Added a notable change.

- layouts/components/content-grid.pug
https://jira.mesosphere.com/browse/DCOS-42052
Needs testing please
> layouts: hide "hidden" grid children of visible articles

- layouts/components/content-grid.pug
> gOnly skip cards if THAT val is hidden

- pages/1.12/metrics/metrics-api/index.md
https://jira.mesosphere.com/browse/DCOS-43121
> 1.12 metrics API page - Removed Datadog plugin.

- docker/nginx/redirects-301.map
https://jira.mesosphere.com/browse/DCOS-43058
> Added a redirect for 1.12 opt-out page.

- pages/1.12/installing/production/advanced-configuration/configuration-reference/index.md
https://jira.mesosphere.com/browse/COPS-2994
https://docs.mesosphere.com/1.11/installing/production/advanced-configuration/configuration-reference/#license-key-contents-enterprise
https://docs.mesosphere.com/1.12/installing/production/advanced-configuration/configuration-reference/#license-key-contents-enterprise
> 1.12 - Added license key contents.

- pages/services/beta-hdfs/2.1.2-2.6.0-cdh5.11.0-beta/install/index.md
https://jira.mesosphere.com/browse/DCOS-43202
Update beta-hdfs 2.1.2-2.6.0-cdh5.11.0-beta install requirements.
> ss/DCOS-43202 Updating install requirements.

- pages/services/edge-lb/0.1/installing/index.md
- pages/services/edge-lb/1.0/installing/index.md
- pages/services/edge-lb/1.1/installing/index.md
- pages/services/edge-lb/1.2/installing/index.md
- pages/services/include/configuration-install-with-options.tmpl
https://jira.mesosphere.com/browse/DCOS-40392
First pass at trying to fix the install docs for Edge-LB.
Versions affected:
0.1
1.0
1.1
1.2
> ss/DCOS-40326 Correcting install instructions.

- pages/services/spark/v1.0.9-2.1.0-1/hdfs/index.md
- pages/services/spark/v1.1.0-2.1.1/hdfs/index.md
- pages/services/spark/v1.1.1-2.2.0/hdfs/index.md
https://jira.mesosphere.com/browse/DCOS-26200
- [ X] Medium
> ck/DCOS-26200 Update hdfs endpoint in Spark docs

- pages/1.12/deploying-services/multi-tenancy-primitives/index.md
https://jira.mesosphere.com/browse/DCOS-42791
> 1.12 Multi-tenancy Primitives documentation

- pages/1.12/deploying-services/multi-tenancy-primitives/index.md
https://jira.mesosphere.com/browse/DCOS-42791
https://github.com/mesosphere/dcos-docs-site/pull/1555
> 1.12 Multi-tenancy page: Renamed section heading and removed a Note.

- layouts/components/content-grid.pug
- pages/1.12/cli/command-reference/index.md
- pages/1.12/cli/experiments/index.md
- pages/1.12/cli/index.md
- pages/1.12/cli/plugins/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4199
> Br lewis/dcos oss 4199

- index.js
- layouts/partials/sidebar.pug
- pages/1.11/index.md
- pages/1.12/index.md
> Make 1.12 live

- pages/1.12/release-notes/1.12/index.md
https://jira.mesosphere.com/browse/DCOS-42375
> 1.12 Release Notes

- docker/nginx/redirects-301.map
> Added a redirect for 1.12 RN.

- pages/1.11/installing/production/patching/index.md
- pages/1.11/installing/production/upgrading/index.md
- pages/1.12/installing/production/upgrading/index.md
Following data from this matrix here: https://docs.google.com/spreadsheets/d/13YucIODQOvRVlkd8VBh6sUuCelj5HMQ0Yu46sLVhWDQ/edit#gid=0
> Adding upgrade and patching matrices for 1.12 & 1.11

- pages/1.12/release-notes/1.12.0/index.md
Broken link effects 1.12 release
> docs: update correct link

- pages/1.12/release-notes/1.12.0/index.md
> Updated release date on 1.12 RN.

- pages/1.11/hybrid-cloud/fault-domain-awareness-with-zones/index.md
- pages/1.12/hybrid-cloud/fault-domain-awareness-with-zones/index.md
[https://jira.mesosphere.com/browse/COPS-3535](url)
- [ x] Medium
> LG/COPS-3535 Removed duplicated word

- pages/1.12/administering-clusters/repo/package-registry/index.md
> typo remove 'git'

- pages/1.12/release-notes/1.12.0/index.md
Added "Expanded JSON editor view and GPU’s included if deployed in a cluster." in UI/UX enhancements section based on Ian's inputs. 
> Added an entry in UI/UX section.

- pages/version-policy/index.md
> Fixed broken tag in version policy page.

- pages/1.12/metrics/metrics-api/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4330
> Added an important note for Metrics API.

- pages/1.12/release-notes/1.12.0/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4408
> 1.12 RN - Updated Metrics content.

- pages/1.10/installing/production/deploying-dcos/installation/index.md
- pages/1.11/installing/production/deploying-dcos/installation/index.md
- pages/1.12/installing/production/deploying-dcos/installation/index.md
https://jira.mesosphere.com/browse/DCOS-44132
> Fixed broken links.

- pages/1.10/installing/production/system-requirements/index.md
- pages/1.11/installing/production/system-requirements/index.md
- pages/1.12/installing/production/system-requirements/index.md
https://jira.mesosphere.com/browse/COPS-3983
> Added a note about nscd.

- pages/1.11/release-notes/1.11.0-rc1/index.md
- pages/1.11/release-notes/1.11.0-rc4/index.md
- pages/1.11/release-notes/1.11.0/index.md
- pages/1.11/release-notes/1.11.1/index.md
- pages/1.11/release-notes/1.11.2/index.md
- pages/1.11/release-notes/1.11.3/index.md
- pages/1.11/release-notes/1.11.4/index.md
- pages/1.11/release-notes/1.11.5/index.md
- pages/1.11/release-notes/1.11.6/index.md
- pages/1.11/release-notes/1.11.7/index.md
https://jira.mesosphere.com/browse/DCOS-44232
> Content development for 1.11.7 RN.

- pages/1.11/release-notes/1.11.5/index.md
> Fixed display issues.

- pages/1.11/installing/production/advanced-configuration/configuration-reference/index.md
- pages/1.11/installing/production/deploying-dcos/configuration/index.md
- pages/1.11/monitoring/logging/index.md
- pages/1.11/monitoring/logging/logging-api/index.md
- pages/1.12/installing/production/advanced-configuration/configuration-reference/index.md
- pages/1.12/monitoring/logging/index.md
- pages/1.12/monitoring/logging/logging-api/index.md
https://jira.mesosphere.com/browse/COPS-3594
> Addressed comments on COPS-3594.

- pages/1.10/installing/production/index.md
- pages/1.11/installing/production/index.md
- pages/1.12/installing/production/index.md
> Added login info for config files.

- pages/1.12/release-notes/1.12.0/index.md
> ck/DCOS-44363 Add punctuation

- pages/1.12/release-notes/1.12.0/index.md
> Moved issues into Notable Changes section.

- pages/1.10/release-notes/1.10.0-beta1/index.md
- pages/1.10/release-notes/1.10.0-beta2/index.md
- pages/1.10/release-notes/1.10.0-rc1/index.md
- pages/1.10/release-notes/1.10.0/index.md
- pages/1.10/release-notes/1.10.1/index.md
- pages/1.10/release-notes/1.10.2/index.md
- pages/1.10/release-notes/1.10.3/index.md
- pages/1.10/release-notes/1.10.4/index.md
- pages/1.10/release-notes/1.10.5/index.md
- pages/1.10/release-notes/1.10.6/index.md
- pages/1.10/release-notes/1.10.8/index.md
- pages/1.10/release-notes/1.10.9/index.md
https://jira.mesosphere.com/browse/DCOS-44269
> 1.10.9 Release Notes

- pages/1.11/monitoring/logging/aggregating/splunk/index.md
- pages/1.12/monitoring/logging/aggregating/splunk/index.md
[https://jira.mesosphere.com/browse/DCOS-44106](url)
- [x ] Medium
> LG/DCOS-44106 Changed format for important paragraph

- pages/1.12/release-notes/1.12.0/index.md
> Changed format in RN.

- pages/services/confluent-kafka/2.4.0-4.1.1/advanced/index.md
- pages/services/confluent-kafka/2.4.0-4.1.1/api-reference/index.md
- pages/services/confluent-kafka/2.4.0-4.1.1/configuration/index.md
- pages/services/confluent-kafka/2.4.0-4.1.1/getting-started/index.md
- pages/services/confluent-kafka/2.4.0-4.1.1/index.md
- pages/services/confluent-kafka/2.4.0-4.1.1/limitations/index.md
- pages/services/confluent-kafka/2.4.0-4.1.1/operations/index.md
- pages/services/confluent-kafka/2.4.0-4.1.1/release-notes/index.md
- pages/services/confluent-kafka/2.4.0-4.1.1/security/index.md
- pages/services/confluent-kafka/2.4.0-4.1.1/support-policy/index.md
- pages/services/confluent-kafka/2.4.0-4.1.1/troubleshooting/index.md
- pages/services/confluent-kafka/2.4.0-4.1.1/uninstall/index.md
- pages/services/confluent-kafka/2.4.0-4.1.1/updates/index.md
https://jira.mesosphere.com/browse/DCOS-43919
> [DCOS-43919] Release Confluent Kafka 2.4.0-4.1.1

- pages/services/cassandra/2.4.0-3.0.16/advanced/index.md
- pages/services/cassandra/2.4.0-3.0.16/api-reference/index.md
- pages/services/cassandra/2.4.0-3.0.16/configuration/index.md
- pages/services/cassandra/2.4.0-3.0.16/getting-started/index.md
- pages/services/cassandra/2.4.0-3.0.16/index.md
- pages/services/cassandra/2.4.0-3.0.16/limitations/index.md
- pages/services/cassandra/2.4.0-3.0.16/operations/index.md
- pages/services/cassandra/2.4.0-3.0.16/release-notes/index.md
- pages/services/cassandra/2.4.0-3.0.16/security/index.md
- pages/services/cassandra/2.4.0-3.0.16/support-policy/index.md
- pages/services/cassandra/2.4.0-3.0.16/troubleshooting/index.md
- pages/services/cassandra/2.4.0-3.0.16/uninstall/index.md
- pages/services/cassandra/2.4.0-3.0.16/updates/index.md
https://jira.mesosphere.com/browse/DCOS-43384
> [DCOS-43384] release cassandra 2.4.0-3.0.16

- pages/services/dse/2.4.0-5.1.10/advanced/index.md
- pages/services/dse/2.4.0-5.1.10/api-reference/index.md
- pages/services/dse/2.4.0-5.1.10/configuration/index.md
- pages/services/dse/2.4.0-5.1.10/getting-started/index.md
- pages/services/dse/2.4.0-5.1.10/index.md
- pages/services/dse/2.4.0-5.1.10/limitations/index.md
- pages/services/dse/2.4.0-5.1.10/operations/index.md
- pages/services/dse/2.4.0-5.1.10/release-notes/index.md
- pages/services/dse/2.4.0-5.1.10/security/index.md
- pages/services/dse/2.4.0-5.1.10/support-policy/index.md
- pages/services/dse/2.4.0-5.1.10/troubleshooting/index.md
- pages/services/dse/2.4.0-5.1.10/uninstall/index.md
- pages/services/dse/2.4.0-5.1.10/updates/index.md
https://jira.mesosphere.com/browse/DCOS-43590
> [DCOS-43590] Release dse 2.4.0-5.1.10

- pages/1.10/security/ent/index.md
- pages/1.11/security/ent/index.md
- pages/1.12/security/ent/index.md
- pages/1.9/security/ent/index.md
https://jira.mesosphere.com/browse/DCOS-44713
- [x ] Medium
> ck/DCOS-44713 Removed sentence for clarity

- pages/services/kubernetes/1.3.0-1.10.8/kubernetes-dashboard/index.md
- pages/services/kubernetes/1.3.1-1.10.8/kubernetes-dashboard/index.md
- scripts/service-update-scripts/kubernetes-1x-merge-branch.sh
https://jira.mesosphere.com/browse/COPS-3935
> kubernetes: [COPS-3935] add recommended dashboard deployment

- pages/1.10/release-notes/1.10.0-beta1/index.md
- pages/1.10/release-notes/1.10.0-beta2/index.md
- pages/1.10/release-notes/1.10.0-rc1/index.md
- pages/1.10/release-notes/1.10.0/index.md
- pages/1.10/release-notes/1.10.1/index.md
- pages/1.10/release-notes/1.10.2/index.md
- pages/1.10/release-notes/1.10.3/index.md
- pages/1.10/release-notes/1.10.4/index.md
- pages/1.10/release-notes/1.10.5/index.md
- pages/1.10/release-notes/1.10.6/index.md
- pages/1.10/release-notes/1.10.7/index.md
- pages/1.10/release-notes/1.10.8/index.md
- pages/1.10/release-notes/1.10.9/index.md
https://jira.mesosphere.com/browse/DCOS-26186
- [ x] High
> ck/DCOS-26816 Update 1.10 RNs for a breaking change

- pages/services/percona-server-mongodb/0.4.1-3.6.8/api-reference/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/connecting-clients/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/deploy-best-practice/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/disaster-recovery/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/getting-started/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/known-issues/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/limitations/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/managing/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/mongodb-administration/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/quick-start/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/release-notes/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/support/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/terms-of-use/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/troubleshooting/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/uninstall/index.md
Docs for percona-server-mongodb 0.4.1-3.6.8
CC @ryadav88
> percona-server-mongodb 0.4.1-3.6.8

- pages/services/edge-lb/1.1/upgrading/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/api-reference/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/connecting-clients/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/deploy-best-practice/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/disaster-recovery/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/getting-started/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/known-issues/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/limitations/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/managing/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/mongodb-administration/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/quick-start/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/release-notes/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/support/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/terms-of-use/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/troubleshooting/index.md
- pages/services/percona-server-mongodb/0.4.1-3.6.8/uninstall/index.md
- pages/services/percona-server-mongodb/data.yml
- pages/services/percona-server-mongodb/index.md
https://jira.mesosphere.com/browse/DCOS-44642
Docs for percona-server-mongodb 0.4.1-3.6.8
> Percona lab percona server mongodb 0.4.1 3.6.8

- pages/1.12/deploying-services/multi-tenancy-primitives/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4458
> LG/DCOS_OSS-4458 Add Support, change deploying to deploy, remove Latin

- pages/1.12/installing/evaluation/mesosphere-supported-methods/gcp/index.md
https://jira.mesosphere.com/browse/DCOS-44090
- [X ] High
> Fixup install method main.tf file ref.

- pages/1.12/networking/SDN/cni-plugins/index.md
- pages/1.12/release-notes/1.12.0/index.md
https://jira.mesosphere.com/browse/DCOS-44762
> DCOS-44762 Update Networking's RNs

- pages/services/edge-lb/1.2/uninstalling/index.md
https://github.com/mesosphere/dcos-docs-site/pull/1690
Fixing formatting isue that made everything boldface.
> Correcting format issue in uninstall page.

- pages/services/edge-lb/1.2/uninstalling/index.md
Fixing misspelled word on uninstall page.
> Correcting misspelled word.

- pages/version-policy/index.md
https://jira.mesosphere.com/browse/COPS-4114
> add k8s kmem 7.5 warning note

- pages/1.12/release-notes/1.12.0/index.md
https://jira.mesosphere.com/browse/COPS-4094
- [x ] High
> ck/COPS-4094 AdK8s release notes

- pages/1.12/cli/enterprise-cli/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4500
https://jira.mesosphere.com/browse/COPS-4138
- [ X] High
> DC_OSS-4500 - add ent cli pages and edit for 1.12.

- pages/1.12/release-notes/1.12.0/index.md
> ck/DCOS-44527 update note on EE download

- pages/1.12/installing/production/system-requirements/docker-centos/index.md
https://jira.mesosphere.com/browse/DCOS-44764
- [x ] High
> ck/DCOS-44764 Docker 1.13 install

- pages/version-policy/index.md
https://jira.mesosphere.com/browse/COPS-4114
- [X ] High
> Fix link typo

- pages/1.12/release-notes/1.12.0/index.md
> ck/DCOS-44527 Update wording on note

- pages/1.11/tutorials/dcos-debug/index.md
> flush master cache

- pages/1.12/installing/production/patching/index.md
[https://jira.mesosphere.com/browse/COPS-4154](https://jira.mesosphere.com/browse/COPS-4154)
- [ x] Blocker 
> COPS-4154 Correct dcos generate node update script

- pages/1.12/api/nginx.agent.yaml
- pages/1.12/api/nginx.master.yaml
- pages/1.12/cli/command-reference/dcos-backup/index.md
- pages/1.12/cli/command-reference/dcos-help/index.md
[https://jira.mesosphere.com/browse/DCOS_OSS-4410](https://jira.mesosphere.com/browse/DCOS_OSS-4410)
- [ x] Medium
> ck/DCOS_OSS-4410 Correct links

- pages/services/dcos-monitoring/0.1.0/index.md
- pages/services/dcos-monitoring/0.1.0/install/index.md
- pages/services/dcos-monitoring/0.1.0/tutorial/alertmanager-configs/index.md
- pages/services/dcos-monitoring/0.1.0/tutorial/grafana-dashboard-configs/index.md
- pages/services/dcos-monitoring/0.1.0/tutorial/index.md
- pages/services/dcos-monitoring/0.1.0/uninstall/index.md
- pages/services/dcos-monitoring/index.md
DC/OS Monitoring Service v0.1.0 release.
> dcos-monitoring: Update docs for 0.1.0

- pages/1.10/metrics/reference/index.md
- pages/1.11/metrics/reference/index.md
- pages/1.12/metrics/reference/index.md
https://jira.mesosphere.com/browse/COPS-4071
> LG/COPS-4071 Disclaimer for Docker network metrics

- pages/1.10/tutorials/index.md
> Changed tutorial intro in 1.10.

- pages/1.10/cli/install/index.md
- pages/1.10/cli/update/index.md
- pages/1.11/cli/install/index.md
- pages/1.11/cli/update/index.md
- pages/1.12/cli/install/index.md
- pages/1.12/cli/update/index.md
- pages/1.8/usage/cli/update/index.md
- pages/1.9/cli/install/index.md
- pages/1.9/cli/update/index.md
https://jira.mesosphere.com/browse/DCOS-25683
> LG/DCOS-25683 Modify update CLi instructions

- pages/1.12/installing/evaluation/mesosphere-supported-methods/aws/aws-advanced/index.md
https://jira.mesosphere.com/browse/DCOS-44613
Hello, the Universal Installer team would like to add the following pages to our documentation based on feedback from customers and field:
https://docs.mesosphere.com/1.12/installing/evaluation/mesosphere-supported-methods/
- [x High
Created new page, added text and tables as desired. Table overflows bounds of work site; working on this with other Tech Writers.
> ss/DCOS-44613 Creating new page for Advanced AWS.

- pages/1.12/installing/evaluation/mesosphere-supported-methods/gcp/advanced-gcp/index.md
https://jira.mesosphere.com/browse/DCOS-44615
Hello, the Universal Installer team would like to add the following pages to our documentation based on feedback from customers and field:
https://docs.mesosphere.com/1.12/installing/evaluation/mesosphere-supported-methods/
Added page as requested. Still working on table cell wrap problem.
> ss/DCOS-46615 Adding page on Advanced GCP to installation docs.

- pages/cn/1.11/cli/command-reference/dcos-task/dcos-task-exec/index.md
https://jira.mesosphere.com/browse/DCOS-42180
Fix format error
> ss/DCOS-42180  Fix error in Chinese doc

- pages/services/marathon-lb/advanced/index.md
[https://jira.mesosphere.com/browse/COPS-4158](https://jira.mesosphere.com/browse/COPS-4158)
- [X ] High
> ck/COPS-4158 Update Haproxy_Head script in example

- pages/1.12/cli/experiments/index.md
https://jira.mesosphere.com/browse/DCOS-45343
- [ X] Medium
> ck/DCOS-45343 Add link to local universe

- pages/1.12/installing/evaluation/mesosphere-supported-methods/azure/advanced-azure/index.md
https://jira.mesosphere.com/browse/DCOS-44616
The Universal Installer team would like to add the following pages to our documentation based on feedback from customers and field:
Added page, added contents as noted.
> ss/DCOS-44616 Adding Advanced Azure page to install docs.

- pages/services/cassandra/2.3.0-3.0.16/limitations/index.md
https://jira.mesosphere.com/browse/COPS-4179
> LG/COPS-4179 Fix missing node count variable for Cassandra

- pages/1.12/administering-clusters/repo/package-registry/operating/planning/index.md
https://jira.mesosphere.com/browse/DCOS-45713
- [ X] High
> Add 443 port address to snippet.

- pages/1.12/installing/production/advanced-configuration/configuration-reference/index.md
https://jira.mesosphere.com/browse/COPS-4200
- [x ] High
> COPS-4200: Correct yaml formatting for 'dns_forward_zones'.

- pages/1.12/cli/command-reference/dcos-task/dcos-task-attach/index.md
https://jira.mesosphere.com/browse/COPS-4020
- [ x] High
> ck/COPS-4020 Add task attach page

- pages/services/kubernetes/2.1.0-1.12.3/getting-started/install-basic/index.md
> ck Add test page of k8s in 2.10-1.12.13

- Makefile
- docker/Dockerfile.docs
- docker/docker-compose.production.yml
- scripts/build-site.sh
https://jira.mesosphere.com/browse/DCOS-39232
https://jira.mesosphere.com/browse/DCOS-25476
> Link checker

- pages/1.12/administering-clusters/repo/package-registry/index.md
- pages/1.12/administering-clusters/repo/package-registry/operating/index.md
- pages/1.12/administering-clusters/repo/package-registry/operating/installing/index.md
- pages/1.12/administering-clusters/repo/package-registry/operating/managing/index.md
- pages/1.12/administering-clusters/repo/package-registry/operating/planning/index.md
- pages/1.12/administering-clusters/repo/package-registry/quickstart/index.md
https://jira.mesosphere.com/browse/COPS-4101
- [x ] Medium
> Remove beta tags.

- docker/docker-compose.production.yml
- scripts/build-site.sh
> Replace latest links with 1.12

- pages/services/kubernetes/2.0.0-1.12.1/getting-started/install-basic/index.md
- pages/services/kubernetes/2.0.1-1.12.2/getting-started/install-basic/index.md
- pages/services/kubernetes/2.1.0-1.12.3/getting-started/install-basic/index.md
https://jira.mesosphere.com/browse/COPS-4199
Reported broken link in one page, scoped and found others in related pages
- [ x] High
> ck/COPS-4199 Fix broken links in k8s getting-started

- pages/services/marathon-lb/advanced/index.md
https://jira.mesosphere.com/browse/COPS-4212
> LG/COPS-4212 Modify settings to make true a string

- pages/1.12/monitoring/debugging/slow-docker/index.md
[https://jira.mesosphere.com/browse/COPS-4045](https://jira.mesosphere.com/browse/COPS-4045)
- [ x] Medium
> ck/COPS-4045 Update cpu scheduling page

- pages/1.12/deploying-jobs/metronome-constraints/index.md
- pages/1.12/deploying-jobs/running-jobs-in-remote-regions/index.md
- pages/1.12/deploying-services/fault-domain-awareness/index.md
- pages/1.12/deploying-services/marathon-constraints/index.md
Document which operators are supported by Metronome, and talks about region and zone support.
JIRA Issues: DCOS_OSS-4455
> Add documentation for constraints in Metronome

- pages/1.12/installing/evaluation/mesosphere-supported-methods/aws/index.md
> PR into docs-christina

- pages/1.10/deploying-services/task-handling/configure-task-handling/index.md
- pages/1.11/deploying-services/marathon-parameters/index.md
- pages/1.11/deploying-services/task-handling/configure-task-handling/index.md
- pages/1.12/deploying-services/marathon-parameters/index.md
- pages/1.12/deploying-services/task-handling/configure-task-handling/index.md
- pages/1.9/deploying-services/task-handling/configure-task-handling/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4549
- [x ] High
> ck/DCOS-OSS-4549 update defaults for unreachableStrategy

- pages/1.12/installing/evaluation/index.md
- pages/1.12/installing/evaluation/mesosphere-supported-methods/aws/index.md
- pages/1.12/installing/evaluation/mesosphere-supported-methods/index.md
- pages/1.12/installing/index.md
> Install rewrites

- pages/services/beta-jupyter/installing/index.md
https://jira.mesosphere.com/browse/DCOS-46172
> LG/DCOS-41672 Beta-Jupyter - Fix the GUI installation text

- pages/1.10/cli/command-reference/dcos-marathon/dcos-marathon-app-update/index.md
- pages/1.11/cli/command-reference/dcos-marathon/dcos-marathon-app-update/index.md
- pages/1.12/cli/command-reference/dcos-marathon/dcos-marathon-app-update/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4457
> LG/DCOS_OSS-4457 Changed the command description from add to update

- pages/1.10/installing/production/upgrading/index.md
- pages/1.11/installing/production/upgrading/index.md
- pages/1.12/installing/production/upgrading/index.md
https://jira.mesosphere.com/browse/COPS-4265
> Added a link for ZooKeeper backup using Guano

- pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/managing/index.md
- pages/services/beta-kafka-zookeeper/2.1.0-3.4.11-beta/api-reference/index.md
- pages/services/beta-kafka-zookeeper/2.1.0-3.4.11-beta/connecting-clients/index.md
- pages/services/beta-kafka-zookeeper/2.1.0-3.4.11-beta/kerberos/index.md
- pages/services/beta-kafka-zookeeper/2.1.0-3.4.11-beta/managing/index.md
- pages/services/beta-kafka-zookeeper/2.1.0-3.4.11-beta/troubleshooting/index.md
- pages/services/beta-kafka-zookeeper/2.1.0-3.4.11-beta/uninstall/index.md
- pages/services/beta-kafka-zookeeper/2.1.1-3.4.11-beta/install/index.md
- pages/services/beta-kafka-zookeeper/2.1.1-3.4.11-beta/kerberos/index.md
- pages/services/beta-kafka-zookeeper/2.1.1-3.4.11-beta/managing/index.md
- pages/services/beta-kafka-zookeeper/2.1.1-3.4.11-beta/quick-start/index.md
- pages/services/beta-kafka-zookeeper/2.1.1-3.4.11-beta/uninstall/index.md
- pages/services/beta-kafka-zookeeper/2.1.2-3.4.11-beta/api-reference/index.md
- pages/services/beta-kafka-zookeeper/2.1.2-3.4.11-beta/connecting-clients/index.md
- pages/services/beta-kafka-zookeeper/2.1.2-3.4.11-beta/install/index.md
- pages/services/beta-kafka-zookeeper/2.1.2-3.4.11-beta/kerberos/index.md
- pages/services/beta-kafka-zookeeper/2.1.2-3.4.11-beta/managing/index.md
- pages/services/beta-kafka-zookeeper/2.1.2-3.4.11-beta/quick-start/index.md
- pages/services/beta-kafka-zookeeper/2.1.2-3.4.11-beta/troubleshooting/index.md
- pages/services/beta-kafka/2.1.0-1.0.0-beta/install/index.md
- pages/services/beta-kafka/2.1.0-1.0.0-beta/kerberos/index.md
- pages/services/beta-kafka/2.1.1-1.0.0-beta/install/index.md
- pages/services/beta-kafka/2.1.1-1.0.0-beta/kerberos/index.md
- pages/services/beta-kafka/2.1.2-1.0.0-beta/install/index.md
- pages/services/beta-kafka/2.1.2-1.0.0-beta/kerberos/index.md
https://jira.mesosphere.com/browse/COPS-2199
> LG/COPS-2199 checking for package name, changed note styles

- pages/1.12/administering-clusters/repo/package-registry/index.md
https://jira.mesosphere.com/browse/DCOS-46293
> Added a note in 1.12 package registry.

- pages/1.12/release-notes/1.12.1/index.md
https://jira.mesosphere.com/browse/DCOS-46539
> LG/RN-1.12.1-A Update download link.

- pages/1.12/installing/production/deploying-dcos/installation/index.md
> Fix fault_domain

- pages/services/beta-storage/0.5.1-beta/upgrades/index.md
https://jira.mesosphere.com/browse/DCOS-46503
Storage docs fixes. These changes were already reviewed as per https://github.com/mesosphere/dcos-storage/pull/343
> storage: update storage doc for 0.5.1

- pages/services/kubernetes/2.1.0-1.12.3/getting-started/config-edgelb-for-k8s/index.md
https://jira.mesosphere.com/browse/DCOS-46624
> Changed Edge-LB download link in K8s doc page.

- pages/version-policy/index.md
Update entries for Beta and Certified Packages
Note: This PR includes the fix for the merge conflict from https://github.com/mesosphere/dcos-docs-site/pull/1846 which can be closed in favor of this PR
> Update entries for Beta and Certified Packages

- pages/services/kafka/2.3.0-1.1.0/security/index.md
https://jira.mesosphere.com/browse/COPS-4349
> Added an example of json-encoded CSR.

- pages/services/kafka/2.3.0-1.1.0/security/index.md
> Added include to security accounts and permissions sections.

- pages/1.12/installing/production/deploying-dcos/configuration/index.md
Wanted to go to this link and discovered that it was broken :)
> Fix broken "bootstrap node" link

- pages/services/jenkins/3.5.3-2.150.1/release-notes/index.md
https://jira.mesosphere.com/browse/DCOS-46679
> Release notes for Jenkins 3.5.3 2.150.1

- pages/version-policy/index.md
https://jira.mesosphere.com/browse/DCOS-47307
> Added DC/OS 1.12.0 qualification on RHEL 7.6 to version policy matrix.

- pages/version-policy/index.md
https://jira.mesosphere.com/browse/DCOS-47305
> Undo PR 1884.

- pages/services/beta-dcos-monitoring/0.4.0-beta/release-notes/index.md
Update the release notes for the v0.4.0 release.
> beta-dcos-monitoring: Update docs for 0.4.0-beta

- pages/services/hdfs/2.5.0-2.6.0-cdh5.11.0/api-reference/index.md
- pages/services/hdfs/2.5.0-2.6.0-cdh5.11.0/getting-started/index.md
- pages/services/hdfs/2.5.0-2.6.0-cdh5.11.0/index.md
- pages/services/hdfs/2.5.0-2.6.0-cdh5.11.0/limitations/index.md
- pages/services/hdfs/2.5.0-2.6.0-cdh5.11.0/operations/configuration/index.md
- pages/services/hdfs/2.5.0-2.6.0-cdh5.11.0/operations/index.md
- pages/services/hdfs/2.5.0-2.6.0-cdh5.11.0/operations/security/index.md
- pages/services/hdfs/2.5.0-2.6.0-cdh5.11.0/operations/troubleshooting/index.md
- pages/services/hdfs/2.5.0-2.6.0-cdh5.11.0/operations/uninstall/index.md
- pages/services/hdfs/2.5.0-2.6.0-cdh5.11.0/operations/updates/index.md
- pages/services/hdfs/2.5.0-2.6.0-cdh5.11.0/overview/index.md
- pages/services/hdfs/2.5.0-2.6.0-cdh5.11.0/release-notes/index.md
- pages/services/hdfs/2.5.0-2.6.0-cdh5.11.0/support-policy/index.md
> Release HDFS 2.5.0-2.6.0-cdh5.11.0

- pages/services/hdfs/2.4.0-2.6.0-cdh5.11.0/index.md
https://jira.mesosphere.com/browse/COPS-4372
> Quick edit on HDFS file.

- pages/services/kubernetes/2.1.1-1.12.4/getting-started/config-edgelb-for-k8s/index.md
https://jira.mesosphere.com/browse/DCOS-47656
> Changed Edge-LB download link in K8s page.

- pages/services/cassandra/2.4.0-3.0.16/getting-started/index.md
- pages/services/elastic/2.3.1-5.6.5/getting-started/index.md
- pages/services/hdfs/2.0.4-2.6.0-cdh5.11.0/install/index.md
- pages/services/hdfs/2.4.0-2.6.0-cdh5.11.0/getting-started/index.md
- pages/services/kafka/2.3.0-1.1.0/started/index.md
https://jira.mesosphere.com/browse/DCOS-46318
> Revert/Fix use of generic templates for data-services docs

- pages/1.10/release-notes/1.10.10/index.md
- pages/services/marathon-lb/data.yml
- pages/services/marathon-lb/mlb-install/index.md
https://jira.mesosphere.com/browse/DCOS-46836
> LG/DCOS-46836 - DRAFT content for 1.10.10 release notes

- pages/services/beta-dcos-monitoring/0.4.1-beta/data.yml
- pages/services/beta-dcos-monitoring/0.4.1-beta/data.yml.tmpl
- pages/services/beta-dcos-monitoring/0.4.1-beta/getting-started/index.md
- pages/services/beta-dcos-monitoring/0.4.1-beta/index.md
- pages/services/beta-dcos-monitoring/0.4.1-beta/index.md.tmpl
- pages/services/beta-dcos-monitoring/0.4.1-beta/operations/alertmanager/config/index.md
- pages/services/beta-dcos-monitoring/0.4.1-beta/operations/alertmanager/index.md
- pages/services/beta-dcos-monitoring/0.4.1-beta/operations/alertmanager/ui/index.md
- pages/services/beta-dcos-monitoring/0.4.1-beta/operations/grafana/dashboard-configs/index.md
- pages/services/beta-dcos-monitoring/0.4.1-beta/operations/grafana/default-dashboards/index.md
- pages/services/beta-dcos-monitoring/0.4.1-beta/operations/grafana/index.md
- pages/services/beta-dcos-monitoring/0.4.1-beta/operations/grafana/ui/index.md
- pages/services/beta-dcos-monitoring/0.4.1-beta/operations/index.md
- pages/services/beta-dcos-monitoring/0.4.1-beta/operations/install/index.md
- pages/services/beta-dcos-monitoring/0.4.1-beta/operations/placement-constraint/index.md
- pages/services/beta-dcos-monitoring/0.4.1-beta/operations/prometheus/alert-rules/index.md
- pages/services/beta-dcos-monitoring/0.4.1-beta/operations/prometheus/index.md
- pages/services/beta-dcos-monitoring/0.4.1-beta/operations/prometheus/storage/index.md
- pages/services/beta-dcos-monitoring/0.4.1-beta/operations/prometheus/ui/index.md
- pages/services/beta-dcos-monitoring/0.4.1-beta/operations/uninstall/index.md
- pages/services/beta-dcos-monitoring/0.4.1-beta/release-notes/index.md
DC/OS monitoring service v0.4.1 release.
> beta-dcos-monitoring: Update docs for 0.4.1-beta

- pages/1.10/installing/production/advanced-configuration/configuration-reference/index.md
- pages/1.11/installing/production/advanced-configuration/configuration-reference/index.md
- pages/1.12/installing/production/advanced-configuration/configuration-reference/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4672
> Lg/dcos oss 4672 network_cni_root_dir_persist config option

- pages/1.11/release-notes/1.11.0/index.md
- pages/1.11/release-notes/1.11.1/index.md
- pages/1.11/release-notes/1.11.2/index.md
- pages/1.11/release-notes/1.11.3/index.md
- pages/1.11/release-notes/1.11.4/index.md
- pages/1.11/release-notes/1.11.5/index.md
- pages/1.11/release-notes/1.11.6/index.md
- pages/1.11/release-notes/1.11.7/index.md
- pages/1.11/release-notes/1.11.8/index.md
- pages/1.11/release-notes/1.11.9/index.md
https://jira.mesosphere.com/browse/DCOS-47761
> Moved the ENT tags after the period.

- pages/1.12/cli/autocompletion/index.md
> Fixed typo in autocompletion docs.

- pages/1.10/installing/evaluation/aws/index.md
- pages/1.11/installing/evaluation/aws/index.md
- pages/1.12/installing/evaluation/aws/index.md
https://jira.mesosphere.com/browse/DCOS-47316
Updated PR to provide clear change-set
- [ x] Medium
> DCOS-47316 SSH changes

- pages/services/edge-lb/1.0/upgrading/index.md
- pages/services/edge-lb/1.1/upgrading/index.md
- pages/services/edge-lb/1.2/upgrading/index.md
> edge-lb upgrade

- pages/services/edge-lb/1.0/uninstalling/index.md
- pages/services/edge-lb/1.1/uninstalling/index.md
- pages/services/edge-lb/1.2/uninstalling/index.md
https://jira.mesosphere.com/browse/DCOS-48123
> LG/DCOS-48123 change syntax for deleting a names Edge-LB pool

- pages/1.10/deploying-services/creating-services/deploy-docker-app/index.md
- pages/1.10/deploying-services/expose-service/index.md
- pages/1.10/tutorials/autoscaling/requests-second/index.md
- pages/1.10/tutorials/iot_pipeline/index.md
- pages/1.11/deploying-services/creating-services/deploy-docker-app/index.md
- pages/1.11/deploying-services/expose-service/index.md
- pages/1.11/tutorials/autoscaling/requests-second/index.md
- pages/1.12/deploying-services/creating-services/deploy-docker-app/index.md
- pages/1.12/deploying-services/expose-service/index.md
- pages/1.12/tutorials/autoscaling/requests-second/index.md
- pages/1.12/tutorials/iot_pipeline/index.md
- pages/1.13/deploying-services/creating-services/deploy-docker-app/index.md
- pages/1.13/deploying-services/expose-service/index.md
- pages/1.13/tutorials/autoscaling/requests-second/index.md
- pages/1.13/tutorials/iot_pipeline/index.md
- pages/1.9/deploying-services/creating-services/deploy-docker-app/index.md
- pages/1.9/deploying-services/expose-service/index.md
- pages/1.9/tutorials/autoscaling/requests-second/index.md
- pages/1.9/tutorials/iot_pipeline/index.md
- pages/cn/1.11/deploying-services/creating-services/deploy-docker-app/index.md
- pages/cn/1.11/deploying-services/expose-service/index.md
- pages/cn/1.11/tutorials/autoscaling/requests-second/index.md
- pages/cn/services/Marathon-LB/usage-ee/index.md
- pages/cn/services/Marathon-LB/usage-oss/index.md
https://jira.mesosphere.com/browse/DCOS-48143
> LG/marathon-lb-links Change links for renamed folders

- pages/1.10/installing/evaluation/aws/aws-advanced/index.md
- pages/1.11/installing/evaluation/aws/aws-advanced/index.md
- pages/1.12/installing/evaluation/aws/aws-advanced/index.md
- pages/1.13/installing/evaluation/aws/aws-advanced/index.md
Add docs about new installer config variables.
> Update docs about new installer config variables.

- pages/services/edge-lb/1.3/upgrading/index.md
https://jira.mesosphere.com/browse/DCOS-48214
> LG/DCOS-48214 Remove -aws from command strings (request-Mike Jennings)

- pages/1.12/installing/production/virt-infra/index.md
> je/quickfixmenutitle1: lengthen title.

- pages/services/hdfs/2.5.0-2.6.0-cdh5.11.0/index.md
> Fixed typo in HDFS doc.

- pages/1.13/cli/command-reference/dcos-marathon/dcos-marathon-task-list/index.md
- pages/1.13/cli/command-reference/dcos-service/index.md
- pages/1.13/cli/command-reference/dcos-task/index.md
This adds more context on the CLI command references related to apps,
tasks and services.
https://jira.mesosphere.com/browse/DCOS-17278
> Add a clarification regarding tasks/apps/services

- pages/version-policy/index.md
Account for releases of EdgeLB 1.3.0, Elastic 6.3.2, HDFS 5.11.0, Kubernetes 1.13.3 and Spark 2.3.2
cc @razi-malik @chrisgaun
> Update certified package versions

- pages/1.12/api/access/index.md
- pages/1.12/deploying-services/expose-service/index.md
- pages/1.12/tutorials/dcos-101/loadbalancing/index.md
https://jira.mesosphere.com/browse/DCOS-48457
> Fixed Marathon-LB broken links in 1.12 docs

- pages/1.10/release-notes/1.10.11/index.md
- pages/1.11/release-notes/1.11.10/index.md
https://jira.mesosphere.com/browse/DCOS-48309
> LG/RN-security-link-fix Add a new line between download buttons

- docker/nginx/redirects-301.map
- pages/1.7/index.md
- pages/1.8/index.md
> Add landing pages and redirects for 1.7 and 1.8

- pages/version-policy/index.md
https://jira.mesosphere.com/browse/DCOS-48484
> Updated Version Policy Matrix with runc/Day 0 vulernabilities.

- pages/version-policy/index.md
https://jira.mesosphere.com/browse/DCOS-48512
> Added CoreOS 1967.6.0 & RHEL 7.6, 7.5, & 7.4 to the version policy page

- docker/nginx/redirects-301.map
https://jira.mesosphere.com/browse/COPS-4519
> Add redirect for custom-service-auth.

- pages/version-policy/index.md
> Fixing CoreOS version.

- pages/1.11/installing/production/patching/index.md
- pages/1.12/installing/production/patching/index.md
https://jira.mesosphere.com/browse/COPS-4188
> LG/COPS-4188-new Change the example for modifying the configuration

- pages/services/beta-dcos-monitoring/0.4.3-beta/data.yml
- pages/services/beta-dcos-monitoring/0.4.3-beta/data.yml.tmpl
- pages/services/beta-dcos-monitoring/0.4.3-beta/getting-started/index.md
- pages/services/beta-dcos-monitoring/0.4.3-beta/index.md
- pages/services/beta-dcos-monitoring/0.4.3-beta/index.md.tmpl
- pages/services/beta-dcos-monitoring/0.4.3-beta/operations/alertmanager/config/index.md
- pages/services/beta-dcos-monitoring/0.4.3-beta/operations/alertmanager/index.md
- pages/services/beta-dcos-monitoring/0.4.3-beta/operations/alertmanager/ui/index.md
- pages/services/beta-dcos-monitoring/0.4.3-beta/operations/grafana/dashboard-configs/index.md
- pages/services/beta-dcos-monitoring/0.4.3-beta/operations/grafana/default-dashboards/index.md
- pages/services/beta-dcos-monitoring/0.4.3-beta/operations/grafana/index.md
- pages/services/beta-dcos-monitoring/0.4.3-beta/operations/grafana/ui/index.md
- pages/services/beta-dcos-monitoring/0.4.3-beta/operations/index.md
- pages/services/beta-dcos-monitoring/0.4.3-beta/operations/install/index.md
- pages/services/beta-dcos-monitoring/0.4.3-beta/operations/placement-constraint/index.md
- pages/services/beta-dcos-monitoring/0.4.3-beta/operations/prometheus/alert-rules/index.md
- pages/services/beta-dcos-monitoring/0.4.3-beta/operations/prometheus/index.md
- pages/services/beta-dcos-monitoring/0.4.3-beta/operations/prometheus/storage/index.md
- pages/services/beta-dcos-monitoring/0.4.3-beta/operations/prometheus/ui/index.md
- pages/services/beta-dcos-monitoring/0.4.3-beta/operations/uninstall/index.md
- pages/services/beta-dcos-monitoring/0.4.3-beta/release-notes/index.md
Beta DC/OS Monitoring service 0.4.3-beta release.
Diff w.r.t. v0.4.2:
```patch
diff --git a/docs/getting-started/index.md b/docs/getting-started/index.md
index 1486532..b3b5fb3 100644
--- a/docs/getting-started/index.md
+++ b/docs/getting-started/index.md
@@ -107,6 +107,7 @@ Create a custom options file (`options.json`):
```json
{
"service": {
+    "name": "{{ model.packageName }}",
"service_account": "{{ model.packageName }}-principal",
"service_account_secret": "{{ model.packageName }}/service-private-key"
}
diff --git a/docs/release-notes/index.md b/docs/release-notes/index.md
index 51f3ebf..42a42af 100644
--- a/docs/release-notes/index.md
+++ b/docs/release-notes/index.md
@@ -10,6 +10,25 @@ model: ../data.yml
#include /services/include/beta-software-warning.tmpl
+# Version v0.4.3
+ …
> beta-dcos-monitoring: Update docs for 0.4.3-beta

- pages/services/marathon-lb/mlb-configuration/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4815
> LG/DCOS_OSS-4815-MLB Fix formatting/numbering issue

- pages/1.12/installing/production/advanced-configuration/configuration-reference/index.md
- pages/1.12/security/ent/hardening/index.md
https://jira.mesosphere.com/browse/DCOS-48850
> Fixed ZK broken links, reviewed and fixed additional broken links, and formatted Notes.

- pages/1.11/administering-clusters/update-a-node/index.md
- pages/1.12/administering-clusters/update-a-node/index.md
https://jira.mesosphere.com/browse/COPS-3126
> LG/COPS-3126 Update the steps for restarting an agent after mainteance

- pages/services/cassandra/2.5.0-3.11.3/advanced/index.md
- pages/services/cassandra/2.5.0-3.11.3/api-reference/index.md
- pages/services/cassandra/2.5.0-3.11.3/configuration/index.md
- pages/services/cassandra/2.5.0-3.11.3/getting-started/index.md
- pages/services/cassandra/2.5.0-3.11.3/index.md
- pages/services/cassandra/2.5.0-3.11.3/limitations/index.md
- pages/services/cassandra/2.5.0-3.11.3/operations/index.md
- pages/services/cassandra/2.5.0-3.11.3/release-notes/index.md
- pages/services/cassandra/2.5.0-3.11.3/security/index.md
- pages/services/cassandra/2.5.0-3.11.3/support-policy/index.md
- pages/services/cassandra/2.5.0-3.11.3/troubleshooting/index.md
- pages/services/cassandra/2.5.0-3.11.3/uninstall/index.md
- pages/services/cassandra/2.5.0-3.11.3/updates/index.md
> [DCOS-46650] Add docs for Cassandra 2.5.0-3.11.3 release

- pages/1.13/installing/production/advanced-configuration/configuration-reference/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-3870
Add docs about new installer config variables.
> Added description of Seccomp configuration options.

- scss/components/_sidebar.scss
https://jira.mesosphere.com/browse/DCOS-49107
> CK DCOS-49107 Update fonts for legibility

- pages/1.10/security/ent/secrets/custom-key/index.md
> Update link DCOS-49296

- scss/components/_sidebar.scss
> revert to gray

- pages/1.10/installing/evaluation/community-supported-methods/aws/index.md
- pages/1.11/installing/evaluation/community-supported-methods/aws/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4758
1.12 already completed, this finishes 1.10 and 1.11
- [ x] Medium
> CK DCOS_OSS-4758 Update warnings on cloudformation pages

- pages/services/confluent-kafka/kafka-auth/index.md
- pages/services/nifi/0.1.0-1.5.0/index.md
- pages/services/nifi/0.2.0-1.5.0/index.md
- pages/services/nifi/0.3.0-1.7.1/index.md
- pages/services/nifi/configure-dcos-access/index.md
https://jira.mesosphere.com/browse/DCOS-48668
> Added configuring DC/OS access for NiFi.

- pages/1.12/installing/production/advanced-configuration/configuration-reference/index.md
[x] page inspected after localhost build
> Fix formatting on Config Reference page 

- pages/services/beta-jupyter/1.2.0-0.33.7-beta/example/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4848
> Services docs : beta-jupyter/1.2.0-0.33.7-beta/example page - Fixed broken links for content and images

- pages/version-policy/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4872
> Version Policy page: Created a new table for Beta packages and added description.

- pages/1.12/installing/evaluation/community-supported-methods/aws/index.md
https://jira.mesosphere.com/browse/DCOS-49644
> 1.12 Installing docs - Fixed broken link.

- pages/1.12/deploying-services/private-docker-registry/index.md
https://jira.mesosphere.com/browse/COPS-4227
> LG/COPS-4227 DRAFT using a custom cert for the Docker registry

- pages/services/spark/2.6.0-2.3.2/index.md
- pages/services/spark/2.6.0-2.3.2/quickstart/index.md
- pages/services/spark/spark-auth/index.md
https://jira.mesosphere.com/browse/DCOS-49127
> Edited Spark-Auth doc.

- pages/1.11/release-notes/1.11.10/index.md
- pages/1.11/release-notes/1.11.9/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4879
> Fixed Mesos version for 1.11.10 and 1.11.9 RNs.

- pages/1.10/tutorials/iot_pipeline/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4137
> 1.10 - Tutorials - IOT-Pipeline: Added a Note for Zeppelin supported version.

- pages/services/nifi/0.2.0-1.5.0/install/index.md
- pages/services/nifi/configure-dcos-access/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4370
> NiFi:0.2.0-1.5.0:install page - Fixed broken links.

- pages/services/beta-dcos-monitoring/0.4.3-beta/getting-started/index.md
https://jira.mesosphere.com/browse/DCOS-49790
> Beta-dcos-monitoring: Removed download package information

- pages/1.12/installing/production/upgrading/index.md
- pages/1.13/installing/production/upgrading/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4894
> LG/DCOS_OSS-4894 Fix broken link in Upgrade

- pages/1.12/installing/production/deploying-dcos/installation/index.md
- pages/1.12/installing/production/upgrading/index.md
- pages/1.13/installing/production/deploying-dcos/installation/index.md
- pages/1.13/installing/production/upgrading/index.md
https://jira.mesosphere.com/browse/DCOS-49850
> LG/DCOS-49850 Change links for Ent users step 5.4 and OSS step 3.4

- pages/1.11/deploying-services/gpu/index.md
- pages/1.12/deploying-services/gpu/index.md
https://jira.mesosphere.com/browse/DCOS-49040
> 1.11 and 1.12: Deploying Services-GPU page: Fixed broken links.

- pages/1.12/release-notes/open-source-attribution/index.md
https://jira.mesosphere.com/browse/DCOS-43449
> 1.12-RN-open source attribution page: Fixed broken links.

- pages/1.12/deploying-jobs/index.md
https://jira.mesosphere.com/browse/COPS-4631
> 1.12 - Deploying Jobs page - Removed Beta tag.

- pages/1.12/installing/production/upgrading/index.md
- pages/1.13/installing/production/upgrading/index.md
https://jira.mesosphere.com/browse/COPS-4620
- [X ] High
> LG/COPS-4620 fix link to Node and cluster heath checks

- pages/services/percona-server-mongodb/0.4.2-3.6.10/api-reference/index.md
- pages/services/percona-server-mongodb/0.4.2-3.6.10/connecting-clients/index.md
- pages/services/percona-server-mongodb/0.4.2-3.6.10/deploy-best-practice/index.md
- pages/services/percona-server-mongodb/0.4.2-3.6.10/disaster-recovery/index.md
- pages/services/percona-server-mongodb/0.4.2-3.6.10/getting-started/index.md
- pages/services/percona-server-mongodb/0.4.2-3.6.10/index.md
- pages/services/percona-server-mongodb/0.4.2-3.6.10/known-issues/index.md
- pages/services/percona-server-mongodb/0.4.2-3.6.10/limitations/index.md
- pages/services/percona-server-mongodb/0.4.2-3.6.10/managing/index.md
- pages/services/percona-server-mongodb/0.4.2-3.6.10/mongodb-administration/index.md
- pages/services/percona-server-mongodb/0.4.2-3.6.10/quick-start/index.md
- pages/services/percona-server-mongodb/0.4.2-3.6.10/release-notes/index.md
- pages/services/percona-server-mongodb/0.4.2-3.6.10/support/index.md
- pages/services/percona-server-mongodb/0.4.2-3.6.10/terms-of-use/index.md
- pages/services/percona-server-mongodb/0.4.2-3.6.10/troubleshooting/index.md
- pages/services/percona-server-mongodb/0.4.2-3.6.10/uninstall/index.md
- pages/services/percona-server-mongodb/index.md
> Docs for Percona Server for MongoDB 0.4.2-3.6.10

- pages/services/spark/2.7.0-2.4.0/custom-docker/index.md
- pages/services/spark/2.7.0-2.4.0/fault-tolerance/index.md
- pages/services/spark/2.7.0-2.4.0/hdfs/index.md
- pages/services/spark/2.7.0-2.4.0/history-server/index.md
- pages/services/spark/2.7.0-2.4.0/index.md
- pages/services/spark/2.7.0-2.4.0/install/index.md
- pages/services/spark/2.7.0-2.4.0/job-scheduling/index.md
- pages/services/spark/2.7.0-2.4.0/kerberos/index.md
- pages/services/spark/2.7.0-2.4.0/limitations/index.md
- pages/services/spark/2.7.0-2.4.0/limits/index.md
- pages/services/spark/2.7.0-2.4.0/quickstart/index.md
- pages/services/spark/2.7.0-2.4.0/release-notes/index.md
- pages/services/spark/2.7.0-2.4.0/run-job/index.md
- pages/services/spark/2.7.0-2.4.0/runtime-config-change/index.md
- pages/services/spark/2.7.0-2.4.0/security/index.md
- pages/services/spark/2.7.0-2.4.0/spark-shell/index.md
- pages/services/spark/2.7.0-2.4.0/troubleshooting/index.md
- pages/services/spark/2.7.0-2.4.0/uninstall/index.md
- pages/services/spark/2.7.0-2.4.0/upgrade/index.md
- pages/services/spark/2.7.0-2.4.0/usage-examples/index.md
- pages/services/spark/2.7.0-2.4.0/version-policy/index.md
Resolves [DCOS-49231](https://jira.mesosphere.com/browse/DCOS-49231)
> [DCOS-49231] Spark 2.4.0 release notes and site docs update

- pages/services/spark/2.7.0-2.4.0/quickstart/index.md
Noticed Quickstart had formatting issues with the code blocks, did quick pass on the new spark pages
> Formatting fixes

- pages/1.12/security/ent/secrets/custom-key/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4400
> 1.12 Secrets:custom key page - Removed misleading unseal-cust-keys link.

- pages/1.12/security/ent/secrets/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4401
> Added a blog link in 1.12 security:ent:secrets page.

- pages/1.12/installing/production/advanced-configuration/configuring-zones-regions/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4878
> 1.12 Installing-config zones-regions:Fixed broken links.

- pages/1.12/installing/production/advanced-configuration/configuring-zones-regions/multi-zone/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4721
> 1.12:Multi Zone page - Remove Beta tag.

- pages/services/edge-lb/1.3/release-notes/index.md
No JIRA. Discovered this while reading - https://docs.mesosphere.com/services/edge-lb/1.3/release-notes/
Please let me know if you need a JIRA for tracking purposes.
- [] High
- [x ] Medium
> Remove the spurious markers from the documentation

- pages/1.11/installing/production/patching/index.md
- pages/1.11/installing/production/upgrading/index.md
https://jira.mesosphere.com/browse/DCOS-49712
> 1.11 patching and upgrading pages: Updated matrix

- pages/1.10/installing/production/patching/index.md
https://jira.mesosphere.com/browse/DCOS-49968
> 1.10 Patching page -  Update supported patching path matrix.

- pages/1.12/cli/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4664
> 1.12 CLI page - Moved commands from one section to another.

- pages/1.10/installing/installation-faq/index.md
- pages/1.11/installing/installation-faq/index.md
- pages/1.11/installing/production/patching/index.md
- pages/1.12/installing/installation-faq/index.md
- pages/1.12/installing/production/patching/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4932
> Added a "Note" on FAQ page for ZK backup and included a ZK backup link on Patching page.

- pages/1.13/installing/production/advanced-configuration/configuration-reference/index.md
Reverts mesosphere/dcos-docs-site#1994
> Revert "Added description of Seccomp configuration options."

- pages/services/include/security-configure-transport-encryption.tmpl
https://jira.mesosphere.com/browse/DCOS-39455
> LG/DCOS-39455 HDFS service account settings in an include file

- pages/1.13/storage/persistent-volume/index.md
https://jira.mesosphere.com/browse/DCOS-49815
https://jira.mesosphere.com/browse/COPS-4624
> LG/DCOS-49815 Postgres persistent storage example-DRAFT

- pages/version-policy/index.md
> Edited Version Policy page

- pages/services/elastic/2.5.0-6.3.2/how-to-guides/index.md
https://jira.mesosphere.com/browse/DCOS-51108
> LG/DCOS-51108-Typo Fix missing letter

- pages/services/cassandra/2.5.0-3.11.3/limitations/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4991
- [x ] High
> Added JVM operations limitation

- pages/1.12/installing/production/upgrading/index.md
> Added a line regarding /opt/mesosphere being wiped during upgrades

- pages/1.12/networking/SDN/cni-plugins/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4993
> Added a note about backing up config files for DC/OS upgrades

- pages/services/hdfs/2.5.0-2.6.0-cdh5.11.0/limitations/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4995
> Added a note about JVM options limitations

- pages/1.12/release-notes/1.12.3/index.md
https://jira.mesosphere.com/browse/DCOS-50848
> 1.12.3 Release Notes: Added an entry in Mesos section.

- pages/services/confluent-kafka/2.5.0-4.1.2/advanced/index.md
- pages/services/confluent-kafka/2.5.0-4.1.2/api-reference/index.md
- pages/services/confluent-kafka/2.5.0-4.1.2/configuration/index.md
- pages/services/confluent-kafka/2.5.0-4.1.2/getting-started/index.md
- pages/services/confluent-kafka/2.5.0-4.1.2/index.md
- pages/services/confluent-kafka/2.5.0-4.1.2/limitations/index.md
- pages/services/confluent-kafka/2.5.0-4.1.2/operations/index.md
- pages/services/confluent-kafka/2.5.0-4.1.2/release-notes/index.md
- pages/services/confluent-kafka/2.5.0-4.1.2/security/index.md
- pages/services/confluent-kafka/2.5.0-4.1.2/support-policy/index.md
- pages/services/confluent-kafka/2.5.0-4.1.2/troubleshooting/index.md
- pages/services/confluent-kafka/2.5.0-4.1.2/uninstall/index.md
- pages/services/confluent-kafka/2.5.0-4.1.2/updates/index.md
https://jira.mesosphere.com/browse/DCOS-51242
> DCOS-51242 - Confluent kafka 2.5.0 4.1.2

- pages/version-policy/index.md
https://jira.mesosphere.com/browse/DCOS-51154
> Formatted the OS Qual Version Policy Matrix

- pages/services/cassandra/index.md
> DCOS-50693 Make Kubernetes the first service

- pages/services/confluent-kafka/2.4.0-4.1.1/release-notes/index.md
- pages/services/confluent-kafka/2.5.0-4.1.2/release-notes/index.md
Jira down at the time of this ticket
- [ X] High
> Fix html formatting

- pages/services/kafka/2.4.0-1.1.1/advanced/index.md
- pages/services/kafka/2.4.0-1.1.1/configuration/index.md
- pages/services/kafka/2.4.0-1.1.1/index.md
- pages/services/kafka/2.4.0-1.1.1/limitations/index.md
- pages/services/kafka/2.4.0-1.1.1/notes/index.md
- pages/services/kafka/2.4.0-1.1.1/operations/index.md
- pages/services/kafka/2.4.0-1.1.1/policy/index.md
- pages/services/kafka/2.4.0-1.1.1/reference/index.md
- pages/services/kafka/2.4.0-1.1.1/security/index.md
- pages/services/kafka/2.4.0-1.1.1/started/index.md
- pages/services/kafka/2.4.0-1.1.1/troubleshooting/index.md
- pages/services/kafka/2.4.0-1.1.1/uninstall/index.md
- pages/services/kafka/2.4.0-1.1.1/updates/index.md
- pages/services/kafka/2.5.0-2.1.0/advanced/index.md
- pages/services/kafka/2.5.0-2.1.0/configuration/index.md
- pages/services/kafka/2.5.0-2.1.0/index.md
- pages/services/kafka/2.5.0-2.1.0/limitations/index.md
- pages/services/kafka/2.5.0-2.1.0/notes/index.md
- pages/services/kafka/2.5.0-2.1.0/operations/index.md
- pages/services/kafka/2.5.0-2.1.0/policy/index.md
- pages/services/kafka/2.5.0-2.1.0/reference/index.md
- pages/services/kafka/2.5.0-2.1.0/security/index.md
- pages/services/kafka/2.5.0-2.1.0/started/index.md
- pages/services/kafka/2.5.0-2.1.0/troubleshooting/index.md
- pages/services/kafka/2.5.0-2.1.0/uninstall/index.md
- pages/services/kafka/2.5.0-2.1.0/updates/index.md
Add changelog for 2.4.0 and 2.5.0 kafka package release.
ℹ️  Added DO NOT MERGE label until the following PRs are merged:
* https://github.com/mesosphere/universe/pull/2204
* https://github.com/mesosphere/universe/pull/2205
> Add changelog for 2.4.0 and 2.5.0 kafka package release

- pages/1.13/cli/command-reference/dcos-node/dcos-node-list/index.md
> LG/DCOS-50125-options Add the common options to the cmd reference

- pages/1.13/storage/external-storage/index.md
https://jira.mesosphere.com/browse/DCOS-51357
Document rexray nvme support prerequisites
The EBS section is growing too large to be a bullet point, so it is now a subsection.
I added the script from https://jira.mesosphere.com/browse/DCOS-51356 and broke it up into steps. 
Since there is some uncertainty in the JIRA tickets about whether this change will apply to 1.12 docs and earlier, right now the only version I have edited is 1.13.
> ss/DCOS-51357 Adding new script to RexRay doc.

- pages/1.12/deploying-jobs/quickstart/index.md
- pages/1.13/deploying-jobs/quickstart/index.md
https://jira.mesosphere.com/browse/DCOS-45360
https://jira.mesosphere.com/browse/DCOS-49995
https://jira.mesosphere.com/browse/DCOS-48308
> Lg/dcos oss 4818 new 1.13-UI changes for creating/managing jobs

- pages/1.12/release-notes/1.12.3/index.md
https://jira.mesosphere.com/browse/COPS-3585
https://jira.mesosphere.com/browse/DCOS-38600
https://jira.mesosphere.com/browse/DCOS-51771
> Move Networking COPS-3585 issue from known issues to issues fixed.

- pages/1.13/api/endpoints.yaml
- pages/1.13/api/logs.yaml
- pages/1.13/gui/updating-gui/index.md
- pages/services/elastic/2.5.0-6.3.2/how-to-guides/index.md
https://jira.mesosphere.com/browse/DCOS-48183
Add GUI update pages to DC/OS 1.13 documents.
Added Updating the GUI page to /1.13/gui/ pages, including call to 'endpoints.yaml' API.
Created endpoints.yaml file and added text from R. Norris paper.
> ss/DCOS-48183 Added GUI update page and endpoints.yaml file.

- docker/nginx/redirects-307.map
- layouts/cn-dcos-docs-landing.pug
- layouts/dcos-docs-landing.pug
- layouts/partials/header/cn-header.pug
- layouts/partials/header/en-header.pug
- layouts/partials/header/header.pug
- pages/cn/index.md
- pages/cn/services/index.md
- pages/cn/services/kubernetes/latest/index.md
- pages/index.md
- pages/services/index.md
- pages/services/kubernetes/latest/index.md
https://jira.mesosphere.com/browse/DCOS-50692
> DCOS-50692 Add kubernetes to top nav

- pages/1.12/deploying-jobs/quickstart/index.md
https://jira.mesosphere.com/browse/DCOS-51848
> Remove trailing slash / that broke the graphic path.

- pages/1.10/installing/evaluation/azure/index.md
- pages/1.11/installing/evaluation/azure/index.md
- pages/1.12/installing/evaluation/azure/index.md
Changing the defaults for this so that it will perform a warning rather than a destroy for the Azure provider.
https://jira.mesosphere.com/browse/DCOS-51030
> azure: updating to support up to 1.X

- pages/services/beta-storage/0.5.2-beta/install/package-registry-based/index.md
Reverts mesosphere/dcos-docs-site#2138
> Revert "Update command and removed $"

- pages/1.12/security/ent/secrets/use-secrets/index.md
https://jira.mesosphere.com/browse/COPS-4632
> Added Metronome Secret for 1.12

- pages/1.13/release-notes/1.13.0-beta1/index.md
https://jira.mesosphere.com/browse/DCOS-51853
https://jira.mesosphere.com/browse/DCOS-50945
> 1.13 BETA-RN-menu weight, excerpt, date, link hashes, changes - final updates

- config.json
- layouts/partials/sidebar/en-sidebar.pug
- pages/1.13/index.md
> feat: make 1.13-beta live

- pages/1.13/cli/command-reference/dcos-node/dcos-node-list/index.md
- pages/1.13/release-notes/1.13.0-beta1/index.md
https://jira.mesosphere.com/browse/DCOS-52005
Quick edit pass of 1.13-beta RN
Review and correct hyperlinks
- [x High
> DCOS-52005 Review and correct hyperlinks in 1.13 beta Release Notes.

- pages/1.13/release-notes/1.13.0-beta1/index.md
> Adjusted the docker manifest v2 schema2 support doc.

- pages/1.13/release-notes/1.13.0-beta1/index.md
- pages/1.13/release-notes/1.13.0/index.md
https://jira.mesosphere.com/browse/DCOS-50946
> Release notes for 1.13 GA - content development

- pages/services/spark/2.8.0-2.4.0/release-notes/index.md
> link format

- pages/1.13/networking/SDN/dcos-overlay/index.md
https://jira.mesosphere.com/browse/DCOS-39531 
> Note formatting and one misplaced comma.

- pages/1.10/installing/evaluation/aws/index.md
- pages/1.11/installing/evaluation/aws/index.md
- pages/1.12/installing/evaluation/aws/index.md
https://jira.mesosphere.com/browse/DCOS-46823
- [ x] Medium
> ck/DCOS-46823 Update to AWS for clarity

- pages/1.13/installing/production/system-requirements/index.md
https://jira.mesosphere.com/browse/COPS-4568
> LG/COPS-4568: added statement about swap to system requirements

- pages/1.12/security/ent/service-auth/custom-service-auth/index.md
I tested the curl command on macOS.
> Fixed section header formatting and curl command.

- pages/1.12/installing/production/upgrading/index.md
- pages/1.13/installing/production/upgrading/index.md
https://jira.mesosphere.com/browse/COPS-4791
https://jira.mesosphere.com/browse/DCOS-52737
> Lg/cops 4791-Upgrade from/to matrix for 1.12 and 1.13

- pages/1.13/installing/production/upgrading/index.md
https://jira.mesosphere.com/browse/DCOS-50054
> 1.13 Upgrading page - Updated matrix table.

- scss/base/_content.scss
https://jira.mesosphere.com/browse/DCOS-41223
> ui: fix content sections width and allow wrapping

- pages/services/edge-lb/1.3/release-notes/index.md
This PR adds release notes for v1.3.1
Tracking Jira: https://jira.mesosphere.com/browse/DCOS-53057
> Edge-LB: release notes for v1.3.1

- pages/services/edge-lb/1.3/release-notes/index.md
https://jira.mesosphere.com/browse/DCOS-53058
> Fix two typos, switch to sentence capitalization for readability.

- pages/1.12/metrics/quickstart/index.md
- pages/1.13/metrics/quickstart/index.md
https://jira.mesosphere.com/browse/COPS-4818
> 1.12 and 1.13 Metrics Quick Start page - Updated task metrics.

- pages/1.13/installing/production/dcos-ansible/ansible-faq/index.md
> fix link format

- pages/1.10/deploying-services/creating-services/deploy-docker-app/index.md
- pages/1.10/deploying-services/expose-service/index.md
- pages/1.11/deploying-services/creating-services/deploy-docker-app/index.md
- pages/1.11/deploying-services/expose-service/index.md
- pages/1.9/deploying-services/creating-services/deploy-docker-app/index.md
- pages/1.9/deploying-services/expose-service/index.md
- pages/1.9/installing/oss/custom/index.md
- pages/cn/services/Marathon-LB/usage-ee/index.md
- pages/cn/services/Marathon-LB/usage-oss/index.md
test run to see if works and identify problems 
> fix internal links 1.9

- pages/1.13/installing/evaluation/aws/aws-tf-faq/index.md
https://jira.mesosphere.com/browse/DCOS-51999
- [x ] Medium
> CK DCOS-51999 Add and edit aws tf faq

- pages/1.10/installing/production/advanced-configuration/configuration-reference/index.md
- pages/1.11/installing/production/advanced-configuration/configuration-reference/index.md
- pages/1.12/installing/production/advanced-configuration/configuration-reference/index.md
- pages/1.13/installing/production/advanced-configuration/configuration-reference/index.md
- pages/1.9/installing/ent/custom/configuration/configuration-parameters/index.md
- pages/1.9/installing/ent/custom/configuration/examples/index.md
- pages/1.9/installing/ent/custom/configuration/index.md
- pages/1.9/installing/oss/custom/configuration/configuration-parameters/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-5132
https://jira.mesosphere.com/browse/DCOS-53264
Additonal fix to display page
- [x ] High
> CK Update private docker registry info and display 1.9 oss config table

- pages/1.12/deploying-services/private-docker-registry/index.md
- pages/1.13/deploying-services/private-docker-registry/index.md
https://jira.mesosphere.com/browse/DCOS-53230
- [ x] High
> CK DCOS-53230 Update docker section in 1.13

- pages/1.13/installing/production/system-requirements/index.md
https://jira.mesosphere.com/browse/DCOS-49954
https://jira.mesosphere.com/browse/DCOS-21142
> Add more about storage recommendations for master nodes.

- pages/1.13/gui/services/index.md
[DCOS-50120](https://jira.mesosphere.com/browse/DCOS-50120)
> Added documentation for SDK based Service Status

- pages/1.13/installing/production/system-requirements/index.md
https://jira.mesosphere.com/browse/DCOS-53536
> LG/DCOS-53536: change partition to device-Jon's review

- pages/1.13/installing/production/system-requirements/zookeeper-requirements/index.md
https://jira.mesosphere.com/browse/DCOS-49954
https://jira.mesosphere.com/browse/DCOS-50570
Tangentially:
https://jira.mesosphere.com/browse/COPS-4538
https://jira.mesosphere.com/browse/DCOS-21142
> LG/DCOS-49954: new section for ZooKeeper-specific recommendations

- pages/1.13/release-notes/1.13.0/index.md
https://jira.mesosphere.com/browse/DCOS-50946
- [X ] Medium
> Lg/rn ga 1.13 final known issues

- config.json
- docker/nginx/redirects-307.map
- index.js
- layouts/partials/sidebar/en-sidebar.pug
- pages/1.12/index.md
- pages/1.13/index.md
> feat: release 1.13 GA

- pages/cn/1.11/cli/command-reference/dcos-experimental/dcos-experimental-package-start/index.md
- pages/cn/1.11/deploying-services/gpu/index.md
- pages/cn/1.11/monitoring/debugging/debug-perms/index.md
- pages/cn/1.11/overview/architecture/components/index.md
- pages/cn/1.11/security/ent/perms-management/index.md
- pages/cn/1.11/security/oss/managing-authentication/index.md
- pages/cn/1.12/installing/evaluation/community-supported-methods/aws/advanced/index.md
- pages/cn/services/hdfs/2.2.0-2.6.0-cdh5.11.0/getting-started/index.md
> CK Link fixes

- pages/services/beta-elastic/2.6.0-6.3.2-beta/configuration/index.md
- pages/services/beta-elastic/2.6.0-6.3.2-beta/index.md
- pages/services/beta-elastic/2.6.0-6.3.2-beta/release-notes/index.md
- pages/services/beta-elastic/data.yml
Add data.yml file so that templates expand to "beta" phrasings.
> Use "Beta DC/OS Elastic" phrasing.

- pages/install-include/all-create-first-cluster.tmpl
- pages/install-include/aws-cluster-setup.tmpl
- pages/install-include/azure-cluster-setup.tmpl
- pages/install-include/gcp-cluster-setup.tmpl
https://jira.mesosphere.com/browse/COPS-4852
- [X ] High
> CK COPS-4852 Standardize demo folder name

- pages/1.10/installing/production/deploying-dcos/configuration/examples/index.md
- pages/1.11/installing/production/deploying-dcos/configuration/examples/index.md
- pages/1.12/installing/production/deploying-dcos/configuration/examples/index.md
- pages/1.13/installing/production/deploying-dcos/configuration/examples/index.md
- pages/cn/1.11/installing/production/deploying-dcos/configuration/examples/index.md
- pages/cn/1.12/installing/production/deploying-dcos/configuration/examples/index.md
https://jira.mesosphere.com/browse/DCOS-53746
- [X ] High
> Update example to proper _path

- pages/1.13/administering-clusters/update-a-node/index.md
https://jira.mesosphere.com/browse/DCOS-53762
- [X ] Medium
> Add missing agent restart change to 1.13.

- pull_request_template
> Updated PR form
