mesosphere/dcos-docs-site

pages/services/hdfs/hdfs-auth/index.md
https://jira.mesosphere.com/browse/DOCS-2380
The "Development" documentation does not have content which shows me how to build the documentation. However, the problem, which has a screenshot on the JIRA issue, also shows up in Atom, GitHub's text editor, when using Markdown preview.
In Atom, this is the rendering before this change:
And after:
=> Fix section formatting in HDFS documentation

1.11/monitoring/logging/aggregating/elk/index.md, pages/1.10/monitoring/logging/aggregating/elk/index.md, pages/1.8/administration/logging/elk/index.md, pages/1.9/monitoring/logging/aggregating/elk/index.md
- change to append instead of create in systemd file / add logrotate
- Remove the journalctl --vacuum-size=10M since this complicates debugging and RCAs
- Added Example config for logrotate
- Stream-lined the filebeat-journald service
https://jira.mesosphere.com/browse/DCOS_OSS-1811
=> DCOS_OSS-1811 Fixes ELK example

1.11/installing/ent/custom/configuration/configuration-parameters/index.md, 1.11/installing/oss/custom/configuration/configuration-parameters/index.md
This adds documentation for the `mesos_master_work_dir` and `mesos_agent_work_dir` config params that were added in 1.11.
https://jira.mesosphere.com/browse/DOCS-2146
=> Document Mesos work dir config params

pages/services/spark/2.1.0-2.2.0-1/history-server/index.md, pages/services/spark/2.1.0-2.2.0-1/release-notes/index.md, pages/services/spark/2.1.0-2.2.1-1/release-notes/index.md
https://jira.mesosphere.com/browse/RELEASE-483
- Updated the release notes 
- Updated the history-server page within version 2.1.0-2.2.0-1 of Spark
- [ x] Blocker
=> [Spark docs] Updated Spark docs for release of spark-history 2.1.0-2.2.0-1

pages/1.10/release-notes/1.10.4/index.md
The initial description claimed that the bundles didn't contain
sensitive configuration values. However, from [DCOS-19073](https://jira.mesosphere.com/browse/DCOS-19073) we can
conclude that passwords from ZooKeeper can still leak in the
diagnostic bundles.
[DCOS-19073](https://jira.mesosphere.com/browse/DCOS-19073): ZK credentials for Mesos master show up in diagnostics bundles
=> Specifies which information is no longer in the diagnostic bundles.

pages/services/spark/2.1.0-2.2.0-1/index.md, pages/services/spark/2.1.0-2.2.1-1/index.md, pages/services/spark/2.2.1-2.2.0-2-beta/custom-docker/index.md, pages/services/spark/2.2.1-2.2.0-2-beta/fault-tolerance/index.md, pages/services/spark/2.2.1-2.2.0-2-beta/hdfs/index.md, pages/services/spark/2.2.1-2.2.0-2-beta/history-server/index.md, pages/services/spark/2.2.1-2.2.0-2-beta/index.md, pages/services/spark/2.2.1-2.2.0-2-beta/install/index.md, pages/services/spark/2.2.1-2.2.0-2-beta/job-scheduling/index.md, pages/services/spark/2.2.1-2.2.0-2-beta/limitations/index.md, pages/services/spark/2.2.1-2.2.0-2-beta/quickstart/index.md, pages/services/spark/2.2.1-2.2.0-2-beta/release-notes/index.md, pages/services/spark/2.2.1-2.2.0-2-beta/run-job/index.md, pages/services/spark/2.2.1-2.2.0-2-beta/runtime-config-change/index.md, pages/services/spark/2.2.1-2.2.0-2-beta/security/index.md, pages/services/spark/2.2.1-2.2.0-2-beta/spark-shell/index.md, pages/services/spark/2.2.1-2.2.0-2-beta/troubleshooting/index.md, pages/services/spark/2.2.1-2.2.0-2-beta/uninstall/index.md, pages/services/spark/2.2.1-2.2.0-2-beta/upgrade/index.md, pages/services/spark/2.2.1-2.2.0-2-beta/usage-examples/index.md, pages/services/spark/2.2.1-2.2.0-2-beta/version-policy/index.md, pages/services/spark/v1.0.9-2.1.0-1/index.md, pages/services/spark/v1.1.0-2.1.1/index.md, pages/services/spark/v1.1.1-2.2.0/index.md, pages/services/spark/v2.0.0-2.2.0-1/index.md, pages/services/spark/v2.0.1-2.2.0-1/index.md
Spark-2.2.1-2.2.0-2-beta documentation.
=> Adding Spark-2.2.1-2.2.0-2-beta docs.

pages/1.9/release-notes/1.9.7/index.md
https://jira.mesosphere.com/browse/RELEASE-434
=> Revised description of DCOS-20158 and DCOS_OSS-2003.

pages/services/edge-lb/0.1.9/installing/index.md, pages/services/edge-lb/0.1.9/permissions/index.md, pages/services/edge-lb/1.0.0/installing/index.md, pages/services/edge-lb/1.0.0/permissions/index.md
Grant access to the service account for all pools - this has caused confusion for several customers.
=> Fix edge-lb service account permissions

pages/1.11/deploying-services/containerizers/index.md, pages/1.11/deploying-services/containerizers/ucr/index.md
[DOCS-2241](https://jira.mesosphere.com/browse/DOCS-2241) - Document UCR container image garbage collection for DC/OS and other parity improvements.
=> Added Container Image GC user doc to Containerizer section.

pages/1.11/installing/oss/cloud/digitalocean/index.md
fixed minor typo (`anf` to `and`) in digitalocean install docs
really?
=> fixed minor typo in DigitalOcean install docs

pages/1.10/installing/ent/custom/configuration/configuration-parameters/index.md
This PR updates the DC/OS EE documentation on parameters related to **Enterprise** DC/OS installation with a custom CA certificate. The change is identical to the previous one on DC/OS OSS documentation (branch ah/DCOS-19638, merged).
https://jira.mesosphere.com/browse/DCOS-19638
- [x ] High
=> Fix the custom ca params in EE docs

pages/1.11/installing/ent/custom/configuration/configuration-parameters/index.md, pages/1.11/installing/oss/custom/configuration/configuration-parameters/index.md, pages/1.11/security/ent/tls-ssl/ca-custom/index.md
This PR updates the documentation on EE DC/OS v1.11 installation with a custom CA certificate. The update is similar to the earlier PR (https://github.com/mesosphere/dcos-docs-site/pull/385) on EE DC/OS v1.10 documentation.
https://jira.mesosphere.com/browse/DCOS-19638
- [ X] High
=> Update docs on EE DC/OS 1.11 installation with a custom CA certificate

pages/1.10/cli/command-reference/dcos-task/dcos-task-log/index.md, pages/1.11/cli/command-reference/dcos-task/dcos-task-log/index.md, pages/1.9/cli/command-reference/dcos-task/dcos-task-log/index.md
It is the other way around, `<task>` must come before `<file>`.
https://jira.mesosphere.com/browse/COPS-2173
=> Correct `dcos task log` positional arguments

pages/1.10/cli/index.md, pages/1.11/cli/index.md
Some CLI versions are spelled with O instead if 0.
=> Fix some CLI versions

index.js, package.json
Rendering tweaks to speed up rendering:
- Improve rendering speed with `cache: true`: I found this sped up the rendering step from 5 minutes to 2 minutes on my (pretty beefy) laptop.
- Adds a developer option (in the form of a `RENDER_PATH_PATTERN` envvar to be passed when doing the build) to specify a subset of pages to be rendered. Useful when making local edits and just want to verify those changes.
- Also adds some timer calls where they were previously missing.
Console output tweaks to display progress while rendering:
- Add `metalsmith-layouts`: As layouts are being rendered, print something to the console, rather than going totally silent for potentially several minutes
- Remove `metalsmith-revision`: Didn't find this output to be useful when rendering in dev mode.
- Also updates …
=> Speed up rendering, improve output while rendering

pages/1.11/security/ent/index.md
This PR aligns the Security subsections' titles in `/pages/1.11` to that of `/pages/1.10`.
https://jira.mesosphere.com/browse/DCOS-20752
=> pages/1.11/security: distinguish between EE and OSS security subsections

pages/services/beta-kubernetes/0.1.0-1.7.5-beta/index.md, pages/services/beta-kubernetes/0.2.0-1.7.6-beta/index.md, pages/services/beta-kubernetes/0.2.1-1.7.7-beta/index.md, pages/services/beta-kubernetes/0.4.0-1.9.0-beta/index.md, pages/services/beta-kubernetes/0.5.0-1.9.1-beta/index.md, scripts/service-update-scripts/beta-kubernetes-merge-branch.sh
This PR fixes the merge branch script (important for incremental doc updates between releases) and makes the navigation titles consistent for the various versions of Beta Kubernetes service.
=> Kubernetes docs

pages/1.10/release-notes/1.10.5/index.md
This is the fix for 1.10.5 Release Notes.
=> Added Enterprise Tags for CockroachDB

pages/services/beta-storage/0.1.0-beta/cli-references/dcos-storage-volume/index.md, pages/services/beta-storage/0.1.0-beta/install/index.md, pages/services/beta-storage/0.1.0-beta/uninstall/index.md
Given that storage service is still beta, use beta-storage for the package name.
=> Used beta-storage consistently in the doc

pages/services/beta-storage/0.1.0-beta/install/index.md
Mentioned that storage service package can be downloaded from the support site.
=> Updated storage service install doc about download site

pages/1.10/installing/ent/faq/index.md, pages/1.10/installing/ent/upgrading/index.md, pages/1.11/installing/ent/faq/index.md, pages/1.11/installing/ent/upgrading/index.md
This PR adds a bullet-point to the Upgrading pages for 1.10 and 1.11 to add a prerequisite step that is "Take a snapshot of the IAM database". That links to a new FAQ entry in the Installing section's FAQ that gives the exact command necessary to do so.
Fixes https://jira.mesosphere.com/browse/DOCS-2457
=> 1.10,1.11/installing/ent/upgrading: backup IAM database

pages/1.10/installing/ent/upgrading/index.md, pages/1.11/installing/ent/upgrading/index.md
This PR updates the Upgrading documentation for 1.10 and 1.11 to specify that Dan must wait for the underreplicated_ranges value to drop to zero after a master was upgraded. 
@vishnu2kmohan do we have "master replacement" documentation somewhere or are these upgrade docs as close as we have?
Fixes https://jira.mesosphere.com/browse/DOCS-2458
=> 1.10,1.11/installing/ent/upgrading: wait for cockroachdb underreplicated ranges

pages/1.11/installing/ent/ports/index.md, pages/1.11/installing/oss/ports/index.md, pages/1.11/metrics/index.md
[DOCS-2472](https://jira.mesosphere.com/browse/DOCS-2472) - Update dcos-metrics port number
=> Update prometheus port number across docs

pages/services/beta-hdfs/2.1.0-2.6.0-cdh5.11.0-beta/quick-start/index.md, pages/services/beta-hdfs/2.1.1-2.6.0-cdh5.11.0-beta/quick-start/index.md, pages/services/beta-hdfs/2.1.2-2.6.0-cdh5.11.0-beta/quick-start/index.md, pages/services/beta-hdfs/v1.3.2-2.6.0-cdh5.9.1-beta/quick-start/index.md, pages/services/beta-hdfs/v1.3.3-2.6.0-cdh5.11.0-beta/quick-start/index.md, pages/services/beta-hdfs/v2.0.0-2.6.0-cdh5.11.0/quick-start/index.md, pages/services/hdfs/2.0.1-2.6.0-cdh5.11.0/quick-start/index.md, pages/services/hdfs/2.0.2-2.6.0-cdh5.11.0/quick-start/index.md, pages/services/hdfs/2.0.3-2.6.0-cdh5.11.0/quick-start/index.md, pages/services/hdfs/2.0.4-2.6.0-cdh5.11.0/quick-start/index.md, pages/services/hdfs/2.1.0-2.6.0-cdh5.11.0/quick-start/index.md, pages/services/hdfs/v1.3.0-2.6.0-cdh5.9.1/quick-start/index.md, pages/services/hdfs/v2.0.0-2.6.0-cdh5.11.0/quick-start/index.md
The quick start for the HDFS service have a small error in describing how to run the client. This fixes said error. The file being referenced lives at the root of the FS in the Docker image and not the working directory that's specified in the Dockerfile so when one enters the container, the `configure-hdfs.sh` file is referenced wrong by one level.
https://jira.mesosphere.com/browse/INFINITY-3273
=> [INFINITY-3273] Corrected slight error in HDFS client docs

pages/1.10/installing/ent/custom/configuration/configuration-parameters/index.md, pages/1.11/installing/ent/custom/configuration/configuration-parameters/index.md
This PR adds the configuration parameter `master_external_loadbalancer` to the configuration reference sections for DC/OS EE 1.10 and 1.11.
https://jira.mesosphere.com/browse/COPS-2114
- [ x] High
=> Add master_external_loadbalancer config param to the config reference.

pages/services/kubernetes/1.0.1-1.9.4/advanced-install/index.md
Fixes https://jira.mesosphere.com/browse/DCOS-21664
=> kubernetes: fix tls image broken by dodgy import of latest docs

pages/1.10/security/ent/secrets/seal-store/index.md, pages/1.11/security/ent/secrets/seal-store/index.md, pages/1.11/security/ent/secrets/unseal-store/index.md, pages/1.9/security/ent/secrets/seal-store/index.md
This PR:
* updates dcos-secrets unsealing&unsealing documentation for 1.11, so that it matches the changes in dcos-secrets.
* makes small clarity adjustments for dcos-secrets sealing documentation for 1.10 and 1.9 
https://jira.mesosphere.com/browse/DCOS-19303 `docs: Improve DC/OS Secrets unseal documentation`
=> Improve dcos-secrets sealing/unsealing docs

pages/services/beta-hdfs/2.1.0-2.6.0-cdh5.11.0-beta/limitations/index.md, pages/services/beta-hdfs/2.1.1-2.6.0-cdh5.11.0-beta/limitations/index.md, pages/services/beta-hdfs/2.1.2-2.6.0-cdh5.11.0-beta/limitations/index.md, pages/services/hdfs/2.1.0-2.6.0-cdh5.11.0/limitations/index.md
https://jira.mesosphere.com/browse/INFINITY-3036
This PR documents a limitation for toggling security settings on HDFS.
=> [INFINITY-3026] Add limitations for toggling Kerberos on HDFS

pages/services/beta-hdfs/2.1.0-2.6.0-cdh5.11.0-beta/limitations/index.md, pages/services/beta-hdfs/2.1.1-2.6.0-cdh5.11.0-beta/limitations/index.md, pages/services/beta-hdfs/2.1.2-2.6.0-cdh5.11.0-beta/limitations/index.md, pages/services/hdfs/2.1.0-2.6.0-cdh5.11.0/limitations/index.md
This is a follow-up of #769 where the TLS limitations are also added.
=> [INFINITY-3026] Add limitations for toggling TLS on HDFS 

pages/1.11/installing/oss/ports/index.md
https://jira.mesosphere.com/browse/COPS-2964
https://jira.mesosphere.com/browse/DCOS-21712
https://github.com/dcos/dcos/blob/1.11/docs/admin-ports.md
=> Update networking ports documentation for 1.11

pages/1.10/installing/oss/custom/system-requirements/index.md
In response to the comments on this JIRA: https://jira.mesosphere.com/browse/DOCS-2454, the link to the install_prereqs.sh script has been removed. The new CentOS script that is linked in the JIRA needs to be tested before adding to the docs.
=> Removing link to install_prereqs.sh script for CentOS 7.

pages/1.10/installing/ent/custom/configuration/configuration-parameters/index.md, pages/1.11/installing/ent/custom/configuration/configuration-parameters/index.md
This PR adds documentation for a new `adminrouter_auth_cache_enabled` parameter added in https://github.com/mesosphere/dcos-enterprise/pull/2496 (1.10) and https://github.com/mesosphere/dcos-enterprise/pull/2318 (1.11).
The diff includes a some trailing whitespace removal.
This should go live when 1.10.6 and 1.11.1 are released.
=> configuration-parameters: add adminrouter_auth_check_enabled

pages/1.11/release-notes/1.11.1/index.md
Based on feedback from Jan Philip, I've removed INFINITY-3331 in 1.11.1 RN.
=> Removed INFINITY-3331 in 1.11.1 RN

plugins/metalsmith-hierarchy.js
`menuWeight` is used to sort navigation items. If two `menuWeight` entries are the same for siblings then the order of navigation items is not guaranteed to be stable. This PR falls back to sorting on `navigationTitle` or else `title` in such cases.
=> nav: fallback to sort by nagivationTitle (or else title) for items w/ equivalent menuWeight

pages/1.11/release-notes/1.11.1/index.md
DCOS-19586 is a last minute bug reported by Philipp Hinrichsen on 4/19/2018.
=> Added a new entry for DCOS-19586 in 1.11.1 RN

pages/1.11/release-notes/1.11.1/index.md
I went through the commits of the dcos/dcos and mesosphere/dcos-enterprise repositories to manually curate a list of user-facing changes between our 1.11.0 and 1.11.1 releases. The primary outcome are these two changelog PRs:
https://github.com/dcos/dcos/pull/2365
https://github.com/mesosphere/dcos-enterprise/pull/2628
The secondary outcome is this PR here for updating our public release notes with critical entries (that we should not have missed in the first place). This PR also corrects one or more mistakes (wrong Metronome release was mentioned, ..), introduces missing `enterprise` tags, and introduces some minor improvements.
I believe that this PR is a good indication for how many valuable release note items we miss by purely relying on JIRA as a reference.
- Test all commands and …
=> 1.11.1 release notes: add manually curated items, consolidate

pages/1.10/monitoring/debugging/slow-docker/index.md, pages/1.11/monitoring/debugging/slow-docker/index.md
COPS-2982 https://jira.mesosphere.com/browse/COPS-2982
=> COPS-2982 Removing mention of dcos-config.yaml from 1.10 and 1.10

pages/1.11/deploying-services/update-user-service/index.md
The DC/OS CLI marathon subcommand does not allow the update of only
one specific key in a JSON field. The documentation has been updated
to not documenting this unexisting feature and to correspond to what
we have in the CLI since the merge of the [DCOS CLI PR 1215](https://github.com/dcos/dcos-cli/pull/1215).
https://jira.mesosphere.com/browse/DCOS_OSS-2391
=> Update documentation regarding update of a user-created service.

docker/nginx/redirects-301.map
=> added backslash to beginning of redirect paths.

pages/1.10/monitoring/logging/quickstart/index.md, pages/1.11/monitoring/logging/quickstart/index.md
Since the dcos-adminrouter-reload.service and dcos-adminrouter-reload.timer do not exist anymore in DC/OS 1.10, they should not be displayed.
https://jira.mesosphere.com/browse/COPS-2187
- Change all affected versions (e.g. 1.10 and 1.11).
=> Remove dcos-adminrouter-reload.service/timer refs

docker/nginx/redirects-301.map
Customer facing issue. 
Redirected  /1.9/installing/local/ to point to /1.9/installing/ent/local/;
=> Fixed dead URL

pages/1.11/release-notes/1.11.2/index.md
NOTE:
The following commit message is incorrect and should be "Removed CoreOS 1688.5.3 since it is not supported for this release."
=> 1.11.2 Release Notes

pages/1.10/cli/index.md, pages/1.11/cli/index.md, pages/1.7/usage/cli/install/index.md, pages/1.8/usage/cli/index.md, pages/1.9/cli/index.md
The CLI versions requirements are:
- DC/OS <=1.9: CLI 0.4.x
- DC/OS 1.10: CLI 0.5.x
- DC/OS 1.11: CLI 0.6.x
https://jira.mesosphere.com/browse/DCOS-37542
=> Document CLI version requirements for DC/OS <=1.9

docker/nginx/redirects-301.map
https://jira.mesosphere.com/browse/SITE-1493
Resolved issues in redirects map due to Jenkins build failure. 
=> Deleted duplicate entries.

pages/services/beta-cassandra/1.0.30-3.0.13-beta/node-settings/index.md, pages/services/beta-cassandra/1.0.31-3.0.13-beta/node-settings/index.md, pages/services/beta-cassandra/1.0.32-3.0.14-beta/node-settings/index.md, pages/services/beta-cassandra/2.1.0-3.0.15-beta/node-settings/index.md, pages/services/beta-cassandra/2.1.1-3.0.15-beta/node-settings/index.md, pages/services/beta-cassandra/2.1.2-3.0.15-beta/index.md, pages/services/beta-cassandra/2.1.2-3.0.15-beta/node-settings/index.md, pages/services/beta-cassandra/index.md, pages/services/include/node-disk-type-warning.tmpl
https://jira.mesosphere.com/browse/COPS-405
Added note that changing disk types is not possible on an existing deployment, data will not be migrated for example from root to mount volume. For an existing deployment, data should be backed up, the cluster re-deployed with the new disk type, then data restored. I created this as a template, which deploys on every relevant page of each version to date.
=> COPS-405 Adding disk node setting warning to all versions, using .tmpl

pages/services/cassandra/2.0.1-3.0.14/managing/index.md, pages/services/cassandra/2.0.2-3.0.14/managing/index.md, pages/services/cassandra/2.0.3-3.0.14/managing/index.md, pages/services/cassandra/v2.0.0-3.0.14/managing/index.md
https://jira.mesosphere.com/browse/COPS-1940
Corrected line break errors in /managing/index.md in Cassandra versions
Could not find this paragraph in earlier versions.
=> COPS-1940 Correcting line breaks in Cassandra config docs.

pages/1.11/installing/ent/custom/cli/index.md
`customer_key` removed, `fault_domain_enabled` and `enable_ipv6` added, comment regarding `bootstrap_url` improved.
https://jira.mesosphere.com/browse/COPS-3411
=> [COPS-3411] Improved `config.yaml`

pages/version-policy/index.md
Updated compatibility matrix as per Senthil's suggestion on #dcos-release channel. 
=> Moved * against CoreOS 1688.5.3.

pages/1.10/installing/ent/custom/cli/index.md, pages/1.10/installing/oss/custom/cli/index.md, pages/1.11/installing/ent/custom/cli/index.md, pages/1.11/installing/oss/custom/cli/index.md, pages/1.8/administration/installing/ent/custom/cli/index.md, pages/1.9/installing/ent/custom/cli/index.md, pages/1.9/installing/oss/custom/cli/index.md
https://jira.mesosphere.com/browse/COPS-3411
This PR fixes up the configuration section of CLI install docs to correct or clarify guidance, makes clear which config values are required, and explains default values specific to the CLI installer. See commits for a list of individual fixes.
Tested the 1.11 Enterprise doc manually.
=> CLI install doc fixes

pages/1.11/networking/DNS/index.md
https://jira.mesosphere.com/browse/DCOS-34436
Only the 1.11 docs were corrected, since the  1.10 and earlier docs are very different.
=> DCOS-34436 Correcting service name issues in 1.11

pages/1.10/installing/oss/custom/gui/index.md, pages/1.11/installing/oss/custom/gui/index.md, pages/1.9/installing/oss/custom/gui/index.md
https://jira.mesosphere.com/browse/DCOS-25802
*URL:* http://docs2-staging.mesosphere.com/1.10/installing/oss/custom/gui/
*Description:* 
1. Add an open source label to this page
2. Has the logo on the login page been updated? If so we might need new screenshots here. 
3. Misformatted subheadings. 1st subheading under sections displaying on same line as heading see [example here|http://docs2-staging.mesosphere.com/1.10/installing/oss/custom/gui/#deployment-settings]
Corrections:
1. Already there
2. No and No; this feature discontinued in 1.11
3. Updated versions 1.9, 1.10, and 1.11
=> DCOS-25802 Corrected formatting on subheadings.

pages/1.10/installing/ent/custom/system-requirements/index.md, pages/1.10/installing/oss/custom/system-requirements/index.md, pages/1.11/installing/ent/custom/system-requirements/index.md, pages/1.11/installing/oss/custom/system-requirements/index.md
https://jira.mesosphere.com/browse/COPS-3375
The COPS issue refers to 1.10, so I changed 1.10+.
This increases the recommended free space in `/var` to 20 GB.
If approved, we will recommend @mikejennings 's customer from the `COPS` issue to give `/var` more free space.
However, this is not backed by tests.
As proposed by Gustav, this should be looked at by "Andrew Shahan or Justin Lee, etc" - @gpaul , please add anyone from "etc' to "Reviewers".
For one of  "Andrew Shahan or Justin Lee, etc" - please could you consider whether it is useful to do the following (also suggested by @gpaul ) and if so, do it - "Informally we could just ask how full /var is on a strict mode cluster at JPMC?".
- Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/R …
=> Increase the agent requirements for `/var` free space to 20 GB

docker/nginx/redirects-301.map
https://jira.mesosphere.com/browse/DCOS_OSS-3734
=> DCOS_OSS-3734: Add redirect for webinterface for all versions since it was renamed gui

docker/nginx/redirects-301.map
Combine two regex and remove error. This regex adds a `/` to the
end of appropriate paths that don't already have them.
^.*/ => capture everything up to the last `/`
[^.]* => don't match when `.` in last section (eg: /assets/image.png)
[^/] => last character shouldn't already be a `/`
=> DCOS-26143 Remove double slash `//` redirect issue

docker/nginx/redirects-301.map
This regex adds a `/` to the end of appropriate paths that don't
already have them.
^.*/ => capture everything up to the last `/`
[^.]* => don't match when `.` in last section (eg: /assets/image.png)
[^/] => last character shouldn't already be a `/`
=> DCOS-26143 Add missing `~` at front of regex

pages/services/edge-lb/0.1/index.md, pages/services/edge-lb/1.0/index.md, pages/services/edge-lb/index.md
https://jira.mesosphere.com/browse/DCOS-26349
In the EdgeLB documentation introduction - the statement is ambiguous. 
"Edge-LB proxies and load balances traffic to all services that run on DC/OS. Edge-LB provides both North-South (external to internal) load balancing, while the Minuteman component provides East-West (internal to internal) load balancing."
It should either say both North-south and East-West, or remove the word both.
Corrected versions:
=> DCOS-26349 Correcting intro in both versions

pages/services/kafka/2.3.0-1.1.0/index.md, pages/services/kafka/2.3.0-1.1.0/ordr_0-getting-started/index.md, pages/services/kafka/2.3.0-1.1.0/ordr_1-configuration/index.md, pages/services/kafka/2.3.0-1.1.0/ordr_10-support-policy/index.md, pages/services/kafka/2.3.0-1.1.0/ordr_11-release-notes/index.md, pages/services/kafka/2.3.0-1.1.0/ordr_2-operations/index.md, pages/services/kafka/2.3.0-1.1.0/ordr_3-updates/index.md, pages/services/kafka/2.3.0-1.1.0/ordr_4-security/index.md, pages/services/kafka/2.3.0-1.1.0/ordr_5-uninstall/index.md, pages/services/kafka/2.3.0-1.1.0/ordr_6-troubleshooting/index.md, pages/services/kafka/2.3.0-1.1.0/ordr_7-advanced/index.md, pages/services/kafka/2.3.0-1.1.0/ordr_8-api-reference/index.md, pages/services/kafka/2.3.0-1.1.0/ordr_9-limitations/index.md
[DCOS-37640](https://jira.mesosphere.com/browse/DCOS-37640)
There is now a DCOS `2.3.0-1.1.0`.
Note: The only change I made was add a new line in the release notes
page pointing to Kafka's own release notes. The rest is just a copy of
folder 2.3.0-1.0.0.
=> Create new docs for Kafka 1.1.0 upgrade

pages/1.11/storage/mount-disk-resources/index.md
Documentation on mount disk resources is outdated and incomplete.
When the user changes the agent resources, there is one step missing in the guide; removing the agent's checkpointed resources
https://jira.mesosphere.com/browse/DCOS_OSS-3713
=> Fixed checkpointed resources removal omission.

pages/services/kafka/2.3.0-1.1.0/index.md
Missed updating the meta version number for the 1st page.
=> Fix Kafka version number for pages in 2.3.0-1.1.0

pages/services/edge-lb/1.0/installing/index.md
https://jira.mesosphere.com/browse/DCOS-39518
Spurious backslash found in two commands:
dcos package repo add --index=0 edgelb \ https://<insert download link>/stub-universe-edgelb.json
dcos package repo add --index=0 edgelb-pool \ https://<insert download link>/stub-universe-edgelb-pool.json
Deleted both backslashes.
=> ss/DCOS-39518 Deleting extra backslashes in commands.

pages/services/percona-mongo/0.2.0-3.4.13/deploy-best-practice/index.md, pages/services/percona-mongo/0.2.0-3.4.13/mongodb-administration/index.md, pages/services/percona-mongo/0.2.0-3.4.13/quick-start/index.md
Internal Percona QA JIRAs (not public) identified a few typos or corrections needed in the docs:
1. Transparent HugePages isn't RedHat/CentOS only.
2. Wrong username in Quick Start example.
3. Typos.
4. Broken link.
=> Fixing typos and correcting a few mistakes in 0.2.0 docs after QA

pages/services/edge-lb/1.0/installing/index.md
https://jira.mesosphere.com/browse/DCOS-39731
On the following page: https://docs.mesosphere.com/services/edge-lb/1.0/installing/#create-a-configuration-file-for-service-authentication
Add a 5th bullet (beneath service.mem) that says:
service.mesosProtocol: "https" (default) for Permissive and Strict security modes, "http" for Disabled security mode.
=====
Done.
=> ss/DCOS-39731 Adding service.mesosProtocol info to install docs.

index.js
If not, gaze will break with a "too many files" error. This is a
better fix than changing people's computer config to allow more
files to be open at once.
https://jira.mesosphere.com/browse/DCOS-40191
=> Only allow watching with a RENDER_PATH_PATTERN

pages/services/kafka/2.0.1-0.11.0/troubleshooting/index.md, pages/services/kafka/2.0.2-0.11.0/troubleshooting/index.md, pages/services/kafka/2.0.3-0.11.0/troubleshooting/index.md, pages/services/kafka/2.0.4-1.0.0/troubleshooting/index.md, pages/services/kafka/v1.1.19.1-0.10.1.0/troubleshooting/index.md, pages/services/kafka/v2.0.0-0.11.0/troubleshooting/index.md
https://jira.mesosphere.com/browse/DCOS-25729
via Community Slack: https://dcos-community.slack.com/archives/C132NTZJN/p1508943125000320
The current Service Docs for Kafka at https://docs.mesosphere.com/service-docs/kafka/2.0.2-0.11.0/troubleshooting/ state that a broker can be replaced with dcos kafka broker replace <broker_i> which is incorrect and must instead be dcos kafka pod replace <name> as corrected by Nicholas Parker - https://dcos-community.slack.com/archives/C132NTZJN/p1508950250000087
Please fix.
Corrected in following versions:
1.1.19.1-0.10-0
2.0.0-0.11.0
2.0.1-0.11.0
2.0.2-0.11.0
2.0.3-0.11.0
2.0.4-1.0.0
=> ss/DCOS-25729 Replacing variable name in Troubleshooting sections.

pages/services/kafka/2.0.1-0.11.0/troubleshooting/index.md, pages/services/kafka/2.0.2-0.11.0/troubleshooting/index.md, pages/services/kafka/2.0.3-0.11.0/troubleshooting/index.md, pages/services/kafka/2.0.4-1.0.0/troubleshooting/index.md, pages/services/kafka/v1.1.19.1-0.10.1.0/troubleshooting/index.md, pages/services/kafka/v2.0.0-0.11.0/troubleshooting/index.md
https://jira.mesosphere.com/browse/DCOS-25729
via Community Slack: https://dcos-community.slack.com/archives/C132NTZJN/p1508943125000320
The current Service Docs for Kafka at https://docs.mesosphere.com/service-docs/kafka/2.0.2-0.11.0/troubleshooting/ state that a broker can be replaced with dcos kafka broker replace <broker_i> which is incorrect and must instead be dcos kafka pod replace <name> as corrected by Nicholas Parker - https://dcos-community.slack.com/archives/C132NTZJN/p1508950250000087
Please fix.
My earlier fix was incorrect. This  fix replaces
`dcos kafka broker replace <broker-id>`
with 
`dcos kafka pod replace <name>' 
as requested.
Versions fixed:
=> ss/DCOS-25729 Correcting correction to Troubleshooting docs.

pages/services/cassandra/2.0.1-3.0.14/connecting-clients/index.md, pages/services/cassandra/2.0.2-3.0.14/connecting-clients/index.md, pages/services/cassandra/2.0.3-3.0.14/connecting-clients/index.md, pages/services/cassandra/v2.0.0-3.0.14/connecting-clients/index.md
https://jira.mesosphere.com/browse/COPS-1843
The Cassandra 2.0.1-3.0.14 documentation at https://docs.mesosphere.com/service-docs/cassandra/2.0.1-3.0.14/connecting-clients/ needs the following edit:
Hi! We need to update this string `docker run cassandra:3.0.13 cqlsh node-0-server.cassandra.autoip.dcos.thisdcos.directory`; as it will not open up an interactive session. We need to add -it.
The correct string is `docker run -it cassandra:3.0.13 cqlsh node-0-server.cassandra.autoip.dcos.thisdcos.directory`
Corrected code as specified in versions:
=> ss/COPS-1843 Correcting code in connecting-clients.

pages/services/kafka/2.0.1-0.11.0/api-reference/index.md, pages/services/kafka/2.0.2-0.11.0/api-reference/index.md, pages/services/kafka/2.0.3-0.11.0/api-reference/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-1719
There's a documentation bug in https://docs.mesosphere.com/service-docs/kafka/2.0.1-0.11.0/api-reference/#view-plan-status .  The curl command should be `curl -H "Authorization: token=$auth_token" "$dcos_url/service/kafka/v1/plans/deploy"`
Corrected in versions
=> ss/DCOS_OSS-1719 Fixing curl command bug.

pages/services/edge-lb/1.0/installing/index.md, pages/services/edge-lb/1.0/upgrading/index.md
This PR adds a description for the newly introduced package option for EdgeLB: `mesosAuthNZ`. It enables users to install EdgeLB on 1.10 cluster working in security mode `Disabled`.
@SarahStegall @masonse @GoelDeepak  Please feel free to edit this PR the way you like, and treat my work just as a draft. I have marked it as Blocker as we need to get it out ASAP, as EdgeLb v1.1 is out today.
=> Add information about the new install-time param: `mesosAuthNZ`

pages/1.11/networking/load-balancing-vips/index.md, pages/services/edge-lb/1.0/release-notes/index.md
This PR adds release notes for EdgeLB v1.1.0 plus some minor improvements to the existing docs.
**Please do not merge until EdgeLB v1.1.0 is released**
* https://jira.mesosphere.com/browse/DCOS-25625 `edgelb: upgrade HAProxy to version 1.8`
* https://jira.mesosphere.com/browse/DCOS-38061 `[Edge-lb]: Provide operator methods to update instances with long running connections`
* https://jira.mesosphere.com/browse/COPS-3463 `Timeout kill haproxy if it takes longer than X to reload`
* https://jira.mesosphere.com/browse/COPS-3462 `EdgeLB should be able to re-load even if one of the backends have long running connections`
* https://jira.mesosphere.com/browse/DCOS-37564 `edgelb: Iptables rules removal should be attempted only once.`
* https://jira.mesosphere.com/browse/COPS-3166 `Possible …
=> EdgeLB v1.1.0 release notes

docker/nginx/redirects-301.map
Added redirect for Apache Ignite documentation
`old link` -https://docs.mesosphere.com/getting-started/datacenter/install/
`new link` - https://docs.mesosphere.com/latest/installing/
=> Added redirect for Apache Ignite documentation.

pages/services/spark/2.1.0-2.2.0-1/hdfs/index.md, pages/services/spark/2.1.0-2.2.1-1/hdfs/index.md, pages/services/spark/v2.0.0-2.2.0-1/hdfs/index.md, pages/services/spark/v2.0.1-2.2.0-1/hdfs/index.md
https://jira.mesosphere.com/browse/COPS-1736
Added this to /spark/version/hdfs/index.md:
For DC/OS HDFS, these configuration files are served at `http://api.<hdfs>.marathon.l4lb.thisdcos.directory/v1/endpoints` where <hdfs> is the name of the HDFS package configured at installation.
*Example:*
````
"hdfs":
{  "config-url": "[http://api.hdfs.marathon.l4lb.thisdcos.directory/v1/endpoints\|http://api.hdfs.marathon.l4lb.thisdcos.directory/v1/endpoints%5C]"  }
,
````
Versions:
=> ss/COPS-1736 correcting Spark HDFS config.

pages/1.12/installing/production/advanced-configuration/configuration-reference/index.md
Document new ``permissions_cache_ttl_seconds`` configuration parameter.
This is a 1.12 only parameter.
https://jira.mesosphere.com/browse/DCOS-38958
=> Document new ``permissions_cache_ttl_seconds`` configuration parameter.

pages/services/edge-lb/index.md
https://jira.mesosphere.com/browse/DCOS-40529
Fixing order of service docs.
Corrected menuweight value of Edge-LB docs.
=> ss/DCOS-40529 Fixing menuweight in Edge-LB docs.

pages/services/dse/2.3.0-5.1.2/advanced/index.md, pages/services/dse/2.3.0-5.1.2/api-reference/index.md, pages/services/dse/2.3.0-5.1.2/configuration/index.md, pages/services/dse/2.3.0-5.1.2/getting-started/index.md, pages/services/dse/2.3.0-5.1.2/index.md, pages/services/dse/2.3.0-5.1.2/limitations/index.md, pages/services/dse/2.3.0-5.1.2/operations/index.md, pages/services/dse/2.3.0-5.1.2/release-notes/index.md, pages/services/dse/2.3.0-5.1.2/security/index.md, pages/services/dse/2.3.0-5.1.2/support-policy/index.md, pages/services/dse/2.3.0-5.1.2/troubleshooting/index.md, pages/services/dse/2.3.0-5.1.2/uninstall/index.md, pages/services/dse/2.3.0-5.1.2/updates/index.md
Release docs of DataStax 2.3.0 including:
- `datastax-dse`: `2.3.0-5.1.2`
- `datastax-ops`: `2.3.0-6.1.2`
https://jira.mesosphere.com/browse/DCOS-38715
=> Add docs for DSE 2.3.0-5.1.2

scss/base/_content.scss, scss/base/_global.scss, scss/components/_prism.scss
https://jira.mesosphere.com/browse/DCOS-25764
=> DCOS-25764 Documentation styling is too wide in Firefox

pages/1.10/deploying-services/uninstall/index.md, pages/1.11/deploying-services/uninstall/index.md, pages/1.12/deploying-services/uninstall/index.md, pages/services/include/uninstall.tmpl
(Background: Before 1.10, janitor.py was how users needed to uninstall data services. As of 1.10+ they use a new flow which no longer requires running janitor.py)
Adds documentation for the -a/--username/--password arguments which are needed on strict mode clusters.
Also makes the following clarifications in older docs:
- This command should only rarely be needed on 1.10+ clusters, so 1.10+ docs have been updated to reflect that.
- Removes references to the unused `-p` argument, which is actually ignored by janitor.py.
- Updates examples to not make references to data services which no longer use janitor for uninstall.
https://jira.mesosphere.com/browse/DCOS-38576
- Change …
=> DCOS-38576: Fixes to old janitor documentation

pages/1.10/administering-clusters/deploying-a-local-dcos-universe/index.md, pages/1.11/administering-clusters/deploying-a-local-dcos-universe/index.md, pages/1.12/administering-clusters/deploying-a-local-dcos-universe/index.md, pages/1.7/administration/installing/ent/custom/deploying-a-local-dcos-universe/index.md, pages/1.9/administering-clusters/deploying-a-local-dcos-universe/index.md
[DCOS-38551](https://jira.mesosphere.com/browse/DCOS-38551)
- The instructions are referring to a step 27 that is supposed to be different from what they instruct, but it is the same command copied over again. Hence I removed the phrasing `.... except step 27. Replace the command in step 27 with the following.......`
- 1.8 already looks good so I did not touch those files.
=> Remove stale documentation from local universe deployment

entry.js, js/ellipsis.js, js/main.js, js/sidebar.js, js/tabs.js, package.json, scss/components/_tabs.scss, scss/style.scss, webpack.config.js
* [DCOS_OSS-4004](https://jira.mesosphere.com/browse/DCOS_OSS-4004)
This commit introduces a run-time extension to the docs page that automatically converts annotated headings into tabs. The PDF version of the documentation should not be affected by this PR.
This would greatly simplify some documentation updates that I am preparing for marathon, so if such PR matches to your standards, please merge it as soon as possible 😄 
_NOTE: I also performed some boy-scout clean-up in order to fix some problems that I encountered while debugging offline_
To use this, append the class `{.tabs}` on the heading section of your choice
and the extension will automatically convert child headings into tabs. For example:
```md
...
Here is a preamble that does not participate in the tab creation.
Here are …
```
=> Introduce Tabbed Content Support

pages/1.10/installing/oss/custom/system-requirements/index.md, pages/1.11/installing/production/system-requirements/index.md, pages/1.12/installing/production/system-requirements/index.md, pages/1.8/administration/installing/oss/custom/system-requirements/index.md, pages/1.9/installing/oss/custom/system-requirements/index.md
https://jira.mesosphere.com/browse/COPS-2966
For all versions, docs currently say that mounting /tmp/ with noexec is not supported.
https://docs.mesosphere.com/1.10/installing/oss/custom/system-requirements/#agent-nodes
Based on COPS-1663 and DCOS_OSS-634, it appears that this is no longer a requirement. 
However, a caveat might be necessary to indicate that noexec on a system where you intend to use the DC/OS CLI could break CLI functionality unless a TMPDIR environment variable is set to something other than /tmp/.
Versions edited:
1.8
1.9
1.10
1.11
1.12
=> ss/COPS-2966 Editing requirement to not mount /tmp/ with noexec.

pages/1.10/developing-services/index.md, pages/1.11/developing-services/index.md, pages/1.12/developing-services/index.md, pages/1.9/developing-services/index.md
https://jira.mesosphere.com/browse/COPS-677
It would be helpful to add a note somewhere in this documentation that our general recommendation is to utilize the DC/OS CLI rather than the DC/OS GUI throughout the process of creating a package for the Universe.
Added the following to /developing-services/index.md:
"Our general recommendation is to use the DC/OS CLI rather than the DC/OS web interface throughout the process of creating a package for the Universe."
Versions changed:
=> ss/COPS-677 Added recommendation to use CLI for package creation.

pages/1.10/installing/ent/custom/system-requirements/index.md, pages/1.11/installing/production/system-requirements/index.md, pages/1.12/installing/production/system-requirements/index.md, pages/1.9/installing/oss/custom/system-requirements/index.md
https://jira.mesosphere.com/browse/COPS-2968
Original customer requests:
https://mesosphere.zendesk.com/agent/tickets/10148
https://mesosphere.zendesk.com/agent/tickets/5100
https://mesosphere.slack.com/archives/C114BQSKD/p1523988179000195
Documentation page: https://docs.mesosphere.com/1.11/installing/ent/custom/system-requirements/
According to Mesos engineers, UCR containerizer is using OverlayFS backend to create a root directory for containers.
When using OverlayFS over XFS, the XFS volume should be created with the -n ftype=1 flag. Please see the Red Hat and 
Mesos documentation for more details.
I think it would be very beneficial for our customers to have this information in the list of prerequisites. It's not the first time when a customer is contacting us with this: …
=> ss/COPS-2968 Adding XFS-n flag in prerequisites.

pages/1.11/networking/SDN/usage/index.md
https://jira.mesosphere.com/browse/COPS-2883
Here is the page:
https://docs.mesosphere.com/1.11/networking/SDN/usage/
I think the portMappings section should be under container, not under docker.
And the network section under docker isn't allowed.
I've been able to deploy an app by changing the location of the portMappings section and by removing the network section. It seems to work well this way...We need to do it only on DC/OS 1.11 docs.
=> ss/COPS-2883 Replaced older JSON file with newer version.

pages/1.11/administering-clusters/index.md
Administering-clusters index page had duplicate enterprise tags. Deleted "enterprise: true" tag.
=> Fixing enterprise tag error in Administering-Clusters.

pages/1.11/monitoring/logging/aggregating/splunk/index.md
This issue was discovered while working on [MESOS-9196](https://issues.apache.org/jira/browse/MESOS-9196). Discussed with @jieyu that this may be causing a serious issue for splunk users.
[MESOS-9196](https://issues.apache.org/jira/browse/MESOS-9196)
Scraping the /mesos/slave directory in environments that frequently launch and destroy jobs causes forwarder to lock files and prevent containers from being destroyed. This cascades into situations where containers become stuck in a restart cycle.
- [ x ] High
=> Update and correct path for log capture

pages/1.10/monitoring/logging/aggregating/splunk/index.md, pages/1.11/monitoring/logging/aggregating/splunk/index.md, pages/1.9/monitoring/logging/aggregating/splunk/index.md
https://jira.mesosphere.com/browse/DCOS-41397
https://jira.mesosphere.com/browse/DCOS-41398
iflowfor8hours:patch-1
Problem:
We have documentation around splunk integration
https://docs.mesosphere.com/1.11/monitoring/logging/aggregating/splunk/
To collect sandbox logs, we recommand our customers to use this command:
"$SPLUNK_HOME/bin/splunk" add monitor '/var/lib/mesos/slave' \
-whitelist '/stdout$|/stderr$'
This will cause splunk to scan Mesos provisioner directories which contain Mesos container rootfses. Instead, we should ask Splunk to only scan `/var/lib/mesos/slave/slaves` where sandboxes are located.
Solution:
Changed 
'$SPLUNK_HOME/bin/splunk" add monitor '/var/lib/mesos/slave' '
to 
'$SPLUNK_HOME/bin/splunk" add monitor '/var/lib/mesos/slave/slave'
in …
=> ss/DCOS-41397 corrected splunk code for forwarder.

pages/services/kubernetes/1.0.0-1.9.3/advanced-install/index.md, pages/services/kubernetes/1.0.1-1.9.4/advanced-install/index.md, pages/services/kubernetes/1.0.2-1.9.6/advanced-install/index.md, pages/services/kubernetes/1.0.2-1.9.6/release-notes/index.md, pages/services/kubernetes/1.0.3-1.9.7/advanced-install/index.md, pages/services/kubernetes/1.1.0-1.10.3/advanced-install/index.md, pages/services/kubernetes/1.1.1-1.10.4/advanced-install/index.md, pages/services/kubernetes/1.1.1-1.10.4/exposing-the-kubernetes-api/index.md, pages/services/kubernetes/1.2.0-1.10.5/advanced-install/index.md, pages/services/kubernetes/1.2.0-1.10.5/exposing-the-kubernetes-api/index.md, pages/services/kubernetes/1.2.0-1.10.5/install/index.md, pages/services/kubernetes/1.2.1-1.10.6/advanced-install/index.md, pages/services/kubernetes/1.2.1-1.10.6/exposing-the-kubernetes-api/index.md, pages/services/kubernetes/1.2.1-1.10.6/install/index.md, scripts/service-update-scripts/kubernetes-merge-branch.sh, scripts/service-update-scripts/kubernetes-merge.sh
Changes for [docs layout proposal](https://docs.google.com/document/d/1IyD9rZOUgsSSG6O1f119tedJKyYqSgGGlbi1YQGydZc/edit)
PR https://github.com/mesosphere/dcos-kubernetes/pull/643 must be merged to support the new scripts.
```
./scripts/service-update-scripts/kubernetes-merge-branch.sh $BRANCH [comma separated versions to skip when copying]
```
- This looked like a bug?
Existing code - moved 1.10 to 1.11 references and was missing for 1.12
```
awk '{gsub(/https:\/\/docs.mesosphere.com\/1.9\//,"/1.9/");}{print}' $p > tmp && mv tmp $p
awk '{gsub(/https:\/\/docs.mesosphere.com\/1.10\//,"/1.10/");}{print}' $p > tmp && mv tmp $p
awk '{gsub(/https:\/\/docs.mesosphere.com\/1.10\//,"/1.11/");}{print}' $p > tmp && mv tmp $p
awk '{gsub(/https:\/\/docs.mesosphere.com\/latest\//,"/latest/");}{print}' …
```
=> Kubernetes service docs layout

Makefile
https://jira.mesosphere.com/browse/DCOS-41611
A `Makefile` contains dependencies (artifacts that must be built before the current artifact) and shell commands. The dependencies must be listed after the colon following the artifact to be built. Currently, they are listed in following lines, and hence are interpreted as shell commands.
=> Put Makefile dependencies in correct position

pages/services/include/common-operations.tmpl, pages/services/include/diagnostic-tools.tmpl, pages/services/include/install1.tmpl, pages/services/include/install2.tmpl, pages/services/include/overview.tmpl
https://jira.mesosphere.com/browse/DCOS-40326
Editing /services/include/ files. These five files were marked "TBDeleted" and were not called by any of the existing documents in the repo.
=> ss/DCOS-40326 Deleting service files marked for deletion.

pages/services/dse/2.0.2-5.1.2/api-reference/index.md, pages/services/dse/2.0.3-5.1.2/api-reference/index.md, pages/services/dse/2.0.4-5.1.2/api-reference/index.md, pages/services/dse/2.0.5-5.1.2/api-reference/index.md, pages/services/dse/v2.0.0-5.1.2/api-reference/index.md
https://jira.mesosphere.com/browse/DCOS-25801
URL: http://docs2-staging.mesosphere.com/services/dse/v2.0.0-5.1.2/api-reference/
Description:
If you are using open source DC/OS, follow these instructions to [pass your HTTP API token to the DC/OS endpoint]https://dcos.io/1.10/security/oss/iam-api/).
Actually, all the links in this section are out of date. Corrected /ent/ and /oss/ links to security docs for the following versions:
2.0.0-5.1.2
2.0.2-5.1.2
2.0.3-5.1.2
2.0.4-5.1.2
2.0.5-5.1.2
=> ss/DCOS-25801 Correcting links to REST API authentication.

index.js
https://jira.mesosphere.com/browse/DCOS-39286
I did testing to make sure data loading and templates work. Feel free to do some testing of your own. I just copied existing template and data files from the service docs.
=> DCOS-39286 Allow data loading and templates in dcos versions

scss/components/_grid.scss
When it doesn't, this causes a problem with the width of
the subtopic cards when there is only one because the
card width is ~50% of grid
https://jira.mesosphere.com/browse/DCOS-40865
=> DCOS-40865 Allow grid to take up entire width

pages/services/kubernetes/1.3.0-1.10.8/index.md
This PR is to remove the extra `Version` string in the `1.3.0-1.10.8` documentation 
https://jira.mesosphere.com/browse/DCOS-42027
=> kubernetes: remove extra version string in the title

pages/1.10/storage/mount-disk-resources/index.md, pages/1.11/storage/mount-disk-resources/index.md, pages/1.12/storage/mount-disk-resources/index.md
We now recommend to move the previous Mesos resources file to a cache
instead of removing it. Following the DC/OS update for 1.10/1.11/1.12,
this cache will automatically be used when creating the new resources
file and thus fix the issue described in DCOS_OSS-3921.
https://jira.mesosphere.com/browse/DCOS_OSS-3921
=> Updated Mount Disk Resources instructions to use cache system.

pages/1.10/installing/ent/cloud/aws/advanced/template-reference/index.md, pages/1.10/installing/oss/cloud/aws/advanced/template-reference/index.md, pages/1.11/installing/evaluation/cloud-installation/aws/advanced/template-reference/index.md, pages/1.12/installing/evaluation/cloud-installation/aws/advanced/template-reference/index.md, pages/1.7/administration/installing/ent/cloud/aws/advanced/template-reference/index.md, pages/1.7/administration/installing/oss/cloud/aws/advanced/template-reference/index.md, pages/1.8/administration/installing/ent/cloud/aws/advanced/template-reference/index.md, pages/1.8/administration/installing/oss/cloud/aws/advanced/template-reference/index.md, pages/1.9/installing/ent/cloud/aws/advanced/template-reference/index.md, pages/1.9/installing/oss/cloud/aws/advanced/template-reference/index.md
Remove linking in header for Zen template info and normalize the styling across all the docs
https://jira.mesosphere.com/browse/DCOS-25758
- [x ] Medium
=> ck/DCOS-25758 Correct Zen template header and normalize styling 

pages/1.12/installing/evaluation/cloud-installation/aws/advanced/index.md, pages/1.12/installing/evaluation/cloud-installation/aws/advanced/template-reference/index.md, pages/1.12/installing/evaluation/cloud-installation/aws/basic/index.md, pages/1.12/installing/evaluation/cloud-installation/aws/index.md, pages/1.12/installing/evaluation/cloud-installation/azure/index.md, pages/1.12/installing/evaluation/cloud-installation/digitalocean/index.md, pages/1.12/installing/evaluation/cloud-installation/index.md, pages/1.12/installing/evaluation/cloud-installation/packet/index.md, pages/1.12/installing/evaluation/index.md, pages/1.12/installing/evaluation/on-premise-installation/index.md, pages/1.12/installing/index.md, pages/1.12/installing/installation-faq/index.md, pages/1.12/installing/production/advanced-configuration/configuration-reference/index.md, pages/1.12/installing/production/advanced-configuration/configuring-gpu-nodes/index.md, pages/1.12/installing/production/advanced-configuration/configuring-zones-regions/index.md, pages/1.12/installing/production/advanced-configuration/index.md, pages/1.12/installing/production/deploying-dcos/configuration/index.md, pages/1.12/installing/production/deploying-dcos/configure-proxy/index.md, pages/1.12/installing/production/deploying-dcos/index.md, pages/1.12/installing/production/deploying-dcos/installation/index.md, pages/1.12/installing/production/deploying-dcos/node-cluster-health-check/index.md, pages/1.12/installing/production/deploying-dcos/opt-out/index.md, pages/1.12/installing/production/patching/index.md, pages/1.12/installing/production/system-requirements/custom-ami/index.md, pages/1.12/installing/production/system-requirements/docker-centos/index.md, pages/1.12/installing/production/system-requirements/ports/index.md, pages/1.12/installing/production/upgrading/index.md, pages/1.12/installing/troubleshooting/index.md
Replaced 1.11 with 1.12 on https://docs.mesosphere.com/1.12/installing/
=> 1.12>>Installing docs - Replaced 1.11 with 1.12.

pages/1.11/developing-services/tunnel/index.md, pages/1.12/developing-services/cli-spec/index.md, pages/1.12/developing-services/index.md, pages/1.12/developing-services/tunnel/index.md
https://jira.mesosphere.com/browse/DCOS-42316
1.12 edits in the developing dcos services page
also updated a table on the tunnel subpage, and went to 1.11 to fix that one too
=> 1.12 edits in developing dcos, fix table on tunnel page

pages/1.10/tutorials/autoscaling/cpu-memory/index.md, pages/1.11/tutorials/autoscaling/cpu-memory/index.md, pages/1.12/tutorials/autoscaling/cpu-memory/index.md, pages/1.9/tutorials/autoscaling/cpu-memory/index.md
https://jira.mesosphere.com/browse/DCOS-25870
Broken link format fixed across 1.9-1.12
- [ X] Medium
=> Fix broken autoscale repo link ck/DCOS-25870

pages/1.12/monitoring/logging/configure-task-logs/index.md
These environment variables supersede the documentation on the Apache
Mesos website: http://mesos.apache.org/documentation/latest/sandbox/
The same documentation applies to older versions of DC/OS as well (1.9.0 and upwards).
I will copy the document to the other versions once this one is reviewed.
[DCOS-41566](https://jira.mesosphere.com/browse/DCOS-41566)
=> Added descriptions of task-level tweaks to task logging.

pages/1.10/administering-clusters/securing-your-cluster/index.md, pages/1.10/installing/ent/ports/index.md, pages/1.10/installing/oss/ports/index.md, pages/1.10/installing/ports/index.md, pages/1.10/security/ent/hardening/index.md, pages/1.10/security/oss/index.md, pages/1.11/administering-clusters/securing-your-cluster/index.md, pages/1.11/installing/production/system-requirements/ports/index.md, pages/1.11/security/ent/hardening/index.md, pages/1.11/security/oss/index.md, pages/1.12/administering-clusters/securing-your-cluster/index.md, pages/1.12/installing/production/system-requirements/ports/index.md, pages/1.12/security/ent/hardening/index.md, pages/1.12/security/oss/index.md
https://jira.mesosphere.com/browse/DCOS-42583
We need to ensure that our documentation emphasizes network security, especially from external access. This changes text in several relevant places to give a more definite action for cluster installers and administrators to take.
=> Add network security section

pages/1.11/release-notes/1.11.6/index.md
Reverts mesosphere/dcos-docs-site#1532
=> Revert "1.11.6 relnotes: Remove Enterprise label from ZooKeeper bump"

pages/1.11/release-notes/1.11.6/index.md
See discussion in https://groups.google.com/a/dcos.io/d/msgid/users/CAPrjPrDqAMw0rHodzppiaa0QkYX37prvMZdSDcggn%3DsQ5mC-ow%40mail.gmail.com?utm_medium=email&utm_source=footer
=> 1.11.6 relnotes: Remove Enterprise label from ZooKeeper bump

pages/1.12/deploying-services/marathon-on-marathon/advanced/index.md, pages/1.12/deploying-services/private-docker-registry/index.md
* [DCOS-39293](https://jira.mesosphere.com/browse/DCOS-39293)
This commit does some major refactoring on the 1.12 documentation pages regarding deployment
of a custom marathon-on-marathon instance with security features. Once this PR is accepted, these changes will be applied to the 1.11, 1.10, and 1.9 documentation branches.
=> 1.12: Deploying Services using a Custom Marathon with Security Features

pages/1.12/cli/install/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4011
This fixes come incorrectly merged docs.
=> Remove old documentation that was somehow added in during the merge

pages/services/cassandra/2.0.1-3.0.14/disaster-recovery/index.md, pages/services/cassandra/2.0.2-3.0.14/disaster-recovery/index.md, pages/services/cassandra/2.0.3-3.0.14/disaster-recovery/index.md, pages/services/cassandra/2.1.0-3.0.16/operations/index.md
https://jira.mesosphere.com/browse/DCOS-21390
On the Cassandra documentation:
https://docs.mesosphere.com/services/cassandra/2.0.3-3.0.14/disaster-recovery/
On the section to restore an S3 backup, it gives you the command to backup it.
Expected:
Command should be restore-s3 and not backup-s3
Corrected as described. Affects versions
2.0.1-3.0.14
2.0.2-3.0.14
2.0.3-3.0.14
2.1.0-3.0.16
Previous and subsequent versions do not have this error.
=> ss/DCOS-21390 Correcting error in restore s3 instructions.

pages/1.10/administering-clusters/securing-your-cluster/index.md, pages/1.10/installing/ent/ports/index.md, pages/1.10/installing/oss/ports/index.md, pages/1.10/installing/ports/index.md, pages/1.11/administering-clusters/securing-your-cluster/index.md, pages/1.11/installing/evaluation/cloud-installation/digitalocean/index.md, pages/1.11/installing/evaluation/cloud-installation/packet/index.md, pages/1.11/installing/evaluation/on-premise-installation/index.md, pages/1.11/installing/production/system-requirements/ports/index.md, pages/1.12/administering-clusters/securing-your-cluster/index.md, pages/1.12/installing/evaluation/cloud-installation/digitalocean/index.md, pages/1.12/installing/evaluation/cloud-installation/packet/index.md, pages/1.12/installing/evaluation/on-premise-installation/index.md, pages/1.12/installing/production/system-requirements/ports/index.md
https://jira.mesosphere.com/browse/DCOS-42708
Document the network rules required inside the cluster. Provides an explicit list of all the ports to be allowed or blocked between every type of node.
The list is removed from the ports page, to reduce duplication, but is linked from that page.
=> Document intra-cluster network access explicitly

docker/Dockerfile.docs
When I run the instructions at https://github.com/mesosphere/dcos-docs-site/wiki/Local-Build#using-docker I get the error:
```
Building: /usr/local/bin/node /src/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/src/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@https://registry.npmjs.org/node-gyp/-/node-gyp-3.6.2.tgz
gyp info using node@8.1.2 | linux | x64
gyp verb command rebuild []
gyp verb command clean [] …
```
=> Add Python to Docker container

pages/1.11/installing/production/patching/index.md, pages/1.11/installing/production/upgrading/index.md, pages/1.12/installing/production/patching/index.md, pages/1.12/installing/production/upgrading/index.md
https://jira.mesosphere.com/browse/DCOS-42511
https://jira.mesosphere.com/browse/DCOS-42762
Correct some ambiguities between patching and upgrading docs.
=> Split upgrading and patching docs more consistently

pages/1.12/overview/architecture/components/index.md
Noticed some dupe sections on a[ 1.12 docs page](https://docs.mesosphere.com/1.12/overview/architecture/components/#networking).
Going into the README code, looks like an html block (with the dupe sections) somehow got into this page. This seems to only affect 1.12 docs.
=> Remove dupe html block in 1.12 architecture/components docs

pages/services/percona-server-mongodb/index.md
A few more missing renames from percona-mongo -> percona-server-mongodb.
CC @ryadav88 
=> Missing rename for percona-mongo -> percona-server-mongodb

pages/services/beta-storage/0.3.0-beta/index.md, pages/services/beta-storage/0.3.2-beta/index.md, pages/services/beta-storage/0.4.0-beta/index.md
DSS versions 0.3.x+ all require DC/OS 1.12 and since we have not yet
released that, we do not want to show those versions of DSS in our docs.
https://jira.mesosphere.com/browse/DCOS-42911
=> beta-storage: hide versions that require DCOS 1.12

pages/1.10/cli/enterprise-cli/index.md, pages/1.10/deploying-services/private-docker-registry/index.md, pages/1.11/cli/command-reference/dcos-security/index.md, pages/1.11/deploying-services/private-docker-registry/index.md, pages/1.12/cli/command-reference/dcos-security/index.md, pages/1.12/deploying-services/private-docker-registry/index.md, pages/1.8/usage/cli/enterprise-cli/index.md, pages/1.9/cli/enterprise-cli/index.md, pages/services/beta-confluent-kafka-zookeeper/2.1.1-4.0.0e-beta/kerberos/index.md, pages/services/beta-confluent-kafka/2.1.1-4.0.0e-beta/kerberos/index.md, pages/services/beta-confluent-kafka/2.1.2-4.0.0e-beta/kerberos/index.md, pages/services/beta-hdfs/2.1.1-2.6.0-cdh5.11.0-beta/kerberos/index.md, pages/services/beta-hdfs/2.1.2-2.6.0-cdh5.11.0-beta/kerberos/index.md, pages/services/beta-kafka-zookeeper/2.1.0-3.4.11-beta/kerberos/index.md, pages/services/beta-kafka-zookeeper/2.1.1-3.4.11-beta/kerberos/index.md, pages/services/beta-kafka-zookeeper/2.1.2-3.4.11-beta/kerberos/index.md, pages/services/beta-kafka/2.1.0-1.0.0-beta/kerberos/index.md, pages/services/beta-kafka/2.1.1-1.0.0-beta/kerberos/index.md, pages/services/beta-kafka/2.1.2-1.0.0-beta/kerberos/index.md, pages/services/beta-spark/2.2.0-2.2.0-2-beta/security/index.md, pages/services/beta-spark/2.2.1-2.2.0-2-beta/security/index.md, pages/services/beta-spark/2.3.0-2.2.0-2-beta/security/index.md, pages/services/beta-spark/2.3.1-2.2.1-2-beta/security/index.md, pages/services/include/advanced.tmpl, pages/services/spark/2.3.0-2.2.1-2/security/index.md, pages/services/spark/2.3.1-2.2.1-2/security/index.md
https://jira.mesosphere.com/browse/DCOS-40831
Updating the security cli for secrets creation to use --file instead of the old --value-file. 
- #### All code instances are currently changed to use --file
- #### Please indicate which ones should be --text-file (if any?)
Note, these changes will take effect for all docs 1.8-1.12
=> security cli update: change to --file ck/DCOS-40831

pages/1.10/security/ent/perms-reference/index.md, pages/1.11/security/ent/perms-reference/index.md, pages/1.12/security/ent/perms-reference/index.md, pages/1.9/security/ent/perms-reference/index.md, pages/include/permissions-inheritance-disclaimer.tmpl
https://jira.mesosphere.com/browse/COPS-2141
Per DCOS-15872, we do not currently support permissions inheritance for nested services in AdminRouter.  It would be helpful to call this out explicitly for customers.  
1. I created a .tmpl file in the /include/ folder: "NOTE: Mesosphere does not currently support permissions inheritance for nested services in AdminRouter."
2. I added this line to the /security/ent/perms-reference/#admin-router/ page:
#include /include/permissions-inheritance-disclaimer.tmpl
Versions affected:
1.9
1.10
1.11
1.12
SCREENSHOT of rendered file:
=> ss/COPS-2141 Added /include/ file disclaimer on AdminRouter permissions.

pages/services/edge-lb/0.1/pool-configuration/index.md, pages/services/edge-lb/1.0/pool-configuration/v2-examples/index.md, pages/services/edge-lb/1.1/pool-configuration/v2-examples/index.md, pages/services/edge-lb/1.2/pool-configuration/v2-examples/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-3724
Source: https://docs.mesosphere.com/services/edge-lb/1.0/pool-configuration/v2-examples
https://docs.mesosphere.com/services/edge-lb/1.0/pool-configuration/v2-examples/#mesos-frameworks-and-dcos-services
The protocol here should be TCP not HTTP.
Corrected all versions of Edge-LB to date.
=> ss/DCOS_OSS-3724 Correcting protocol in pool config docs.

pages/1.12/administering-clusters/repo/package-registry/operating/installing/index.md
[DCOS-44393](https://jira.mesosphere.com/browse/DCOS-44393) : Fix package registry documentation to refer to a working version of jenkins
=> Update package registry documentation to refer a working version of jenkins

pages/1.12/administering-clusters/deploying-a-local-dcos-universe/index.md
https://jira.mesosphere.com/browse/DCOS-44475
https://docs.mesosphere.com/1.12/administering-clusters/deploying-a-local-dcos-universe/ is leaking Markdown formatting at the very end (there's raw Markdown where there should be a link).
Fixed and tested formatting for hyperlink/anchor so that it takes user to correct link. Fixed only in 1.12; issue not found in earlier versions of this page.
=> ss/DCOS-44475 Correcting hyperlink to Certified Universe Packages.

pages/1.10/installing/production/system-requirements/docker-centos/index.md, pages/1.10/installing/production/system-requirements/index.md, pages/1.11/installing/production/system-requirements/docker-centos/index.md, pages/1.12/installing/production/system-requirements/docker-centos/index.md
https://jira.mesosphere.com/browse/DCOS-44149
Remove docker instructions due to bug that renders docker 17 unsupportable at the moment, these will be updated again once new set is written.
- [ x] High
=> CK/DCOS-44149 Remove docker instructions

pages/services/edge-lb/0.1/index.md, pages/services/edge-lb/1.0/index.md, pages/services/edge-lb/1.1/index.md, pages/services/edge-lb/1.2/index.md
https://jira.mesosphere.com/browse/DCOS-40388
The nav menu for Edge-LB is out of order. Also, reporter requested a change to the ordering of release notes for different versions of the software.
=> ss/DCOS-40388 Corrected menuweights for Edge-LB nav menu.

pages/1.10/installing/index.md, pages/1.11/installing/index.md, pages/1.12/installing/index.md
https://jira.mesosphere.com/browse/DCOS-44598
https://docs.mesosphere.com/1.12/installing/#mesosphere-supported
Although this issue is valid for all supported versions, meaning 1.12, 1.11, 1.10.
After the heading on installation, it says:
The DC/OS installation methods are as follows:
Mesosphere-supported installation: Use the Mesosphere-supported installation methods to test or demo DC/OS on AWS, Azure, or GCP using an Universal Installer.
Community-supported installation: Use the Community-supported installation methods to test or demo DC/OS on AWS, Azure, Digital Ocean or Packet.
It should not say *to test or demo DC/OS on AWS, Azure, or GCP using an Univeral Installer."
It should say Use the Mesosphere-supported installation methods to deploy DC/OS on AWS, Azure, or GCP using the …
=> ss/DCOS-44598 Correct wording on DC/OS installation page.

pages/version-policy/index.md
https://jira.mesosphere.com/browse/DCOS-44578
We have some updates needed for the Version Policy page.
https://docs.mesosphere.com/version-policy/
Specifically, with the DC/OS Platform Version Compatibility Matrix:
1. List the OSes by recency (i.e CentOS 7.5, 7.4, 7.3, CoreOS 1855, then CoreOS 1800.7, etc...) rather than from the opposite order (which is currently the oldest version of the OS first). THis is because we want to push users to the latest & greatest and show our support for that.
2. Please add "Oracle Linux 7.5 (RHCK), Oracle Linux 7.4 (RHCK), Oracle Linux 7.3 (RHCK)" as Platform component that is supported on all 3 latest stable of "DC/OS 1.12, 1.11, 1.10" - the bullet point should be the same as the CentOS/RHEL of "RH Fork of Docker CE 1.13.1".
1. Components re-ordered by …
=> ss/DCOS-44578 Re-order compatibility matrix, add Oracle.

pages/services/edge-lb/1.1/upgrading/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4062?filter=29702
Source: https://docs.mesosphere.com/services/edge-lb/1.1/upgrading
This page has references to a different package name:
```
dcos package repo remove edgelb-aws
dcos package repo remove edgelb-pool-aws
```
It is noted in other sections of the same document.
These should refer to:
```
dcos package repo remove edgelb
dcos package repo remove edgelb-pool
```
Corrected command in v. 1.2. Does not apply to previous versions.
=> ss/DCOS_OSS-4062 Corrected reference to package name.

pages/services/edge-lb/1.2/installing/index.md
https://jira.mesosphere.com/browse/COPS-4046?filter=29702
The Local Universe build instructions for Edge LB 1.2.1 reference a different version, and don't address a change that was made for edgelb-pool:
https://docs.mesosphere.com/services/edge-lb/1.2/installing/#deploying-a-local-universe-containing-edge-lb-enterprise
The code block under subheading 6 currently reads:
[sudo make DCOS_VERSION=1.11 DCOS_PACKAGE_INCLUDE="edgelb:v1.1.3,edgelb-pool:stub-universe,<other-package>:<version>" local-universe](url)
This is under the "1.2" doc, and edgelb-pool now uses discrete versions rather than "stub-universe", so it should be:
`sudo make DCOS_VERSION=1.11 DCOS_PACKAGE_INCLUDE="edgelb:v1.2.1,edgelb-pool:v1.2.1,<other-package>:<version>" local-universe`
This might also need to be changed in the …
=> ss/COPS-4046 Correcting Edge-LB version in code block.

pages/1.10/security/ent/index.md, pages/1.11/security/ent/index.md, pages/1.12/security/ent/index.md, pages/1.9/security/ent/index.md
Looking at defaults in 1.11 strict and 1.12-rc2 strict,
I see this is not the case: the default containerizer
is Docker, not Mesos (UCR).
Also clarify that Mesos is the same as UCR.
=> Update default containerizer type in "security/ent/index.md".

pages/services/pxc/0.1.0-5.7.21/security/index.md
Fix incorrect /services/include/ command in PXC security page.
=> ss/fix-pxc Correcting /include/ command in security page.

pages/services/spark/2.1.0-2.2.0-1/limitations/index.md, pages/services/spark/2.1.0-2.2.1-1/limitations/index.md, pages/services/spark/2.3.0-2.2.1-2/limitations/index.md, pages/services/spark/2.3.1-2.2.1-2/limitations/index.md, pages/services/spark/2.4.0-2.2.1-3/limitations/index.md, pages/services/spark/v2.0.0-2.2.0-1/limitations/index.md, pages/services/spark/v2.0.1-2.2.0-1/limitations/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4394
Added line indicating Spark does not currentlly work with CNI and shuffle operations will fail. 
- [ X] High
=> ck/DCOS_OSS-4394 Add Spark limitation

pages/services/dcos-monitoring/0.1.1/index.md, pages/services/dcos-monitoring/0.1.1/install/index.md, pages/services/dcos-monitoring/0.1.1/release-notes/index.md, pages/services/dcos-monitoring/0.1.1/tutorial/alertmanager-configs/index.md, pages/services/dcos-monitoring/0.1.1/tutorial/grafana-dashboard-configs/index.md, pages/services/dcos-monitoring/0.1.1/tutorial/index.md, pages/services/dcos-monitoring/0.1.1/uninstall/index.md
DC/OS Monitoring service v0.1.1 release.
Comparing v0.1.0, this release adds the missing release note. Nothing else has been changed.
=> dcos-monitoring: Update docs for 0.1.1

pages/services/edge-lb/1.2/release-notes/index.md
https://jira.mesosphere.com/browse/COPS-4192
Ask 1. Edit this date
v1.2.3
Released on November 27, 2018.
Ask 2. Add this section: under the Notable Changes section
Bug Fixes
LB task getting killed intermittently leading to outage for apps being load balanced
Ask 3. Add this section: Under the Notable Changes v1.2.2 section:
Bug Fixes
In DC/OS 1.11.3 EE (strict mode), non-superuser access needed to Edge-LB pool logs
EdgeLB – default template for SNI is incorrect
Edgelb should ignore terminal but not ack'ed tasks from Mesos when subscribing.
Edge-LB pool is unable to launch additional load balancer tasks
Edge LB pool can not deploy if app and secret are under namespace/group
Added bug fix sections, corrected date.
=> ss/COPS-4192 Additions to release notes 1.2.3.

docker/nginx/redirects-307.map
https://jira.mesosphere.com/browse/COPS-4184?filter=-1
By adding a redirect for spark/latest, we are covering a gap created by CLI instructions that point to services/spark/latest/uninstall, as there isn't actually a 'latest' redirect for any of the services docs.
The benefits of this are that it can handle latest for any subpage as long as that page exists in that version.
The drawbacks are making sure it stays up to date as the versions iterate through, and maintaining further redirects should there be a restructure of the services pages. However, they seem to be more static than the regular docs pages, and maintaining redirects would be a necessary check after that. 
- [ X] High
- Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redir …
=> ck/DCOS-4184 Add latest as a redirect for spark

pages/1.10/installing/installation-faq/index.md, pages/1.11/installing/installation-faq/index.md
https://jira.mesosphere.com/browse/COPS-4196
Restored the older information for 1.10 and 1.11 regarding backup and restoring the IAM database
=> ck/COPS-4196 ReRestore backup/restore information for 1.10 and 1.11

pages/1.10/installing/production/advanced-configuration/configuration-reference/index.md, pages/1.11/installing/production/advanced-configuration/configuration-reference/index.md
https://jira.mesosphere.com/browse/COPS-4200
- [x ] High
- Change all affected versions (e.g. 1.7, 1.8, 1.9, **1.10, 1.11,** 1.12).
=> Correct yaml formatting for 'dns_forward_zones' for 1.10 and 1.11.

pages/cn/1.11/administering-clusters/index.md
https://jira.mesosphere.com/browse/DCOS-45427
Metadata error in Administering Clusters Chinese edition caused the title to disappear from the landing page. Error fixed.
=> ss/DCOS-45427 Correcting metadata in admin-cluster docs.

pages/1.11/installing/production/upgrading/index.md
This reverts commit a1246d210616ece933f89cd3f5194dfcd41b1659.
=> Revert "ck/DCOS-45908 Remove upgrade paths matrix"

pages/services/edge-lb/1.0/pool-configuration/v2-reference/index.md, pages/services/edge-lb/1.1/pool-configuration/v2-reference/index.md, pages/services/edge-lb/1.2/pool-configuration/v2-reference/index.md
https://jira.mesosphere.com/browse/DCOS-25910
https://docs.mesosphere.com/services/edge-lb/1.0.0/pool-configuration/v2-reference/#poolhaproxybackendserviceendpoint
portName type marked as integer when it should have been a string. other pages that references this might have the same issue.
* Please see Zendesk Support tab for further comments and attachments.
Corrected in versions 1.0, 1.1, and 1.2
=> ss/DCOS-25910 Correcting field type of portName from integer to string.

pages/services/dcos-monitoring/0.2.1/index.md, pages/services/dcos-monitoring/0.2.1/install/index.md, pages/services/dcos-monitoring/0.2.1/release-notes/index.md, pages/services/dcos-monitoring/0.2.1/tutorial/alertmanager-configs/index.md, pages/services/dcos-monitoring/0.2.1/tutorial/default-grafana-dashboards/index.md, pages/services/dcos-monitoring/0.2.1/tutorial/grafana-dashboard-configs/index.md, pages/services/dcos-monitoring/0.2.1/tutorial/grafana-ui/index.md, pages/services/dcos-monitoring/0.2.1/tutorial/index.md, pages/services/dcos-monitoring/0.2.1/tutorial/placement-constraint/index.md, pages/services/dcos-monitoring/0.2.1/uninstall/index.md
Documentation for dcos-monitoring package v0.2.1 release - only change in this patch release is updating the docs to have the correct set of permissions required to run the package
=> dcos-monitoring: Update docs for 0.2.1

pages/1.10/installing/production/deploying-dcos/installation/index.md, pages/1.11/deploying-services/fault-domain-awareness/index.md, pages/1.11/hybrid-cloud/capacity-extension-with-regions/index.md, pages/1.11/installing/production/deploying-dcos/installation/index.md, pages/1.12/deploying-services/fault-domain-awareness/index.md, pages/1.12/hybrid-cloud/capacity-extension-with-regions/index.md, pages/1.12/installing/production/deploying-dcos/installation/index.md, pages/cn/1.11/deploying-services/fault-domain-awareness/index.md, pages/cn/1.11/hybrid-cloud/features/capacity-extension-with-regions/index.md
https://jira.mesosphere.com/browse/COPS-4275
Fault domain output example incorrectly formatted. 1.10-1.12
Additionally fixed code block formatting. 
- [X ] Blocker 
=> COPS-4275 Fix fault_domain output format

pages/services/cassandra/2.4.0-3.0.16/operations/index.md
https://jira.mesosphere.com/browse/DCOS-33518
Add description of how to pass proxy settings to the Cassandra backup plans
Added "-p HTTPS_PROXY=http://internal.proxy:8080" to backup command per JIRA ticket. Added Note: "It may also be necessary to set the AWS_SESSION_ID, depending on how you authenticate with AWS" to S3 backup info.
**QUESTIONS**
1. Does this information need to be added to other methods, such as backing up to Azure?
2. Does this information need to be added to other versions of DC/OS? Which ones?
=> ss/DCOS-33518 Adding HTTPS_PROXY setting to Backup instructions.

pages/1.10/deploying-services/uninstall/index.md, pages/services/edge-lb/1.2/release-notes/index.md
https://jira.mesosphere.com/browse/DCOS-45629
Under “Known Limitation”, I see “The steps provided in the DC/OS web interface to uninstall Edge-LB are incorrect. Follow these steps in the [Edge-LB uninstall documentation](/services/edge-lb/1.2/uninstalling/).”
Do you think you could change it to:
The steps provided in the DC/OS 1.10 web interface to uninstall Edge-LB are incorrect. In order to correctly uninstall Edge-LB for any given DC/OS version, please follow the steps in the Edge-LB uninstall documentation. (the link of course stays :slightly_smiling_face: ). 
The problem is that the warning message is broken only for 1.10. The 1.11+ does not have any message, but still - the uninstall instructions should be followed. As the Edge-LB cannot be simply uninstalled via the UI.
The changes …
=> ss/DCOS-45629 Editing Edge-LB uninstall instructions for DC/OS 1.10.

pages/version-policy/index.md
Adding new OS qualification combinations to the version policy page: CoreOS 1911.4.0 and RHEL 7.6
https://jira.mesosphere.com/browse/DCOS-46246
=> Updating Version Policy Page

pages/1.12/metrics/architecture/index.md, pages/1.12/metrics/datadog/index.md, pages/1.12/metrics/mesos/index.md
https://jira.mesosphere.com/browse/DCOS-42214
Updates the metrics docs with the user-editable telegraf config dir that can now be used to add settings to telegraf.
=> Update metrics docs

pages/1.11/security/ent/perms-management/index.md, pages/1.12/security/ent/perms-management/index.md
https://jira.mesosphere.com/browse/DCOS-46180
Add the typical pattern used to create a permission in the IAM.
This is in response to clarification provided for https://jira.mesosphere.com/browse/COPS-4026
=> Add pattern for setting IAM permissions using the API

pages/services/confluent-kafka/2.4.0-4.1.1/configuration/index.md, pages/services/include/configuration-install-with-options.tmpl
https://jira.mesosphere.com/browse/COPS-3816
> From the adminrouter logs in a bundle I was able to determine that the missing permission they needed was:
> 
> dcos:adminrouter:service:kafka-confluent full
> The purpose of this JIRA is to request that we improve the documentation in this regard, particularly adding some content which describes the permissions which will enable a non-superuser access to the subcommand.
Response:
The permissions are listed in "Integration with DC/OS access controls: 
In Enterprise DC/OS, DC/OS access controls can be used to restrict access to your service. To give a non-superuser complete access to a service, grant them the following list of permissions:
```
dcos:adminrouter:service:marathon full
dcos:service:marathon:marathon:<service-name> full …
```
=> ss/COPS-3816 Edited config permissions file.

pages/1.12/metrics/quickstart/index.md
[DCOS_OSS-4670](https://jira.mesosphere.com/browse/DCOS_OSS-4670) - Statsd-emitter URL is wrong in 1.12 documentation	
=> Revert statsd-emitter URL

pages/version-policy/index.md
https://jira.mesosphere.com/browse/DCOS-47306
=> Removed old CoreOS versions from version policy matrix

pages/services/beta-dcos-monitoring/0.4.0-beta/data.yml, pages/services/beta-dcos-monitoring/0.4.0-beta/data.yml.tmpl, pages/services/beta-dcos-monitoring/0.4.0-beta/getting-started/index.md, pages/services/beta-dcos-monitoring/0.4.0-beta/index.md, pages/services/beta-dcos-monitoring/0.4.0-beta/index.md.tmpl, pages/services/beta-dcos-monitoring/0.4.0-beta/operations/alertmanager/config/index.md, pages/services/beta-dcos-monitoring/0.4.0-beta/operations/alertmanager/index.md, pages/services/beta-dcos-monitoring/0.4.0-beta/operations/alertmanager/ui/index.md, pages/services/beta-dcos-monitoring/0.4.0-beta/operations/grafana/dashboard-configs/index.md, pages/services/beta-dcos-monitoring/0.4.0-beta/operations/grafana/default-dashboards/index.md, pages/services/beta-dcos-monitoring/0.4.0-beta/operations/grafana/index.md, pages/services/beta-dcos-monitoring/0.4.0-beta/operations/grafana/ui/index.md, pages/services/beta-dcos-monitoring/0.4.0-beta/operations/index.md, pages/services/beta-dcos-monitoring/0.4.0-beta/operations/install/index.md, pages/services/beta-dcos-monitoring/0.4.0-beta/operations/placement-constraint/index.md, pages/services/beta-dcos-monitoring/0.4.0-beta/operations/prometheus/alert-rules/index.md, pages/services/beta-dcos-monitoring/0.4.0-beta/operations/prometheus/index.md, pages/services/beta-dcos-monitoring/0.4.0-beta/operations/prometheus/storage/index.md, pages/services/beta-dcos-monitoring/0.4.0-beta/operations/prometheus/ui/index.md, pages/services/beta-dcos-monitoring/0.4.0-beta/operations/uninstall/index.md, pages/services/beta-dcos-monitoring/0.4.0-beta/release-notes/index.md
Docs for dcos-monitoring service v0.4.0-beta release.
=> beta-dcos-monitoring: Update docs for 0.4.0-beta

pages/1.12/installing/production/deploying-dcos/node-cluster-health-check/index.md, pages/1.12/installing/production/patching/index.md, pages/1.12/installing/production/upgrading/index.md
This updates 1.12 docs to reflect that `dcos-diagnostics check` is replaced with `dcos-check-runner-check`. See https://jira.mesosphere.com/browse/DCOS_OSS-3491.
=> Use `dcos-check-runner` for running checks in 1.12

pages/1.10/installing/evaluation/aws/index.md, pages/1.10/installing/evaluation/azure/index.md, pages/1.10/installing/evaluation/gcp/index.md, pages/1.11/installing/evaluation/aws/index.md, pages/1.11/installing/evaluation/azure/index.md, pages/1.11/installing/evaluation/gcp/index.md, pages/1.12/installing/evaluation/aws/index.md, pages/1.12/installing/evaluation/azure/index.md, pages/1.12/installing/evaluation/gcp/index.md
https://jira.mesosphere.com/browse/DCOS-45545
Installer instructions added to the same level of support we provide mac/homebrew. There is a link to the terraform dl page for further dl's and support. 
=> ck/DCOS-45545 Add Windows Instrs to universal installer guides

pages/1.10/installing/evaluation/aws/index.md, pages/1.10/installing/evaluation/azure/index.md, pages/1.10/installing/evaluation/gcp/index.md, pages/1.11/installing/evaluation/aws/index.md, pages/1.11/installing/evaluation/azure/index.md, pages/1.11/installing/evaluation/gcp/index.md, pages/1.12/installing/evaluation/aws/index.md, pages/1.12/installing/evaluation/azure/index.md, pages/1.12/installing/evaluation/gcp/index.md
https://jira.mesosphere.com/browse/DCOS-47317
A diff of the two files reveals the changes requested are:
- change the instance_os to be 'centos_7.5' (default val, but also important for MKE)
- change the instance sizes to be medium (default is xlarge)
Edit: **Note**: this update also includes the updates from #1882 in order to prevent merge conflicts, it should be merged prior to this one.
=> DCOS-47317 Update template for AWS universal installer

pages/1.10/installing/evaluation/aws/index.md, pages/1.11/installing/evaluation/aws/index.md, pages/1.12/installing/evaluation/aws/index.md
https://jira.mesosphere.com/browse/DCOS-47318
Change: Users do not have to be instructed to export a region, they can set it inside the main.tf
Added the explanation to the section that explains key params of the main.tf, and provide a link to the configuration reference
=> DCOS-47318 Move AWS region export step to single param config

pages/1.10/administering-clusters/update-a-node/index.md, pages/1.9/administering-clusters/update-a-node/index.md
https://jira.mesosphere.com/browse/COPS-2138
Please update the documentation https://docs.mesosphere.com/1.9/administering-clusters/update-a-node/ (and any other relevant places in DC/OS docs ) to mention that maintenance endpoints are disabled in strict mode.
- [x Medium
Added warning to relevant docs in 1.9 and 1.10.
=> ss/COPS-2138 Added warning about maintenance endpoints to 1.9 and 1.10

pages/1.10/networking/index.md, pages/1.9/networking/index.md
https://jira.mesosphere.com/browse/DCOS-26386
Documentation page: https://docs.mesosphere.com/1.9/networking/#dns-forwarder-spartan
I cannot understand the following sentence in the DNS Forwarder (Spartan) section:
The Spartan instance on each agent is configured to listen to three different local interfaces on the agent and the nameservers on the agent are set to these three interfaces.
Also, that would be great to list these three interfaces.
UPD: here is the change which I think would make the sentence a bit more useful:
The Spartan instance on each agent is configured to listen to three different local interfaces: 198.51.100.1, 198.51.100.2, and 198.51.100.3. The nameserver option in the /etc/resolv.conf on the agent is set to these three interfaces.
Changed text as required in …
=> ss/DCOS-26386 Added note on local interfaces to networking page.

pages/1.10/installing/evaluation/aws/aws-advanced/index.md, pages/1.10/installing/evaluation/azure/advanced-azure/index.md, pages/1.10/installing/evaluation/gcp/advanced-gcp/index.md, pages/1.11/installing/evaluation/aws/aws-advanced/index.md, pages/1.11/installing/evaluation/azure/advanced-azure/index.md, pages/1.11/installing/evaluation/gcp/advanced-gcp/index.md, pages/1.12/installing/evaluation/aws/aws-advanced/index.md, pages/1.12/installing/evaluation/azure/advanced-azure/index.md, pages/1.12/installing/evaluation/gcp/advanced-gcp/index.md
https://jira.mesosphere.com/browse/DCOS-47499
Adds in supported dc/os versions and node instance versions to config reference pages
- [ X] Medium
=> WIP ck/DCOS-47499 Add tables to config reference

CODEOWNERS
Add the networking team to the CODEOWNERS file to include the team in the review process.
=> Add the networking team to CODEOWNERS

pages/1.13/installing/production/advanced-configuration/configuration-reference/index.md, pages/1.13/metrics/architecture/index.md, pages/1.13/metrics/mesos/index.md
Noticed that 1.13 docs came up on the repo, so went in to make the 1.13 relevant docs updates for mesos metrics (plugin is not enabled by default in 1.12, but is in 1.13)
=> Update mesos metrics docs in 1.13

pages/version-policy/index.md
https://jira.mesosphere.com/browse/DCOS-48368
=> Added OS Qualification for RunC Vulnerability to Version Policy Page.

pages/1.10/administering-clusters/deploying-a-local-dcos-universe/index.md, pages/1.11/administering-clusters/deploying-a-local-dcos-universe/index.md, pages/1.12/administering-clusters/deploying-a-local-dcos-universe/index.md, pages/1.9/administering-clusters/deploying-a-local-dcos-universe/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-3111
> Source: https://docs.mesosphere.com/1.10/administering-clusters/deploying-a-local-dcos-universe
> 
> It doesn't appear that we support creating a local universe on MacOS. Can we note that explicitly on the prerequisites section? Prospect was struggling with doing this and we later determined that we don't actually support this.
Added the following disclaimer to all affected versions in Prerequisites section:
> NOTE: Creation of a local universe on MacOS is not supported.
Versions affected:
- 1.9
- 1.10
- 1.11
- 1.12
Also removed "Preview" tag from 1.9 page.
=> ss/DCOS_OSS-3111 Adding disclaimer to Deploying a Local Universe pages.

pages/services/cassandra/2.0.1-3.0.14/disaster-recovery/index.md, pages/services/cassandra/2.0.2-3.0.14/disaster-recovery/index.md, pages/services/cassandra/2.0.3-3.0.14/disaster-recovery/index.md, pages/services/cassandra/2.1.0-3.0.16/operations/index.md, pages/services/cassandra/2.2.0-3.0.16/operations/index.md, pages/services/cassandra/2.3.0-3.0.16/operations/index.md, pages/services/cassandra/2.4.0-3.0.16/operations/index.md
https://jira.mesosphere.com/browse/DCOS-41471
Backup instructions for AWS S3 backups are missing reference to AWS_SESSION_TOKEN.
Added the following line to list of definitions: 
- `AWS_SESSION_TOKEN`: needed if you’re including temporary security credentials in the file
Added the following line to config file example:
AWS_SESSION_TOKEN=AQoDYXdzEJr...<remainder of security token>
Source: https://aws.amazon.com/blogs/security/a-new-and-standardized-way-to-manage-credentials-in-the-aws-sdks/
Versions changed:
- 2.4.0-3.0.16
- 2.3.0-3.0.16
- 2.2.0-3.0.16
- 2.1.0-3.0.16
- 2.0.3-3.0.14
- 2.0.2-3.0.14
- 2.0.1-3.0.14
=> ss/DCOS-41471 Adding AWS session token info to backup operations doc.

pages/services/spark/2.1.0-2.2.0-1/run-job/index.md, pages/services/spark/2.1.0-2.2.1-1/run-job/index.md, pages/services/spark/2.3.0-2.2.1-2/run-job/index.md, pages/services/spark/2.3.1-2.2.1-2/run-job/index.md, pages/services/spark/2.4.0-2.2.1-3/run-job/index.md, pages/services/spark/2.5.0-2.2.1/run-job/index.md, pages/services/spark/2.6.0-2.3.2/run-job/index.md, pages/services/spark/v1.0.9-2.1.0-1/run-job/index.md, pages/services/spark/v1.1.0-2.1.1/run-job/index.md, pages/services/spark/v1.1.1-2.2.0/run-job/index.md, pages/services/spark/v2.0.0-2.2.0-1/run-job/index.md, pages/services/spark/v2.0.1-2.2.0-1/run-job/index.md
https://jira.mesosphere.com/browse/COPS-3895
Description
https://docs.mesosphere.com/services/spark/2.3.1-2.2.1-2/run-job/#submission
the end of the command is a ' instead of "
Fixed typo in all versions.
=> ss/COPS-3895 Fixed typo in code block in run-job pages for all versions.

scss/base/_content.scss, scss/base/_header.scss, scss/base/_search.scss, scss/base/_typography.scss, scss/components/_actions.scss, scss/components/_grid-toc.scss, scss/components/_grid.scss, scss/components/_localization.scss, scss/components/_sidebar.scss, scss/pages/_landing.scss, scss/shortcodes/_badge.scss, scss/shortcodes/_button.scss, scss/shortcodes/_message.scss, scss/shortcodes/_notes.scss, scss/shortcodes/_switch.scss
https://jira.mesosphere.com/browse/DCOS-48951
Additional branch to handle color updates for visibility/readability
All icons, borders and links now display in darker purple.
Sidebar nav font color changed to bold white on active for easier breadcrumbs
- [ x] Medium
=> CK DCOS-48951 Change to darker color text

pages/services/cassandra/2.3.0-3.0.16/index.md, pages/services/cassandra/2.5.0-3.11.3/release-notes/index.md, pages/version-policy/index.md
Removes Cassandra `2.3.0` package from main menu
- also small markdown fix
=> Remove Cassandra 2.3.0 from main menu

pages/1.12/tutorials/autoscaling/cpu-memory/index.md, pages/1.12/tutorials/autoscaling/microscaling-queue/index.md, pages/1.12/tutorials/create-service/index.md, pages/1.12/tutorials/dcos-101/app1/index.md, pages/1.12/tutorials/dcos-101/app2/index.md, pages/1.12/tutorials/dcos-101/cli/index.md, pages/1.12/tutorials/dcos-101/loadbalancing/index.md, pages/1.12/tutorials/dcos-101/marathon-lb/index.md, pages/1.12/tutorials/dcos-101/redis-package/index.md, pages/1.12/tutorials/dcos-101/resources/index.md, pages/1.12/tutorials/dcos-101/service-discovery/index.md, pages/1.12/tutorials/dcos-debug/gen-strat/index.md, pages/1.12/tutorials/dcos-debug/index.md, pages/1.12/tutorials/dcos-debug/problems/index.md, pages/1.12/tutorials/dcos-debug/scenarios/index.md, pages/1.12/tutorials/dcos-debug/scenarios/scen-1/index.md, pages/1.12/tutorials/dcos-debug/scenarios/scen-2/index.md, pages/1.12/tutorials/dcos-debug/scenarios/scen-3/index.md, pages/1.12/tutorials/dcos-debug/tools/index.md, pages/1.12/tutorials/deploy-on-marathon/index.md, pages/1.12/tutorials/index.md, pages/1.12/tutorials/iot_pipeline/index.md, pages/1.12/tutorials/stateful-services/index.md, pages/1.12/tutorials/task-labels/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4835
Broken links in DC/OS tutorials; images not displaying.
Corrected links to images and URLs in 1.12 tutorials ONLY.
=> ss/DCOS_OSS-4835 Fixed broken links to images and URLs.

pages/1.12/release-notes/1.12.1/index.md, pages/1.12/release-notes/1.12.2/index.md
https://jira.mesosphere.com/browse/COPS-4595
> The 1.12.1 release notes have this entry:
> 
> https://docs.mesosphere.com/1.12/release-notes/1.12.1/#upgrade
> 
> One issue with this note is that it is a bit ambiguous and doesn't make it clear that this note ONLY applies if you are using the beta DSS package.  Perhaps it could be improved to start with something like this?
> 
> "If you have installed the optional DC/OS Storage Service package...  "
> 
> A bigger issue is that the link in this note points to Mesosphere private github page, and thus is not reachable by customers.   It should instead point at this page:
> 
> https://docs.mesosphere.com/services/beta-storage/0.5.1-beta/upgrades
Replaced link with link to /beta-storage/ upgrade docs for 0.5.2 (newest release). Link replacements …
=> ss/COPS-4595 Corrected links to DSS upgrade doc from release notes.

layouts/components/content-sections.pug
https://jira.mesosphere.com/browse/DCOS-49303
Problem addressed: ngindox does not create a heading.id that can be used by the pug layout, created a workaround to take the heading text and put into the proper href form of #lowercase-and-dashes
- [x ] High
=> CK DCOS-49303 Update content-sections logic

pages/1.11/installing/production/upgrading/index.md
https://jira.mesosphere.com/browse/COPS-4239
=> Lg/cops 4239 upgrade Fix 1.10 to 1.11 upgrade table formatting.

pages/1.10/installing/evaluation/gcp/index.md, pages/1.11/installing/evaluation/gcp/index.md, pages/1.12/installing/evaluation/gcp/index.md
This PR is to update the GCP instructions for the new provider that will pin the version of the GCP provider to 1.X along with the version of the Universal Installer to 0.1.X so that they are both compatable. The universal installer currently does support GCP 2.X however this will need to be run with the Universal Installer version of 0.2.0 which will no longer support the GCP labels beta feature as Google has deprecated this but is quite useful from the Universal Installer side.
https://jira.mesosphere.com/browse/COPS-4521
- See the [contribution …
=> Updating GCP Instructions for new Provider Version

pages/1.10/installing/evaluation/azure/index.md, pages/1.11/installing/evaluation/azure/index.md, pages/1.12/installing/evaluation/azure/index.md
https://jira.mesosphere.com/browse/DCOS-49976
This is to help pin the known working version of the Azure Provider backend with the version of the universal installer. This has been tested and confirmed to work against the latest supported version of the Azure provider before the warning message occur.
=> universal installer: pinning azure api version

docker/Dockerfile.docs
https://jira.mesosphere.com/browse/DCOS-50839
Docs site build fail due to deprecated image resources of our node image.
Upgraded to Debian Stretch and now up from Node 8.1.2 to Node 8.15.
Ran test build on docs-christina, server functions as expected, patching staging
- [ x] Blocker 
=> Node Image change from dep'd Jessie to LTS Stretch

pages/services/elastic/2.5.0-6.3.2/configuration/index.md, pages/services/elastic/2.5.0-6.3.2/how-to-guides/index.md, pages/services/elastic/2.5.0-6.3.2/limitations/index.md
This PR is related to [DCOS-47356: Expose Kibana 6.3.2 without Adminrouter](https://jira.mesosphere.com/browse/DCOS-47356).
In addition to doing some general documentation improvements (https://github.com/mesosphere/dcos-docs-site/pull/2054/commits/64e7c7ec929041a5b4215e9dd56cc3dd1d305fba), a new major section named "How-To Guides" was added, with an initial entry for exposing Kibana using EdgeLB ([link](https://github.com/mesosphere/dcos-docs-site/blob/expose-kibana-with-edgelb/pages/services/elastic/2.5.0-6.3.2/how-to-guides/index.md)).
- See the [contribution …
=> DCOS-47356: Expose Kibana 6.3.2 without Adminrouter.

pages/1.11/overview/feature-maturity/index.md, pages/1.12/overview/feature-maturity/index.md, pages/1.13/overview/feature-maturity/index.md
https://jira.mesosphere.com/browse/DCOS-51013
=> 1.11, 1.12, and 1,13 feature maturity page: Fixed incorrect representation of GA to Retired

pages/1.10/installing/production/system-requirements/index.md, pages/1.11/installing/production/system-requirements/index.md, pages/1.12/installing/production/system-requirements/index.md, pages/1.13/installing/production/system-requirements/index.md
As part of https://jira.mesosphere.com/browse/DCOS-49360 we want to emphasise the importance of providing an isolated partition for `/var/lib/dcos/exhibitor/zookeeper/transactions`. This disk location being slow is a major cause of COPS issues.
=> Add ZooKeeper transaction log isolation as system requirement

pages/services/spark/2.3.1-2.2.1-2/quickstart/index.md, pages/services/spark/2.4.0-2.2.1-3/quickstart/index.md, pages/services/spark/2.5.0-2.2.1/quickstart/index.md, pages/services/spark/2.6.0-2.3.2/quickstart/index.md, pages/services/spark/2.7.0-2.4.0/quickstart/index.md
https://jira.mesosphere.com/browse/DCOS-44364
In this tutorial for Spark:
https://docs.mesosphere.com/services/spark/2.3.1-2.2.1-2/quickstart/
At the bottom we state:
To view the logs, the Mesos UI at http://<your-master-ip>/mesos
But that's obsolete. We should give directions of how to get the logs from the DC/OS ui, unless there's something in the mesos logs that are missing (I'm not aware of this). We need to have somebody on the data services team review this and verify that we can and should remove the mesos gui from the tutorials.
We also need to check other tutorials and see if they are referencing the mesos logs.
Corrected link to monitoring in versions 2.3.0 onward. I did not search for other references to Mesos logs; that job is large enough to require another JIRA ticket.
=> ss/DCOS-44364 Editing link to monitoring and logging.

pages/1.10/api/marathon.yaml, pages/1.11/api/marathon.yaml, pages/1.12/api/marathon.yaml, pages/1.13/api/marathon.yaml
https://jira.mesosphere.com/browse/DCOS_OSS-3598
It is suggested that this endpoint can return multiple apps, though it returns only one app for the given ID. The JSON example given is wrong and starts with
```
{
"apps": [
```
But there should be just app, not apps.
Changed in following versions:
=> ss/DCOS_OSS-3598 Changed apps to app in all versions from 1.10 forward.

pages/services/confluent-zookeeper/2.3.0-4.0.0e/getting-started/index.md, pages/services/confluent-zookeeper/2.3.0-4.0.0e/index.md, pages/services/confluent-zookeeper/2.3.0-4.0.0e/release-notes/index.md, pages/services/confluent-zookeeper/2.4.0-4.0.0e/getting-started/index.md, pages/services/confluent-zookeeper/2.4.0-4.0.0e/index.md, pages/services/confluent-zookeeper/2.4.0-4.0.0e/release-notes/index.md, pages/services/confluent-zookeeper/2.5.0-4.1.3e/getting-started/index.md, pages/services/confluent-zookeeper/2.5.0-4.1.3e/index.md, pages/services/confluent-zookeeper/2.5.0-4.1.3e/release-notes/index.md, pages/services/confluent-zookeeper/2.6.0-5.1.2e/getting-started/index.md, pages/services/confluent-zookeeper/2.6.0-5.1.2e/index.md, pages/services/confluent-zookeeper/2.6.0-5.1.2e/release-notes/index.md
1. Confluent ZooKeeper versions not displayed in order on nav menu
2. Release Notes not at top of nav menu
Corrected following versions:
2.3.0-4.0.0e
2.4.0-4.0.0e
2.5.0-4.1.3e
2.6.0-5.1.2e
=> Fix confluent zoo keeper navmenu

pages/1.12/cli/command-reference/dcos-cluster/dcos-cluster-list/index.md
=> Correcting typo on CLI command ref page.

pages/services/beta-storage/0.5.2-beta/install/package-registry-based/index.md
Updated the dcos repository addition command to use the dcos package repo add and removed all the $ which cause a problem when using the copy function.
=> Update command and removed $

pages/cn/services/edge-lb/1.1/pool-configuration/v2-examples/index.md, pages/services/edge-lb/1.0/pool-configuration/v2-examples/index.md, pages/services/edge-lb/1.1/pool-configuration/v2-examples/index.md, pages/services/edge-lb/1.2/pool-configuration/v2-examples/index.md, pages/services/edge-lb/1.3/pool-configuration/v2-examples/index.md
Regular expression used to identify a task name `"^broker-*$"` shown in an example does not reache the original goal to match the task starting with `broker-` and ending with combination of any letters.
=> correct the regular expression of task name pattern

pages/1.10/installing/evaluation/aws/aws-advanced/index.md, pages/1.10/installing/evaluation/aws/index.md, pages/1.10/installing/evaluation/azure/advanced-azure/index.md, pages/1.10/installing/evaluation/gcp/advanced-gcp/index.md, pages/1.11/installing/evaluation/aws/aws-advanced/index.md, pages/1.11/installing/evaluation/aws/index.md, pages/1.11/installing/evaluation/azure/advanced-azure/index.md, pages/1.11/installing/evaluation/gcp/advanced-gcp/index.md, pages/1.12/installing/evaluation/aws/aws-advanced/index.md, pages/1.12/installing/evaluation/aws/index.md, pages/1.12/installing/evaluation/azure/advanced-azure/index.md, pages/1.12/installing/evaluation/dcos-ansible/index.md, pages/1.12/installing/evaluation/gcp/advanced-gcp/index.md, pages/1.13/installing/evaluation/aws/aws-advanced/index.md, pages/1.13/installing/evaluation/aws/index.md, pages/1.13/installing/evaluation/azure/advanced-azure/index.md, pages/1.13/installing/evaluation/azure/index.md, pages/1.13/installing/evaluation/gcp/advanced-gcp/index.md, pages/cn/1.11/installing/evaluation/aws/aws-advanced/index.md, pages/cn/1.11/installing/evaluation/aws/index.md, pages/cn/1.11/installing/evaluation/azure/advanced-azure/index.md, pages/cn/1.11/installing/evaluation/azure/index.md, pages/cn/1.11/installing/evaluation/gcp/advanced-gcp/index.md, pages/services/beta-storage/0.5.2-beta/install/provision-extra-volumes/index.md, pages/services/beta-storage/0.5.3-beta/install/provision-extra-volumes/index.md
Source: https://docs.mesosphere.com/1.12/installing/evaluation/aws
In the section "Creating a DC/OS Cluster" Item 3 has the example main.ft.
The version is inconsistent with the documentation for Azure and GCP.  version = "> 0.1" means from 0.1 to 0.X including all version less than 1.0.  It should read version = "> 0.1.0" which means at least 0.1.0 and up to 0.1.X but less that 0.2.X.  
```
{{module "dcos" { }}
{{source = "dcos-terraform/dcos/aws" }}
version = "~> 0.1"
```
This is causing users to use the 0.1.0 main.tf that is no longer compatible with 0.2.0 module version.
https://jira.mesosphere.com/browse/DCOS_OSS-5038
- Change all affected versions (e.g. 1.7, 1.8, 1.9, …
=> universal installer: pinning the existing version to only 0.1.X

CODEOWNERS
https://jira.mesosphere.com/browse/DCOS-51783
Removing codeowners automatic notifications as it has been found to be confusing and not helping workflow and process.
- [X ] High
=> Revise content codeowners

pages/1.10/installing/evaluation/aws/aws-advanced/index.md, pages/1.10/installing/evaluation/azure/advanced-azure/index.md, pages/1.10/installing/evaluation/gcp/advanced-gcp/index.md, pages/1.11/installing/evaluation/aws/aws-advanced/index.md, pages/1.11/installing/evaluation/azure/advanced-azure/index.md, pages/1.11/installing/evaluation/gcp/advanced-gcp/index.md, pages/1.12/installing/evaluation/aws/aws-advanced/index.md, pages/1.12/installing/evaluation/azure/advanced-azure/index.md, pages/1.12/installing/evaluation/gcp/advanced-gcp/index.md
This updates all the docs to add the dcos_security in the comment section if a user decides to change it.
https://jira.mesosphere.com/browse/DCOS-47945
=> docs: adding dcos_security to advance docs

pages/1.13/deploying-services/containerizers/ucr/index.md
Docker manifest v2 schema2 is supported starting from DC/OS 1.13.0,
while it is still compatible with the manifest v2 schema1.
[DCOS-50641](https://jira.mesosphere.com/browse/DCOS-50641)
[DCOS-50124](https://jira.mesosphere.com/browse/DCOS-50124)
=> Updated UCR doc for the docker manifest v2 schema2 support.

pages/services/spark/2.5.0-2.2.1/index.md, pages/services/spark/2.7.0-2.4.0/index.md, pages/services/spark/2.8.0-2.4.0/custom-docker/index.md, pages/services/spark/2.8.0-2.4.0/fault-tolerance/index.md, pages/services/spark/2.8.0-2.4.0/hdfs/index.md, pages/services/spark/2.8.0-2.4.0/history-server/index.md, pages/services/spark/2.8.0-2.4.0/index.md, pages/services/spark/2.8.0-2.4.0/install/index.md, pages/services/spark/2.8.0-2.4.0/job-scheduling/index.md, pages/services/spark/2.8.0-2.4.0/kerberos/index.md, pages/services/spark/2.8.0-2.4.0/limitations/index.md, pages/services/spark/2.8.0-2.4.0/limits/index.md, pages/services/spark/2.8.0-2.4.0/quickstart/index.md, pages/services/spark/2.8.0-2.4.0/release-notes/index.md, pages/services/spark/2.8.0-2.4.0/run-job/index.md, pages/services/spark/2.8.0-2.4.0/runtime-config-change/index.md, pages/services/spark/2.8.0-2.4.0/security/index.md, pages/services/spark/2.8.0-2.4.0/spark-shell/index.md, pages/services/spark/2.8.0-2.4.0/troubleshooting/index.md, pages/services/spark/2.8.0-2.4.0/uninstall/index.md, pages/services/spark/2.8.0-2.4.0/upgrade/index.md, pages/services/spark/2.8.0-2.4.0/usage-examples/index.md, pages/services/spark/2.8.0-2.4.0/version-policy/index.md
Resolves [DCOS-51582: Release and site docs for Spark 2.4.0 Hadoop 2.9.2 release](https://jira.mesosphere.com/browse/DCOS-51582)
=> Spark 2.8.0-2.4.0 release notes and site docs update

pages/1.12/metrics/index.md, pages/1.13/metrics/index.md
This adds a note about the gather interval for task metrics. This is relevant to users because a task that lives for shorter than the interval may not have its metrics gathered and reported by Telegraf.
https://jira.mesosphere.com/browse/DCOS-49035
=> Add note about application metrics gather interval

pages/1.11/networking/SDN/dcos-overlay/index.md, pages/1.12/networking/SDN/dcos-overlay/index.md
https://jira.mesosphere.com/browse/DCOS-39531
URL: https://docs.mesosphere.com/1.11/networking/SDN/dcos-overlay/
Notes are improperly formatted, either as code or embedded in italics in text. 
Corrections already made to 1.13 by Lisa Gunn. I made the corrections to the 1.11 and 1.12 docs.
=> ss/DCOS-39531 Correcting note formatting in 1.11 and 1.12 docs.

pages/1.13/installing/evaluation/aws/aws-advanced/index.md, pages/1.13/installing/evaluation/aws/aws-remote-region/index.md, pages/1.13/installing/evaluation/aws/aws-replaceable-masters/index.md
This change requires the latest versions of the v0.2 to be available before this PR can be merged. The following changes below were also required to make this work:
* https://github.com/dcos-terraform/terraform-aws-lb/pull/3
* https://github.com/dcos-terraform/terraform-aws-vpc-peering/releases/tag/1.0.1
https://jira.mesosphere.com/browse/DCOS-53149
=> universal installer v0.2: provide working examples for multi-region / replaceable masters

pages/services/marathon-lb/1.12.x/index.md, pages/services/marathon-lb/1.13.x/index.md, pages/services/marathon-lb/1.13.x/mlb-advanced-tutorial/index.md, pages/services/marathon-lb/1.13.x/mlb-basic-tutorial/index.md, pages/services/marathon-lb/1.13.x/mlb-configuration/index.md, pages/services/marathon-lb/1.13.x/mlb-install/index.md, pages/services/marathon-lb/1.13.x/mlb-overview/index.md, pages/services/marathon-lb/1.13.x/mlb-reference/index.md, pages/services/marathon-lb/1.13.x/mlb-scaling-tutorial/index.md, pages/services/marathon-lb/1.13.x/mlb-troubleshooting/index.md, pages/services/marathon-lb/1.13.x/release-notes/index.md
- Copies the 1.12.x structure over to 1.13.x
- Sets 1.13.x as the default
- Adds release notes for 1.13.0
https://jira.mesosphere.com/browse/DCOS_OSS-5111
=> Document Marathon-LB Release 1.13.0

pages/1.13/metrics/index.md
https://jira.mesosphere.com/browse/DCOS-53227
Upgrading directly from 1.11 to 1.13 is supported, so this section is still relevant. This PR updates version numbers accordingly.
=> Update metrics upgrade section for 1.13

pages/1.12/deploying-services/task-handling/index.md, pages/1.13/administering-clusters/delete-node/index.md, pages/1.13/deploying-services/task-handling/index.md
Adjusted docs to explain handling of persistent volumes in the event of TASK_GONE_BY_OPERATOR.
[DCOS-51225](https://jira.mesosphere.com/browse/DCOS-51225)
=> Adjusted docs for TASK_GONE_BY_OPERATOR

pages/1.13/deploying-jobs/quickstart/index.md
https://jira.mesosphere.com/browse/DCOS-51848
=> LG/graphics-only-fix: screen shots missing in staging/production for 1.13

pages/services/beta-dcos-monitoring/0.5.0-beta/configure-dcos-access/index.md, pages/services/beta-dcos-monitoring/0.5.0-beta/data.yml, pages/services/beta-dcos-monitoring/0.5.0-beta/data.yml.tmpl, pages/services/beta-dcos-monitoring/0.5.0-beta/getting-started/index.md, pages/services/beta-dcos-monitoring/0.5.0-beta/index.md, pages/services/beta-dcos-monitoring/0.5.0-beta/index.md.tmpl, pages/services/beta-dcos-monitoring/0.5.0-beta/operations/alertmanager/config/index.md, pages/services/beta-dcos-monitoring/0.5.0-beta/operations/alertmanager/index.md, pages/services/beta-dcos-monitoring/0.5.0-beta/operations/alertmanager/ui/index.md, pages/services/beta-dcos-monitoring/0.5.0-beta/operations/grafana/dashboard-configs/index.md, pages/services/beta-dcos-monitoring/0.5.0-beta/operations/grafana/default-dashboards/index.md, pages/services/beta-dcos-monitoring/0.5.0-beta/operations/grafana/index.md, pages/services/beta-dcos-monitoring/0.5.0-beta/operations/grafana/ui/index.md, pages/services/beta-dcos-monitoring/0.5.0-beta/operations/index.md, pages/services/beta-dcos-monitoring/0.5.0-beta/operations/install/index.md, pages/services/beta-dcos-monitoring/0.5.0-beta/operations/placement-constraint/index.md, pages/services/beta-dcos-monitoring/0.5.0-beta/operations/prometheus/alert-rules/index.md, pages/services/beta-dcos-monitoring/0.5.0-beta/operations/prometheus/index.md, pages/services/beta-dcos-monitoring/0.5.0-beta/operations/prometheus/storage/index.md, pages/services/beta-dcos-monitoring/0.5.0-beta/operations/prometheus/ui/index.md, pages/services/beta-dcos-monitoring/0.5.0-beta/operations/uninstall/index.md, pages/services/beta-dcos-monitoring/0.5.0-beta/release-notes/index.md
This is a beta v0.5.0 release we're doing for dcos-monitoring since we are pushing v1.0 (GA) back to the next RI. These docs have technically already been reviewed in the dcos-monitoring repo. There have also been subsequent docs changes done that will be included in 1.0, so I would prefer not to make too many changes here since it was already done in a later version and beta will soon be removed altogether.
=> beta-dcos-monitoring: Update docs for 0.5.0-beta

pages/version-policy/index.md
Need to update Version Policy page with 1.13 qualification results. Also updated the matrix for Oracle Linux:
Oracle Linux JIRA: https://jira.mesosphere.com/browse/DCOS-53456
=> Updating version policy page with 1.13 & Oracle Linux.

pages/services/beta-storage/0.6.0-beta/release-notes/index.md
https://jira.mesosphere.com/browse/DCOS-53723
This fix has already landed upstream in dcos-storage, both on the releases/v0.6.x branch and master branch. It's also already in this repo on the storage/0_6_1 branch. But we want this fixed for DSS v0.6.0 users, so ... here's the backport.
=> beta-storage/release-notes: backport spelling fix from 0.6.1

pages/1.11/installing/production/system-requirements/index.md, pages/1.12/installing/production/system-requirements/index.md, pages/1.13/installing/production/system-requirements/index.md
This aims to fulfil part of [DCOS_OSS-5127 - "Document that `/var/lib/dcos/exec` is a custom temporary directory and what to do about that"](https://jira.mesosphere.com/browse/DCOS_OSS-5127). Later we can follow-up with documentation about how and when to clean up this directory, when we have more information.
I will create the following once the Security Team is happy with this:
```
```
See [DCOS_OSS-5174](https://jira.mesosphere.com/browse/DCOS_OSS-5174) for the Doc Team to review.
Document that `/var/lib/dcos/exec` is a custom temporary directory and cannot be …
=> [DCOS_OSS-5127] Add note about noexec requirement on 1.13

pages/install-include/all-install-terraform.tmpl
https://jira.mesosphere.com/browse/DCOS-54284
updated the template files for universal installer to point the user to the 0.11 terraform release
=> updating docs as 0.12 will cause issues

pages/1.10/installing/production/advanced-configuration/configuration-reference/index.md, pages/1.11/installing/production/advanced-configuration/configuration-reference/index.md, pages/1.12/installing/production/advanced-configuration/configuration-reference/index.md, pages/1.13/installing/production/advanced-configuration/configuration-reference/index.md
https://jira.mesosphere.com/browse/DCOS-41487
Update to point versions and default values for adminrouter_auth_cache_enabled
=> CK DCOS-41487 Clarify adminrouter_auth_cache_enabled parameter

pages/1.10/monitoring/index.md, pages/1.11/monitoring/index.md, pages/1.12/monitoring/index.md, pages/1.13/monitoring/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-5146
Docs Ticket https://jira.mesosphere.com/browse/DCOS_OSS-5219
=> Document lack of guarantees with respect to the contents of diagnostics bundles

pages/1.10/installing/production/advanced-configuration/configuration-reference/index.md, pages/1.10/installing/production/deploying-dcos/installation/index.md, pages/1.11/installing/production/advanced-configuration/configuration-reference/index.md, pages/1.12/installing/production/advanced-configuration/configuration-reference/index.md, pages/1.13/installing/production/advanced-configuration/configuration-reference/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-4323
fault_domain_enabled is confusing and wrongly showing in 1.10 docs. This PR is to remove from 1.10 and clarify in docs as needed. 
=> CK Remove fault_domain info from 1.10 docs

pages/services/kubernetes/2.0.0-1.12.1/getting-started/install-basic/index.md, pages/services/kubernetes/2.0.1-1.12.2/getting-started/install-basic/index.md, pages/services/kubernetes/2.1.0-1.12.3/getting-started/installing-mke/index.md, pages/services/kubernetes/2.1.1-1.12.5/getting-started/installing-mke/index.md, pages/services/kubernetes/2.2.0-1.13.3/getting-started/installing-mke/index.md, pages/services/kubernetes/2.2.1-1.13.4/getting-started/installing-mke/index.md, pages/services/kubernetes/2.2.2-1.13.5/getting-started/installing-mke/index.md, pages/services/kubernetes/2.3.0-1.14.1/getting-started/installing-mke/index.md, pages/services/kubernetes/2.3.1-1.14.2/getting-started/installing-mke/index.md, pages/services/kubernetes/2.3.2-1.14.1/getting-started/installing-mke/index.md
Update documentation to add missing delete reservation permission for Kubernetes package.
=> kubernetes: Fix missing strict permissions for kubernetes package

pages/1.13/gui/settings/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-5227
Corrected exposed HTML code in https://docs.mesosphere.com/1.13/gui/settings/. Issue does not appear in earlier versions of the page.
=> ss/DCOS_OSS-5227 Correcting HTML exposure in GUI doc.

pages/1.11/installing/production/advanced-configuration/configuration-reference/index.md, pages/1.12/installing/production/advanced-configuration/configuration-reference/index.md, pages/1.13/installing/production/advanced-configuration/configuration-reference/index.md
https://jira.mesosphere.com/browse/DCOS-51026
(figuring out how to create a ticket for docs directly)
Adds documentation for a new flag `dcos_net_cluster_identity`. See more at:
https://mesosphere.slack.com/archives/G771N1T46/p1553794752020600
=> Add docs for `dcos_net_cluster_identity` on 1.11, 1.12 and 1.13

pages/services/confluent-kafka/2.3.0-4.0.0e/index.md, pages/services/confluent-kafka/2.4.0-4.1.1/index.md, pages/services/confluent-zookeeper/2.3.0-4.0.0e/index.md, pages/services/confluent-zookeeper/2.4.0-4.0.0e/index.md, pages/services/elastic/2.4.0-5.6.9/index.md, pages/services/kafka/2.3.0-1.0.0/index.md, pages/services/kafka/2.3.0-1.1.0/index.md, pages/version-policy/index.md
https://jira.mesosphere.com/browse/DCOS-51550
Updates to version support page https://docs.mesosphere.com/version-policy/. I checked the listed version on the service docs page against the listed supported versions on the version-policy page.
- Chronos: listed in UI Catalog, not mentioned in version support page and not on Service docs page.
- Confluent-Kafka: hid versions 2.3.0 and 2.4.0 on Services page, as they are not listed as supported verisons.
- Confluent-ZooKeeper: hid versions 2.3.0e and 2.4.0e on Services page, as they are not listed as supported versions.
- Couchbase: added v. 0.2.0 and 0.3.0 to Versions page because they are listed on Service docs page.
- Elastic: hid version 2.4.0 because it is not listed as supported
- DataStax-Ops: hid entry on versions page because there …
=> ss/DCOS-51550 Updates to version-policy support page.

pages/services/spark/2.7.0-2.4.0/index.md
https://jira.mesosphere.com/browse/DCOS-51550
Hiding obsolete service docs.
See https://docs.google.com/spreadsheets/d/1r4CrlTGKnmBp2frkQanhdVRWj6YHIT8nH0wUXR9fDCw/edit#gid=0
=> Hide Spark 2.7.0 docs

pages/1.13/storage/external-storage/index.md
https://jira.mesosphere.com/browse/COPS-5003
The bash markup describing how to set up a system for use with NVMe volumes is in the wrong places so the instructions don't make sense.  Also, a 1.12.x restriction needed to be removed as we updated the RexRay component in 1.13 to a newer one.
=> Fix NVMe scripts

pages/version-policy/index.md
https://jira.mesosphere.com/browse/DCOS-53456
Currently the Docker version that Oracle Linux is supported on is listed as `RH Fork of Docker CE 1.13.1*`. I want to remove this Docker version and add Docker EE 18.09.2 in its place.
Please refer to the Internal Version Policy Matrix document here. The highlighted yellow matrix cells are the ones that should be updated:
https://docs.google.com/document/d/10lTEBRA6opbAmaNrJYF45pz8PW0SR2yXroyn4P1Ja-4/edit
=> ss/DCOS-53456 Updating Ocracle Linux support matrix.

pages/1.13/cli/index.md
https://jira.mesosphere.com/browse/COPS-4062
"...with 1.12, and with earlier versions, we do not formally support the CLI working with different versions. So a 1.10 CLI might work with 1.12, or might not, but if there's a problem we don't support it."
We need this documented in the CLI pages, along with documentation of how to make multiple CLI installs work, and we need to state that work is underway to address this."
Added a link and text to CLI support matrix on version support page.
Moved discussion of incompatibility of DC/OS versions with some CLI versions from middle of page to top.
Replaced hard /1.13/ links with variable for {{ model.version }} and tested.
=> COPS-4062 Adding link to CLI support matrix

pages/1.14/data.yml
https://jira.mesosphere.com/browse/DCOS-55734
This change affects all of 1.14. I changed the value of "version" from 1.13 to 1.14 so that all variables linked to that file which call on "version" will be correct. Note that I did NOT change the value of "folder_version", which refers to the install guide. I will leave that to the writer in charge of install docs.
=> Update yaml file to version 1.14.

pages/1.14/cli/command-reference/dcos-task/dcos-task-download/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-5315
We added a new command (`dcos task download`) to the CLI. This adds the respective docs page.
=> Add `dcos task download` to cmd reference

pages/1.13/monitoring/logging/aggregating/elk/index.md, pages/1.13/monitoring/logging/aggregating/splunk/index.md
https://jira.mesosphere.com/browse/DCOS-55170
This updates our log aggregation tutorials to use the Fluent Bit that is built into DC/OS 1.13.
=> Use Fluent Bit in log aggregation tutorials

pages/services/storage/1.0.0/troubleshooting/index.md, pages/services/storage/1.0.0/tutorials/cassandra-dss-volumes/index.md
https://jira.mesosphere.com/browse/DCOS-56418
The cassandra package has been promoted to GA. This updates the dcos-storage documentation to use the GA'd version and its accompanied configuration change where `disk_profile` got renamed to `volume_profile` when it switched from beta- to GA.
=> pages/services/storage/1.0.0: rename beta-cassandra -> cassandra

pages/1.11/cli/install/index.md, pages/1.12/cli/install/index.md, pages/1.13/cli/install/index.md, pages/1.14/cli/install/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-5364
Added step for DC/OS CLI installation on Fedora 30. Some whitespaces have also been removed by my text editor.
=> Added workaround to use the DC/OS CLI on Fedora >= 30.

pages/services/data-science-engine/1.0.0/hdfs/index.md, pages/services/data-science-engine/1.0.0/tensorflow/index.md
[DCOS-57165: Add documentation for TensorBoard](https://jira.mesosphere.com/browse/DCOS-57165)
Adds a section on TensorBoard to the HDFS page
=> [DCOS-57165] Add documentation for TensorBoard

pages/services/data-science-engine/1.0.0/quick-start/index.md, pages/services/data-science-engine/1.0.0/security/index.md, pages/services/data-science-engine/1.0.0/tensorflow/index.md, pages/services/include/service-account.tmpl
[DCOS-57317 - Test Data Science Engine documentation](https://jira.mesosphere.com/browse/DCOS-57317)
- [Quick Start] Removed outdated instructions to set public agent host name
Doesn't seem to be necessary after migration from marathon-lb to Admin Router
- [Quick Start] Clarified default password to Jupyter UI
- [Quick Start] Removed 'To view job details ...' line 
It looks to be a carry-over bit from Spark documentation, but here the mention of submission id is confusing
- [TensorFlow] Fixed missing service name in a URL
- [Security] Fixed a service name place holder in the Service Account Template
- [Security] Removed indentation from "Create and assign permissions" command listing, that caused markdown characters to be shown on the page
=> [DCOS-57317] Changes for some minor issues and inconsistencies

docker/nginx/default.conf
Purpose of this change is to take out caching of the docs site as much as possible.
I could even set the expiration to 0
The regex for the file names/types may need to be adjusted, see what you think, it's borrowed
=> Add cache-control to header

pages/mesosphere/dcos/services/data-science-engine/1.0.0/security/index.md
This PR adds details for service accounts setup page as per [COPS-5233: Only 1 service account should be created for DSE, current docs are unclear](https://jira.mesosphere.com/browse/COPS-5233)
- added a note that only a single service account should be used(no need for a new account for Spark)
- added a note about `app_id` permission setting
- added a configuration snippet for mapping of service account to Spark principals
=> Added details for DSEngine service accounts setup and configuration

pages/mesosphere/dcos/1.14/cli/command-reference/dcos-diagnostics/dcos-diagnostics-create/index.md, pages/mesosphere/dcos/1.14/cli/command-reference/dcos-diagnostics/dcos-diagnostics-delete/index.md, pages/mesosphere/dcos/1.14/cli/command-reference/dcos-diagnostics/dcos-diagnostics-download/index.md, pages/mesosphere/dcos/1.14/cli/command-reference/dcos-diagnostics/dcos-diagnostics-list/index.md, pages/mesosphere/dcos/1.14/cli/command-reference/dcos-diagnostics/index.md, pages/mesosphere/dcos/1.14/cli/command-reference/dcos-node/dcos-node-diagnostics-create/index.md, pages/mesosphere/dcos/1.14/cli/command-reference/dcos-node/dcos-node-diagnostics-delete/index.md, pages/mesosphere/dcos/1.14/cli/command-reference/dcos-node/dcos-node-diagnostics-download/index.md, pages/mesosphere/dcos/1.14/cli/command-reference/dcos-node/dcos-node-diagnostics/index.md, pages/mesosphere/dcos/1.14/cli/command-reference/dcos-task/index.md
https://jira.mesosphere.com/browse/DCOS_OSS-5446
https://jira.mesosphere.com/browse/DCOS_OSS-5437
* Add deprecation notice for diagnostics to docs site
* Create documentation for new diagnostics subcommand
=> add 'dcos diagnostics' documentation; deprecate 'dcos node diagnostics ...'

pages/mesosphere/dcos/1.13/release-notes/1.13.4/index.md
It has come to our attention that this fix indicated is not actually a fix but a feature addition that is coming out with 1.13.5. This PR removes the line from the 1.13.4 release notes. 
=> Remove point about encrypted volumes

pages/mesosphere/dcos/services/cassandra/2.7.0-3.11.4/limitations/index.md
Resolves [DCOS-60485](https://jira.mesosphere.com/browse/DCOS-60485)
This PR remove info from limitation page of latest Cassandra which stat that `Cassandra does not support  backup and restore with authN/Z` but does supports it.
=> [DCOS-60485] Update docs for cassandra 2.7.0-3.11.4

docker/nginx/redirects-307.map, pages/mesosphere/dcos/services/jenkins/3.6.0-2.190.1/architecture/index.md, pages/mesosphere/dcos/services/jenkins/3.6.0-2.190.1/quickstart/index.md, pages/mesosphere/dcos/services/jenkins/3.6.0-2.190.1/release-notes/index.md, pages/mesosphere/dcos/services/jenkins/3.6.0-2.190.1/upgrade/index.md
Fix broken links on service page.
Point `latest` to `3.6.0-2.190.1`
JIRA [DCOS-60471](https://jira.mesosphere.com/browse/DCOS-60471)
Fix broken links.
=> DCOS-60471: Fix broken links for 3.6.0-2.190.1

docker/nginx/redirects-307.map
Parent JIRA ticket : [here](https://jira.mesosphere.com/browse/DCOS-58684)
Updated the redirect-309 map to point `hive-metastore`'s latest version i.e. `1.0.0-3.0.0` over the live [URL](https://docs.d2iq.com/mesosphere/dcos/services/hive-metastore/latest/)
=> [DCOS-58684] Fix broken links for hive metastore v1.0.0-3.0.0

pages/ksphere/konvoy/partner-solutions/aqua/index.md, pages/ksphere/konvoy/partner-solutions/lightbend/index.md
https://jira.mesosphere.com/browse/DCOS-61027
Moving section on that Konvoy cluster has to be created with AlwaysPullImages removed from cluster yaml.
=> moving section on konvoy cluster creation

pages/mesosphere/dcos/services/include/security-create-permissions.tmpl, pages/mesosphere/dcos/services/include/service-account.tmpl
https://jira.mesosphere.com/browse/DCOS-60933
This is an effort to simplify/clean-up docs for service account provisioning by using DC/OS CLI commands instead of curl based commands. Since I changed a template file used in multiple services I need to verify ACLs are accurate by deploying those services. So please do not merge this until all the services listed below are checked
- [] confluent zookeeper
I still want to get some feedback on the changes I have made,irrespective of the testing I'm going to do for ACL accuracy
=> Simplify service account provisioning commands using DC/OS CLI

pages/mesosphere/dcos/services/elastic/2.7.0-6.8.1/how-to-guides/index.md
The HTTP Path Rewrite should get removed within the Edge-LB Pool, since the behavior of internal Kibana proxy changed in version 2.7.0-6.8.1.
=> Removes HTTP Path Rewrite within the Edge-LB Pool

pages/mesosphere/dcos/1.11/installing/production/virt-infra/index.md, pages/mesosphere/dcos/1.12/installing/production/virt-infra/index.md, pages/mesosphere/dcos/1.13/installing/production/virt-infra/index.md, pages/mesosphere/dcos/2.0/installing/production/virt-infra/index.md, pages/mesosphere/dcos/2.1/installing/production/virt-infra/index.md
https://jira.mesosphere.com/browse/COPS-5416
- Adding missing virt-infra page to DC/OS 1.13 and above.
- Fixing incorrect NTP link in the virt-infra page
=> Adding missing virt-infra page to DC/OS 1.13 and above (COPS-5416)

pages/mesosphere/dcos/services/cassandra/2.7.0-3.11.4/security/index.md, pages/mesosphere/dcos/services/confluent-kafka/2.8.0-5.3.1/security/index.md, pages/mesosphere/dcos/services/confluent-zookeeper/2.7.0-5.1.2e/security/index.md, pages/mesosphere/dcos/services/hive-metastore/1.0.0-3.0.0/security/index.md, pages/mesosphere/dcos/services/include/security-create-permissions.tmpl, pages/mesosphere/dcos/services/kafka-zookeeper/2.7.0-3.4.14/security/index.md, pages/mesosphere/dcos/services/kafka/2.8.0-2.3.0/security/index.md, pages/mesosphere/dcos/services/nifi/1.0.0-1.9.2/security/index.md
https://jira.mesosphere.com/browse/DCOS-61934
Mofified the service role table for package versions that are quota aware to have a column that shows the role that will be used if installing the service in `enforceRole=true` group.
=> Add service role examples for enforceRole=true and quota aware versions of packages

pages/mesosphere/dcos/1.10/installing/production/system-requirements/ports/index.md, pages/mesosphere/dcos/1.11/installing/production/advanced-configuration/configuration-reference/index.md, pages/mesosphere/dcos/1.11/installing/production/system-requirements/ports/index.md, pages/mesosphere/dcos/1.12/installing/production/advanced-configuration/configuration-reference/index.md, pages/mesosphere/dcos/1.12/installing/production/system-requirements/ports/index.md, pages/mesosphere/dcos/1.13/installing/production/advanced-configuration/configuration-reference/index.md, pages/mesosphere/dcos/1.13/installing/production/system-requirements/ports/index.md, pages/mesosphere/dcos/2.0/installing/production/advanced-configuration/configuration-reference/index.md, pages/mesosphere/dcos/2.0/installing/production/system-requirements/ports/index.md, pages/mesosphere/dcos/2.1/installing/production/advanced-configuration/configuration-reference/index.md, pages/mesosphere/dcos/2.1/installing/production/system-requirements/ports/index.md
In https://docs.mesosphere.com/1.12/installing/production/system-requirements/ports/#tcp-2 updated port 3888 with to master and added port 2888 with the same values as the modified 3888 port for versions 1.10,1.11,1.12,1.13,2.0 and 2.1
=> [DCOS-47688] Added ports 2888 and updated 3888 to master

pages/mesosphere/dcos/1.11/installing/production/advanced-configuration/configuration-reference/index.md, pages/mesosphere/dcos/1.12/installing/production/advanced-configuration/configuration-reference/index.md, pages/mesosphere/dcos/1.13/installing/production/advanced-configuration/configuration-reference/index.md, pages/mesosphere/dcos/2.0/installing/production/advanced-configuration/configuration-reference/index.md, pages/mesosphere/dcos/2.1/installing/production/advanced-configuration/configuration-reference/index.md
…ll versions of dcos documentation
Updating documentation for flag "feature_dcos_storage_enabled" with default value to true in all the versions wherever its applicable.
feature_dcos_storage_enabled default should be described as "true"
=> [DCOS-45892] updated flag feature_dcos_storage_enabled to have default described as "true"

pages/mesosphere/dcos/1.10/cli/command-reference/dcos-node/dcos-node-diagnostics-create/index.md, pages/mesosphere/dcos/1.11/cli/command-reference/dcos-node/dcos-node-diagnostics-create/index.md, pages/mesosphere/dcos/1.12/cli/command-reference/dcos-node/dcos-node-diagnostics-create/index.md, pages/mesosphere/dcos/1.13/cli/command-reference/dcos-node/dcos-node-diagnostics-create/index.md, pages/mesosphere/dcos/2.0/cli/command-reference/dcos-node/dcos-node-diagnostics-create/index.md, pages/mesosphere/dcos/2.1/cli/command-reference/dcos-node/dcos-node-diagnostics-create/index.md
https://jira.mesosphere.com/browse/COPS-5280
* Removing incorrect note about using quotes with the DC/OS diagnostics CLI.
* Adding backticks to the 1.10 and 1.11 version so they match the current docs.
=> Removing incorrect note about using quotes with the DC/OS diagnostics CLI - COPS-5280

pages/mesosphere/dcos/1.12/deploying-services/private-docker-registry/index.md, pages/mesosphere/dcos/1.13/deploying-services/private-docker-registry/index.md, pages/mesosphere/dcos/2.0/deploying-services/private-docker-registry/index.md, pages/mesosphere/dcos/2.1/deploying-services/private-docker-registry/index.md, pages/mesosphere/dcos/cn/1.12/deploying-services/private-docker-registry/index.md, pages/mesosphere/dcos/cn/1.13/deploying-services/private-docker-registry/index.md, pages/mesosphere/dcos/cn/2.0/deploying-services/private-docker-registry/index.md
https://jira.mesosphere.com/browse/DCOS-62543
Code sample in /deploying-services/private-docker-registry/ section is missing triple back ticks at end of sample
=> ss/DCOS-62543 Correcting missing back ticks in code sample.

pages/ksphere/dispatch/latest/starlark-reference/index.md
Nav headers have "Starklark" rather than Starlark.
=> Correct typo - Starklark -> Starlark

pages/mesosphere/dcos/1.13/administering-clusters/package-registry/index.md, pages/mesosphere/dcos/2.0/administering-clusters/package-registry/index.md, pages/mesosphere/dcos/2.1/administering-clusters/package-registry/index.md
A missing `</tt>` was changing the look of the end of the page as well as the links on the right.
=> Adding a missing closing tag (</tt>)

docker/nginx/redirects-307.map
https://jira.mesosphere.com/browse/DCOS-62747
Does not have it's own doc ticket as too small to need one. 
changing redirects. 
=> redirecting services/kubernetes to version 2.4.6-1.15.6

pages/ksphere/kommander/latest/centralized-monitoring/index.md
https://jira.d2iq.com/browse/D2IQ-63676
Add note that makes it clear that metrics are not backed up on clusters, and that if a cluster goes down, the kommander cluster will no longer present its metrics, current or past metrics.
=> Add note in kommander centralized monitoring docs

pages/ksphere/kommander/latest/tutorials/using-istio/index.md
Empty page in the tutorial section for a feature 'Coming Soon' is misleading. I recommend deleting it and adding an actual tutorial when we have something worked out.
Note: I'm creating a PR off @ck4adventure's branch that includes a number of kommander doc fixes.
=> [kommander] Delete istio 'coming soon' page

pages/ksphere/kommander/latest/clusters/attach-cluster/index.md
https://jira.d2iq.com/browse/D2IQ-64528
This PR adds documentation for the user on how to deploy a custom Certificate Authority to a Kubernetes cluster attached to Kommander. This procedure is a prerequisite at the time of writing to enable centralized API access to said cluster via Kommander.
=> SSO for Kubernetes API of attached non-Konvoy clusters

pages/ksphere/kommander/latest/licensing/index.md
Closes D2IQ-64510
https://jira.d2iq.com/browse/D2IQ-64510
Adds details for accessing Kommander license from support downloads
=> feat(Licensing): how to get a kommander license

pages/mesosphere/dcos/1.10/cli/command-reference/dcos-marathon/dcos-marathon-app-add/index.md, pages/mesosphere/dcos/1.11/cli/command-reference/dcos-marathon/dcos-marathon-app-add/index.md, pages/mesosphere/dcos/1.12/cli/command-reference/dcos-marathon/dcos-marathon-app-add/index.md, pages/mesosphere/dcos/1.13/cli/command-reference/dcos-marathon/dcos-marathon-app-add/index.md, pages/mesosphere/dcos/2.0/cli/command-reference/dcos-marathon/dcos-marathon-app-add/index.md, pages/mesosphere/dcos/2.1/cli/command-reference/dcos-marathon/dcos-marathon-app-add/index.md
This commit removes the extra comma that resulted in invalid JSON and a parse error when attempting to use the example verbatim.
It also applies the correct language syntax tag and tidies the formatting slightly.
=> Fix erroenous comma in dcos marathon app add CLI example

pages/ksphere/kommander/latest/operations/cloud-providers/index.md
Resolves [D2IQ-64511](https://jira.d2iq.com/browse/D2IQ-64511)
This commit fixes the cloud providers image (public site shows [empty image](https://docs.d2iq.com/ksphere/kommander/latest/operations/cloud-providers/)) and deletes the figure number
=> docs(kommander): fix cloud providers image

pages/ksphere/kommander/latest/clusters/attach-cluster/index.md
https://jira.d2iq.com/browse/D2IQ-65044
Adds docs to attaching clusters section relating to isolating permissions to a new kommander service account
=> feat(kommander): attach cluster using isolated service account

pages/ksphere/kommander/latest/operations/identity-providers/index.md, pages/ksphere/kommander/latest/security/distributed-authnz/index.md, pages/ksphere/kommander/latest/security/index.md, pages/ksphere/konvoy/latest/install/install-airgapped/index.md, pages/ksphere/konvoy/latest/install/install-onprem/index.md, pages/ksphere/konvoy/latest/operations/accessing-the-cluster/index.md, pages/ksphere/konvoy/latest/quick-start/index.md
https://jira.d2iq.com/browse/D2IQ-63368
Source COPS: https://jira.d2iq.com/browse/COPS-5800
Adds new page that describes distributed authentication and authorization architecture of Kommander.
As I am not a native speaker please review also grammar and style.
=> docs(kommander): Add distributed authnz pages

docker/nginx/redirects-307.map, pages/mesosphere/dcos/services/hive-metastore/1.2.0-3.0.0/advanced/index.md, pages/mesosphere/dcos/services/hive-metastore/1.2.0-3.0.0/cli/index.md, pages/mesosphere/dcos/services/hive-metastore/1.2.0-3.0.0/configuration/index.md, pages/mesosphere/dcos/services/hive-metastore/1.2.0-3.0.0/getting-started/index.md, pages/mesosphere/dcos/services/hive-metastore/1.2.0-3.0.0/index.md, pages/mesosphere/dcos/services/hive-metastore/1.2.0-3.0.0/limitations/index.md, pages/mesosphere/dcos/services/hive-metastore/1.2.0-3.0.0/operations/index.md, pages/mesosphere/dcos/services/hive-metastore/1.2.0-3.0.0/release-notes/index.md, pages/mesosphere/dcos/services/hive-metastore/1.2.0-3.0.0/security/index.md, pages/mesosphere/dcos/services/hive-metastore/1.2.0-3.0.0/support-policy/index.md, pages/mesosphere/dcos/services/hive-metastore/1.2.0-3.0.0/supported-databases/index.md, pages/mesosphere/dcos/services/hive-metastore/1.2.0-3.0.0/troubleshooting/index.md, pages/mesosphere/dcos/services/hive-metastore/1.2.0-3.0.0/uninstall/index.md, pages/mesosphere/dcos/services/hive-metastore/1.2.0-3.0.0/updates/index.md
https://jira.d2iq.com/browse/D2IQ-65568
Changes done regarding https://jira.d2iq.com/browse/D2IQ-63349
The changes are regarding new Hive-Metastore 1.2.0-3.0.0 release.
- Upgraded SDK library to version 0.57.3.
=> [D2IQ-63349] Upgrade Hive-Metastore sdk to 0.57.3

pages/mesosphere/dcos/2.1/installing/production/upgrading/index.md
* [D2IQ-65610](https://jira.d2iq.com/browse/D2IQ-65610)
The current upgrade process can lead to crash loops in Marathon. Eg when
an older version of Mesos but a newer version of Marathon are leaders.
=> [D2IQ-65610] Describe new upgrade procedure for master nodes.

CODEOWNERS
This sets @dkoshkin and me as codeowners so that we're made aware of docs changes in docs-site.
The process for updating docs is to update them directly in the Konvoy repo and only use automation to update docs here in this repo. So basically, contributors _should not_ be making Konvoy docs changes in this repo.
=> Update CODEOWNERS for konvoy docs

docker/nginx/redirects-307.map, pages/mesosphere/dcos/services/confluent-kafka/2.9.0-5.4.0/advanced/index.md, pages/mesosphere/dcos/services/confluent-kafka/2.9.0-5.4.0/api-reference/index.md, pages/mesosphere/dcos/services/confluent-kafka/2.9.0-5.4.0/configuration/index.md, pages/mesosphere/dcos/services/confluent-kafka/2.9.0-5.4.0/getting-started/index.md, pages/mesosphere/dcos/services/confluent-kafka/2.9.0-5.4.0/index.md, pages/mesosphere/dcos/services/confluent-kafka/2.9.0-5.4.0/limitations/index.md, pages/mesosphere/dcos/services/confluent-kafka/2.9.0-5.4.0/operations/index.md, pages/mesosphere/dcos/services/confluent-kafka/2.9.0-5.4.0/release-notes/index.md, pages/mesosphere/dcos/services/confluent-kafka/2.9.0-5.4.0/security/index.md, pages/mesosphere/dcos/services/confluent-kafka/2.9.0-5.4.0/support-policy/index.md, pages/mesosphere/dcos/services/confluent-kafka/2.9.0-5.4.0/troubleshooting/index.md, pages/mesosphere/dcos/services/confluent-kafka/2.9.0-5.4.0/uninstall/index.md, pages/mesosphere/dcos/services/confluent-kafka/2.9.0-5.4.0/updates/index.md, pages/mesosphere/dcos/version-policy/index.md
Updated PR to cover #2780 for a clean rebase and merge. 
Keeping the 2.8 folder because it creates a weird gap of available docs versions but can also delete if it needs to be taken down for whatever reason.
This PR has 15 files instead of 16, a changed file in 2780 was a line space addition to an outside file and the change not kept.
=> [D2IQ-64606] Add release docs for confluent-kafka 2.9.0-5.4.0

pages/mesosphere/dcos/2.0/installing/production/upgrading/index.md
https://jira.d2iq.com/browse/COPS-5899
Bad 1.12 references in the 2.0 Upgrading Instructions
=> Fixed 1.12 references on 2.0 Upgrading page

layouts/components/content-actions.pug
This is a workaround fix for the feedback button not properly setting the Doc team when linking out to Jira. 
There's a bug in the redirect server that duplicates and appends the entire query to the URL string so instead of setting `team=44`, JIRA bugs out and doesn't know to set `team=44?pid=10415&blahblah` (@jaxesn has more info) but this change should solve the immediate problem until we sort out the redirect issue.
=> fix: feedback button query

js/search.js
Fix the path for the search landing so that it redirects to the actual page instead of a 404.
The issue is without the forward slash the URL was a relative path and you'd end up with something like `/dcos/pages/docs/` instead of `/pages/dcos/`
=> fix: search landing path

config.json
Optimize the `dispatch` branch build so that our dispatch CI builds do not have to build all of the DC/OS documentation.
=> Ignore more DC/OS documentation for the dispatch branch build

package.json, plugins/metalsmith-algolia.js
- konvoy versions are not properly indexed with the right versions/weights
- kommander and dispatch should be ready to handle versions
- documents are not limited to the 500 characters when indexing
- beta versions are given a lower weight than stable versions in the index
- konvoy partner docs are given a specific version
=> chore: update indexing

pages/mesosphere/dcos/install-include/aws-cluster-setup.tmpl
https://jira.d2iq.com/browse/COPS-6100
Updating the AWS instance types used in the example as they are too small for DC/OS. Also adding a note that the user must use instance types that meet DC/OS' system requirements.
=> COPS-6100: Terraform Universal Installer documentation needs to be updated regarding minimum requirements for main.tf

config.json, docker/nginx/redirects-307.map, pages/mesosphere/dcos/1.12/index.md, pages/mesosphere/dcos/1.13/index.md, pages/mesosphere/dcos/2.0/index.md, pages/mesosphere/dcos/2.0/release-notes/index.md, pages/mesosphere/dcos/2.1/index.md, pages/mesosphere/dcos/2.1/release-notes/2.1.0/index.md, pages/mesosphere/dcos/2.1/release-notes/index.md
DC/OS 2.1 is currently blocked from building on staging/master. This allows local preview work. Once the 2.1 content is in and approved, simply merge this PR into staging and promote. The block is released by deleting the lines. The build will pick up the change and add 2.1 in.
=> Publish DCOS 2.1 

docker/nginx/redirects-307.map
These were incorrectly removed in https://github.com/mesosphere/dcos-docs-site/pull/2828/files#diff-ffadabb9049686535404014ce18e6a3bL1-L4 and broke the `/latest` redirects.
Bringing it back.
=> ksphere: bring back redirects from latest/

pages/ksphere/kommander/1.0/install/index.md, pages/ksphere/kommander/1.1.0-beta/install/index.md
N/A - quick update for docs where a button was removed.
Button no longer in the header in the UI. Just making sure that this is in the docs. Updating where it is.
=> UI change where Try Kommander button moved Apps dropdown now in nav

entry.js, index.js, plugins/metalsmith-revision.js, webpack.config.js
1. the numbers and depicted speeds you can see in the screencasts below changed because #2873 merged.
2. you'll only want to review the last commit (`chore: fix the revision-plugin`) here. the other commits came here due to rebasing and are already approved/merged.
----------------------
to speed up builds, we now make use of the revision-plugin and
assume that all files that need processing are changed after the
markdown-step. the revision-plugin will then generate a hash out of the
current state of that file and not apply further transformers in case
the hash is the same as in the previous run.
note that the official revision plugin would introduce caching issues as it does not care about changes in frontmatter.
here are two (almost) identical cycles of starting the server, making a …
=> chore: fix the revision-plugin

docker/nginx/redirects-307.map
Update latest kubernetes redirect to 2.5.0-1.16.9
=> chore: Update latest kubernetes redirect to 2.5.0-1.16.9

scss/base/_global.scss
TL;DR: We have a horizontal scrollbar on most pages. This PR removes those.
there seems to be no need to set the width of a block element to the
full viewport width. even more so as the drawback is that every device
that's not in "touch mode" (try not using your macs trackpad but an
external mouse) will have a horizontal scrollbar because 100vw does not
account for the vertical scrollbar.
=> Remove horizontal scrollbar

pages/ksphere/kommander/1.0/clusters/creating-konvoy-cluster-azure/index.md, pages/ksphere/kommander/1.1.0-beta/clusters/creating-konvoy-cluster-azure/index.md, pages/ksphere/konvoy/1.4/install/install-airgapped/index.md, pages/ksphere/konvoy/1.4/install/install-dev/index.md, pages/ksphere/konvoy/1.4/install/install-onprem/index.md, pages/ksphere/konvoy/1.4/install/ssh-configuration/index.md, pages/ksphere/konvoy/1.4/quick-start/index.md, pages/ksphere/konvoy/1.4/reference/cluster-configuration/index.md, pages/ksphere/konvoy/1.4/storage/index.md, pages/ksphere/konvoy/1.4/tutorials/deploy-sample-app/index.md, pages/ksphere/konvoy/1.5.0-beta/install/install-airgapped/index.md, pages/ksphere/konvoy/1.5.0-beta/install/install-dev/index.md, pages/ksphere/konvoy/1.5.0-beta/install/install-onprem/index.md, pages/ksphere/konvoy/1.5.0-beta/install/ssh-configuration/index.md, pages/ksphere/konvoy/1.5.0-beta/quick-start/index.md, pages/ksphere/konvoy/1.5.0-beta/storage/index.md, pages/ksphere/konvoy/1.5.0-beta/tutorials/deploy-sample-app/index.md
https://jira.d2iq.com/browse/COPS-6126
A number of reference links are broken. Adding the missing references to fix that. This change can be merged any time.
=> COPS-6126: Fixing invalid reference links in ksphere docs

pages/mesosphere/dcos/1.12/installing/production/deploying-dcos/opt-out/index.md, pages/mesosphere/dcos/1.13/installing/production/deploying-dcos/opt-out/index.md, pages/mesosphere/dcos/2.0/installing/production/deploying-dcos/opt-out/index.md, pages/mesosphere/dcos/2.1/installing/production/deploying-dcos/opt-out/index.md
https://jira.d2iq.com/browse/COPS-6134
Removing an invalid reference link. There no longer is a need to use an "advanced" installation method the link is referring to in the currently supported releases of DC/OS. This change can be merged at any time.
=> Removing invalid reference link

config.json
the layouts are written in a way that requires the latest version of any
given doc to be present during build time. the DO_NOT_BUILD sections
exclude dcos 2.0 since 771142bbdce3c03bbf07cdf5f10b84f01d4c7c81.
unfortunately that version is needed to properly build the docs for the
`dispatch` and `kommander` branches.
i also removed the `christina`-branch as nobody seems to use it.
=> Fix build when using dispatch or kommander branch

entry.js, index.js, js/search.js, layouts/partials/scripts.pug, package.json, plugins/metalsmith-revision.js
1. the livereload-script is moved to partials/scripts as that seems to
be included in more pages (like the landing page)
2. the pug- and consolidate-cache are cleared inbetween runs. we want to
keep the cache within a run though as it massively speeds up things.
3. add hashes for layouts within the revision-plugin to rebuild
everything when a layout changed.
4. `metalsmith-branch` is removed. does not seem to bring any benefit as we ran all files through both pipelines and the processors did the work of filtering our stuff anyway.
you now can edit layouts and see the changes without having to restart the dev environment. layouts and stylesheets/js should livereload now, so we have faster feedback cycles when changing stuff there.
=> Livereload for layouts and assets

docker/Dockerfile.production
While having a look at an issue that led to the docs not being able to
be built when one specifies a git_branch, i saw that line and wondered
whether it would be able to work.
As per google (https://developers.google.com/search/reference/robots_txt)
it shouldn't, as we need a line separator inbetween statements. A space
is not enough here.
This may mean that our stagings will be indexed by google. Here's
a current instance that won't behave as intended: http://docs-staging.d2iq.com/robots.txt
=> fix robots-txt

docker/Dockerfile.production
unfortunately the mechanism that has [been "fixed" recently](https://github.com/mesosphere/dcos-docs-site/pull/2922) seemed to
never have worked in the first place. during the build-time for
production `GIT_BRANCH` does not seem to equal "master" and thus we now
have a valid robots.txt on docs.d2iq.com
(https://docs.d2iq.com/robots.txt 😱) which effectively tells google to
not index the docs anymore.
this is a hotfix as to not potentially lose scoring on google. we should follow up
with a fix that properly adds a robot.txt on all non-prod-instances but
NOT on production.
as the `robots.txt`-files we had until a couple days ago were invalid, this change effectively restores the former state.
=> don't ban crawlers from production

pages/mesosphere/dcos/1.13/metrics/quickstart/index.md, pages/mesosphere/dcos/2.0/metrics/quickstart/index.md, pages/mesosphere/dcos/2.1/metrics/quickstart/index.md
DCOS_OSS-5294
1. The formatting was off in `DC/OS Metrics Quickstart Section 3` in versions 1.13, 2.0, 2.1. Reverted back to the 1.12 formatting after double checking no json values had changed.
=> Updated DC/OS Metrics Quickstart Formatting: DCOS_OSS-5294

pages/mesosphere/dcos/2.0/release-notes/2.0.3/index.md
https://jira.d2iq.com/browse/COPS-6187
This PR fixes incorrect Mesos version in the 2.0.3 release notes.
See https://github.com/dcos/dcos/blob/2.0.3/CHANGES.md
and also https://github.com/dcos/dcos/blob/2.0.3/packages/mesos/buildinfo.json
=> Fixed Mesos version in 2.0.3 release notes.

pages/mesosphere/dcos/1.11/deploying-services/creating-services/deploy-docker-app/index.md, pages/mesosphere/dcos/1.12/deploying-services/creating-services/deploy-docker-app/index.md, pages/mesosphere/dcos/1.13/deploying-services/creating-services/deploy-docker-app/index.md, pages/mesosphere/dcos/2.0/deploying-services/creating-services/deploy-docker-app/index.md, pages/mesosphere/dcos/2.1/deploying-services/creating-services/deploy-docker-app/index.md
D2IQ-38763: [Deploying Services Docs Bugs] Misleading documentation example in 'Deploying a Docker-based Service'
Removed the Parameters key from  from the Docker object in the Marathon service section of the docs, for versions 2.1, 2.0, 1.13, 1.12, 1.11
=> [DC/OS D2IQ-38763]: remove Parameters key from Docker object in Marathon service section 

pages/mesosphere/dcos/2.0/release-notes/2.0.4/index.md
https://jira.d2iq.com/browse/COPS-6187
This PR fixes incorrect Mesos version in the 2.0.4 release notes.
See https://github.com/dcos/dcos/blob/2.0.4/CHANGES.md
Also
https://github.com/dcos/dcos/blob/2.0.4/packages/openssl/buildinfo.json
and https://github.com/dcos/dcos/blob/2.0.4/packages/mesos/buildinfo.json
=> Fixed Mesos and OpenSSL versions in 2.0.4 release notes.

pages/mesosphere/dcos/services/edge-lb/1.5/getting-started/installing/index.md
**None yet**
I noticed there are a few permissions missing on the latest EdgeLB 1.5 installation instructions. Even worse, it seems they are correctly defined on EdgeLB 1.4 version, so I am not sure why this happened.
=> Typo: Adding missing permissions on EdgeLB

pages/mesosphere/dcos/1.13/installing/troubleshooting/index.md, pages/mesosphere/dcos/2.0/installing/production/patching/index.md, pages/mesosphere/dcos/2.0/installing/production/system-requirements/ports/index.md, pages/mesosphere/dcos/2.0/installing/production/upgrading/index.md, pages/mesosphere/dcos/2.0/installing/troubleshooting/index.md, pages/mesosphere/dcos/2.0/security/ent/tls-ssl/exhibitor/index.md, pages/mesosphere/dcos/2.1/installing/production/patching/index.md, pages/mesosphere/dcos/2.1/installing/production/system-requirements/ports/index.md, pages/mesosphere/dcos/2.1/installing/production/upgrading/index.md, pages/mesosphere/dcos/2.1/installing/troubleshooting/index.md, pages/mesosphere/dcos/2.1/security/ent/tls-ssl/exhibitor/index.md
https://jira.d2iq.com/browse/D2IQ-68867
Provide a way to contact Exhibitor when its endpoint has TLS enabled. https://jira.d2iq.com/browse/D2IQ-67335
Remove restriction on `/tmp` being `noexec`. https://jira.d2iq.com/browse/D2IQ-47741
=> Modify Exhibitor access to support TLS where appropriate

pages/ksphere/kommander/1.1.0-beta/clusters/attach-cluster/index.md
https://jira.d2iq.com/browse/D2IQ-65608 `Remove unnecessary steps from "attach cluster" documentation.`
The part that is being removed has been automated via https://jira.d2iq.com/browse/D2IQ-65077 and will be available in the next version of Kommander (1.1).
PR can be merged imediatelly, the change is already merged.
=> Remove steps related to manual provisioning of root certificate for attached clusters

pages/mesosphere/dcos/1.10/security/ent/tls-ssl/haproxy-adminrouter/index.md, pages/mesosphere/dcos/1.11/security/ent/tls-ssl/haproxy-adminrouter/index.md, pages/mesosphere/dcos/1.12/security/ent/tls-ssl/haproxy-adminrouter/index.md, pages/mesosphere/dcos/1.13/security/ent/tls-ssl/haproxy-adminrouter/index.md, pages/mesosphere/dcos/2.0/security/ent/tls-ssl/haproxy-adminrouter/index.md, pages/mesosphere/dcos/2.1/security/ent/tls-ssl/haproxy-adminrouter/index.md
https://jira.d2iq.com/browse/D2IQ-68894
For 2.0 and earlier, link to custom CA certificates as an alternative approach for HAProxy.
For 2.1, link to custom external certificates as a better approach.
=> Changed HAProxy to link to custom CA and external certificates

pages/ksphere/konvoy/1.4/install/install-airgapped/index.md, pages/ksphere/konvoy/1.4/install/install-aws/index.md, pages/ksphere/konvoy/1.4/install/install-azure/advanced-provisioning/index.md, pages/ksphere/konvoy/1.4/install/install-azure/index.md, pages/ksphere/konvoy/1.4/install/install-dev/index.md, pages/ksphere/konvoy/1.4/install/install-onprem/index.md, pages/ksphere/konvoy/1.4/install/install-secured/index.md, pages/ksphere/konvoy/1.4/operations/managing-nodes/index.md, pages/ksphere/konvoy/1.4/quick-start/index.md, pages/ksphere/konvoy/1.4/reference/cluster-configuration/index.md, pages/ksphere/konvoy/1.4/release-notes/index.md
Minor docs for `v1.4.4`.
Majority of the install-secured doc was a copy paste of what was there already.
=> konvoy: Update docs for konvoy release v1.4.4

config.json
Since kubeflow will be a new product, we need to update algolia and a few places in code to begin indexing. 
This change skips algolia indexing on kubeflow for the time being until we make those changes.
=> Skip indexing kubeflow on master (temporary)

layouts/components/content-actions.pug
- Added a "needs_triage" label to the Jira bug creation form that appears when the user clicks "Feedback" from our docs, so that we can quickly see and triage new issues.
=> Added a "needs_triage" label to track Feedback button docs for better triaging

pages/mesosphere/dcos/1.13/security/oss/secure-compute-profiles/index.md
Seccomp is disabled by default in DC/OS 1.13.x
=> Fix seccomp for 1.13

pages/ksphere/kommander/1.0/install/index.md, pages/ksphere/kommander/1.1.0-beta/install/index.md
The install page was suggesting that a folder, when having been extracted from an archive was completely named like the tarball -- but commonly "tar" and "gz"/"bz2"/... are removed.
=> Fix: Kommander installation example nit removal.

pages/ksphere/kommander/1.1.0-beta/clusters/index.md
This just came up when I ran 'npm run dev' - just one more broken img tag.
Broken img tag got fixed - works local now
=> just one more img

config.json
The latest DCOS docs has been pointed to 2.1, and is required to build kommander or dispatch docs. This patch adjusts the `DO_NOT_BUILD` list accordingly.
=> Build DCOS 2.1 docs when branch is `kommander` or `dispatch`.

pages/mesosphere/dcos/1.10/tutorials/autoscaling/cpu-memory/index.md, pages/mesosphere/dcos/1.11/tutorials/autoscaling/cpu-memory/index.md, pages/mesosphere/dcos/1.12/tutorials/autoscaling/cpu-memory/index.md, pages/mesosphere/dcos/1.13/tutorials/autoscaling/cpu-memory/index.md, pages/mesosphere/dcos/1.9/tutorials/autoscaling/cpu-memory/index.md, pages/mesosphere/dcos/2.0/tutorials/autoscaling/cpu-memory/index.md, pages/mesosphere/dcos/2.1/tutorials/autoscaling/cpu-memory/index.md, pages/mesosphere/dcos/cn/1.11/tutorials/autoscaling/cpu-memory/index.md, pages/mesosphere/dcos/cn/1.12/tutorials/autoscaling/cpu-memory/index.md, pages/mesosphere/dcos/cn/1.13/tutorials/autoscaling/cpu-memory/index.md, pages/mesosphere/dcos/cn/2.0/tutorials/autoscaling/cpu-memory/index.md
to verify: check out https://github.com/mesosphere/marathon-autoscale/
and see that the script is called `marathon-autoscaler.py` and not
`marathon-autoscale.py`.
closes COPS-4997 (https://jira.d2iq.com/browse/COPS-4997)
=> COPS-4997 - fix incorrect script path

docker/nginx/redirects-307.map
Update kubernetes service latest package redirect for new release
=> Update kubernetes service latest package redirect for new release

pages/ksphere/konvoy/1.4/install/install-azure/index.md
Fixed the by default Azure compute vm size which is now Standard_D4S_v3 and fixed a misplaced of  `--cluster-name.`
=> Typo fixes

pages/ksphere/konvoy/1.4/reference/cluster-configuration/index.md, pages/ksphere/konvoy/1.4/release-notes/index.md, pages/ksphere/konvoy/1.4/upgrade/upgrade-kubernetes-addons/index.md, pages/ksphere/konvoy/1.5/reference/cluster-configuration/index.md, pages/ksphere/konvoy/1.5/release-notes/index.md, pages/ksphere/konvoy/1.5/upgrade/upgrade-cli/index.md
Found while working on https://jira.d2iq.com/browse/D2IQ-69280.
Without this, trying to run Konvoy with the given `cluster.yaml` fails with `Error: failed to deploy the cluster: yaml: line 104: did not find expected key`.
=> Fixed configRepository line in cluster.yaml

docker/nginx/redirects-307.map, pages/mesosphere/dcos/services/edge-lb/1.6/getting-started/auto-pools/index.md, pages/mesosphere/dcos/services/edge-lb/1.6/related-documentation/release-notes/index.md, pages/mesosphere/dcos/services/edge-lb/1.6/tutorials/using-auto-pools/index.md, pages/mesosphere/dcos/services/edge-lb/index.md
https://jira.d2iq.com/browse/D2IQ-69799
* Add EdgeLB v1.6.1 release notes.
* Remove enterprise tag from EdgeLB on services page
* Change 307 map to point to v1.6.1
=> Edgelb 1.6.1

pages/ksphere/kommander/1.1.0-beta/tutorials/use-kcl-from-kubectl/index.md
https://jira.d2iq.com/browse/D2IQ-69967
Updates "Using Kommander Cluster Lifecycle API via kubectl" for the upcoming release - based on RC2.
- updates list of expected PODs
- updates names of CM and Webhook
- unifies the use of prepended prompt characters `$` by omitting them entirely
=> chore: updates kommander API via kubectl tutorial

docker/nginx/redirects-307.map, pages/mesosphere/dcos/services/jenkins/4.0.0-2.204.6/architecture/index.md, pages/mesosphere/dcos/services/jenkins/4.0.0-2.204.6/custom-install/index.md, pages/mesosphere/dcos/services/jenkins/4.0.0-2.204.6/index.md, pages/mesosphere/dcos/services/jenkins/4.0.0-2.204.6/jenkins-auth/index.md, pages/mesosphere/dcos/services/jenkins/4.0.0-2.204.6/options-compatibility-matrix/index.md, pages/mesosphere/dcos/services/jenkins/4.0.0-2.204.6/quickstart/index.md, pages/mesosphere/dcos/services/jenkins/4.0.0-2.204.6/release-notes/index.md, pages/mesosphere/dcos/services/jenkins/4.0.0-2.204.6/uninstall/index.md, pages/mesosphere/dcos/services/jenkins/jenkins-auth/index.md
[D2iQ-70163](https://jira.d2iq.com/browse/D2IQ-70163)
This PR captures the release of Jenkins 4.0.0-2.204.6
This PR is a minor modification of #2863 which has been reviewed and releaed with the following minor changes:
- Replaced `beta-jenkins` with `jenkins`
- Set `beta` flag to `false` in the headers.
- Updated version to `4.0.0-2.204.6`
- Removed any instances of `windows` as it is deprecated.
=> [D2iQ-70163][DOCS] Jenkins 4.0.0-2.204.6 Release Documentation.

docker/nginx/redirects-307.map
Follow up to https://github.com/mesosphere/dcos-docs-site/pull/3095, when CI ran the second time the commit got reverted.
=> konvoy: redirect latest to 1.5

docker/nginx/redirects-301.map
https://jira.d2iq.com/browse/D2IQ-69826
The URL changed in https://github.com/mesosphere/konvoy/pull/1736. Introduce a redirect for users that bookmarked the old URL.
=> nginx: redirect konvoy 1.5 "replace a failed node" URL

index.js
Link to 1.5 when clicking on page links
=> konvoy: use 1.5 as the latest docs

pages/ksphere/konvoy/1.5/addons/index.md, pages/ksphere/konvoy/1.5/logging/fluentbit/index.md
Move the KBA page to after logging and monitoring, instead of the first one in the list.
=> konvoy: move addons page

index.js
Similar change to https://github.com/mesosphere/dcos-docs-site/pull/3103 but for Kommander, use 1.1 links from the landing page.
=> kommander: use 1.1 as latest

pages/ksphere/konvoy/1.5/backup/index.md
N/A - docs for 1.5 release
standardizing links, just small grammar stuff, tested all the code snippets
PR into the konvoy repo, because it's release time: 
https://github.com/mesosphere/konvoy/pull/1869
=> small changes for backup/index.md, standardized links

pages/mesosphere/dcos/1.13/security/ent/perms-reference/index.md, pages/mesosphere/dcos/2.0/security/ent/perms-reference/index.md, pages/mesosphere/dcos/2.1/security/ent/perms-reference/index.md
https://jira.d2iq.com/browse/D2IQ-68709
Add a link to details of the Admin Router `/service` endpoint. The variations are complex, so the link is to a large section in the Admin Router README.md file in the `dcos` repository.
I also removed the action columns for this section, as Admin Router always uses `full`.
=> Add link to service endpoint details for Admin Router permissions

pages/mesosphere/dcos/1.13/deploying-services/private-docker-registry/index.md, pages/mesosphere/dcos/2.0/deploying-services/private-docker-registry/index.md, pages/mesosphere/dcos/2.1/deploying-services/private-docker-registry/index.md
https://jira.d2iq.com/browse/COPS-6365
- Adding information on how to use a DC/OS parameter to access private docker registries.
- Re-org of the page to improve readability.
This change can be merged any time.
- [n/a] Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects) if you are moving a page.
=> COPS-6365: Adding info about private Docker registry options in DC/OS

Makefile, README.md, docker/Dockerfile.liveedit, index.js
Adds two make targets:
1. `make docker-liveedit-image` builds the site in a container
2. `make docker-liveedit` runs the site in the container, with live rendering of changes to files in the `pages` directory.
We would like to make use of this functionality to "live edit" konvoy docs, e..g,
```
make --debug docker-liveedit \
LIVEEDIT_PAGES_SRC_ABS_PATH=/path/to/konvoy/repo/docs/site \
LIVEEDIT_PAGES_DST_REL_PATH=ksphere/konvoy/latest \
'LIVEEDIT_RENDER_PATH_PATTERN=ksphere/**'
```
The `docker-site-run` make target does run the site in a container, but requires docker-compose, and does not support live rendering.
This change does not affect any docs, or the existing toolchain.
See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/wiki/Contributing) for more …
=> Add make targets to build/run site in container, with "live editing"

config.json
=> removing dispatch 1.3 from do not build list

pages/mesosphere/dcos/1.13/deploying-services/private-docker-registry/index.md, pages/mesosphere/dcos/2.0/deploying-services/private-docker-registry/index.md, pages/mesosphere/dcos/2.1/deploying-services/private-docker-registry/index.md
https://jira.d2iq.com/browse/COPS-6402
Adding another parameter to an example which prevents operators from hitting the bug described in the COPS.
This change can be merged any time.
- [n/a] Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects) if you are moving a page.
=> COPS-6402: Add config parameter which avoids the issue

pages/mesosphere/dcos/1.13/installing/production/advanced-configuration/configuration-reference/index.md, pages/mesosphere/dcos/2.0/installing/production/advanced-configuration/configuration-reference/index.md, pages/mesosphere/dcos/2.1/installing/production/advanced-configuration/configuration-reference/index.md
https://jira.d2iq.com/browse/COPS-6362
Fixing incorrect information about DC/OS private Docker registry parameters. Adding missing parameters to the documentation.
This change can be merged any time.
- [n/a] Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects) if you are moving a page.
=> COPS-6362: Fixing incorrect information about Docker credentials in DC/OS

layouts/partials/head.pug
[D2IQ-70666](https://jira.d2iq.com/browse/D2IQ-70666)
* This changes the container ID within the Google Tag Manager snippet.
=> [D2IQ-70666] Change Google Tag Manager container ID.

index.js
unfortunately the gaze-library uses a mechanism that can only watch so many files (as
it declares the things to watch recursively - which worked back at the
time when node.js supported tail recursion).
we recently tried to be more clever with watching as that helped
massively speeding up the rebuilds in the newly introduced
docker-dev-env (70sec => 10sec). within that docker image node.js 
seems to be configured in a way that allows to recurse that deep.
we go back to the previous behaviour now in order to later find out which 
way to go from here.
we could ditch the metalsmitch-watcher for something as simple as `npx
nodemon ./rebuild-pages` (which should work reasonably fast with our
caching mechanisms), change `metalsmith-watch` to not use recursion or
write a new plugin using …
=> fix watching when using RPP on osx

pages/mesosphere/dcos/services/kubernetes/2.7.0-1.18.6/changelog/index.md, pages/mesosphere/dcos/services/kubernetes/2.7.0-1.18.6/release-notes/index.md
Adds release date to MKE 2.7.0.
=> chore: adds release date for MKE 2.7.0

config.json, index.js
there seem to be some obsolete branch-configs in `config.json`.
as i think it would be wise to completely get rid of this file in favour of a `draft`-mechanism, we now start by trimming it down.
1. `DO_NOT_INDEX` has no effect currently. things that are not built also won't be indexed.
2. the `develop`- and `alpha`-envs are not used anymore
3. `dispatch` does not have an according branch. IT MIGHT BE that someone specifies dispatch as a docker-arg in some build-process that is now slowed down. if so, they could use the RPP to only build dispatch, which would be even faster.
4. evade the need for `local` and `always` via changes in `index.js`.
--------------
this PR emerged while adding DCOS 2.2.
=> remove obsolete entries from config.json

layouts/components/content-sections.pug, plugins/metalsmith-headings.js
having a look at the biggest time consumers of our pipeline these changes emerged.
* we don't have `relatedPages`, let's remove the reference to that.
* remove some dead code and refactor the according code to be more
revealing of its intentions.
if we'd put the determination of headings into the markdown-step that
produces anchors anyway, we could save all the cheerio-parsing. but
that's for another day.
----------------
if i had made an error in here, the table-of-contents component that most pages display on the right would be off. i checked a couple sites of each product and they're all the same than they were before.
=> refactor the headings-plugin and remove some dead code

pages/mesosphere/dcos/1.13/installing/production/deploying-dcos/installation/index.md, pages/mesosphere/dcos/2.0/installing/production/deploying-dcos/installation/index.md, pages/mesosphere/dcos/2.1/installing/production/deploying-dcos/installation/index.md
[D2IQ-70965](https://jira.d2iq.com/browse/D2IQ-70965) Fault domain detect example in on-prem docs missleading
- Changed the example to be an script instead of just example output of an undefined script
=> fix: improve fault domain example to be a valid script

layouts/404.pug, layouts/all-products-landing.pug, layouts/cn-dcos-docs-landing.pug, layouts/cn-service-docs-landing.pug, layouts/components/content-actions.pug, layouts/components/content-grid.pug, layouts/conductor-docs-landing.pug, layouts/dcos-docs-landing.pug, layouts/dispatch-docs-landing.pug, layouts/kommander-docs-landing.pug, layouts/konvoy-docs-landing.pug, layouts/konvoy-partners-landing.pug, layouts/kudo-kubeflow-docs-landing.pug, layouts/partials/content.pug, layouts/partials/header/header-dropdown.pug, layouts/partials/header/header.pug, layouts/partials/header/ksphere-dropdown.pug, layouts/partials/header/localization-dropdown.pug, layouts/partials/header/mesosphere-dropdown.pug, layouts/partials/search-results.pug, layouts/search.pug, layouts/service-docs-landing.pug
piped our layouts through a "pugifier".
```pug
span(class="myClass")
div(class="myClass")
span.myClass
.myClass
```
reasoning: less visual noise makes it easier to work with those
templates.
=> convert templates to use pugs class and id notation

pages/ksphere/kommander/1.1/centralized-cost-monitoring/index.md
https://jira.d2iq.com/browse/D2IQ-70685
Minor change to remove a note that cost data takes 3hr to show up (it is now 5min - essentially immediately)
=> Remove kubecost 3hr wait time from centralized cost monitoring docs

layouts/components/content-actions.pug, scss/components/_actions.scss
this fixes the print-button.
due to some recent changes that add a `target="_blank"` to every
non-internal link, the print button broke.
you'd click it and it would navigate away to an empty page and then try
to print that empty page.
we now replaced the anchor with a button, as buttons don't suffer from
that target-changing we do.
i don't say printing is pretty. but at least we get to see something now again.
=> D2iQ-41078

README.md, js/code-container.js, package.json, scss/vendor/_prism.scss
@russurquhart1 recently asked whether we could add asciidoctor to our stack. it turned out that the most-wanted feature was line-highlighting.
to have a look or play around with that yourself:
the `data-line` attribute can take the following values:
* `1` - highlight line 1.
* `1-3` - highlight the range 1 to 3.
* `1,3` - highlight the lines 1 and 3.
* `1-3,42` - highlight lines 1 to 3 and 42.
=> Line Highlighting

.github/styles/Vocab/Docs/accept.txt, .github/workflows/vale.yml, .vale.ini, pages/index.md
... as well as the term `COPS`.
had a look at https://github.com/mesosphere/dcos-docs-site/pull/3153 and and fixed the most urgent misconfigurations, so that the warnings and suggestions start to seem mostly meaningful (for that PR).
=> only lint markdown files and ignore shortcodes

pages/ksphere/konvoy/1.5/concepts/index.md, scss/base/_content.scss
we should also start thinking about a max-width for the main content
whilst centering it.
that would be an easy to implement measure that
would make the docs look much better on large monitors.
closes D2IQ-71207
note that the view has been scaled down on that one, so things might look weird. it's all about displaying the light-grey border around the image in the content section:
=> D2IQ-71207 add a border around images in content

Makefile, README.md, docker/Dockerfile.liveedit, docker/Dockerfile.production, package.json, scripts/clean.sh, shortcodes/index.js
I think this is a pretty impactful one. Here are the commit messages: 
why? because they were only ever rendered to be included in PDFs.
so currently we're waiting like 10 minutes on every deployment (and on
every dev's machine that's setup to render docs) for no good reason.
if we want to build PDFs in the futue, we'd most likely do so by using
puppeteer or wkhtml2pdf, so even then this output is of no use.
we now compile ngindox-content on the fly, as the compiler seems to be
pretty darn fast. this way we can get rid of the whole "prebuild" step
and can start right at `npm run dev`. 
-----
imagine deploying or setting up a new dev-env in the future 😻 
if you see that the includes work as they did before, everything should be fine!
* [prod …
=> speed up deployment and setup

pages/ksphere/kommander/1.2/clusters/attach-cluster/federated-addons/index.md
[D2IQ-71134](https://jira.d2iq.com/browse/D2IQ-71134)
added prometheusadapter to the list of default federated addons for non-konvoy
clusters. This is to ensure metrics are available in the Kommander GUI.
[PR #176](https://github.com/mesosphere/yakcl/pull/176) makes this
change.
=> feat: document prometheusadapter being federated

pages/mesosphere/dcos/2.1/release-notes/2.1.1/index.md
DC/OS UI overview lists these two versions, 
https://jira.d2iq.com/browse/COPS-6329 is indicator that this is not quite correct.
=> correcting versions on deployed 2.1.1 cluster

docker/nginx/redirects-301.map
https://jira.d2iq.com/browse/D2IQ-71280
Redirecting a broken link
=> D2IQ-71280: redirects cloud-providers URL to infrastructure-providers

index.js
we formerly made sure that an `RPP` could only be used in
development-mode. that restriction seems to be cumbersome for other
teams as they'd like to have a fast build (and not a fast dev-mode).
see
https://github.com/mesosphere/dispatch/pull/746#issuecomment-683142668
we have pretty solid control over how we deploy to production so it looks like it's worth removing this safety-measure in exchange for those (way!) faster builds.
=> allow to set RPP for `npm run build`

.github/styles/Vocab/Docs/accept.txt
None.
Created in response to https://github.com/mesosphere/dcos-docs-site/pull/3182/files#annotation_397289461
=> Add namespace and namespaced to Vale vocab

scripts/build-site.sh
The staging site is not working due to a moving dependency of pyrex.
The error message is
```
Collecting pyrsistent>=0.14.0 (from jsonschema<4,>=2.5.1->docker-compose)
Downloading https://files.pythonhosted.org/packages/7d/ae/90ddcf28fb8eee5d4990920586d2856342e42faa95f39223f0b9762ef264/pyrsistent-0.17.2.tar.gz (106kB)
pyrsistent requires Python '>=3.5' but the running Python is 2.7.15
```
This is coming from the latest version of pyristent. We are trying to solve this problem by pinning it to an earlier version of pyrsistent.
=> Pin pyristent to fix the CI issue.

pages/mesosphere/dcos/2.2/security/ent/tls-ssl/ca-custom/index.md
https://jira.d2iq.com/browse/D2IQ-71528
Rewrite custom certificate page to add support for certificate renewal.
Although this will also work in the next minor versions of 2.1 and 2.0, I am just changing 2.2 for now to support the beta release. Once we're happy with 2.2 beta results and perhaps closer to minor updates to earlier versions, I will copy this back to 2.1 and 2.0
=> Modify custom CA instructions for certificate renewal

pages/mesosphere/dcos/2.2/deploying-services/marathon-parameters/index.md, pages/mesosphere/dcos/2.2/installing/production/advanced-configuration/configuration-reference/index.md, pages/mesosphere/dcos/2.2/storage/external-storage/csi/index.md, pages/mesosphere/dcos/2.2/storage/external-storage/dvdi/index.md, pages/mesosphere/dcos/2.2/storage/external-storage/index.md
[D2IQ-70189](https://jira.d2iq.com/browse/D2IQ-70189)
This PR adds new documentation for the new type of CSI external volumes which we're adding in DC/OS 2.2. It also restructures the external volumes docs by adding a new top-level summary page for external volumes, with two subpages, one each for CSI and DVDI volumes, which are the two types of external volumes we currently offer.
=> Updated external storage docs for CSI volumes.

pages/mesosphere/dcos/2.2/storage/external-storage/csi/index.md, pages/mesosphere/dcos/2.2/storage/external-storage/dvdi/index.md
[D2IQ-70189](https://jira.d2iq.com/browse/D2IQ-70189)
This PR makes some essential updates to the CSI external volume documentation for DC/OS 2.2.
=> Update the CSI external storage documentation.

pages/ksphere/konvoy/partner-solutions/jenkins/index.md
Jenkins docs had some (more!) indentation errors which are fixed by this PR. Also, update docs to move to new jenkins chart repo at `jenkinsci/helm-charts` instead of the default helm repo.
For [COPS-6503](https://jira.d2iq.com/browse/COPS-6503)
=> Fix typos in jenkins docs

docker/nginx/redirects-307.map
https://jira.d2iq.com/browse/D2IQ-71861
Add a `latest` redirect for kubeflow.
=> Add a `latest` redirect for kubeflow.

pages/mesosphere/dcos/2.1/networking/SDN/calico/index.md, pages/mesosphere/dcos/2.2/networking/SDN/calico/index.md
https://jira.d2iq.com/browse/COPS-6328
The docker isolator does not parse and forward networkinfo labels, so customers must set the labels explicitly in the docker parameters.
=> mesos-calico: clarify labeling for Docker vs UCR

pages/ksphere/kubeflow/1.0.1-0.5.0/install/air-gapped/index.md
AFAIK, there is no "config.yaml" associated with a Konvoy cluster?
Renamed to "cluster.yaml" to avoid end user confusion.
=> change "config.yaml" to "cluster.yaml"

scss/shortcodes/_message.scss, shortcodes/index.js
while working on #3233 i wanted to use the message-shortcode. it currently is not flexible enough for my use case. then these changes emerged before implementing what i need.
1. because they're not used in the codebase anymore we remove
* `icon`
* `switch`
* `case`
* `image`
* `tooltip`
validated via grepping for `"\[<SHORTCODE>"`.
2. remove `sanitize` as its name should rather had been `trim` and we
don't actually need it when writing our shortcodes differently.
3. add a helper for all those `badge` thingies. we might even introduce a `badge` shortcode that replaces all those later.
4. we remove the `fill` option from `message` as it's not used anywhere and even looks really broken currently.
5. we remove the "inline-block" `type` handling within the badge-helper as that's not used …
=> clean up the shortcodes file

pages/mesosphere/dcos/1.12/networking/DNS/mesos-dns/index.md, pages/mesosphere/dcos/1.13/networking/DNS/mesos-dns/index.md, pages/mesosphere/dcos/2.0/networking/DNS/mesos-dns/index.md, pages/mesosphere/dcos/2.1/networking/DNS/mesos-dns/index.md, pages/mesosphere/dcos/2.2/networking/DNS/mesos-dns/index.md
As of 1.10 (or 1.11??), MesosDNS is never sent any requests for domains other than .mesos.  So it will never forward any requests to outside cluster addresses because it is never sent any. 
The current diagram confuses customers and results in support tickets, so the purpose of this PR is to avoid customer confusion.
[COPS-6583](https://jira.d2iq.com/browse/COPS-6583)
=> Fixing Mesos-DNS documentation to avoid customer confusion.

pages/ksphere/kommander/1.0/install/index.md, pages/ksphere/kommander/1.1/install/index.md, pages/ksphere/kommander/1.2/install/index.md
My understanding is that intended behavior for kommander docs to link to the corresponding konvoy docs .We had install docs point to latest konvoy docs. It seems like un-intended behavior to me because:
* If i go to an older kommander release (eg 1.0) it points me to konvoy 1.5 docs right now which is not correct for kommander 1.0
* If I go to a 1.2(beta) kommander release it points to konvoy 1.5 since konvoy 1.6 is still in beta but the correct konvoy for this is 1.6
=> Point to corresponding Konvoy docs instead of latest

pages/mesosphere/dcos/1.13/installing/production/advanced-configuration/configuring-zones-regions/index.md, pages/mesosphere/dcos/2.0/installing/production/advanced-configuration/configuring-zones-regions/index.md, pages/mesosphere/dcos/2.1/installing/production/advanced-configuration/configuring-zones-regions/index.md, pages/mesosphere/dcos/2.2/installing/production/advanced-configuration/configuring-zones-regions/index.md
https://jira.d2iq.com/browse/COPS-6601
Adding the "Enterprise" tag to a page which describes an enterprise-only feature.
=> COPS-6601: "Zones and Regions" page missing Enterprise tag

pages/ksphere/kommander/1.2/centralized-monitoring/index.md
N/A
Removes duplicated frontmatter property that was causing the centralized monitoring tab to not show in kommander 1.2 docs
Before (No centralized monitoring tab in sidebar):
After:
=> fix: show centralized monitoring tab in kommander 1.2 docs

pages/mesosphere/dcos/2.0/administering-clusters/replacing-a-master-node/index.md, pages/mesosphere/dcos/2.0/installing/production/upgrading/index.md, pages/mesosphere/dcos/2.0/security/ent/tls-ssl/exhibitor/index.md, pages/mesosphere/dcos/2.1/administering-clusters/replacing-a-master-node/index.md, pages/mesosphere/dcos/2.1/installing/production/upgrading/index.md, pages/mesosphere/dcos/2.1/security/ent/tls-ssl/exhibitor/index.md, pages/mesosphere/dcos/2.2/administering-clusters/replacing-a-master-node/index.md, pages/mesosphere/dcos/2.2/installing/production/upgrading/index.md, pages/mesosphere/dcos/2.2/security/ent/tls-ssl/exhibitor/index.md
https://jira.d2iq.com/browse/D2IQ-72618
Clarify what happens with Exhibitor TLS when upgrading from DC/OS pre-2.0.
=> Improve instructions for Exhibitor TLS on upgrade

pages/mesosphere/dcos/1.13/deploying-services/faq/index.md, pages/mesosphere/dcos/2.0/deploying-services/faq/index.md, pages/mesosphere/dcos/2.1/deploying-services/faq/index.md, pages/mesosphere/dcos/2.2/deploying-services/faq/index.md
https://jira.d2iq.com/browse/COPS-6615
Removing reference to CoreOS as it is no longer supported. Replace with a link to the version-policy page.
=> Removing reference to CoreOS

pages/ksphere/konvoy/1.4/reference/addons/index.md, pages/ksphere/konvoy/1.5/reference/addons/index.md
n/a, but described here: https://github.com/mesosphere/konvoy/pull/2337
Backporting changes to the location of the helm repo to change from the one being depracated.
=> backporting changes for helm repo location

pages/mesosphere/dcos/2.2/installing/production/advanced-configuration/configuration-reference/index.md, pages/mesosphere/dcos/2.2/installing/production/deploying-dcos/configuration/examples/index.md, pages/mesosphere/dcos/2.2/installing/production/deploying-dcos/opt-out/index.md, pages/mesosphere/dcos/2.2/security/ent/tls-ssl/ca-custom/index.md, pages/mesosphere/dcos/2.2/security/ent/tls-ssl/exhibitor/index.md, pages/mesosphere/dcos/2.2/security/ent/tls-ssl/haproxy-adminrouter/index.md
https://jira.d2iq.com/browse/D2IQ-71896
Separate the description of custom CA's being added to an initial installation and being changed in an existing installation.
The instructions for an existing installation are more complicated as they require 3 patch upgrades.
There is a new configuration variable (`ca_truststore_path`) which is required to set two trusted CA's during the changeover.
=> Split certificate renewal into setting and renewing sections

pages/ksphere/kommander/1.2/release-notes/legal-notices/index.md
n/a
There's an issue when there are two beta tags in the header part of this markdown file, it makes it look a bit messed up.
So, just making it go from this: 
to this: 
=> fixing template tags for legal notices page on 1.2

layouts/partials/head.pug
TL;DR: nothing changes. just prevents errors for folks that use an automatic formatter.
------------------------
if you run prettier - the prevalent formatter of the JS ecosystem - it will remove the trailing `=` in this snippet:
```diff
-    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
+    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src
```
this is troublesome as only the next line contains the right-hand side of the assignment, which is needed for google tag manager to work.
i think prettier is fooled by the special pug element we're using here (note the trailing `.` on the surrounding `script.` element. 
so let's prevent this from accidentally happening `=` [again](https://github.com/mesosphere/dcos-docs-site/pull/3315/commits/dafcd30e77eae …
=> remove a troublesome line break

pages/ksphere/kommander/1.0/centralized-monitoring/index.md, pages/ksphere/kommander/1.1/centralized-monitoring/index.md, pages/ksphere/kommander/1.1/projects/platform-services/index.md, pages/ksphere/kommander/1.2/centralized-monitoring/index.md, pages/ksphere/kommander/1.2/projects/platform-services/index.md
N/A
Updating repos of helm charts to be upstream repos
=> updating repos for helm charts to be on upstream repos

pages/mesosphere/dcos/2.1/installing/production/advanced-configuration/configuration-reference/index.md, pages/mesosphere/dcos/2.2/installing/production/advanced-configuration/configuration-reference/index.md
This documents the flag added in response to this ticket:
https://jira.d2iq.com/browse/COPS-6451
=> Add documentation for calico_enabled flag

pages/ksphere/konvoy/1.4/monitoring/index.md, pages/ksphere/konvoy/1.4/networking/index.md, pages/ksphere/konvoy/1.4/reference/addons/index.md, pages/ksphere/konvoy/1.4/release-notes/index.md, pages/ksphere/konvoy/1.4/tutorials/addon-repositories/index.md, pages/ksphere/konvoy/1.4/tutorials/use-istio/index.md, pages/ksphere/konvoy/1.5/monitoring/index.md, pages/ksphere/konvoy/1.5/networking/index.md, pages/ksphere/konvoy/1.5/reference/addons/index.md, pages/ksphere/konvoy/1.5/release-notes/index.md, pages/ksphere/konvoy/1.5/tutorials/addon-repositories/index.md
N/A
There were some previous versions of the docs that will mention charts from helm repos that are set to be archived.
Also made some minor changes to the istio install that works more readily.
=> backport helm repo location changes to previous versions of docs

pages/mesosphere/dcos/1.13/security/oss/user-account-management/service-accounts/index.md, pages/mesosphere/dcos/2.0/security/oss/user-account-management/service-accounts/index.md, pages/mesosphere/dcos/2.1/security/oss/user-account-management/service-accounts/index.md, pages/mesosphere/dcos/2.2/security/oss/user-account-management/service-accounts/index.md
https://jira.d2iq.com/browse/D2IQ-73137
Remove section that describes an unsupported operation (changing service account credentials).
=> Remove section for unsupported operation of changing service account creds

s3config.json
We GA'd Konvoy 1.6 and Kommander 1.2. `latest` should point to those docs now
=> chore: update latest redirects for konvoy+kommander

layouts/partials/sidebar.pug
when having a look at the dev-console on production we notice that no
link in the sidebar has a trailing slash, which lets S3 do a redirect to
the slashed version.
on my connection that makes about half of the total loading time for
small to medium sized pages (mostly all those without images).
let's cut loading times in half!
testing: if the sidebar-links in the preview env work everything should be fine
--------------
=> less redirecting

js/actions.js, js/main.js, layouts/components/content-actions.pug, layouts/partials/scripts.pug
addThis is a service that makes for a great share-button.
unfortunately they add 9 script files in total that weight in at ~1MB
and they add a click handler that catches clicks on internal and
external links which makes for a noticeable delay in changing pages.
as we guess that this button is not used very often, we remove it for
now. if we ever want to have share functionality, that's pretty easy
(and also stable by now) to add for the major platforms even without
using a service.
--------
obviously today is docs-performance-day...
=> remove addThis

js/sidebar.js, layouts/partials/head.pug, layouts/partials/sidebar.pug, scss/components/_sidebar.scss
a lot of the markup on our pages belong to the sidebar, as we always
render all entries and each of those has really long classnames attached
to it.
`du -sm` tells us `1482MB` before and `903MB` after this change.
if we take into account that images weight in at `749MB` (and thus are our next
target), we get a html-size reduction of about 80% (from `733MB` to `154MB`).   
the size of e.g. `mesosphere/dcos/2.2/release-notes/2.2.1/` went from 160KB to 15KB.
benefits: 
* upload to S3 is faster (we should see deployments that scratch the 4 minute mark regularly with this)
* metalsmith's layouts-step takes less time (faster deployment, faster dev-cycle)
* ~40% less spend on S3 
* potentially better SEO-score due to improved load times
the change itself is twofold:
1. don't render nested …
=> decrease build size

pages/dkp/kommander/1.2/projects/project-quotas-limit-range/index.md, pages/dkp/kommander/1.3/projects/project-quotas-limit-range/index.md
Part of resolution for COPS-6728
https://jira.d2iq.com/browse/COPS-6728
Fixes limit range docs
=> COPS-6728: kommander limit range docs

pages/dkp/kommander/1.3/clusters/attach-cluster/attach-eks-cluster/index.md, pages/dkp/kommander/1.3/clusters/attach-cluster/federated-platform-services/index.md, pages/dkp/kommander/1.3/clusters/attach-cluster/index.md, pages/dkp/kommander/1.3/clusters/index.md, pages/dkp/kommander/1.3/install-airgapped/index.md, pages/dkp/kommander/1.3/projects/platform-services/index.md, pages/dkp/kommander/1.3/security/distributed-authnz/index.md, pages/dkp/kommander/1.3/tutorials/duplicating-cluster/index.md
https://jira.d2iq.com/browse/D2IQ-73666
docs review ticket: https://jira.d2iq.com/browse/D2IQ-73669
We are renaming "addons" to "platform services" across Kommander UI and docs for kommander 1.3. Konvoy rename will happen later with konvoy/kommander unification work.
=> Rename addons to platform services in kommander docs

pages/dkp/konvoy/1.4/introduction/index.md, pages/dkp/konvoy/1.5/introduction/index.md, pages/dkp/konvoy/1.6/introduction/index.md, pages/dkp/konvoy/1.7/introduction/index.md
This PR fixes the following problem. Konvoy documentation still mentions AWS as the only supported cloud provider for versions 1.7, 1.6, 1.5, and 1.4. At the same time, Konvoy is available for more than one public cloud provider starting at least from v1.4
https://jira.d2iq.com/browse/COPS-6754
Remove mentions of AWS as the only supported cloud provider.
=> Konvoy is available for more than one public cloud provider (AWS)

pages/dkp/konvoy/1.5/install/bastion-hosts/index.md, pages/dkp/konvoy/1.5/install/install-airgapped/index.md, pages/dkp/konvoy/1.5/install/install-azure/advanced-provisioning/index.md, pages/dkp/konvoy/1.5/release-notes/index.md, pages/dkp/konvoy/1.5/version-support/index.md
Release docs for Konvoy v1.5.5.
https://jira.d2iq.com/browse/D2IQ-73794
Release needed for https://jira.d2iq.com/browse/D2IQ-73767
=> konvoy: Update 1.5 docs

pages/dkp/kommander/1.3/install/index.md
https://jira.d2iq.com/browse/D2IQ-62854
Looks like konvoy docs do not include specific details on download instructions, so we should remove them from kommander and just link to the konvoy docs.
=> [op docs] Remove konvoy download instructions from kommander docs

pages/dkp/konvoy/1.6/include/enforce-policies-w-gatekeeper.tmpl
Updating the dead links based on OPA's current structure. They moved the library to a new Github repository https://github.com/open-policy-agent/gatekeeper-library.
=> Updating dead link in the page.

pages/dkp/konvoy/1.6/include/enforce-policies-w-gatekeeper.tmpl, pages/dkp/konvoy/1.7/release-notes/index.md
The default Kubernetes version in the official release is 1.19.7.
=> Updated the default Kubernetes version

js/cve.js
the CVE-export is now directly pulled from its S3-bucket, so changes
will automatically propagate.
note that we set the caching-headers on the export to 24h.
testing this is rather complicated. i suggest merging this to staging and then trying to access the table on https://docs-staging.d2iq.com/dkp/security-updates/ to see that there's an XHR-request pulling the data. i tested this upfront with some js-trickery for `https://docs.d2iq.com` and `https://docs-staging.d2iq.com`.
=> use the "real" export

pages/dkp/kommander/1.0/clusters/attach-cluster/index.md, pages/dkp/kommander/1.1/clusters/attach-cluster/index.md, pages/dkp/kommander/1.2/clusters/attach-cluster/index.md, pages/dkp/kommander/1.3/clusters/attach-cluster/index.md
In some kubeconfigs the cluster-certificate-authority-data field of a
cluster might not exist, causing 'CLUSTER_CA' to be set to '<no
value>'. With this patch, it is set to the empty string.
=> fix: account for cluster CA being empty

js/cve.js, scss/base/_content.scss, scss/components/_cve-table.scss
this lets customers see the difference between mitigated and non-mitigated issues.
things done and looking for more opiniones/suggestions:
- grey out the background of a mitigated CVE
- strikethrough the severity when the CVE is mitigated
- add a tooltip to this striked severity: **"Mitigated - see Addtional Explanation"**
- add a filter-button right to the severity-filters to hide mitigated CVEs. it's filtering by default, so one has to click it to see all the CVEs of the export.
- move filters to the left, so we can fit one more button easily above the table
- adapted responsiveness (so it does not look rubbish on mobile devices)
we might want to run this by the UX-department as i feel like that
eye-button is rather not intention-revealing at first sight. …
=> mark mitigated entries and add an according filter

pages/dkp/kommander/1.3/workspaces/platform-service-dependencies/index.md, pages/dkp/kommander/1.3/workspaces/workspace-platform-services/index.md, pages/dkp/kommander/1.4/workspaces/platform-service-dependencies/index.md, pages/dkp/kommander/1.4/workspaces/workspace-platform-services/index.md
https://jira.d2iq.com/browse/D2IQ-74295
Update docs, there is a bug fix going into kommander 1.3.1 that will also force disable all platform services if foundational components are disabled. Also updated k8s version support to 1.20 for 1.4 since that has been merged into the beta
=> Update kommander platform services docs

pages/dkp/konvoy/1.6/addons/helmv2-to-v3-migration/index.md, pages/dkp/konvoy/1.6/release-notes/1.6.1/index.md, pages/dkp/konvoy/1.6/release-notes/1.6.2/index.md, pages/dkp/konvoy/1.6/release-notes/1.6/index.md, pages/dkp/konvoy/1.6/upgrade/upgrade-cli/index.md
[COPS-6869](https://jira.d2iq.com/browse/COPS-6869)
Adding a note about if there is an issue with prometheus failing due to size of configmaps
=> [COPS-6869] adding bit about upgrading prometheus helm conflicts

pages/dkp/kommander/1.4/index.md, pages/dkp/kommander/2.0/index.md
n/a
Updating the dropdown nav menu titles so it accurately says they're beta.
=> adding beta in dropdown nav for kommander 1.4 and 2.0

pages/dkp/kommander/1.4/clusters/tunnel-cli/index.md
Add description of using a network policy to restrict access from tunnel agents to tunnel connectors.
=> Creating a network policy to restrict tunnel agent connections

pages/dkp/kommander/1.4/clusters/attach-cluster/index.md, pages/dkp/kommander/1.4/clusters/attach-cluster/requirements-for-attaching/index.md
n/a
missed some links - these pages were linking to a page that no longer is valid.
=> fixing link for cluster-with-network-restrictions page

pages/dkp/kommander/1.4/upgrade/index.md
n/a
Adding link to version support policy in the upgrade page, so people know what version is supported by Konvoy for a Kommander upgrade.
=> adding link to version support policy in upgrade/index.md

pages/dkp/kommander/1.4/clusters/attach-cluster/cluster-with-network-restrictions/index.md, pages/dkp/kommander/1.4/release-notes/index.md
...and added NAT gateway to "attach cluster" docs page
https://jira.d2iq.com/browse/D2IQ-74802 
Needed to add a Release Notes blurb for the Network Tunneling feature, and also to mention that a managed cluster can be behind a NAT Gateway and still become attached to Kommander.
=> [Doc][Komm] D2IQ-74802 Added network tunneling blurb to RelNotes... (1.4)

pages/dkp/kaptain/1.2.0-1.0.0/tutorials/pipelines/index.md, pages/dkp/kaptain/1.2.0-1.1.0/tutorials/pipelines/index.md
[D2IQ-70019: broken links in kubeflow docs](https://jira.d2iq.com/browse/D2IQ-70019).
Removes irrelevant links from the tutorials.
=> Kaptain: remove invalid links from Pipelines tutorial

pages/dkp/kommander/1.3/projects/platform-services/platform-services-catalog/kudo-spark/index.md, pages/dkp/konvoy/1.7/release-notes/1.7/index.md
[D2IQ-75005](https://jira.d2iq.com/browse/D2IQ-75005)
Backport the docs PR review fixes from #3603 to Kommander 1.3 here.
=> Kommander 1.3 KUDO Spark Docs: Backport docs fixes from 1.4 Docs Review.

js/cve.js, pages/dkp/security-updates/index.md
JIRA: https://jira.d2iq.com/browse/D2IQ-75575
This PR changes the data source for security-updates page from local static file to live data from S3 bucket that is updated by `cve-reporter`.
=> security-updates: use live s3 data source

s3config.json
D2IQ-75506 - Redirecting the /latest/ to the most up to date versions of konv(1.8)/komm(1.4) and changed a link from Architecture to architecture
[D2IQ-75506](https://jira.d2iq.com/browse/D2IQ-75506)
`Kommander` - Need to update links in Kommander help
Changing the redirects to go from broken in 1.4 /Architecture to /architecture and updating the 'latest' re-directs
=> fix: updating redirects for Arch and latest

layouts/konvoy-partners-landing.pug
The position was off and seemed to be floating too low for the
actual content.
N/A
Changing from this: 
To this: 
=> fix(styles): changing partner solutions header

ci/pull-upstream.sh
Avoid issues like https://github.com/mesosphere/dcos-docs-site/pull/3626/files
```
--delete                delete extraneous files from destination dirs
```
Im assuming here that the upstream repo will be the only source of truth and all files must come from there.
=> fix: use --delete option when rsync from upstream

Jenkinsfile, ci/deploy.sh
This should implement the changes requested in D2IQ-75903 and D2IQ-75904.
The `--delete` flag to `aws s3 sync` makes sure that files that do not exist in the local `build/` directory are being removed from the remote bucket.
The new `beta` branch will be synced to the existing staging bucket. Once the Jenkins job is created and runs against the `beta` branch we'll check if the `docs-d2iq-com-staging` bucket was synced successfully and point the https://beta-docs.d2iq.com/ Cloudfront distribution to the staging bucket instead of the PR 3578 bucket.
=> Deployment changes for D2IQ-75904 and D2IQ-75903

Jenkinsfile
As discussed on Slack this updates the Jenkinsfile to trigger the https://beta-docs.d2iq.com deployment on the `private-beta` branch instead of `beta`.
=> Use private-beta branch instead of beta

pages/dkp/kommander/1.4/release-notes/open-source-attributions/index.md, pages/dkp/konvoy/1.8/legal/open-source-attribution/index.md
The h tags (in markdown, ##) would add a sidebar
for the table pages here
n/a
Changed the markdown headers (`##`) to just be bold, so that it doesn't add a sidebar nav on these pages that are literally just tables anyway.
Issue is visualized here: 
=> docs(fix): removing h tags for open source pages

pages/dkp/kommander/1.3/release-notes/1.3.0/index.md, pages/dkp/kommander/1.3/release-notes/1.3.1/index.md, pages/dkp/kommander/1.3/release-notes/1.3.2/index.md, pages/dkp/kommander/1.3/release-notes/1.3.3/index.md
https://jira.d2iq.com/browse/D2IQ-75774
https://jira.d2iq.com/browse/D2IQ-75885 
Add known issues section with note that kubecost deployment _may_ fail for some customers if their provisioner doesn't allow storage size <1Gi, and an upgrading section in 1.3.3 (not yet released) referencing/repeating kubecost docs and recs on upgrades. I struggled a bit with where to put this info / how to write it so please feel free to rewrite/move things! And whether we need to dupe this in the konvoy RN, since technically kommander is released with konvoy so I guess this upgrade path would be upgrading konvoy versions ❓ 🤔 
When …
=> Add upgrade info for kubecost, and update 1.3.3 RN

pages/dkp/konvoy/1.7/include/os-svc-nodes.tmpl, pages/dkp/konvoy/1.7/install/install-airgapped/index.md, pages/dkp/konvoy/1.8/include/os-svc-nodes.tmpl, pages/dkp/konvoy/1.8/install/install-airgapped/index.md
https://jira.d2iq.com/browse/D2IQ-76725
Air-gapped clusters require Python to be installed before running `konvoy up` because, if it is missing, the Ansible scripts use the network to install it.
=> Specify Python as an OS prerequisite in air-gapped clusters

pages/dkp/kaptain/1.2.0-1.1.0/version-policy/index.md
Adding Secondary Support to Kaptain Version-Policy page PER COPS-6758
https://jira.d2iq.com/browse/COPS-6758
Adding Secondary Support in Kaptain's Version Policy
=> Update kaptain version-policy

plugins/metalsmith-hierarchy.js
This seems to fix the build issue in CI.
We don't know why this happens right now. This should probably be investigated further to know what's going on. 
=> fix: use default function from cheerio

package-lock.json, package.json, plugins/metalsmith-hierarchy.js
Don't rely on cheerio which is currently breaking in CI. Instead, just
use simple regex to determine the first paragraph of content. Wrote a
Jest test for this locally using the first 6 files in the array that is
looped over.
=> Refactor first paragraph logic

pages/dkp/kaptain/1.2.0/legal-notices/index.md
This file doesn't exist and causes failures when running the preview
```
Digest: sha256:1c23ced9247b265b0e7b0ef24278a196eafa9463ac65c7d16d2d8b484c94cec3
Status: Downloaded newer image for mesosphere/docs-dev:latest
docker.io/mesosphere/docs-dev:latest
PID TTY           TIME CMD
29209 ttys001    0:00.01 /bin/bash /Users/dkoshkin/src/github.com/mesosphere/konvoy2/tools/docs/hack/preview.sh /Users/dkoshkin/src/github.com/mesosphere/konvoy2/docs/site dkp/konvoy/2.0
> mesosphere-docs@0.0.1 dev /dcos-docs-site
> NODE_ENV=development DEBUG=metalsmith-timer,metalsmith-algolia,metalsmith-layouts,metalsmith-assets node index.js
[metalsmith-watch] ✓ Live reload server started on port: 35729
metalsmith-timer Init +0ms
metalsmith-timer Ignore +58ms
metalsmith-assets pulling files from …
```
=> fix: remove model

pages/dkp/kaptain/1.2.0/custom-configuration/custom-domain-certs/index.md, pages/dkp/kaptain/1.2.0/custom-configuration/external-dex/index.md, pages/dkp/kaptain/1.2.0/custom-configuration/external-spark/index.md, pages/dkp/kaptain/1.2.0/custom-configuration/notebook-servers-configuration/index.md, pages/dkp/kaptain/1.2.0/download/index.md, pages/dkp/kaptain/1.2.0/install/konvoy/index.md, pages/dkp/kaptain/1.2.0/monitoring/index.md, pages/dkp/kaptain/1.2.0/release-notes/1.2.0/index.md, pages/dkp/kaptain/1.2.0/sdk/credentials/index.md, pages/dkp/kaptain/1.2.0/sdk/private-registries/index.md, pages/dkp/kaptain/1.2.0/sdk/quickstart/index.md, pages/dkp/kaptain/1.2.0/version-policy/index.md
No JIRA, this is the 'support review' of the Kaptain 1.2 docs which was accidentally missed out.
However, I did try to address https://jira.d2iq.com/browse/COPS-7003, which documents the inconsistent version requirements in the current docs.
Most of the changes are grammatical. There were a number of broken link references in the new SDK pages, which I fixed.  I also tried to clean up and 'standardize' many of the link references, and make similar pages consistent with each other.  
Outstanding issues:
+ We need to resolve what versions of Konvoy are supported.  Many of the pages in these docs say "at least 1.7.0, but there are other places that only mention 1.8.0.    These should be consistent.
+ The new "Monitoring" page that was added, as well as the existing "Manage Users" and "Manage …
=> Review Kaptain 1.2 docs

Jenkinsfile.cron
Moving to a pipeline branching strategy and we no longer want to rebase
this every night. Instead we'll try handling hotfixes on a case by case
basis. This will allow us to close the PR and delete the `private-beta` branch.
Tried to update the other crons as well but they have not created
release branches for Konvoy2 and Kommander2 yet.
=> Remove cron job for beta branch

pages/dkp/kaptain/1.2.0/sdk/api/index.md, pages/dkp/kaptain/1.2.0/sdk/credentials/index.md, pages/dkp/kaptain/1.2.0/sdk/private-registries/index.md, pages/dkp/kaptain/1.2.0/tutorials/sdk/pytorch/index.md, pages/dkp/kaptain/1.2.0/tutorials/sdk/tensorflow/index.md
Selective sync from the kudo-kubeflow to fix glaring typos and issues with API docs
Notable fixes include wrapped-parameters were formatting poorly, and '2g' vs '2G' for memory resource specifications (former is invalid)
=> Sync doc fixes from kudo-kubeflow

Jenkinsfile.cron
Now that a release branch has been cut for konvoy2, should point the
cron job to it.
When we've merged in the changes for the new branching model, we'll add
a konvoy job for 2.1
=> point konvoy 2.0 cron to release branch

pages/dkp/security-updates/index.md
Closes D2IQ-79191
Now that security scans include kommander as well as konvoy, changing
the title of the security updates page to use DKP rather than Konvoy.
=> fix: change detail of security updates

pages/dkp/kommander/1.2/release-notes/1.2.0/index.md, pages/dkp/kommander/1.2/release-notes/1.2.1/index.md, pages/dkp/kommander/1.2/release-notes/1.2.2/index.md, pages/dkp/kommander/1.3/release-notes/1.3.0/index.md, pages/dkp/kommander/1.3/release-notes/1.3.1/index.md, pages/dkp/kommander/1.3/release-notes/1.3.2/index.md, pages/dkp/kommander/1.3/release-notes/1.3.3/index.md, pages/dkp/kommander/1.3/release-notes/1.3.4/index.md, pages/dkp/kommander/1.4/release-notes/1.4.0/index.md, pages/dkp/kommander/1.4/release-notes/1.4.1/index.md, pages/dkp/kommander/1.4/release-notes/1.4.2/index.md
Also updated the date format for consistency
N/A
Same thing as here:
https://github.com/mesosphere/dcos-docs-site/pull/3814
So, the links here were using:
`/dkp/konvoy/latest/download/`
and
`/dkp/konvoy/latest/install/`
for the links from the Kommander release notes pages.
This worked up until we got to Konvoy 2.x. Now, those pages aren't the same and the links will go to a dead page.
So, I versioned the release note link of Kommander to the applicable version of Konvoy. Because it's kind of a one-off correction, I feel like this is fine, because we don't have to keep on versioning this in the future, as the 2.x release notes of Kommander have also evolved.
Also updated all the dates here to be consistent with recent date formats for releases.
See the [contribution …
=> docs: updating release notes konvoy download link

pages/dkp/kommander/1.2/licensing/index.md, pages/dkp/kommander/1.2/release-notes/1.2.0/index.md, pages/dkp/kommander/1.2/release-notes/1.2.1/index.md, pages/dkp/kommander/1.2/release-notes/1.2.2/index.md, pages/dkp/kommander/1.3/licensing/index.md, pages/dkp/kommander/1.3/release-notes/1.3.0/index.md, pages/dkp/kommander/1.3/release-notes/1.3.1/index.md, pages/dkp/kommander/1.3/release-notes/1.3.2/index.md, pages/dkp/kommander/1.3/release-notes/1.3.3/index.md, pages/dkp/kommander/1.3/release-notes/1.3.4/index.md, pages/dkp/kommander/1.4/licensing/index.md, pages/dkp/kommander/1.4/release-notes/1.4.0/index.md, pages/dkp/kommander/1.4/release-notes/1.4.1/index.md, pages/dkp/kommander/1.4/release-notes/1.4.2/index.md
No ticket
Fix the support portal links for the old Kommander 1.x pages.   Rest of the links fixes should sync from the code repos.
=> Fix support portal links in Komm 1.x docs

layouts/components/content-actions.pug
D2IQ-80923
Feedback button is broken for external customers
Removing that button
=> chore: remove jira link that no longer works

Jenkinsfile.cron
We want this release branch to now be the source of truth for 2.1 konvoy
docs that are on main. Once we publish the 2.1 docs to production, we
shall update this again and use main branch of konvoy for 2.2
=> point 2.1 to main temporarily

s3config.json
Redirects in config to also point to 2.1
Just another spot for here: 
https://github.com/mesosphere/dcos-docs-site/pull/3895
=> fix: making redirects also for 2.1

.github/workflows/vale.yml
We are ignoring most vale warnings at this point but we have to admin
merge if it fails. This should maintain the errors but allow us to
merge. Because these are happening on PRs coming from upstream, we'd
need to change it there anyhow.
=> vale warns but doesnt block

pages/dkp/konvoy/1.8/install/http-proxy/index.md
Add missing autoip ip range in NO_PROXY variable.
https://jira.d2iq.com/browse/COPS-7078
=> fix: add auto-ips ip range to no_proxy variable

pages/dkp/konvoy/1.8/release-notes/1.8.4/index.md
=> Update 1.8.4 RN with correct date

pages/dkp/kommander/2.1/projects/applications/catalog-applications/custom-resources-workspace-catalog/index.md, pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/application-deployment/index.md, pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/index.md
added new folder of use CR in project with workspace catalog
copy-pasted the /application-deployment/index.md from the workspace platform application one and modified.
added a table of supported workspace catalog apps
=> [kommander][2.1.1]feat: ws catalog appd & use CR in project

.github/styles/Vocab/Docs/accept.txt, pages/dkp/kommander/2.1/major-upgrade/upgrade-clusters/migrate-platform-apps/cleanup/index.md
While the changes requested in this ticket had mostly been made already, there were some writing changes that needed to be made for this to be properly ready for customers. That's done now, and the substantive command and output changes verified. Should be a slam dunk. Also had to add "istio" to the list of Vale's accepted terms to get the commit to work.
=> D2IQ-81520: KM2.1 migration cleanup missing a command

.github/styles/Vocab/Docs/accept.txt, pages/dkp/konvoy/2.1/choose-infrastructure/pre-provisioned/define-infrastructure/index.md, pages/dkp/konvoy/2.1/choose-infrastructure/pre-provisioned/self-managed/index.md, pages/dkp/konvoy/2.1/release-notes/index.md
Added some notes for preprovisioning cluster create. Includes: 
- the swapoff deal for centos in release notes (FYI @cmastr - this is resolved in an upcoming release)
- stopping firewalld
- adding a bit about calico nodes pods if they aren't working post-deploy (@dkoshkin - I know there is a way to run --dry-run for this, but I wasn't able to get that to work in a quick timeframe, so I just did an after-the-fact review for this guy)
=> adding notes for preprov challenges

pages/dkp/kommander/2.1/major-upgrade/upgrade-clusters/migrate-platform-apps/cleanup/index.md
taking into account Cneths note
n/a
adding a line that accidentally got erased some where down the way (from Craig's note comment here):
https://github.com/mesosphere/dcos-docs-site/pull/3963/files
=> docs: just cleanup following JCBs edits

.github/styles/Vocab/Docs/accept.txt, pages/dkp/kommander/2.1/projects/applications/catalog-applications/custom-resources-workspace-catalog/zookeeper/index.md, pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/zookeeper-operator/index.md
https://jira.d2iq.com/browse/D2IQ-82302
Adding docs about the zookeeper operator in the workspace catalog.
The original PR was already approved https://github.com/mesosphere/dcos-docs-site/pull/3961 but I had to create a new branch/PR because the new release-2.1.1 branch is based on `main`
=> Add ZooKeeper operator docs (2.1.1)

.github/styles/Vocab/Docs/accept.txt, pages/dkp/kommander/2.1/projects/applications/catalog-applications/custom-resources-workspace-catalog/kafka/index.md, pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/kafka-operator/index.md
https://jira.d2iq.com/browse/D2IQ-82301
Adding docs about the kafka operator in the workspace catalog and kafka cluster deployments in projects.
=> Add Kafka operator docs (2.1.1)

pages/dkp/konvoy/2.1/choose-infrastructure/aws/advanced/prerequisites/index.md, pages/dkp/konvoy/2.1/choose-infrastructure/aws/air-gapped/prerequisites/index.md, pages/dkp/konvoy/2.1/choose-infrastructure/aws/quick-start-aws/index.md, pages/dkp/konvoy/2.1/choose-infrastructure/eks/advanced/prerequisites/index.md, pages/dkp/konvoy/2.1/choose-infrastructure/eks/quick-start/index.md
https://jira.d2iq.com/browse/D2IQ-82104
The information is incorrect, setting `AWS_REGION` will not change the region of the cluster and as of v2.1.1 no longer required to be set by the user.
=> konvoy: remove incorrect information about AWS_REGION env

pages/dkp/kommander/2.1/reference/dispatch/index.md, pages/dkp/kommander/2.1/reference/dispatch/v1alpha2/index.md, pages/dkp/kommander/2.1/reference/kommander/v1beta1/index.md, pages/dkp/kommander/2.2/reference/dispatch/index.md, pages/dkp/kommander/2.2/reference/dispatch/v1alpha2/index.md, pages/dkp/kommander/2.2/reference/kommander/v1beta1/index.md
Just keeping kommander 2.2 docs in sync with docs-site for 2.2 feature development.
=> docs: add generated kommander api docs in references for 2.2

pages/dkp/kommander/2.1/reference/dispatch/index.md, pages/dkp/kommander/2.1/reference/dispatch/v1alpha2/index.md, pages/dkp/kommander/2.1/reference/kommander/v1beta1/index.md
Add docs for aws licensing changes in 2.1 production docs page.
=> docs: add generated kommander api docs in references for 2.1

pages/dkp/konvoy/2.0/choose_infrastructure/pre-provisioned/define-infrastructure/index.md, pages/dkp/konvoy/2.1/choose-infrastructure/pre-provisioned/define-infrastructure/index.md
Adding a missing label reported in https://mesosphere.slack.com/archives/C02MR1P7286/p1641919879062300.
Based it on `main` because this is a bug in existing docs, but let me know if I should PR it somewhere else.
=> fix: missing PreprovisionedInventory label for md

pages/dkp/kommander/1.2/backup-and-restore/index.md, pages/dkp/kommander/1.3/backup-and-restore/index.md, pages/dkp/kommander/1.4/backup-and-restore/index.md
n/a
There is no backup topic for konvoy 2.1 right now - and Kommander 1.4 is not compatible with dkp 2.x.
So, tying the version for backup to the version that Kommander is compatible with on Konvoy. 
=> docs: fixing link to be tied to konvoy 1.8

pages/dkp/kommander/2.1/install/air-gapped/index.md
=> fix: aws vpc labels for traefik during bootstrap

pages/dkp/kommander/1.2/uninstall/index.md, pages/dkp/kommander/1.3/uninstall/index.md, pages/dkp/kommander/1.4/uninstall/index.md
n/a
In doing some research for uninstalling - I noticed these links need to be updated on the Kommander pages for uninstalling - one points to a different version of Konvoy that is not correct. And then the most recent points to `/latest/`, which isn't valid anymore.
=> docs: editing links for kommander uninstall

pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/dkp-applications/spark-operator/index.md
Fix link reference, taken from https://github.com/mesosphere/dcos-docs-site/pull/4037#discussion_r784328556.
=> fix: Update link in spark install instructions 

pages/dkp/kommander/2.1/workspaces/applications/catalog-applications/dkp-applications/spark-operator/index.md, pages/dkp/kommander/2.2/projects/applications/catalog-applications/dkp-applications/custom-resources-workspace-catalog/kafka/index.md, pages/dkp/kommander/2.2/projects/applications/catalog-applications/dkp-applications/custom-resources-workspace-catalog/spark/index.md, pages/dkp/kommander/2.2/projects/applications/catalog-applications/dkp-applications/custom-resources-workspace-catalog/zookeeper/index.md, pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/dkp-applications/kafka-operator/index.md, pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/dkp-applications/spark-operator/index.md, pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/dkp-applications/zookeeper-operator/index.md
Copying the changes made for 2.1 in https://github.com/mesosphere/dcos-docs-site/pull/4016/files to 2.2. I also fixed some bad links.
=> docs: copy operator installation notes from 2.1 to 2.2

pages/dkp/konvoy/2.2/choose-infrastructure/awsgovcloud/clusterconfig/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/awsgovcloud/clustercontrol/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/awsgovcloud/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/awsgovcloud/prerequisites/index.md
https://jira.d2iq.com/browse/D2IQ-83671
=> [Konvoy 2.2] Air-gapped AWS GovCloud doc migration from 2.1->2.2

pages/dkp/konvoy/2.1/choose-infrastructure/awsgovcloud/clusterconfig/index.md
n/a
Backticks showing up in the p tags in the docs for this one page
=> fix: backticks in the old p tags

pages/dkp/konvoy/2.2/choose-infrastructure/awsgovcloud/clusterconfig/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/awsgovcloud/prerequisites/index.md
n/a
There were some backticks that were showing in the p tags, so just cleaning that up.
=> fix: linting and styles in p tags in docs

pages/dkp/kommander/2.1/release-notes/2.1.1/index.md
https://jira.d2iq.com/browse/D2IQ-80341
Adding a guide to 2.1.1 release note about a workaround towards broken certificates/kube-oidc-proxy. kommander-traefik cert is broken too and also included in the guide.
=> docs: workaround for kube-oidc-proxy 2.1.1

config.json
We don't have the right commands for in the AKS
and EKS replace node topics
[D2IQ-83967](https://jira.d2iq.com/browse/D2IQ-83967)
Hiding this page for now until we can correct the language
=> chore: hiding replace node for now to update

pages/dkp/kommander/2.2/install/air-gapped/index.md
https://jira.d2iq.com/browse/D2IQ-83643
This PR adds steps to the airgap kommander installation to include downloading/installing the DKP catalog application chart bundle. 
I only included how to upload the charts during the installation. It can also be done post installation using the [upload command](https://dev-docs.d2iq.com/dkp/kommander/2.2/install/air-gapped/#kommanders-internal-helm-repository)
=> docs: Add catalog application chart bundle to install instructions

pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/preprovisioned/index.md
https://jira.d2iq.com/browse/COPS-7150
Documenting a workaround for this bug, until a proper fix can be worked on/released.
=> konvoy: document race condition for pre-provisioned adoption

pages/dkp/konvoy/2.1/choose-infrastructure/pre-provisioned/self-managed/index.md
n/a
The get kubeconfig command is on the previous topic, **but** only for under one dkp create path.
This note is to catch every other user that would need the kubeconfig for future steps.
=> docs: adding get kubeconfig on preprov docs

pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/self-managed/index.md
n/a
The get kubeconfig command is on the previous topic, **but** only for under one dkp create path.
This note is to catch every other user that would need the kubeconfig for future steps.
Backport of this ticket: https://github.com/mesosphere/dcos-docs-site/pull/4076
=> docs: updating to show how to retrieve kubeconfig

pages/dkp/kommander/2.2/index.md, pages/dkp/konvoy/2.2/index.md
n/a
Nav and version need to be updated to 2.2 for develop for kommander and konvoy. This should do the trick.
Checked locally and that's good.
=> chore: updating version for 2.2

pages/dkp/konvoy/2.2/deployments/deploy-sample-app/index.md, pages/dkp/konvoy/2.2/deployments/index.md
[D2IQ-78964](https://jira.d2iq.com/browse/D2IQ-78964)
This is the backport of this one: 
https://github.com/mesosphere/dcos-docs-site/pull/4083
Bringing over the Deploy Sample Workload topic to the 2.2 docs.
=> docs: adding deploy sample workloads to 22 docs

package.json
n/a
Docs site was not building w/Jenkins.
This could be the issue.
=> fix: metalsmith staying at 2.3.0

pages/dkp/kommander/2.1/install/air-gapped/index.md
Installing MetalLB is much simpler than described and can actually be
accomplished by simply editing the installation configuration file.
http://docs-d2iq-com-pr-4087.s3-website-us-west-2.amazonaws.com/
https://jira.d2iq.com/browse/COPS-7141
=> fix: MetalLB documentation for air-gapped install

pages/dkp/kommander/2.1/networking/load-balancing/index.md
[](https://jira.d2iq.com/browse/COPS-7161)
Unclear how to deploy metallb to attached clusters - added a few lines to the existing metallb docs to add the namespace field (which is needed anyways) which is set to workspace namespace, and that this allows you to deploy metallb to attached clusters.
=> docs: Clarify metallb config can be deployed to attached clusters

pages/dkp/kommander/2.1/clusters/tunnel-cli/index.md
http://docs-d2iq-com-pr-4095.s3-website-us-west-2.amazonaws.com/
https://jira.d2iq.com/browse/COPS-7160
We changed the kubefed namespace from `kommander` to `kube-federation-system` in 2.1 which resulted in a few outdated commands.
=> docs: Fix kubefed ns

pages/dkp/konvoy/1.6/monitoring/index.md, pages/dkp/konvoy/1.7/monitoring/index.md, pages/dkp/konvoy/1.8/monitoring/index.md
https://jira.d2iq.com/browse/COPS-7071
Fix 1.x monitoring docs to use cm for importing custom grafana dashboards
=> docs: Use cm import custom grafana dashboards

pages/dkp/kommander/2.2/clusters/tunnel-cli/index.md
https://jira.d2iq.com/browse/COPS-7159
This updates the location of the kommander CA secret. This was changed in Kommander 2.1.
=> (kommander 2.2) Fix kommander CA secret name in kubetunnel docs

pages/dkp/kommander/2.1/clusters/tunnel-cli/index.md
https://jira.d2iq.com/browse/COPS-7159
This updates the location of the kommander CA secret. This was changed in Kommander 2.1.
=> (kommander 2.1) Fix kommander CA secret name in kubetunnel docs

pages/dkp/kommander/2.2/networking/load-balancing/index.md
Port https://github.com/mesosphere/dcos-docs-site/pull/4092 to 2.2
=> [2.2] docs: Clarify metallb config can be deployed to attached clusters

pages/dkp/kaptain/1.3.0/download/index.md
[jira.d2iq.com/browse/D2IQ-82306](https://jira.d2iq.com/browse/D2IQ-82306)
Add the AWS download instructions for Kaptain. This needs to go against Main because we're going to publish kaptain on AWS in the next few days. I believe this change will then need to be added to the kudo-kubeflow repo so that we don't lose it going forward. I don't believe it needs to go into the develop branch because AIUI Kaptain docs are not published from there.
- [ X ] Test all commands and procedures, if applicable.
- [ X ] Create new PRs against `develop`, or `main` for hotfixes to production.
=> Add AWS download instructions for Kaptain in Main

pages/dkp/kommander/2.1/security/policy-controls/gatekeeper/index.md, pages/dkp/kommander/2.1/security/policy-controls/index.md
http://docs-d2iq-com-pr-4104.s3-website-us-west-2.amazonaws.com/
https://jira.d2iq.com/browse/D2IQ-78966
Moving the gatekeeper doc from konvoy 1.8 to kommander 2.1. Changed the deploying Gatekeeper part to a link to docs about enabling gatekeeper.
Once this looks good, will open up another PR for 2.2
=> docs: policy control doc

pages/dkp/kommander/2.2/security/policy-controls/gatekeeper/index.md, pages/dkp/kommander/2.2/security/policy-controls/index.md
http://docs-d2iq-com-pr-4112.s3-website-us-west-2.amazonaws.com/
https://jira.d2iq.com/browse/D2IQ-78966
policy control / gatekeeper docs for 2.2
=> docs: gatekeeper for 2.2

pages/dkp/konvoy/2.1/supported-operating-systems/index.md
n/a
This came up in Konv standup - 
As we support the default configuration for Azure builds, this should be added to this grid.
FYI @JohnB64-JBV 
=> docs: adding azure to supported OS grid

pages/dkp/kommander/2.1/backup-and-restore/index.md, pages/dkp/kommander/2.2/backup-and-restore/index.md
n/a
There were some edits needed to update for DKP 2.1, like removing kubeaddons and konvoy commands, just stuff like that.
http://docs-d2iq-com-pr-4120.s3-website-us-west-2.amazonaws.com/
=> Edits to velero to update for dkp 2.1

pages/dkp/konvoy/1.8/install/install-vsphere/index.md, pages/dkp/konvoy/1.8/release-notes/1.8.4/index.md
Jira ticket: https://jira.d2iq.com/browse/D2IQ-84533
Added note: 
-  vSphere provisioning in an air-gapped environment is not supported in this version; however, we will add this functionality to a future release. Refer to the most current release documentation for more information.
Removed note from vSphere install page.
=> [Konvoy] vSphere notes for v1.8.4

pages/dkp/konvoy/2.0/choose_infrastructure/aws/advanced/update/control-plane/index.md, pages/dkp/konvoy/2.1/choose-infrastructure/aws/advanced/update/control-plane/index.md
https://jira.d2iq.com/browse/COPS-7075
Replaced the third command in section 4 of this page: https://docs.d2iq.com/dkp/konvoy/2.0/choose_infrastructure/aws/advanced/update/control-plane/ for MacOS users in both Konvoy 2.0 and 2.1.
=> [COPS-7075] dkp2 docs 1 export cmd not applicable for MacOS

pages/dkp/konvoy/1.8/install/supported-operating-systems/index.md
https://jira.d2iq.com/browse/D2IQ-84284
Removed CentOS 8 support information on Supported OS page w/in Konvoy.
=> [Konvoy] CentOS 8 EOL, update docs

pages/dkp/kommander/2.2/release-notes/index.md
https://jira.d2iq.com/browse/D2IQ-84943
Copied RN of 2.1 to 2.2 and added info on support for k8s 1.22
Replaced Konvoy/Kommander mentions with DKP, when possible
http://docs-d2iq-com-pr-4130.s3-website-us-west-2.amazonaws.com/
=> Upgrade RN for Kommander 2.2 including scope for k8s 1.22

pages/dkp/kommander/2.1/install/air-gapped/index.md, pages/dkp/kommander/2.1/install/networked/index.md, pages/dkp/kommander/2.1/operations/identity-providers/index.md, pages/dkp/kommander/2.1/release-notes/2.1.1/index.md, pages/dkp/kommander/2.2/install/networked/index.md
n/a
I didn't know this kommander open dashboard command was a thing.
Totally worth adding this in the docs, methinks
http://docs-d2iq-com-pr-4134.s3-website-us-west-2.amazonaws.com/
=> docs: adding kommander open dashboard command

pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/aws/index.md
[D2IQ-85275](https://jira.d2iq.com/browse/D2IQ-85275)
Telling users they have to use a specific version of KIB, lest this breaks
http://docs-d2iq-com-pr-4135.s3-website-us-west-2.amazonaws.com/
=> docs: telling users KIB version for major upgrade

.github/styles/Vocab/Docs/accept.txt, pages/dkp/konvoy/1.8/autoscaling/index.md, pages/dkp/konvoy/1.8/gpu/index.md, pages/dkp/konvoy/1.8/install/install-airgapped/index.md, pages/dkp/konvoy/1.8/upgrade/upgrade-cli/index.md, pages/dkp/konvoy/2.1/major-version-upgrade/index.md, pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/aws/index.md
N/A
This was mainly upgrading the version for the Konvoy CLI upgrade path.
It looks like there's a lot of changes, but that's mostly linting on the pages I touched.
http://docs-d2iq-com-pr-4137.s3-website-us-west-2.amazonaws.com/
=> docs: updating cli upgrade versions and linting

pages/dkp/kommander/2.2/install/air-gapped/index.md
http://docs-d2iq-com-pr-4131.s3-website-us-west-2.amazonaws.com/
=> Update kommander air-gapped installation docs to use new airgapped flag

pages/dkp/konvoy/2.1/choose-infrastructure/pre-provisioned/define-control-plane-endpoint/index.md, pages/dkp/konvoy/2.1/choose-infrastructure/pre-provisioned/define-infrastructure/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/define-control-plane-endpoint/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/define-infrastructure/index.md
https://jira.d2iq.com/browse/COPS-7169
The difficulties documented in COPS-7169 may have been avoided if it had been clearer to the end user that the number of nodes specified in the preprovisioned inventory file does not control how many CP nodes Konvoy will try to use.
Additionally, the docs are not very clear about the fact that you cannot currently upgrade clusters with single node control planes.
http://docs-d2iq-com-pr-4133.s3-website-us-west-2.amazonaws.com/
=> Add some clarifications about control pre-provisioned CP nodes

pages/dkp/kommander/2.1/release-notes/2.1.0/index.md
https://jira.d2iq.com/browse/D2IQ-84968
Documents workaround for custom SSL certificate validation failure of managed cluster in the Kommander 2.1.0 release notes. Needs porting to 2.1.1 release notes as well.
=> docs: documents custom cert federation workaround

pages/dkp/kommander/2.1/release-notes/2.1.1/index.md
https://jira.d2iq.com/browse/D2IQ-84968
Backport minus first sentence. We agreed to remove it in https://github.com/mesosphere/dcos-docs-site/pull/4138.
http://docs-d2iq-com-pr-4142.s3-website-us-west-2.amazonaws.com/
=> backport 2.1.1: documents custom cert federation workaround

pages/dkp/kommander/2.1/release-notes/2.1.1/index.md
N/A
We tell users to create this yaml file and then apply and patch this stuff, but we don't tell them to set the WORKSPACE_NAMESPACE - 
SO, this fix won't work unless we tell the user to do this thing.
http://docs-d2iq-com-pr-4147.s3-website-us-west-2.amazonaws.com/
=> docs: adding export workspace to release notes

config.json
Change the config json beta branch settings so that when we merge main
into beta, we will only show 2.2 stuff for Konvoy
=> prepare beta to only show konvoy

pages/dkp/konvoy/2.1/choose-infrastructure/pre-provisioned/create-cluster/index.md, pages/dkp/konvoy/2.1/choose-infrastructure/pre-provisioned/self-managed/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/create-cluster/index.md
makes more sense to be here rather than on the
self manage section
also what if someone does not want to make the
cluster self managed
n/a
This was brought to our attention - where this would make most sense to be on the create page.
Also, I added this as a link to the other different flavors of preprov create, because there are many flavors, and don't want it to get missed by users creating these diff types of clusters.
http://docs-d2iq-com-pr-4153.s3-website-us-west-2.amazonaws.com/
=> docs: changing calico issue to create

pages/dkp/kaptain/1.3.0/install/konvoy-dkp/index.md
port this fix from kaptain docs to live docs: https://github.com/mesosphere/kudo-kubeflow/pull/657
https://jira.d2iq.com/browse/COPS-6863
http://docs-d2iq-com-pr-4155.s3-website-us-west-2.amazonaws.com/
=> docs: add reference to dkp gpu docs in kaptain install docs

pages/dkp/konvoy/2.1/choose-infrastructure/aws/advanced/new/index.md
http://docs-d2iq-com-pr-4151.s3-website-us-west-2.amazonaws.com/dkp/konvoy/2.1/choose-infrastructure/aws/advanced/new/
=> [docs] - removed repeated export cluster name command

pages/dkp/konvoy/2.1/troubleshooting/generate-a-support-bundle/index.md, pages/dkp/konvoy/2.2/troubleshooting/generate-a-support-bundle/index.md
Update download URL of the dkp-diagnose CLI to the latest version, v0.4.1.
http://docs-d2iq-com-pr-4156.s3-website-us-west-2.amazonaws.com/
=> Konvoy 2.1: Update dkp-diagnose download URL from v0.3.2 to v0.4.1

pages/dkp/kommander/2.0/install/networked/index.md, pages/dkp/kommander/2.1/install/networked/index.md, pages/dkp/kommander/2.2/install/networked/index.md
Jira: https://jira.d2iq.com/browse/COPS-7039?filter=57924
Redo: Customers are overlooking that kubectl configuration must point to the correct cluster before running the install command. Goal here is to provide with alternatives on how to install Kommander on the correct cluster (and not accidentally installing it on bootstrap cluster).
Preview
http://docs-d2iq-com-pr-4150.s3-website-us-west-2.amazonaws.com/
=> Redo: Kommander Installation

pages/dkp/konvoy/2.1/choose-infrastructure/aws/advanced/prerequisites/index.md, pages/dkp/konvoy/2.1/choose-infrastructure/aws/quick-start-aws/index.md, pages/dkp/konvoy/2.1/choose-infrastructure/azure/advanced/prerequisites/index.md, pages/dkp/konvoy/2.1/choose-infrastructure/azure/quick-start-azure/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/aws/advanced/prerequisites/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/aws/quick-start-aws/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/azure/advanced/prerequisites/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/azure/quick-start-azure/index.md
Not a fix, per se, but definitely addresses some concerns @fatz brought up here:
[D2IQ-84974](https://jira.d2iq.com/browse/D2IQ-84974)
[D2IQ-84973](https://jira.d2iq.com/browse/D2IQ-84973)
Adding a note to say what OS image is being used and what all is included in the defaults when doing quickstart.
http://docs-d2iq-com-pr-4146.s3-website-us-west-2.amazonaws.com/
=> docs: adding default for azure and aws

pages/dkp/konvoy/2.1/storage/static-local-volume/index.md, pages/dkp/konvoy/2.2/storage/static-local-volume/index.md
Closes D2IQ-78946
We'd like to transfer the information found here [Provision a static local volume](https://docs.d2iq.com/dkp/konvoy/1.8/storage/static-local-volume/)
into 2.1/2.2 docs.
There may be some updates here requested by the Konvoy team, and we can collaborate on this PR to make those changes. 
https://jira.d2iq.com/browse/D2IQ-78946
http://docs-d2iq-com-pr-4163.s3-website-us-west-2.amazonaws.com/
=> docs: provision a static local volume

pages/dkp/konvoy/2.2/choose-infrastructure/aws/advanced/new/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/awsgovcloud/clusterconfig/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/azure/advanced/new/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/eks/advanced/new/index.md
When using kubectl apply, the whole ConfigMap will be stuffed into an annotation thats too long.
http://docs-d2iq-com-pr-4179.s3-website-us-west-2.amazonaws.com/
=> konvoy: use kubectl create because of large ConfigMaps

pages/dkp/kommander/2.0/monitoring/index.md, pages/dkp/kommander/2.2/monitoring/index.md
This updates kommander 2.2 docs to reflect changes from https://github.com/mesosphere/kommander-applications/pull/237.
http://docs-d2iq-com-pr-4181.s3-website-us-west-2.amazonaws.com/
=> [kommander] Update service monitor selector label for 2.2

pages/dkp/konvoy/2.1/storage/static-local-volume/index.md, pages/dkp/konvoy/2.2/storage/static-local-volume/index.md
Following up on this edit. Deepak advised:
> There is no more konvoy or kommander cluster. They all are DKP clusters. 
http://docs-d2iq-com-pr-4190.s3-website-us-west-2.amazonaws.com/
=> docs: rename konvoy cluster to dkp

pages/dkp/kommander/2.2/operations/access-control/rbac/index.md
https://jira.d2iq.com/browse/D2IQ-84281
I made a change in kommander applications: https://github.com/mesosphere/kommander-applications/pull/239/files#r828297086 
To the user, the names of the clusterroles of centralized grafana are changed, but the expected behavior of these roles remain the same.
http://docs-d2iq-com-pr-4180.s3-website-us-west-2.amazonaws.com/
=> docs: updated centralized grafana clusterrole name

pages/dkp/konvoy/2.2/release-notes/index.md
https://jira.d2iq.com/browse/D2IQ-82128
Document flag `--with-aws-bootstrap-credentials` default change in the next release
=> konvoy: document flag's default change in the next release

pages/dkp/kommander/2.2/install/air-gapped/index.md
JIRA: https://jira.d2iq.com/browse/D2IQ-86447
We've restructured some commands in the kommnader-cli and the `helmmirror` subcommands were moved to other places.
=> chore: update airgapped kommander install commands

ci/update-dkp-cli-docs.sh
The script that automatically generates the help pages for the CLI didn't remove pages for commands removed from the CLI. This PR fixes that.
=> fix: automated CLI docs didn't remove pages for removed commands

pages/dkp/kommander/2.2/clusters/attach-cluster/manually-attach-cluster/index.md, pages/dkp/kommander/2.2/clusters/index.md
Adding the new `Unattached` status to the Cluster status table and a new page with instructions on how to manually attach a cluster that was manually created with the DKP CLI. 
There is a feature in 2.3 that will auto-attach these clusters and these docs will become obsolete then, but for 2.2 we want to provide a way to resolve the "Unattached" status correctly.
[D2IQ-86493](https://jira.d2iq.com/browse/D2IQ-86493)
http://docs-d2iq-com-pr-4202.s3-website-us-west-2.amazonaws.com/
=> D2IQ-86493 feat: manually attach cluster

pages/dkp/konvoy/2.1/choose-infrastructure/verify-installation/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/verify-installation/index.md
[D2IQ-78913](https://jira.d2iq.com/browse/D2IQ-78913)
Adding some commands for a similar function for the previous app's take on `konvoy check`
http://docs-d2iq-com-pr-4199.s3-website-us-west-2.amazonaws.com/
=> docs: adding verify konv install topic

layouts/partials/content.pug, scss/shortcodes/_badge.scss, shortcodes/index.js
Created a new badge button style for tech previews. The badge should be filled with a medium grey color with dark text that says "TECH PREVIEW". 
Cleaned up some old comments in the code and prettier formatted the spacing on the badge style. I noticed there are some scss files with 2 spaces and some files with 4 spaces.
http://docs-d2iq-com-pr-4209.s3-website-us-west-2.amazonaws.com/
=> feat: new badge style for tech previews

pages/dkp/kommander/2.2/install/air-gapped/catalog/index.md, pages/dkp/kommander/2.2/install/air-gapped/index.md
The airgap bundles have been moved to a new path to be more consistent. This will be reflected after Kommander RC2 is released.
=> docs: Update airgap bundle URLs

pages/dkp/kommander/2.2/dkp-upgrade/custom-apps/index.md
No Jira for this one, just a short additional info for operators/users/customers.
Since we want customers to upgrade ALL apps (Platform, Catalog, Custom) before upgrading Konvoy (because of breaking changes due to K8s 1.22), we wanted to make sure they are aware of the consequences. This will be linked in the general DKP Upgrade doc. 
http://docs-d2iq-com-pr-4215.s3-website-us-west-2.amazonaws.com/
=> Short upgrade info on Custom Apps

pages/dkp/kommander/2.2/clusters/attach-cluster/cluster-with-network-restrictions/index.md
the existing example command was no longer accurate. The one from the
tunnel-cli docs was correct. I updated the UI example to match the cli
documentation.
At somepoint we may want to reconsider have 2 pages to document connecting a cluster with a tunnel, one for cli and one for UI. this is confusing and prone to get out of sync.
http://docs-d2iq-com-pr-4235.s3-website-us-west-2.amazonaws.com/dkp/kommander/2.2/clusters/attach-cluster/cluster-with-network-restrictions/
=> fix: align ca cert example for kubetunnel

pages/dkp/konvoy/2.2/image-builder/create-azure-image/index.md
https://jira.d2iq.com/browse/D2IQ-85257
Adds initial documentation for building azure images in KIB. Based on the exising AWS doc, just updated for azure specific info.
http://docs-d2iq-com-pr-4203.s3-website-us-west-2.amazonaws.com/
=> feat(konvoy): add image builder azure docs

pages/dkp/kommander/2.2/install/configuration/custom-domain/index.md
https://jira.d2iq.com/browse/D2IQ-86818
Removes limitation that we are fixing right now around the use of ACME on managed clusters. 
=> docs: removes note on an outdated limitation

pages/dkp/kommander/2.2/dkp-upgrade/upgrade-kommander/index.md, pages/dkp/kommander/2.2/install/air-gapped/catalog/index.md, pages/dkp/kommander/2.2/install/air-gapped/index.md, pages/dkp/kommander/2.2/install/configuration/enterprise-catalog/index.md
This PR adds some additional information about upgrading with catalog applications installed and also updates some configuration steps to download a new git repo archive that will be available in 2.2.
=> docs: Add info about DKP catalog apps git repo archive

pages/dkp/kommander/2.2/gpu/kommander-config/index.md, pages/dkp/kommander/2.2/install/air-gapped/catalog/index.md, pages/dkp/kommander/2.2/install/air-gapped/index.md, pages/dkp/kommander/2.2/install/configuration/custom-domain/index.md, pages/dkp/kommander/2.2/install/configuration/enterprise-catalog/index.md, pages/dkp/kommander/2.2/install/configuration/http-proxy/index.md, pages/dkp/kommander/2.2/install/configuration/index.md, pages/dkp/kommander/2.2/install/networked/index.md
n/a
in 2.2 and above, there is no longer a dedicated kommander-cli - this has all been folded into the DKP cli. Therefore, these commands in the documentation need to be updated as well.
http://docs-d2iq-com-pr-4252.s3-website-us-west-2.amazonaws.com/
=> docs: replacing kommander cli with dkp

pages/dkp/konvoy/2.2/release-notes/index.md
https://jira.d2iq.com/browse/D2IQ-78060
http://docs-d2iq-com-pr-4213.s3-website-us-west-2.amazonaws.com/
=> Konvoy 2.2 Release Note: Default update strategy changed to "delete first" for Preprovisioned clusters

pages/dkp/kommander/2.2/dkp-upgrade/upgrade-kommander/index.md
No Jira, just reminding customers to back up their environment prior to upgrade. Please check if the page I linked is valid here, not sure.
PS: I added the exact same note to Konvoy upgrade docs in this PR: 
https://github.com/mesosphere/dcos-docs-site/pull/4230
http://docs-d2iq-com-pr-4255.s3-website-us-west-2.amazonaws.com/
=> users must back up prior to upgrading

pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/metal-lb/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/metal-lb/index.md
https://jira.d2iq.com/browse/D2IQ-86750
New MetalLB config page for pre-provisioned
http://docs-d2iq-com-pr-4269.s3-website-us-west-2.amazonaws.com/
=> [Konvoy 2.2] Document any manual steps needed for metallb configuration

pages/dkp/kommander/2.2/dkp-upgrade/upgrade-kommander/index.md
Some links were directing to a page/topic instead of directing to a specific heading/sections.  
http://docs-d2iq-com-pr-4275.s3-website-us-west-2.amazonaws.com/
=> Fixing some links to direct to specific headers

pages/dkp/kommander/2.2/clusters/attach-cluster/attach-eks-cluster/index.md, pages/dkp/kommander/2.2/clusters/attach-cluster/cluster-no-network-restrictions/index.md, pages/dkp/kommander/2.2/clusters/attach-cluster/cluster-with-network-restrictions/index.md, pages/dkp/kommander/2.2/clusters/attach-cluster/index.md, pages/dkp/kommander/2.2/logging/enable-logging/enable-logging-via-ui/index.md, pages/dkp/kommander/2.2/projects/applications/catalog-applications/custom-applications/deploy-custom-app/index.md, pages/dkp/kommander/2.2/projects/applications/catalog-applications/index.md, pages/dkp/kommander/2.2/projects/applications/platform-applications/application-deployment/index.md, pages/dkp/kommander/2.2/projects/applications/platform-applications/index.md, pages/dkp/kommander/2.2/projects/project-configmaps/index.md, pages/dkp/kommander/2.2/projects/project-deployments/continuous-delivery/index.md, pages/dkp/kommander/2.2/projects/project-deployments/view-helm-releases/index.md, pages/dkp/kommander/2.2/projects/project-network-policies/index.md, pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/application-deployment/index.md, pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/custom-applications/deploy-custom-app/index.md, pages/dkp/kommander/2.2/workspaces/applications/platform-applications/application-deployment/index.md, pages/dkp/kommander/2.2/workspaces/applications/platform-applications/index.md
https://jira.d2iq.com/browse/D2IQ-86815
https://jira.d2iq.com/browse/D2IQ-87258
The wording has now changed in the UI so that you "Enable" an application, rather than "Deploy". We need to update the docs to reflect this change. 
I've also updated some of the instructions to make them a little bit clearer.
http://docs-d2iq-com-pr-4274.s3-website-us-west-2.amazonaws.com/
=> Replace mentions of "Deploy" with "Enable" to reflect UI changes

pages/dkp/kommander/2.2/dkp-upgrade/upgrade-kommander/index.md
https://jira.d2iq.com/browse/D2IQ-86748
Added workaround for MetalLB detachment for users who setup MetalLB prior to 2.2.
http://docs-d2iq-com-pr-4279.s3-website-us-west-2.amazonaws.com/
=> [Kommander 2.2] Provide instructions to detach < 2.2 metallb from kommander

pages/dkp/kommander/2.2/workspaces/applications/platform-applications/application-deployment/index.md, pages/dkp/kommander/2.2/workspaces/applications/platform-applications/index.md
Start in 2.2, MetalLB is planned to be moved out of Kommander. This PR removes some references to MetalLB and replaces one of the examples with istio. 
There are still a lot of remaining MetalLB docs that need to be removed or moved to the Konvoy documentation but I don't think any MetalLB documentation for konvoy exists yet so I didn't remove them in this PR. 
=> docs: replace metallb with istio in the WS config override example

pages/dkp/konvoy/2.1/choose-infrastructure/aks/aks-quickstart/index.md, pages/dkp/konvoy/2.1/choose-infrastructure/azure/advanced/prerequisites/index.md, pages/dkp/konvoy/2.1/choose-infrastructure/azure/quick-start-azure/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/aks/aks-quickstart/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/azure/advanced/prerequisites/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/azure/quick-start-azure/index.md, pages/dkp/konvoy/2.2/image-builder/create-azure-image/index.md
No ticket, see Slack discussion here:  https://mesosphere.slack.com/archives/CR8GEL5TL/p1649266430322719
The Azure CLI was updated yesterday (5-April-2022) with a breaking change that requires that the --scopes parameter always be specified when creating a service principal.  Previously it was inferred from your subscription if you did not specify it.   All of our Azure login examples in 2.1 and 2.2 were depending on the old behavior, and thus don't work if you try to copy paste them.
I also fixed up the outputs to match the current azure CLI behavior.
http://docs-d2iq-com-pr-4283.s3-website-us-west-2.amazonaws.com/
See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/mai …
=> Update azure SP examples to include parameters required with latest azure CLI

pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/air-gapped/explore/index.md
[](https://jira.d2iq.com/browse/D2IQ-87168)
Realized that I did not copy the new StorageClass procedure to the air-gapped workflow in PR 4243, so doing that now.
http://docs-d2iq-com-pr-4285.s3-website-us-west-2.amazonaws.com/
=> [DOC][Konvoy 2.2] vSphere - added new StorageClass procedure to the air-gapped workflow

pages/dkp/kommander/2.1/install/air-gapped/index.md
ran into some small errors in 2.1.1 airgapped docs while running through the docs
=> docs: A few fixes for 2.1.1 airgapped docs

pages/dkp/konvoy/2.2/supported-operating-systems/index.md
3033.2.0 is the LTS version of flatcar and what I have tested with. 
=>  fix: put correct version of flatcar that we support

pages/dkp/kommander/2.2/dkp-upgrade/upgrade-kommander/index.md, pages/dkp/kommander/2.2/dkp-upgrade/upgrade-konvoy/enterprise/index.md, pages/dkp/kommander/2.2/dkp-upgrade/upgrade-konvoy/essential/index.md, pages/dkp/konvoy/2.2/dkp-upgrade/upgrade-kommander/index.md, pages/dkp/konvoy/2.2/dkp-upgrade/upgrade-konvoy/enterprise/index.md, pages/dkp/konvoy/2.2/dkp-upgrade/upgrade-konvoy/essential/index.md
https://jira.d2iq.com/browse/D2IQ-87506
- Fixed lack of sequential numbering in Detaching MetalLB section of Kommander Upgrade doc
- Removed single step numbering in both Enterprise/Essential upgrade docs in both Konvoy and Kommander repos
http://docs-d2iq-com-pr-4294.s3-website-us-west-2.amazonaws.com/
=> [DKP 2.2] Fix Numbering in Kommander/Konvoy Upgrade Docs

pages/dkp/konvoy/2.2/choose-infrastructure/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/air-gapped/bootstrap/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/air-gapped/create-bastion-vm/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/explore/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/metal-lb/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/new/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/nodepools/create/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/replace-node/index.md
(https://jira.d2iq.com/browse/D2IQ-87508)
Craig noted in a Slack DM that I needed to remove the bullet point about checksum.txt from the "Create a Bastion VM Host" topic in Choose infrastructure --> vSphere --> Air-gapped, and I forgot to do it as part of the larger PR. Done now.
http://docs-d2iq-com-pr-4296.s3-website-us-west-2.amazonaws.com/
=> [DOC][Konvoy 2.2] vSphere - removed checksum.txt from download list

pages/dkp/kommander/2.2/release-notes/2.2.0/index.md, pages/dkp/konvoy/2.2/release-notes/index.md
No JIRA
- Changed MetalLB version in DKP RN from 0.12.2 -> 0.12.1 since 12.2 is imaginary
=> [DKP 2.2] MetalLB version update + minor spacing tweaks

pages/dkp/kommander/2.2/download/index.md, pages/dkp/konvoy/2.2/download/index.md
n/a
Fixing links in the konvoy download page to point to Kommander.
some minor nit to just make the two download pages the same, too.
http://docs-d2iq-com-pr-4299.s3-website-us-west-2.amazonaws.com/
=> docs: updating links for konv download page

pages/dkp/kommander/2.0/clusters/applications/index.md, pages/dkp/kommander/2.0/clusters/management-cluster/index.md, pages/dkp/kommander/2.1/clusters/applications/index.md, pages/dkp/kommander/2.1/clusters/management-cluster/index.md, pages/dkp/kommander/2.2/clusters/applications/index.md, pages/dkp/kommander/2.2/clusters/management-cluster/index.md
n/a
This page didn't have an excerpt and is just pulling the rest of the content from the page, looking weird in the UI on the parent page in the cards at the bottom.
also had a broken link in there.
=> docs: fix excerpts and links for cluster mgmt

config.json, index.js, s3config.json
No JIRA for this. 
http://docs-d2iq-com-pr-4266.s3-website-us-west-2.amazonaws.com/
=> removing hiding of 2.2 for GA

pages/dkp/kommander/2.2/clusters/attach-cluster/requirements-for-attaching/index.md, pages/dkp/kommander/2.2/release-notes/2.2.0/index.md
Added a note to mention about attaching clusters that has cert-manager installed. This is a known issue since 2.1 and it is not as harmful as it looks on the surface.
=> docs: note attaching cluster with cert-manager

pages/dkp/kommander/2.2/dkp-upgrade/index.md, pages/dkp/konvoy/2.2/dkp-upgrade/index.md
I was reading through the docs and the table was hard for me to understand at first glance. My mind wants to read the table from left to right so i can find my current version and see all the versions I can upgrade to. I would like to have a different table format but that would require using an HTML table instead of markdown :(. 
http://docs-d2iq-com-pr-4308.s3-website-us-west-2.amazonaws.com/
=> docs: Restructure upgrade path table

pages/dkp/kommander/2.1/projects/applications/catalog-applications/dkp-applications/custom-resources-workspace-catalog/spark/index.md, pages/dkp/kommander/2.2/projects/applications/catalog-applications/dkp-applications/custom-resources-workspace-catalog/spark/index.md
While testing spark operator, I found some missing permissions from the docs that were added in 1.1.17 and also some missing permissions for spark 3.1.
New chart (1.1.17):
The PVC permission was added due to a bug when using a specific spark configuration, so I added it to both 2.1 and 2.2.
https://github.com/mesosphere/spark-on-k8s-operator/blob/d2iq-master/charts/spark-operator-chart/templates/spark-rbac.yaml#L22-L33
Spark 3.1 requires some ConfigMap permissions:
https://github.com/mesosphere/spark-on-k8s-operator/blob/spark-operator-chart-1.1.6/charts/spark-operator-chart/templates/spark-rbac.yaml#L22-L27
See the …
=> docs: Update spark permissions

pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/air-gapped/create-capi-vm-image/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/air-gapped/explore/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/create-capi-vm-image/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/explore/index.md
(https://jira.d2iq.com/browse/D2IQ-87699)
Fixed indentation levels in markup to repair numbering in 4 topics, listed in the attached issue. Tested with `npm run dev`until they were right.
http://docs-d2iq-com-pr-4343.s3-website-us-west-2.amazonaws.com/
=> [DOC][Konvoy 2.2] indentation errors causing procedure numbering in 4 topics

pages/dkp/kommander/2.2/dkp-upgrade/upgrade-kommander/index.md, pages/dkp/kommander/2.2/projects/applications/platform-applications/index.md, pages/dkp/kommander/2.2/workspaces/applications/platform-applications/index.md
I was browsing our upgrade docs and saw that the upgrade workspace section was put under a Projects page. I've moved it to Workspace platform apps page where it should be.
=> [kommander] Move ws upgrade section to correct ws page instead of project

pages/dkp/konvoy/2.1/choose-infrastructure/aks/aks-quickstart/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/aks/aks-quickstart/index.md
This is related to a previously closed JIRA ticket 4254 and COPS 7231.  Konvoy team requested the information regarding AKS not supporting self-managed clusters be added to the section of docs in Quick Start, not just under Advanced tab where we added it in previous Jira 4254.
http://docs-d2iq-com-pr-4357.s3-website-us-west-2.amazonaws.com/
=> More locations about clusters for AKS per Dev

.github/styles/Vocab/Docs/accept.txt, pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/air-gapped/explore/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/explore/index.md
n/a
Some spelling that got caught by linters, fixing a link, and there was some yaml allignment/linting stuff.
http://docs-d2iq-com-pr-4350.s3-website-us-west-2.amazonaws.com/
=> docs: fixing yaml and spelling for linter

.github/styles/Vocab/Docs/accept.txt
n/a
fixes broken linter
It'll be good to have gitea both ways, because sometimes it shows up in configs like this (i.e.: lowercase)
http://docs-d2iq-com-pr-4360.s3-website-us-west-2.amazonaws.com/
=> chore: adding gitea lowercase in accept words

pages/dkp/kaptain/1.2.0/install/konvoy/index.md, pages/dkp/kaptain/1.2.0/upgrade/index.md, pages/dkp/kaptain/1.3.0/install/konvoy-dkp/index.md
seems like a missing blank line above a codeblock in a list crashes vale, it is invalid markdown so its sorta ok, but it should post a error instead of just crashing.. nvm, this PR should fix it.
http://docs-d2iq-com-pr-4359.s3-website-us-west-2.amazonaws.com/
=> fix invalid markdown crashing vale

pages/dkp/kommander/2.0/install/air-gapped/index.md
https://jira.d2iq.com/browse/D2IQ-79671
Fixes broken links to konvoy airgapped docs from kommander 2.0 docs (on this page)
=> docs: Fix 2.0 broken konv airgapped links

pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/prerequisites/index.md
Copies the on-prem prereqs from dkp to dkp 2
http://docs-d2iq-com-pr-4347.s3-website-us-west-2.amazonaws.com/
=> docs: adds prereqs from dkp 1.x to 2.2

pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/self-managed/index.md
n/a
Really small potatoes, but just updating the output to be current with what I noticed when running these steps
http://docs-d2iq-com-pr-4374.s3-website-us-west-2.amazonaws.com/
=> docs: just updating dkp output for capi comps

.github/styles/Vocab/Docs/accept.txt, pages/dkp/kommander/2.2/workspaces/applications/catalog-applications/dkp-applications/kaptain/index.md
No Jira, but https://github.com/mesosphere/dcos-docs-site/pull/4362#discussion_r853221337
Adding a page under DKP Catalog applications referencing Kaptain (since it is now a dkp catalog app).
http://docs-d2iq-com-pr-4371.s3-website-us-west-2.amazonaws.com/
=> Adding Kaptain info in Kommander docs

pages/dkp/konvoy/1.6/access-authentication/install-rbac/index.md, pages/dkp/konvoy/1.7/access-authentication/install-rbac/index.md, pages/dkp/konvoy/1.8/access-authentication/install-rbac/index.md
Setup RBAC with Konvoy
(https://jira.d2iq.com/browse/D2IQ-78938)
Wrong command
kubect describe secret <secret-name>
Missing letter 'l' in the command 'kubectl'.
3. About Step 6 - The following command is not clear/detailed:
export TOKEN=$(kubectl get secret john-sa-token-rq4ls -o=jsonpath="{.data.token}" | base64 -d -i -)
The part 'john-sa-token-rq4ls' is individual. My suggestion:
export TOKEN=$(kubectl get secret <secret-name> -o=jsonpath="{.data.token}" | base64 -d -i -)
=> setupRBAC_Jira78938

pages/dkp/kaptain/2.0.0/install/air-gapped-dkp/index.md, pages/dkp/kaptain/2.0.0/install/dkp/index.md, pages/dkp/kaptain/2.0.0/secrets-management/index.md, pages/dkp/kaptain/2.0.0/troubleshooting/index.md
[D2IQ-87584](https://jira.d2iq.com/browse/D2IQ-87584)
Remove kudo references from troubleshooting.
http://docs-d2iq-com-pr-4367.s3-website-us-west-2.amazonaws.com/
=> Remove kudo commands from troubleshooting

pages/dkp/kaptain/2.0.0/install/deploy-kaptain/index.md, pages/dkp/kaptain/2.0.0/install/dkp/index.md, pages/dkp/kaptain/2.0.0/install/on-premise/index.md
Updated on-prem section with additional info and linked to the overall install topic for further steps. 
Also fixed the menu-weights of the pages in that folder, so they are shown in a more structured order.
http://docs-d2iq-com-pr-4366.s3-website-us-west-2.amazonaws.com/
=> [Kaptain]: on-prem install & fixing menu weights

pages/dkp/kommander/2.2/release-notes/2.2.0/index.md, pages/dkp/konvoy/2.2/release-notes/index.md
Add clarification about an assumption made in the command.
Also, fixed the command in the last step to delete pod -- now included a label filter in the command to correctly target spark operator. 
http://docs-d2iq-com-pr-4365.s3-website-us-west-2.amazonaws.com/
=> docs: fix spark workaround steps

pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/air-gapped/create-bastion-vm/index.md
Updated the bootstrap archive name to match what is used everywhere else including the support download page.
=> Updated bootstrap archive name

pages/dkp/kaptain/2.0.0/configuration/auto-cleanup-settings/index.md, pages/dkp/kaptain/2.0.0/sdk/1.0.x/troubleshooting/index.md
https://jira.d2iq.com/browse/D2IQ-87948
This information was already added to the install topics in other PRs. 
So I am not sure if we need this note in these two places as well... WDYT? We can close this PR if you think it is not required here.
Also fixed a link that was broken in one of the pages.
http://docs-d2iq-com-pr-4380.s3-website-us-west-2.amazonaws.com/
=> [Kaptain]: Knative is optional if KServe is configured to work in `RawDeployment` mode

pages/dkp/kaptain/2.0.0/configuration/external-dex/index.md
Remove helm instructions and point users to  the installation docs instead. Fixes service name and namespace in the last section.
=> Remove helm instructions, update endpoint discovery commands

pages/dkp/kaptain/2.0.0/sdk/compatibility/index.md
https://mesosphere.slack.com/archives/G0157326RFD/p1650624080459719
The new release of Kaptain SDK will not be compatible with Kaptain 1.3 and older.
Deleted Kaptain 1.1.0 column and moved everything to the right to include a Kaptain 2.0.0 column. 
Added a SDK 1.0.1 row.
=> [Kaptain] Updating compatibility index for SDK

pages/dkp/kaptain/2.0.0/version-policy/index.md
https://jira.d2iq.com/browse/D2IQ-87586
Updated version policy to reflect Kaptain 2.0 helm and DKP based deployment. I've basicly made this up thinking its the best change to be done, but not sure if we need some other people to have a look? support matrix is important I guess..
http://docs-d2iq-com-pr-4377.s3-website-us-west-2.amazonaws.com/
=> Update kaptain 2.0 version policy

pages/dkp/kaptain/2.0.0/configuration/index.md, pages/dkp/kaptain/2.0.0/tutorials/katib/index.md, pages/dkp/kaptain/2.0.0/tutorials/pipelines/index.md, pages/dkp/kaptain/2.0.0/tutorials/sdk/image-builder/index.md, pages/dkp/kaptain/2.0.0/tutorials/sdk/pytorch/index.md, pages/dkp/kaptain/2.0.0/tutorials/sdk/quick-start/index.md, pages/dkp/kaptain/2.0.0/tutorials/sdk/tensorflow/index.md, pages/dkp/kaptain/2.0.0/tutorials/training/mxnet/index.md, pages/dkp/kaptain/2.0.0/tutorials/training/pytorch/index.md, pages/dkp/kaptain/2.0.0/tutorials/training/spark/index.md, pages/dkp/kaptain/2.0.0/tutorials/training/tensorflow/index.md
https://jira.d2iq.com/browse/D2IQ-87250
Re-generate tutorials and Kaptain chart configuration based on the changes from https://github.com/mesosphere/kaptain/pull/717.
http://docs-d2iq-com-pr-4382.s3-website-us-west-2.amazonaws.com/
=> Re-generate tutorials and chart configuration docs

pages/dkp/kaptain/2.0.0/install/dkp/index.md, pages/dkp/kaptain/2.0.0/install/index.md, pages/dkp/kaptain/2.0.0/install/on-premise/index.md, pages/dkp/kaptain/2.0.0/monitoring/index.md, pages/dkp/kaptain/2.0.0/user-management/index.md
https://jira.d2iq.com/browse/D2IQ-87585
Konvoy 1.x textual references were already removed. However some links were not up-to-date and still referenced 1.8.
Also updated the reference to the "migration" topic which now is a "fresh install" topic.
http://docs-d2iq-com-pr-4393.s3-website-us-west-2.amazonaws.com/
=> Deleting Konvoy 1.x references

pages/dkp/kommander/2.1/security/oidc/index.md, pages/dkp/kommander/2.2/security/oidc/index.md
https://jira.d2iq.com/browse/D2IQ-78929
Copies over this [page](https://docs.d2iq.com/dkp/konvoy/1.8/access-authentication/oidc/change-token-lifetime/) from 1.X and adjusts it to work with 2.X.
=> docs: Add section on configuring dex token expiration

pages/dkp/kommander/2.1/install/air-gapped/index.md
https://jira.d2iq.com/browse/COPS-7205
Remove erroneous `--strip components
http://docs-d2iq-com-pr-4399.s3-website-us-west-2.amazonaws.com/
=> docs: fix tar command in 2.1 AG kommander install docs

pages/dkp/kaptain/2.0.0/user-management/index.md
[D2IQ-87576](https://jira.d2iq.com/browse/D2IQ-87576)
We remove remaining kudo instructions from Kaptain 2.0.0 docs
=> Remove kudo references from user management page

pages/dkp/konvoy/2.1/choose-infrastructure/pre-provisioned/define-infrastructure/index.md
https://jira.d2iq.com/browse/COPS-7222?filter=-1
Added correct quotation marks to commented out item so folks don't get error returned messages for copying code.
=> [Konvoy 2.1] COPS-7222 Fixed Copy+Paste Quotation Error

pages/dkp/kommander/2.1/major-upgrade/upgrade-clusters/migrate-platform-apps/index.md
Noticed this table looked off and link was also bad
http://docs-d2iq-com-pr-4392.s3-website-us-west-2.amazonaws.com/
=> docs: Fix migration table and link

pages/dkp/konvoy/2.2/fips/index.md
n/a
Version of Kubernetes that we use for DKP 2.2 is 1.22.8 - this just needed to be updated here
http://docs-d2iq-com-pr-4416.s3-website-us-west-2.amazonaws.com/
=> Updating k8s version to be v1.22.8 in FIPS docs

.github/styles/Vocab/Docs/accept.txt, pages/dkp/kaptain/1.2.0/custom-configuration/external-dex/index.md, pages/dkp/kaptain/1.2.0/download/index.md, pages/dkp/kaptain/1.2.0/install/konvoy/index.md, pages/dkp/kaptain/1.2.0/install/on-premise/index.md, pages/dkp/kaptain/1.2.0/monitoring/index.md, pages/dkp/kaptain/1.2.0/sdk/0.3.x/private-registries/index.md, pages/dkp/kaptain/1.2.0/sdk/0.4.x/private-registries/index.md, pages/dkp/kaptain/1.2.0/tutorials/katib/index.md, pages/dkp/kaptain/1.2.0/tutorials/pipelines/index.md, pages/dkp/kaptain/1.2.0/tutorials/sdk/pytorch/index.md, pages/dkp/kaptain/1.2.0/tutorials/sdk/tensorflow/index.md, pages/dkp/kaptain/1.2.0/user-management/index.md, pages/dkp/konvoy/2.2/Install/index.md
https://jira.d2iq.com/browse/COPS-7192?filter=57924
There are several broken links in 1.2 documentation that were showing an error. I tried to fix all of these, however, there are a couple of them where I am not 100% sure if they should lead somewhere else. 
For example, the "latest" (instead of version number) in relative links does not always work, specially when pages move around and newer documentation versions change completely (in terms of structure and content). 
http://docs-d2iq-com-pr-4417.s3-website-us-west-2.amazonaws.com/
=> [Kaptain] Fixing broken links from 1.2 documentation (cops)

pages/dkp/kaptain/1.3.0/user-management/index.md
https://jira.d2iq.com/browse/COPS-7232
Instruction on how to enable automatic creation of profiles was not working. Dev provided the correct command to fix this issue and documentation.
This is fixed on 2.0 already, so no need to include there too.
Also did some linting, you can ignore that and just review lines 46 to 60.
http://docs-d2iq-com-pr-4421.s3-website-us-west-2.amazonaws.com/
=> [Kaptain] COPS-7232 profile creation

pages/dkp/konvoy/2.2/dkp-upgrade/upgrade-konvoy/enterprise/index.md
https://jira.d2iq.com/browse/D2IQ-88839
###Description
If a user has previously upgraded from 1.8 to 2.1, an upgrade to 2.2 without the following instructions will break cert-manager.
http://docs-d2iq-com-pr-4424.s3-website-us-west-2.amazonaws.com/
=> Upgrade CAPI commands if from 1.8 to 2.1 first

pages/dkp/konvoy/2.2/dkp-upgrade/upgrade-konvoy/essential/index.md, pages/dkp/konvoy/2.2/release-notes/index.md
https://jira.d2iq.com/browse/D2IQ-88839
If a user has previously upgraded from 1.8 to 2.1, an upgrade to 2.2 without the following instructions will break cert-manager. Please add these to the docs pages as indicated with the appropriate caveats:
http://docs-d2iq-com-pr-4425.s3-website-us-west-2.amazonaws.com/
=> Document work around for bug 88839

pages/dkp/konvoy/2.2/supported-operating-systems/index.md
https://jira.d2iq.com/browse/COPS-7271 
http://docs-d2iq-com-pr-4431.s3-website-us-west-2.amazonaws.com/
=> Fixed Azure and AKS support in the 2.2 Docs

pages/dkp/kommander/2.1/install/mgmt-cluster-apps/index.md, pages/dkp/kommander/2.1/workspaces/applications/platform-applications/platform-application-requirements/index.md
https://jira.d2iq.com/browse/COPS-7168
Backporting these 2 pages from 2.2 into the 2.1 doc set; no other changes.
=> COPS-7168 - backport 2 pages to Kommander 2.1

s3config.json
Evidently the path for this changed in 2.2 docs and as such there are a
number of broken UI links for 2.2. Removed a redirect related to
Kommander 1.4 because we don't support that version anymore, and added
this one to fix the immediate issue.
Closes D2IQ-89309
=> fix: redirect for broken UI links

pages/dkp/konvoy/2.3/choose-infrastructure/aws/advanced/bootstrap/index.md, pages/dkp/konvoy/2.3/choose-infrastructure/aws/advanced/delete/index.md, pages/dkp/konvoy/2.3/choose-infrastructure/aws/advanced/self-managed/index.md, pages/dkp/konvoy/2.3/choose-infrastructure/aws/air-gapped/bootstrap/index.md, pages/dkp/konvoy/2.3/choose-infrastructure/aws/quick-start-aws/index.md, pages/dkp/konvoy/2.3/choose-infrastructure/eks/advanced/bootstrap/index.md, pages/dkp/konvoy/2.3/choose-infrastructure/eks/quick-start/index.md, pages/dkp/konvoy/2.3/release-notes/2.3.0/index.md
https://jira.d2iq.com/browse/D2IQ-89303
Documenting the change of the default value of `--with-aws-bootstrap-credentials` to `false`. Code changes in https://github.com/mesosphere/konvoy2/pull/1279 
http://docs-d2iq-com-pr-4438.s3-website-us-west-2.amazonaws.com/
=> konvoy: changing default value to --with-aws-bootstrap-credentials=false

pages/dkp/konvoy/2.2/choose-infrastructure/aws/quick-start-aws/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/azure/quick-start-azure/index.md, pages/dkp/konvoy/2.3/choose-infrastructure/aws/quick-start-aws/index.md, pages/dkp/konvoy/2.3/choose-infrastructure/azure/quick-start-azure/index.md
This issue affects community-maintained machine images (which users should not use in production). We've worked around this in 2.2 by using the Ubuntu 21.04 image instead of the CentOS7 one (https://github.com/mesosphere/konvoy2/pull/1213/)
http://docs-d2iq-com-pr-4440.s3-website-us-west-2.amazonaws.com/
=> Adding Ubuntu instead of CentOS

pages/dkp/konvoy/2.2/Install/index.md, pages/dkp/konvoy/2.3/Install/index.md
broken Homebrew link to 2.3
http://docs-d2iq-com-pr-4446.s3-website-us-west-2.amazonaws.com/
=> Adding Homebrew link to 23

pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/aws/index.md, pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/preprovisioned/index.md
Jira: [D2IQ-88426](https://jira.d2iq.com/browse/D2IQ-88426)
Update namespace in one of the commands to check calico-node rollout for the Konvoy upgrade.
http://docs-d2iq-com-pr-4447.s3-website-us-west-2.amazonaws.com/
=> Correct namespace for command to check calico-node rollout

.github/styles/Vocab/Docs/accept.txt, pages/dkp/kommander/2.0/security/distributed-authnz/index.md, pages/dkp/kommander/2.1/security/distributed-authnz/index.md, pages/dkp/kommander/2.2/security/distributed-authnz/index.md, pages/dkp/kommander/2.3/security/distributed-authnz/index.md
JIRA: https://jira.d2iq.com/browse/D2IQ-88868
In the https://jira.d2iq.com/browse/COPS-7262 we've discovered that OIDC ID token must have `email_verified` set to value `true` in order to be verified by `kube-oidc-proxy`. This change documents this finding.
http://docs-d2iq-com-pr-4445.s3-website-us-west-2.amazonaws.com/
=> fix: add note about email_verified OIDC token field for KOP

pages/dkp/kommander/2.2/networking/use-istio/index.md, pages/dkp/kommander/2.3/networking/use-istio/index.md
https://jira.d2iq.com/browse/D2IQ-78973
Added relevant istio integration topic with updated application enablement process to the Kommander 2.2 Networking section.
http://docs-d2iq-com-pr-4443.s3-website-us-west-2.amazonaws.com/
=> [Kommander 2.2] Integrate Microservices using istio

pages/dkp/konvoy/2.2/supported-operating-systems/index.md
https://jira.d2iq.com/browse/D2IQ-82728
Fixed RHEL 8.4 kernal version for DKP 2.2
=> Fixed RHEL 8.4 kernal version name

pages/dkp/konvoy/2.2/choose-infrastructure/aws/air-gapped/seed-a-registry/index.md
Urgent work from legal and Tobi.
Added attributions for MinIO code.
=> Added MinIO attribution to docker registry page

pages/dkp/konvoy/2.1/choose-infrastructure/pre-provisioned/create-cluster/index.md, pages/dkp/konvoy/2.1/image-builder/override-files/create-custom-or-files/proxy-or-files/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/create-cluster/index.md, pages/dkp/konvoy/2.2/image-builder/override-files/create-custom-or-files/proxy-or-files/index.md, pages/dkp/konvoy/2.3/choose-infrastructure/pre-provisioned/create-cluster/index.md, pages/dkp/konvoy/2.3/image-builder/override-files/create-custom-or-files/proxy-or-files/index.md
Fixeshttps://jira.d2iq.com/browse/D2IQ-89698.
Documentation for https://jira.d2iq.com/browse/COPS-7214.
I created a separate task https://jira.d2iq.com/browse/D2IQ-89695 for code changes.
Added a Note about users needing to create an override to hold their HTTP proxy configuration. Also fixed the `proxy-or-files/index.md` and made them all consistent across releases.
http://docs-d2iq-com-pr-4450.s3-website-us-west-2.amazonaws.com/
=> konvoy: document that creating an override is required for preprov clusters with an HTTP proxy

pages/dkp/kommander/2.2/release-notes/2.2.0/index.md, pages/dkp/konvoy/2.2/release-notes/2.2.0/index.md
No Jira, this is a fix to the RN files.
We missed the Deprecated section, so re-adding to both files.
http://docs-d2iq-com-pr-4436.s3-website-us-west-2.amazonaws.com/
=> DKP 2.2 Release Notes correction

pages/dkp/konvoy/2.1/choose-infrastructure/aws/advanced/new/index.md, pages/dkp/konvoy/2.1/choose-infrastructure/aws/air-gapped/new/index.md, pages/dkp/konvoy/2.1/choose-infrastructure/aws/quick-start-aws/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/aws/advanced/new/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/aws/air-gapped/new/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/aws/quick-start-aws/index.md, pages/dkp/konvoy/2.3/choose-infrastructure/aws/advanced/new/index.md, pages/dkp/konvoy/2.3/choose-infrastructure/aws/air-gapped/new/index.md, pages/dkp/konvoy/2.3/choose-infrastructure/aws/quick-start-aws/index.md
https://jira.d2iq.com/browse/COPS-7213
The Konvoy documentation around the CLUSTER_NAME variable could be a little unclear.
Konvoy 1.x documentation doesn't have the example one-liner to set a cluster, but dont see that as a problem now. 
For Konvoy 2.x, I would suggest that the following (taken from 1.x) is added, and also some extra text:
NOTE: The cluster name may only contain the following characters: a-z, 0-9, . - and _.
NOTE: Cluster creation will fail if the name has capital letters.  See kubernetes documentation https://kubernetes.io/docs/concepts/overview/working-with-objects/names/ for more details.
This should be in the same section as the first reference of CLUSTER-NAME:
https://docs.d2iq.com/dkp/konvoy/2.1/choose-infrastructure/aws/quick-start-aws/ …
=> COPS7213 Cluster naming

pages/dkp/kommander/2.3/index.md, pages/dkp/konvoy/2.3/index.md
2.3 docs are shown below 2.2 instead of on top, as it should be. Besides, 2.3 is labeled 2.2. 
http://docs-d2iq-com-pr-4459.s3-website-us-west-2.amazonaws.com/
=> Fixing menuweights

pages/dkp/kommander/2.1/install/configuration/http-proxy/index.md, pages/dkp/kommander/2.2/dkp-upgrade/upgrade-kommander/index.md, pages/dkp/kommander/2.2/install/configuration/http-proxy/index.md, pages/dkp/kommander/2.3/install/configuration/http-proxy/index.md, pages/dkp/konvoy/2.2/dkp-upgrade/upgrade-kommander/index.md
https://jira.d2iq.com/browse/COPS-7236
https://jira.d2iq.com/browse/D2IQ-89710
https://jira.d2iq.com/browse/D2IQ-89674
* In the COPS-7236 we've discovered a change in the Gatekeeper configuration file that requires to be reflected in the docs in order to get HTTP proxy clusters working with `v2.2.0`. 
* Add a step to the `v2.1.1` -> `v2.2.0` Kommander upgrade steps for clusters installed with HTTP proxy configuration that is necessary in order to successfully upgrade a cluster.
* Adds an installation step to include `kommander-flux` namespace in Gatekeeper mutated namespaces.
http://docs-d2iq-com-pr-4457.s3-website-us-west-2.amazonaws.com/
See the [contribution …
=> fix: HTTP proxy configuration in 2.2.0+ version

scss/base/_table.scss
https://mesosphere.slack.com/archives/C06FHSK3J/p1652763397844409
USe a fixed layout for tables and break words in tables to let them not overflow, see slack thread.
http://docs-d2iq-com-pr-4464.s3-website-us-west-2.amazonaws.com/
=> fix: use fixed layout for table and break words in tables

pages/dkp/kommander/1.4/archives/index.md, pages/dkp/kommander/2.0/archives/index.md, pages/dkp/kommander/2.1/archives/index.md, pages/dkp/kommander/2.2/archives/index.md, pages/dkp/kommander/2.3/archives/index.md, pages/dkp/konvoy/1.6/archives/index.md, pages/dkp/konvoy/1.8/archives/index.md, pages/dkp/konvoy/2.0/archives/index.md, pages/dkp/konvoy/2.1/archives/index.md, pages/dkp/konvoy/2.2/archives/index.md, pages/dkp/konvoy/2.3/archives/index.md, pages/mesosphere/dcos/2.2/archives/index.md
goes with Mack's archive PR  - https://github.com/mesosphere/dcos-docs-site/pull/4408 
http://docs-d2iq-com-pr-4466.s3-website-us-west-2.amazonaws.com/
=> changing archive references

pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/create-cluster/index.md, pages/dkp/konvoy/2.3/choose-infrastructure/pre-provisioned/create-cluster/index.md
https://jira.d2iq.com/browse/D2IQ-85911
This adds a section explaining how to change the encapsulation method for preprovisioned clusters.
http://docs-d2iq-com-pr-4455.s3-website-us-west-2.amazonaws.com/
=> docs: adds section on encapsulation

pages/dkp/konvoy/2.2/download/index.md, pages/dkp/konvoy/2.3/download/index.md
[](https://jira.d2iq.com/browse/D2IQ-89807)
2.2 had an extra command line that did not pull the correct binary.  Also, Craig said they only download from the button.  ALso took out AWS specific language for 2.2 and 2.3
http://docs-d2iq-com-pr-4479.s3-website-us-west-2.amazonaws.com/
=> Download errant command line in 2x

pages/dkp/kommander/1.4/install-airgapped/index.md, pages/dkp/kommander/1.4/install/index.md, pages/dkp/kommander/2.0/install/air-gapped/index.md, pages/dkp/kommander/2.1/download/index.md, pages/dkp/kommander/2.1/install/air-gapped/catalog/index.md, pages/dkp/kommander/2.1/install/air-gapped/index.md, pages/dkp/kommander/2.2/dkp-upgrade/upgrade-kommander/index.md, pages/dkp/kommander/2.2/download/index.md, pages/dkp/kommander/2.2/install/air-gapped/catalog/index.md, pages/dkp/kommander/2.2/install/air-gapped/index.md, pages/dkp/kommander/2.3/dkp-upgrade/upgrade-kommander/index.md, pages/dkp/kommander/2.3/download/index.md, pages/dkp/kommander/2.3/install/air-gapped/catalog/index.md, pages/dkp/kommander/2.3/install/air-gapped/index.md, pages/dkp/kommander/2.3/install/configuration/enterprise-catalog/index.md
https://jira.d2iq.com/browse/D2IQ-89883
Added minIO attributions to Kommander versions 2.3, 2.2, 2.1, and 1.4 in locations where the product is downloaded.
http://docs-d2iq-com-pr-4483.s3-website-us-west-2.amazonaws.com/
=> [Kommander] MinIO attributions in download locations

pages/dkp/konvoy/2.3/dkp-upgrade/upgrade-konvoy/enterprise/index.md, pages/dkp/konvoy/2.3/dkp-upgrade/upgrade-konvoy/essential/index.md
[](https://jira.d2iq.com/browse/D2IQ-87530?filter=-1)
Adding upgrade image using KIB as a step rather than note.  Also including the Azure step and link as well as the AMI.
http://docs-d2iq-com-pr-4487.s3-website-us-west-2.amazonaws.com/
=> Adding upgrade image info for both AWS and Azure

pages/dkp/konvoy/2.0/image-builder/override-files/index.md, pages/dkp/konvoy/2.1/image-builder/override-files/default-or-files/index.md, pages/dkp/konvoy/2.2/image-builder/override-files/default-or-files/index.md
https://jira.d2iq.com/browse/D2IQ-87545
Un-linked override files from main and pasted content from directory to the docs site as requested by support.
http://docs-d2iq-com-pr-4495.s3-website-us-west-2.amazonaws.com/
=> [Konvoy] KIB Override page updates

pages/dkp/konvoy/2.2/supported-operating-systems/index.md
n/a
This is just to define the specific kernel that was used to build an EKS cluster
```
~/Development/d2iq/konvoy-app/dkp2.2/gaRelease :k get nodes
NAME                                         STATUS   ROLES    AGE   VERSION
ip-10-0-102-49.us-west-2.compute.internal    Ready    <none>   10m   v1.21.12-eks-5308cf7
ip-10-0-123-220.us-west-2.compute.internal   Ready    <none>   10m   v1.21.12-eks-5308cf7
ip-10-0-67-222.us-west-2.compute.internal    Ready    <none>   10m   v1.21.12-eks-5308cf7
ip-10-0-82-192.us-west-2.compute.internal    Ready    <none>   10m   v1.21.12-eks-5308cf7
~/Development/d2iq/konvoy-app/dkp2.2/gaRelease :k node-shell ip-10-0-102-49.us-west-2.compute.internal
spawning "nsenter-ehmv6k" on "ip-10-0-102-49.us-west-2.compute.internal"
If you don't see a command prompt, …
```
=> docs: updating eks to specific kernel

pages/dkp/kommander/2.2/dkp-upgrade/upgrade-kommander/index.md, pages/dkp/kommander/2.3/dkp-upgrade/upgrade-kommander/index.md, pages/dkp/konvoy/2.2/dkp-upgrade/upgrade-kommander/index.md, pages/dkp/konvoy/2.3/dkp-upgrade/upgrade-kommander/index.md
https://jira.d2iq.com/browse/D2IQ-90123
Right now, there is a race condition in documented steps at https://docs.d2iq.com/dkp/kommander/2.2/dkp-upgrade/upgrade-kommander/#detach-metallb-from-kommander which might potentially result in removal of metallb pods sometimes. This fixes the docs to make sure metallb pods do not get removed.
http://docs-d2iq-com-pr-4496.s3-website-us-west-2.amazonaws.com/
=> docs: make metallb unmanaged in kommander upgrade correctly

pages/dkp/kommander/2.2/release-notes/2.2.1/index.md, pages/dkp/konvoy/2.2/release-notes/2.2.1/index.md
http://docs-d2iq-com-pr-4513.s3-website-us-west-2.amazonaws.com/
=> 2.2.1 Release Notes fixes

pages/dkp/konvoy/2.2/choose-infrastructure/aws/air-gapped/new/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/create-cluster/index.md, pages/dkp/konvoy/2.3/choose-infrastructure/aws/air-gapped/new/index.md, pages/dkp/konvoy/2.3/choose-infrastructure/pre-provisioned/create-cluster/index.md
https://jira.d2iq.com/browse/D2IQ-89796
variable pointing to --registry-mirror-url. 
Change this variable from  DOCKER_REGISTRY_ADDRESS to DOCKER_REGISTRY_URL (this is variable pointing to --registry-mirror-url which requires an https URL)
http://docs-d2iq-com-pr-4517.s3-website-us-west-2.amazonaws.com/
=> Change Docker CLI for Registry mirror

pages/dkp/konvoy/2.3/choose-infrastructure/gcp/quick-start-gcp/index.md
https://jira.d2iq.com/browse/D2IQ-88471
My mistake.. found out that Dimitri's notes from Jira https://jira.d2iq.com/browse/D2IQ-88531 were about backend setup for GCP and not customer facing.  He said to make it look like the rest of the Quick Start guides for other providers.  Confirmation of newly coded CLI will come in Sprint 12 so I can update where tags are in code !NEED CONFIRMATION OF STEPS PRE-RELEASE
http://docs-d2iq-com-pr-4515.s3-website-us-west-2.amazonaws.com/
=> Fixing Instructions for GCP Quick Start

pages/dkp/konvoy/2.3/choose-infrastructure/gcp/quick-start-gcp/index.md
n/a - just following up here: 
https://github.com/mesosphere/dcos-docs-site/pull/4515
I was just on the late show to this PR above, and so ... anyway changes are here.
Mostly just to formatting - even though it's a WIP for now, to render it nicely on the dev docs page - it sort of needs to have this formatting.
Also replaced the `gcp` with `gcloud` commands - so one less thing to do when this is all complete.
One thing we may have to add is a section like this:
https://docs.d2iq.com/dkp/konvoy/1.8/install/install-gcp/#permission-settings
This is more or less the gcloud equivalent to setting up the aws IAM policies: 
https://docs.d2iq.com/dkp/konvoy/2.2/choose-infrastructure/aws/iam-policies/ …
=> docs: updates to gcp quickstart

pages/dkp/konvoy/2.2/choose-infrastructure/aws/advanced/prerequisites/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/azure/advanced/prerequisites/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/azure/advanced/replace-node/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/prerequisites/index.md, pages/dkp/konvoy/2.3/choose-infrastructure/aws/advanced/prerequisites/index.md, pages/dkp/konvoy/2.3/choose-infrastructure/azure/advanced/prerequisites/index.md
https://jira.d2iq.com/browse/D2IQ-90252
Add worker node requirements for Essential/Enterprise into/below the pre-req section of each provider. Although for other providers, DKP creates the worker nodes, and so is in a position to  set the number by default via CLI.  We should document them for all providers, but we can also mention that for AWS/Azure/GCP, the CLI will use acceptable numbers by default.   Will add GCP after merge other PR.
http://docs-d2iq-com-pr-4521.s3-website-us-west-2.amazonaws.com/
=> Worker node req Essential vs Enterpr

pages/dkp/kaptain/2.0.0/configuration/external-dex/index.md, pages/dkp/kaptain/2.0.0/install/deploy-kaptain/index.md, pages/dkp/kaptain/2.1.0/configuration/external-dex/index.md, pages/dkp/kaptain/2.1.0/install/deploy-kaptain/index.md
No Jira, but a slack convo: 
https://mesosphere.slack.com/archives/G0157326RFD/p1654702181007889
We decided to move the login section to a place where it is more visible and makes more sense for users. 
NOTE: I will add this to 2.2 docs once we are done contributing and have a final version.
http://docs-d2iq-com-pr-4536.s3-website-us-west-2.amazonaws.com/
=> [Kaptain] Moving login section

pages/dkp/kommander/2.2/operations/access-control/index.md, pages/dkp/kommander/2.2/operations/identity-providers/index.md, pages/dkp/kommander/2.2/projects/project-policies/index.md, pages/dkp/kommander/2.2/workspaces/workspace-role-bindings/index.md, pages/dkp/kommander/2.3/operations/access-control/index.md, pages/dkp/kommander/2.3/operations/identity-providers/index.md, pages/dkp/kommander/2.3/projects/project-policies/index.md, pages/dkp/kommander/2.3/workspaces/workspace-role-bindings/index.md
The relationship between groups created in Identity Providers and then
leveraged by the Access Control sections was not well documented and
circular.
Removed the word "group" from some early explanation of Roles in Access
Control. Removed a redundant section of Access Control, and added
explanation on where to create groups for use with Role Bindings
Additionally, tried to improve the explanation of how to create groups
with identity providers in the first place in all the places I could
find that discussed Role Bindings.
[](https://jira.d2iq.com/browse/COPS-7264)
http://docs-d2iq-com-pr-4527.s3-website-us-west-2.amazonaws.com/
See the [contribution …
=> fix: improve groups explanations

pages/dkp/konvoy/2.1/storage/automated-storage/index.md, pages/dkp/konvoy/2.2/storage/automated-storage/index.md, pages/dkp/konvoy/2.3/storage/automated-storage/index.md
https://jira.d2iq.com/browse/D2IQ-84567
We list default storage driver for AWS. Since we are supporting provisioning DKP on Azure as well, a default storage option for Azure should be added to this page.
http://docs-d2iq-com-pr-4540.s3-website-us-west-2.amazonaws.com/
=> Adding default storage driver for Azure in storage

pages/dkp/konvoy/2.1/major-version-upgrade/understand-standard-config/index.md
Without this change, customers may be led to believe that the described Konvoy migration was covering Kommander as well. If done as documented, customers will hit the following error message:
```
$ kommander migrate -y
✓ Checking if migration from DKP 1.x is necessary 
Error: Kommander is installed on the cluster. Migration of this cluster is not supported.
```
=> fix: kommander upgrade not supported in migration

pages/dkp/kaptain/1.3.0/release-notes/1.3.0/index.md, pages/dkp/kaptain/2.0.0/release-notes/2.0.0/index.md
Offering a workaround for https://jira.d2iq.com/browse/COPS-7287. 
The Kaptain team has decided to have a fix for Kaptain 2.1, therefore adding the workaround to 1.3 and 2.0 only. 
The cert-manager issue we faced with DKP is affecting Kaptain as well. This workaround is based on a [fix provided by support](https://hackmd.io/@d2iq-gs/ryc9LW_Ic). The commands still need to fixed and tested.
http://docs-d2iq-com-pr-4545.s3-website-us-west-2.amazonaws.com/
=> [Kaptain] cert-manager workaround

pages/dkp/kommander/2.1/backup-and-restore/index.md, pages/dkp/kommander/2.2/backup-and-restore/index.md, pages/dkp/kommander/2.3/backup-and-restore/index.md
https://jira.d2iq.com/browse/COPS-7308
When configuring an alternative backup location for Velero, it was not clear how to apply the changes and have Velero recognize the new backup location. You can do this by setting up a ConfigMap and applying an Override. Making this more clear in the documentation.
Adding to 2.2 and 2.3 after I get some reviews.
http://docs-d2iq-com-pr-4543.s3-website-us-west-2.amazonaws.com/
=> [Kommander] COPS-7308: adding more info on how to apply overrides

pages/dkp/kommander/2.2/tutorials/continuous-delivery/storing-secrets-with-gitops/index.md, pages/dkp/kommander/2.3/tutorials/continuous-delivery/storing-secrets-with-gitops/index.md
https://jira.d2iq.com/browse/COPS-7302
Our Kommander CD tutorial here https://docs.d2iq.com/dkp/kommander/2.2/tutorials/continuous-delivery/storing-secrets-with-gitops/#install-the-sealedsecrets-controller-on-your-cluster, instructs a customer to install sealed-secrets controller that still uses rbac.authorization.k8s.io/v1beta1
but our version of kubernetes does not support this anymore. Hence a customer would receive an error.
This has been fixed upstream via release https://github.com/bitnami-labs/sealed-secrets/blob/main/RELEASE-NOTES.md#v0170
So, we can update the installation command with
kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.1/controller.yaml …
=> RBAC command change for secrets controller

pages/dkp/kaptain/2.0.0/release-notes/2.0.0/index.md, pages/dkp/kaptain/2.1.0/release-notes/2.1.0/index.md
https://jira.d2iq.com/browse/COPS-7287
Added the exact same fix in 1.3 and 2.0 and originally thought the fix was on the way to 2.1. https://github.com/mesosphere/dcos-docs-site/pull/4545
However, this will be handled as a feature in 2.2, so we do need the workaround for 2.1.
Basically a copy and paste from 2.0.
http://docs-d2iq-com-pr-4552.s3-website-us-west-2.amazonaws.com/
=> [Kaptain] REDO: adding cert-manager workaround to 2.1 docs

pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/create-capi-vm-image/index.md, pages/dkp/konvoy/2.3/choose-infrastructure/vsphere/create-capi-vm-image/index.md
https://jira.d2iq.com/browse/COPS-7272?jql=issuetype%20%3D%20%22Customer%20Issue%22%20and%20Team%20%3D%2044%20and%20resolution%20is%20EMPTY%20
In the page https://docs.d2iq.com/dkp/konvoy/2.2/choose-infrastructure/vsphere/create-capi-vm-image/ it shows several variables needed to be configured when the `image.yaml` file is created.
There is no explanation on what each of the variable is for but as it is based on Packer, we can put in a link in the docs to point to the Packer documentation.
We can add description of the only configuration needed for the vsphere KIB provisioning. 
Stalin can work with Assignee to add those details.
http://docs-d2iq-com-pr-4550.s3-website-us-west-2.amazonaws.com/
See the …
=> vSphere yaml variable specifics for KIB

pages/dkp/kommander/2.3/clusters/custom-domain-certificate/configuration/index.md, pages/dkp/kommander/2.3/clusters/custom-domain-certificate/index.md, pages/dkp/kommander/2.3/clusters/custom-domain-certificate/managed/index.md, pages/dkp/kommander/2.3/install/configuration/custom-domain/index.md, pages/dkp/kommander/2.3/release-notes/2.3.0/index.md
https://jira.d2iq.com/browse/D2IQ-90373
From 2.3 is it possible to customize the domains and certificates for managed/attached clusters after the installation of DKP (hence the location of this topic in the "managing clusters" section). 
In the past, custom domains and certs were only possible for the management cluster and during installation.
http://docs-d2iq-com-pr-4553.s3-website-us-west-2.amazonaws.com/
=> [Kommander] custom domains and certificates for managed clusters

pages/dkp/konvoy/2.2/choose-infrastructure/aws/advanced/new/index.md
https://jira.d2iq.com/browse/D2IQ-90324. Will add to 2.3 docs in Confluence site
As a user that wants to build a cluster on AWS
I want to have the ami-id flag exposed
so that I know I can deploy a non-default AMI (OS) cluster and not have to find the flag in dkp --help
http://docs-d2iq-com-pr-4564.s3-website-us-west-2.amazonaws.com/
=> Add AMI in new cluster

pages/dkp/kaptain/2.1.0/configuration/index.md, pages/dkp/kaptain/2.1.0/tutorials/katib/index.md, pages/dkp/kaptain/2.1.0/tutorials/pipelines/index.md, pages/dkp/kaptain/2.1.0/tutorials/sdk/image-builder/index.md, pages/dkp/kaptain/2.1.0/tutorials/sdk/pytorch/index.md, pages/dkp/kaptain/2.1.0/tutorials/sdk/quick-start/index.md, pages/dkp/kaptain/2.1.0/tutorials/sdk/tensorflow/index.md, pages/dkp/kaptain/2.1.0/tutorials/training/mxnet/index.md, pages/dkp/kaptain/2.1.0/tutorials/training/pytorch/index.md, pages/dkp/kaptain/2.1.0/tutorials/training/spark/index.md, pages/dkp/kaptain/2.1.0/tutorials/training/tensorflow/index.md
Update Kaptain generated documentation
http://docs-d2iq-com-pr-4565.s3-website-us-west-2.amazonaws.com/
=> Re-generate Kaptain docs

pages/dkp/konvoy/2.2/release-notes/2.2.2/index.md
https://jira.d2iq.com/browse/D2IQ-90183
Release notes for DKP release 2.2.2.
http://docs-d2iq-com-pr-4567.s3-website-us-west-2.amazonaws.com/
=> [DKP] Release Notes 2.2.2

pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/create-cluster/index.md
https://jira.d2iq.com/browse/D2IQ-90124
Edited kube-vip section with expanded info.
http://docs-d2iq-com-pr-4557.s3-website-us-west-2.amazonaws.com/
=> [Konvoy] Documentation around configuring kube-vip

pages/dkp/konvoy/2.2/choose-infrastructure/aws/air-gapped/create-an-ami/index.md, pages/dkp/konvoy/2.3/choose-infrastructure/aws/air-gapped/create-an-ami/index.md
https://jira.d2iq.com/browse/D2IQ-90568
Added some steps to AMI creation.
http://docs-d2iq-com-pr-4558.s3-website-us-west-2.amazonaws.com/
=> [Konvoy] Adding step to download containerd bundle for airgapped builds

pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/air-gapped/create-bastion-vm/index.md, pages/dkp/konvoy/2.3/choose-infrastructure/vsphere/air-gapped/create-bastion-vm/index.md
No ticket
In following the vsphere docs it tells you to download the file dkp_image_bundle_v2.2.1_linux_amd64.tar.gz but this file does not exist.   It is named 'konvoy_image_bundle_v2.2.1_linux_amd64.tar.gz'
http://docs-d2iq-com-pr-4570.s3-website-us-west-2.amazonaws.com/
=> bugfix: Wrong filename in vsphere download instructions

pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/air-gapped/create-capi-vm-image/index.md
https://jira.d2iq.com/browse/D2IQ-91418
Adding the packer builder type to the file images.yaml, specifically the following 2 lines:
```
build_name: "vsphere-rhel-79"
packer_builder_type: "vsphere"
```
without these two lines the following exception is returned:
```
./konvoy-image build images.yaml --overrides offline.yaml
2022/07/08 20:01:15 writing new packer configuration to work/provision_build-1657310475-PSrOj
ERRO error during run: build failure: /packer_builder_type is not defined in image manifest
error encountered: exit status 3
```
See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/mai …
=> adding packer builder type D2IQ-91418

pages/dkp/konvoy/2.3/choose-infrastructure/aws/quick-start-aws/index.md
N/A
There were extra spaces after a `\`
That messes up the command if you just copy/pasta.
The rest was just linting
http://docs-d2iq-com-pr-4580.s3-website-us-west-2.amazonaws.com/
=> docs: extra spaces in dkp create cluster command

pages/dkp/konvoy/2.2/choose-infrastructure/aws/advanced/permissions_role_create_cluster/index.md
https://jira.d2iq.com/browse/D2IQ-90632
Add a page specifying the difference between ec2 user credentials vs instance profiles added here https://d2iq.atlassian.net/wiki/spaces/DENT/pages/29917930/Minimal+Permissions+and+Role+to+Create+Clusters
[Permalink](https://jira.d2iq.com/browse/D2IQ-90632?focusedCommentId=385447&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-385447)
cassandraoxford[Cassandra Oxford](https://jira.d2iq.com/secure/ViewProfile.jspa?name=cassandraoxford) added a comment - 3 days ago
Add page to 2.2 via github before closing this ticket.
http://docs-d2iq-com-pr-4586.s3-website-us-west-2.amazonaws.com/
See the [contribution …
=> Backport Min Perm and Role for AWS Clustser Creation

pages/dkp/kommander/2.2/release-notes/2.2.2/index.md
[](https://jira.d2iq.com/browse/D2IQ-91419)
My automation script was reporting the wrong application versions (it was getting the latest). This fix corrects the previous PR.
http://docs-d2iq-com-pr-4587.s3-website-us-west-2.amazonaws.com/
=> fix: Update DKP 2.2.2 app versions

pages/dkp/konvoy/1.8/release-notes/1.8.5/index.md
https://jira.d2iq.com/browse/D2IQ-91692
=> fix: Konvoy release-notes KBA and Kommander versions

pages/dkp/konvoy/2.1/choose-infrastructure/pre-provisioned/prerequisites-airgapped/index.md, pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/prepare-air-gapped/index.md
https://jira.d2iq.com/browse/D2IQ-84226
Add section to document additional steps needed to successfully upgrade an air-gapped cluster
http://docs-d2iq-com-pr-4551.s3-website-us-west-2.amazonaws.com/
=> chore(konvoy): add airgapped upgrade

pages/dkp/kaptain/2.0.0/install/index.md
https://jira.d2iq.com/browse/D2IQ-91680 
During testing, it was discovered that MinIO needs to be installed manually in attached clusters when installing Kaptain in said cluster. 
This was added to 2.1 via Confluence already.
http://docs-d2iq-com-pr-<4592>.s3-website-us-west-2.amazonaws.com/
=> [Kaptain]: adding MinIO to the prerequisites of Kaptain

pages/dkp/konvoy/2.2/supported-operating-systems/index.md, pages/dkp/konvoy/2.3/supported-operating-systems/index.md
closes - https://jira.d2iq.com/browse/D2IQ-91902 
According to https://jira.d2iq.com/browse/D2IQ-89269 we do not have this feature yet. So removing it from our list
=> fix: remove vsphere centos7 support

pages/dkp/kaptain/2.0.0/install/deploy-kaptain/index.md
https://jira.d2iq.com/browse/D2IQ-91713
Docs improvement. Jan was deploying Kaptain to an attached cluster, which is not possible without adding a reference to the namespace.
Already added this to 2.1 in Confluence.
http://docs-d2iq-com-pr-4597.s3-website-us-west-2.amazonaws.com/
=> [Kaptain]: Adding namespace reference for attached clusters

ci/update-dkp-cli-docs.sh
NA
The CLI docs automation was using an outdated URL for the DKP CLI. This fixes it.
=> fix: update dkp-cli URL

.github/workflows/dkp-cli.yml
NA
Enables manual triggering of the CLI docs generation
=> build: add a manual trigger for the doc generation action

pages/dkp/konvoy/2.2/image-builder/index.md
https://jira.d2iq.com/browse/D2IQ-92208
Take KIB compatibility table from Confluence https://d2iq.atlassian.net/wiki/spaces/DENT/pages/29918909/Konvoy+Image+Builder#Compatible-versions and add through PR to 2.2
http://docs-d2iq-com-pr-4603.s3-website-us-west-2.amazonaws.com/
=> KIB to DKP compatibility matrix

pages/dkp/kommander/2.0/logging/enable-logging/create-appdeployment-workspace/index.md, pages/dkp/kommander/2.1/logging/enable-logging/create-appdeployment-workspace/index.md, pages/dkp/kommander/2.2/logging/enable-logging/create-appdeployment-workspace/index.md, pages/dkp/kommander/2.3/logging/enable-logging/create-appdeployment-workspace/index.md
noticed this when going through logging docs - we don't create this override cm anywhere, we should remove it
http://docs-d2iq-com-pr-4605.s3-website-us-west-2.amazonaws.com/
=> docs: Remove unused grafana-logging override

pages/dkp/konvoy/2.2/release-notes/2.2.0/index.md, pages/dkp/konvoy/2.2/release-notes/2.2.1/index.md, pages/dkp/konvoy/2.2/release-notes/2.2.2/index.md
https://jira.d2iq.com/browse/D2IQ-92258
If upgrading a FIPS cluster, there is a bug in the upgrade of `kube-proxy` `DaemonSet` in that it doesn't get automatically upgraded. To correctly upgrade, run the workaround command shown below:
```bash
kubectl set image -n kube-system daemonset.v1.apps/kube-proxy kube-proxy=[docker.io/mesosphere/kube-proxy:v1.22.8_fips.0](http://docker.io/mesosphere/kube-proxy:v1.22.8_fips.0)
```
=> FIPS Upgrade add to RN

.github/styles/Vocab/Docs/accept.txt, pages/dkp/kaptain/2.0.0/install/air-gapped-2.1/index.md, pages/dkp/kaptain/2.0.0/install/air-gapped-2.2/index.md, pages/dkp/kaptain/2.0.0/install/deploy-kaptain/index.md, pages/dkp/kaptain/2.0.0/install/dkp/index.md, pages/dkp/kaptain/2.0.0/install/index.md, pages/dkp/kaptain/2.0.0/install/on-premise/index.md, pages/dkp/kaptain/2.0.0/install/prerequisites/index.md
https://jira.d2iq.com/browse/D2IQ-92429
Hi. We made a lot of improvements to the Kaptain installation docs in Confluence for 2.1. We are NOT bringing all of those improvements to 2.0 because we need to prioritize other tickets. However, in this ticket, we are trying to bring the most important of those improvements to 2.0: 
- Dedicated prerequisite section with more instructions on how to install dependencies
- "Configure Kap to comunicate with Mgmt via Dex" on the right spot in the documentation
- Better overview of install process
http://docs-d2iq-com-pr-4616.s3-website-us-west-2.amazonaws.com/
=> [Kap] Install pages improvements

pages/dkp/kommander/2.2/install/air-gapped/catalog/index.md
Backporting the air-gap install instructions from 2.3 to 2.2.1
Please review for accuracy and correct tar file designations.
https://jira.d2iq.com/browse/D2IQ-92268
http://docs-d2iq-com-pr-4612.s3-website-us-west-2.amazonaws.com/
=> Backporting Air-gap install

pages/dkp/kommander/2.1/release-notes/2.1.3/index.md, pages/dkp/konvoy/2.1/release-notes/2.1.2/index.md, pages/dkp/konvoy/2.1/release-notes/2.1.3/index.md, pages/dkp/konvoy/2.2/release-notes/2.2.0/index.md
n/a
Mostly just fixing some links I noticed needed to be updated.
=> docs: fixing some links in release notes

.github/styles/Vocab/Docs/accept.txt, pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/aws/index.md, pages/dkp/konvoy/2.1/supported-operating-systems/index.md
n/a
From a slack conversation - we wanted to add a clarifying note to repeat these steps for each additional multi avail zone upon major version upgrade.
Hitchhiker fix for some markdown thing I saw on os support page, no content change here, solely markdown.
http://docs-d2iq-com-pr-4621.s3-website-us-west-2.amazonaws.com/
=> docs: adding clarifying language to major upgrade

pages/dkp/kaptain/2.1.0/configuration/index.md, pages/dkp/kaptain/2.1.0/tutorials/katib/index.md, pages/dkp/kaptain/2.1.0/tutorials/pipelines/index.md, pages/dkp/kaptain/2.1.0/tutorials/sdk/image-builder/index.md, pages/dkp/kaptain/2.1.0/tutorials/sdk/pytorch/index.md, pages/dkp/kaptain/2.1.0/tutorials/sdk/quick-start/index.md, pages/dkp/kaptain/2.1.0/tutorials/sdk/tensorflow/index.md, pages/dkp/kaptain/2.1.0/tutorials/training/mxnet/index.md, pages/dkp/kaptain/2.1.0/tutorials/training/pytorch/index.md, pages/dkp/kaptain/2.1.0/tutorials/training/tensorflow/index.md
[Update tutorials with 2.1.0 release versions in docs page](https://jira.d2iq.com/browse/D2IQ-91193)
=> Update tutorials and configuration with 2.1.0 release versions in docs page

layouts/all-products-landing.pug, layouts/kaptain-docs-landing.pug, layouts/kommander-docs-landing.pug, layouts/konvoy-docs-landing.pug, layouts/partials/header/header.pug, scss/base/_content.scss, scss/base/_header-dropdown.scss, scss/base/_header.scss, scss/pages/_landing.scss, scss/pages/_new-landing.scss
This repo is now for the archived docs site.
These changes are to add a notice that the site has moved.
Closes D2IQ-92031
We want to include a notice for users to route them to the new docs site - https://docs.d2iq.com. 
The text should read - "You are viewing the documentation for older DKP releases. If you're looking for the new help center that includes the latest DKP release, go to https://docs.d2iq.com/."
I've matched the warning banner to a similar style as the "NOTE:" messages throughout the site to keep a consistent UX for notices. I've included the info icon as another indicator of important information if the blue/purple color alone is not indicative enough, which it may not be for those with visual impairments such as color deficiencies.
The banner will display on the main …
=> feat: banner routing to new docs site

pages/dkp/kaptain/2.0.0/install/air-gapped-2.2/index.md, pages/dkp/kaptain/2.0.0/install/deploy-kaptain/index.md, pages/dkp/kaptain/2.0.0/install/dkp/index.md, pages/dkp/kaptain/2.0.0/install/prerequisites/index.md
https://jira.d2iq.com/browse/D2IQ-91603 
Backporting changes that were made and approved in Confluence to archived Kaptain 2.0 documentation.
http://docs-d2iq-com-pr-4625.s3-website-us-west-2.amazonaws.com/
=> [Kap] backporting multi-cluster specifications

pages/dkp/konvoy/2.2/choose-infrastructure/aws/air-gapped/create-an-ami/index.md
D2IQ-92978
Just changing the code block so this code block can be copy/pastable.
http://docs-d2iq-com-pr-4629.s3-website-us-west-2.amazonaws.com/
=> docs: fixing code block for url location

pages/dkp/kommander/2.2/dkp-upgrade/upgrade-kommander/index.md, pages/dkp/kommander/2.2/install/air-gapped/catalog/index.md, pages/dkp/kommander/2.2/install/air-gapped/index.md, pages/dkp/kommander/2.2/install/configuration/enterprise-catalog/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/aws/air-gapped/bootstrap/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/aws/air-gapped/seed-a-registry/index.md, pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/prerequisites-airgapped/index.md, pages/dkp/konvoy/2.2/dkp-upgrade/upgrade-kommander/index.md, pages/dkp/konvoy/2.2/image-builder/index.md
We missed updating lots of 2.2 docs with the latest 2.2.2 version when it was released (e.g. airgapped bundles)
=> docs: Update dkp versions in 2.2 docs to latest 2.2.2

pages/dkp/kommander/2.2/tutorials/continuous-delivery/deploy_app_gitops/index.md
https://d2iq.atlassian.net/browse/D2IQ-92269
This is a backport from 2.4 & 2.3. All steps are already validated on the Confluence 2.4 pages, so this is just copying down to 2.2. Only need to verify the links and code renders correctly.
http://docs-d2iq-com-pr-4631.s3-website-us-west-2.amazonaws.com/
=> Include a podinfo app deployment steps on 'Project Deployment Section Documentation' of Kommander

pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/create-cluster/index.md
https://d2iq.atlassian.net/browse/D2IQ-92966
Backporting 2.3/2,4 change. This is already approved in Confluence, so just need to merge no review necessary.
http://docs-d2iq-com-pr-4633.s3-website-us-west-2.amazonaws.com/
=> Missing link to final step in docs to make cluster self managed

pages/dkp/konvoy/2.2/choose-infrastructure/pre-provisioned/prerequisites-airgapped/index.md
https://d2iq.atlassian.net/browse/D2IQ-93038
This copies over some instructions from the current docs site for 2.3: https://docs.d2iq.com/dkp/2.3/pre-provisioned-prerequisites-air-gapped#id-(2.3)Pre-provisionedPrerequisitesAir-gapped-Copyair-gappedartifactsontoclusterhosts
=> docs: Add documentation for containerd bundles for 2.2.2 On Prem Air Gap

pages/dkp/konvoy/2.1/major-version-upgrade/index.md, pages/dkp/konvoy/2.1/major-version-upgrade/plan/index.md
https://d2iq.atlassian.net/browse/D2IQ-92075
Upgrading your 1.x installation to 2.1 is not possible when Kaptain is enabled. Since we do not support said migrating Kaptain to 2.x, we decided to add a warning in the Konvoy upgrade docs.
http://docs-d2iq-com-pr-4634.s3-website-us-west-2.amazonaws.com/
=> [Kap] warning on upgrading a Kaptain cluster to 2.x

pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/aws/index.md
https://d2iq.atlassian.net/browse/D2IQ-92102
Added progress monitoring command to upgrade docs along with intended output.
http://docs-d2iq-com-pr-4642.s3-website-us-west-2.amazonaws.com/
=> [DKP 2.1] Better Progress Monitoring for 2.1 Upgrade Status

pages/dkp/kommander/2.2/release-notes/2.2.0/index.md, pages/dkp/kommander/2.2/release-notes/2.2.1/index.md, pages/dkp/kommander/2.2/release-notes/2.2.2/index.md
https://d2iq.atlassian.net/browse/D2IQ-89687
Workaround for 2.1x upgrade to 2.2x, when MinIo insufficient space error.
Added to all 2.2x Release Notes.
=> Added workaround - 2.1x to 2.2x upgrade Minio failure

pages/dkp/konvoy/2.1/supported-operating-systems/index.md
[D2IQ-93481](https://d2iq.atlassian.net/browse/D2IQ-93481)
Updating version of qualified Flatcar to include   OS Image:                   Flatcar Container Linux by Kinvolk 2905.2.6 (Oklo)
=> docs: adding new version for flatcar

pages/dkp/kaptain/2.0.0/configuration/external-dex/index.md, pages/dkp/kaptain/2.0.0/install/prerequisites/index.md
No ticket, but related to:
https://d2iq.atlassian.net/browse/D2IQ-91684
https://d2iq.atlassian.net/browse/D2IQ-91683
Since we have added support for customer-issued and ACME certificates in Kaptain for 2.2, just clarifying that 2.0 and 2.1 don't support it. 
This note was added for 2.1 docs in Confluence already.
http://docs-d2iq-com-pr-4648.s3-website-us-west-2.amazonaws.com/
=> [Kap]: adding note on not supported certificates

pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/aws/index.md
n/a
When reviewing this for the patch release, I noticed that the formatting was off at the bottom, and some actual text got swallowed up in some code snippets. This fixes that.
=> docs: formatting was off a bit

pages/dkp/kommander/2.2/release-notes/2.2.3/index.md, pages/dkp/konvoy/2.2/release-notes/2.2.3/index.md
n/a
Just my own vanity saw this and wanted to change it:
The rest was just linting
http://docs-d2iq-com-pr-4656.s3-website-us-west-2.amazonaws.com/
=> The order of the RN was slightly different - fixes that

pages/dkp/kommander/2.2/dkp-upgrade/index.md, pages/dkp/konvoy/2.2/dkp-upgrade/index.md
https://d2iq.atlassian.net/browse/D2IQ-93416
The 2.2 documentation explicitly referred to 2.3 docs for a table of the supported upgrade paths. However, it should reference the `latest` version of DKP instead of 2.4. 
Streamlining to Konvoy and Kommander docs as they were separate and duplicate for 2.2
=> [DKP] upgrade matrix

pages/dkp/kaptain/2.0.0/install/air-gapped-2.1/index.md, pages/dkp/kaptain/2.0.0/install/air-gapped-2.2/index.md
https://d2iq.atlassian.net/browse/D2IQ-93437
Customers can download all air-gapped bundles for Kaptain from the support site. Therefore adding a link from 2.0 docs. 2.1 and 2.2 will be updated in Confluence.
=> [Kap]: downloads now available from support site

pages/dkp/konvoy/2.1/choose-infrastructure/aws/air-gapped/bootstrap/index.md, pages/dkp/konvoy/2.1/choose-infrastructure/aws/air-gapped/seed-a-registry/index.md, pages/dkp/konvoy/2.1/choose-infrastructure/pre-provisioned/prerequisites-airgapped/index.md, pages/dkp/konvoy/2.1/major-version-upgrade/index.md
Signed-off-by: Casie 2 <casie2@MacBook-Pro-3.local>
https://d2iq.atlassian.net/browse/D2IQ-93808 
http://docs-d2iq-com-pr-4655.s3-website-us-west-2.amazonaws.com/
=> changing 2.1.1 to 2.1.4 D2iq-93808

pages/dkp/kommander/2.1/release-notes/2.1.5/index.md, pages/dkp/konvoy/2.1/release-notes/2.1.4/index.md, pages/dkp/konvoy/2.1/release-notes/2.1.5/index.md
https://d2iq.atlassian.net/browse/D2IQ-94232
Release Notes 2.1.5
http://docs-d2iq-com-pr-4663.s3-website-us-west-2.amazonaws.com/
=> [Konvoy] Release Notes 2.1.5

.github/styles/Vocab/Docs/accept.txt, pages/dkp/kommander/2.1/major-upgrade/upgrade-clusters/migrate-platform-apps/index.md, pages/dkp/kommander/2.1/release-notes/2.1.0/index.md, pages/dkp/kommander/2.1/release-notes/2.1.1/index.md, pages/dkp/kommander/2.1/release-notes/2.1.2/index.md, pages/dkp/kommander/2.1/release-notes/2.1.3/index.md, pages/dkp/kommander/2.1/release-notes/2.1.4/index.md, pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/aws/index.md, pages/dkp/konvoy/2.1/major-version-upgrade/upgrade/prepare-local-environment/index.md
[D2IQ-94600](https://d2iq.atlassian.net/browse/D2IQ-94600)
There are some other edits, but the gist is in `pages/dkp/kommander/2.1/major-upgrade/upgrade-clusters/migrate-platform-apps/index.md`
Where not everything was getting deployed correctly for migrated clusters re: gitea. This makes it work.
http://docs-d2iq-com-pr-4669.s3-website-us-west-2.amazonaws.com/
=> docs: updating 21 migration steps

pages/dkp/kommander/2.2/release-notes/2.2.0/index.md, pages/dkp/kommander/2.2/release-notes/2.2.1/index.md, pages/dkp/kommander/2.2/release-notes/2.2.2/index.md, pages/dkp/kommander/2.2/release-notes/2.2.3/index.md
C
https://d2iq.atlassian.net/browse/D2IQ-94862
http://docs-d2iq-com-pr-4672.s3-website-us-west-2.amazonaws.com/
=> Bug: 94862 Calico workaround

pages/dkp/konvoy/2.2/dkp-upgrade/upgrade-konvoy/enterprise/index.md, pages/dkp/konvoy/2.2/dkp-upgrade/upgrade-konvoy/essential/index.md
[D2IQ-95126](https://d2iq.atlassian.net/browse/D2IQ-95126)
Previous PR 4425 was wiped out by another merge from another user.  This PR replaced the Upgrade Caps component command fix for upgrade if your cluster was upgraded to 2.1 from 1.8, remove the remaining old cert-manager resources from 1.8:
[D2IQ-95126]: https://d2iq.atlassian.net/browse/D2IQ-95126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixed missing capi component command from upgrade

pages/dkp/kommander/2.2/release-notes/2.2.0/index.md, pages/dkp/kommander/2.2/release-notes/2.2.1/index.md, pages/dkp/kommander/2.2/release-notes/2.2.2/index.md, pages/dkp/kommander/2.2/release-notes/2.2.3/index.md
Undoing the changes found here:
https://github.com/mesosphere/dcos-docs-site/pull/4676/files
Under advisement from @dkoshkin 
https://d2iq.atlassian.net/browse/D2IQ-94862
Undoing the manual fix in the Release Notes
http://docs-d2iq-com-pr-4678.s3-website-us-west-2.amazonaws.com/
=> docs: removing fix for calico in 2x

pages/dkp/konvoy/2.2/image-builder/index.md
Keeping pace with the release that dropped a bit ago.
Adding new row in KIB Version table to include DKP v2.2.3
http://docs-d2iq-com-pr-4681.s3-website-us-west-2.amazonaws.com/
=> docs: added dkp v2.2.3 to kib docs

pages/dkp/konvoy/2.2/release-notes/2.2.0/index.md
n/a
Default version of Kubernetes is incorrect in the 2.2.0 release notes.
It is actually v1.22.8
http://docs-d2iq-com-pr-4685.s3-website-us-west-2.amazonaws.com/
=> docs: updated default version of kubernetes

pages/dkp/kommander/2.1/install/configuration/http-proxy/index.md
Added workarounds for getting past the chicken & egg situation described in the Jira ticket. Changes made in 2.1-2.5.
Both of the two reviewers named at the right have already reviewed this content prior to backporting.
http://docs-d2iq-com-pr-4688.s3-website-us-west-2.amazonaws.com/
=> DKP 2.1: Added workarounds to Configure HTTP Proxy page

pages/dkp/kommander/2.2/dkp-upgrade/upgrade-konvoy/enterprise/index.md, pages/dkp/kommander/2.2/dkp-upgrade/upgrade-konvoy/essential/index.md
n/a
Saw that there wasn't a step to get the nodepool names, though this is in every other version of the docs (2.3+)
Also, there's a grip of linting that I did here, too - so it looks like there are lots of changes, but honestly, it's just at the end of these files that I did any content changes.
http://docs-d2iq-com-pr-4692.s3-website-us-west-2.amazonaws.com/
=> docs: added steps to get nodepool names

pages/dkp/security-updates/index.md
http://docs-d2iq-com-pr-4691.s3-website-us-west-2.amazonaws.com/
=> docs: add v2.5.0 to security updates page

pages/dkp/konvoy/2.2/choose-infrastructure/vsphere/create-base-os-image/index.md
n/a
Changing the user/pw situation for vsphere for KIB.
http://docs-d2iq-com-pr-4694.s3-website-us-west-2.amazonaws.com/
=> docs: adding vsphere kib image security details

pages/dkp/konvoy/2.2/dkp-upgrade/upgrade-konvoy/enterprise/index.md, pages/dkp/konvoy/2.2/dkp-upgrade/upgrade-konvoy/essential/index.md
N/A
This is basically this, but I am NOW adding it to the konvoy upgrade page:
https://github.com/mesosphere/dcos-docs-site/pull/4692
http://docs-d2iq-com-pr-4693.s3-website-us-west-2.amazonaws.com/
=> docs: adding nodepool biz to konvoy upgrade

pages/dkp/security-updates/index.md
https://d2iq.atlassian.net/browse/D2IQ-98178 
The team has migrated the CVE page from our old site to our new site in: https://docs.d2iq.com/dkp/2.6/d2iq-security-updates
Deleting the content of the CVE page in the old site, and adding wording so that it points to the new Confluence-based site.
http://docs-d2iq-com-pr-4701.s3-website-us-west-2.amazonaws.com/
=> Update old CVE page to point to new CVE page
